Repository eXist-db/exist, pull requests merged in 2018-07, with the labels that each got.

#1990 (5.0.0) Support the Collation used in XQTS 3.1
  src/org/exist/util/Collations.java
Labels: enhancement

#1991 A collection of small fixes for various issues
  src/org/exist/dom/memtree/SAXAdapter.java
  src/org/exist/util/XMLReaderObjectFactory.java
  src/org/exist/xquery/EnclosedExpr.java
  src/org/exist/xquery/functions/fn/FunData.java
  src/org/exist/xquery/functions/map/MapFunction.java
  src/org/exist/xquery/value/AbstractSequence.java
  src/org/exist/xquery/value/Sequence.java
  test/src/org/exist/dom/memtree/DocumentBuilderReceiverIntegrationTest.java
  test/src/org/exist/xquery/XQueryTest.java
  test/src/org/exist/xquery/functions/fn/ExtDocTest.java
  test/src/xquery/maps/maps.xql
Labels: bug, needs 4.xx backport, needs 5.0.0 backport

#1992 (5.0.0) A collection of small fixes for various issues
  src/org/exist/dom/memtree/SAXAdapter.java
  src/org/exist/util/XMLReaderObjectFactory.java
  src/org/exist/xquery/EnclosedExpr.java
  src/org/exist/xquery/functions/fn/FunData.java
  src/org/exist/xquery/functions/map/MapFunction.java
  src/org/exist/xquery/value/AbstractSequence.java
  src/org/exist/xquery/value/Sequence.java
  test/src/org/exist/dom/memtree/DocumentBuilderReceiverIntegrationTest.java
  test/src/org/exist/xquery/XQueryTest.java
  test/src/org/exist/xquery/functions/fn/ExtDocTest.java
  test/src/xquery/maps/maps.xql
Labels: bug

#1993 (4.x.x) A collection of small fixes for various issues
  src/org/exist/dom/memtree/SAXAdapter.java
  src/org/exist/util/XMLReaderObjectFactory.java
  src/org/exist/xquery/EnclosedExpr.java
  src/org/exist/xquery/functions/fn/FunData.java
  src/org/exist/xquery/functions/map/MapFunction.java
  src/org/exist/xquery/value/AbstractSequence.java
  src/org/exist/xquery/value/Sequence.java
  test/src/org/exist/dom/memtree/DocumentBuilderReceiverIntegrationTest.java
  test/src/org/exist/xquery/XQueryTest.java
  test/src/org/exist/xquery/functions/fn/ExtDocTest.java
  test/src/xquery/maps/maps.xql
Labels: bug

#1989 Support the Collation used in XQTS 3.1
  src/org/exist/util/Collations.java
Labels: enhancement, needs documentation

#2004 (5.0.0) Fix an issue where AbstractSequence#convertTo(int) was returning an empty sequence when it should not
  src/org/exist/xquery/value/AbstractSequence.java
Labels: bug

#2003 (4.x.x) Fix an issue where AbstractSequence#convertTo(int) was returning an empty sequence when it should not
  src/org/exist/xquery/value/AbstractSequence.java
Labels: bug

#2002 Fix an issue where AbstractSequence#convertTo(int) was returning an empty sequence when it should not
  src/org/exist/xquery/value/AbstractSequence.java
Labels: bug

#2009 (4.x.x) Fix encoding of file:serialize
  extensions/modules/src/org/exist/xquery/modules/file/SerializeToFile.java
Labels: bug

#2010 (5.x.x) Fix encoding of file:serialize
  extensions/modules/src/org/exist/xquery/modules/file/SerializeToFile.java
Labels: bug

#1986 Basic support for available collections of Dynamic Context
  extensions/indexes/range/test/src/xquery/field-type.xql
  src/org/exist/xquery/XQueryContext.java
  src/org/exist/xquery/functions/fn/ExtCollection.java
  test/src/org/exist/xquery/functions/fn/CollectionTest.java
  test/src/xquery/count.xql
Labels: enhancement

#2008 Fix encoding of file:serialize
  extensions/modules/src/org/exist/xquery/modules/file/SerializeToFile.java
Labels: bug

#1987 (5.0.0) Basic support for available collections of Dynamic Context
  extensions/indexes/range/test/src/xquery/field-type.xql
  src/org/exist/xquery/XQueryContext.java
  src/org/exist/xquery/functions/fn/ExtCollection.java
  test/src/org/exist/xquery/functions/fn/CollectionTest.java
  test/src/xquery/count.xql
Labels: enhancement

#2017 Reduce unnecessary error logging
  src/org/exist/xquery/functions/fn/FunError.java
  src/org/exist/xquery/functions/fn/FunExactlyOne.java
Labels: enhancement, needs 4.xx backport, needs 5.0.0 backport

#2019 (5.0.0) Reduce unnecessary error logging
  src/org/exist/xquery/functions/fn/FunError.java
  src/org/exist/xquery/functions/fn/FunExactlyOne.java
Labels: bug

#2018 (4.x.x) Reduce unnecessary error logging
  src/org/exist/xquery/functions/fn/FunError.java
  src/org/exist/xquery/functions/fn/FunExactlyOne.java
Labels: bug

#2011 Fixes a couple of issues with LDAP authentication
  extensions/security/ldap/README.txt
  extensions/security/ldap/src/org/exist/security/realm/TransformationContext.java
  extensions/security/ldap/src/org/exist/security/realm/ldap/AbstractLDAPPrincipalRestrictionList.java
  extensions/security/ldap/src/org/exist/security/realm/ldap/AbstractLDAPSearchPrincipal.java
  extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPAccountImpl.java
  extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPGroupImpl.java
  extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPPrincipalBlackList.java
  extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPPrincipalWhiteList.java
  extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPRealm.java
  extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPSearchAccount.java
  extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPSearchContext.java
  extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPSearchGroup.java
  extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPTransformationContext.java
  extensions/security/ldap/src/org/exist/security/realm/ldap/LdapContextFactory.java
  extensions/security/ldap/src/org/exist/security/realm/ldap/LdapUtils.java
  extensions/security/ldap/src/org/exist/security/realm/ldap/xquery/AccountFunctions.java
  extensions/security/ldap/src/org/exist/security/realm/ldap/xquery/LDAPModule.java
Labels: bug

#2013 (5.0.0) Fixes a couple of issues with LDAP authentication
  extensions/security/ldap/README.txt
  extensions/security/ldap/src/org/exist/security/realm/TransformationContext.java
  extensions/security/ldap/src/org/exist/security/realm/ldap/AbstractLDAPPrincipalRestrictionList.java
  extensions/security/ldap/src/org/exist/security/realm/ldap/AbstractLDAPSearchPrincipal.java
  extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPAccountImpl.java
  extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPGroupImpl.java
  extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPPrincipalBlackList.java
  extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPPrincipalWhiteList.java
  extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPRealm.java
  extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPSearchAccount.java
  extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPSearchContext.java
  extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPSearchGroup.java
  extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPTransformationContext.java
  extensions/security/ldap/src/org/exist/security/realm/ldap/LdapContextFactory.java
  extensions/security/ldap/src/org/exist/security/realm/ldap/LdapUtils.java
  extensions/security/ldap/src/org/exist/security/realm/ldap/xquery/AccountFunctions.java
  extensions/security/ldap/src/org/exist/security/realm/ldap/xquery/LDAPModule.java
Labels: bug

#2012 (4.x.x) Fixes a couple of issues with LDAP authentication
  extensions/security/ldap/README.txt
  extensions/security/ldap/src/org/exist/security/realm/TransformationContext.java
  extensions/security/ldap/src/org/exist/security/realm/ldap/AbstractLDAPPrincipalRestrictionList.java
  extensions/security/ldap/src/org/exist/security/realm/ldap/AbstractLDAPSearchPrincipal.java
  extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPAccountImpl.java
  extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPGroupImpl.java
  extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPPrincipalBlackList.java
  extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPPrincipalWhiteList.java
  extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPRealm.java
  extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPSearchAccount.java
  extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPSearchContext.java
  extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPSearchGroup.java
  extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPTransformationContext.java
  extensions/security/ldap/src/org/exist/security/realm/ldap/LdapContextFactory.java
  extensions/security/ldap/src/org/exist/security/realm/ldap/LdapUtils.java
  extensions/security/ldap/src/org/exist/security/realm/ldap/xquery/AccountFunctions.java
  extensions/security/ldap/src/org/exist/security/realm/ldap/xquery/LDAPModule.java
Labels: bug

#2030 (4.x.x) Fix a problem with node equality when using the DOM from the XML:DB Local API
  src/org/exist/xmldb/LocalXMLResource.java
Labels: bug, high prio

#2032 (5.0.0) Reinstates protection for leaky DOM in XML:DB Local API
  src/org/exist/xmldb/LocalXMLResource.java
Labels: bug

#2031 Reinstates protection for leaky DOM in XML:DB Local API
  src/org/exist/xmldb/LocalXMLResource.java
Labels: bug

#2027 Fix document URI logging during restore
  src/org/exist/backup/restore/CollectionDeferredPermission.java
  src/org/exist/backup/restore/ResourceDeferredPermission.java
Labels: bug

#2028 (4.x.x) Fix document URI logging during restore
  src/org/exist/backup/restore/CollectionDeferredPermission.java
  src/org/exist/backup/restore/ResourceDeferredPermission.java
Labels: bug

#2029 (5.0.0) Fix document URI logging during restore
  src/org/exist/backup/restore/CollectionDeferredPermission.java
  src/org/exist/backup/restore/ResourceDeferredPermission.java
Labels: bug

#2025 Fix an NPE when preserve-on-copy is set and we are adding binary document
  src/org/exist/collections/MutableCollection.java
  test/src/org/exist/collections/AllCollectionTests.java
  test/src/org/exist/collections/CollectionStoreTest.java
Labels: bug

#2034 (5.0.0) Test for importing a main module from the classpath
  test/src/org/exist/xquery/XQueryTest.java
  test/src/org/exist/xquery/external-classpath-library-module.xqm
  test/src/org/exist/xquery/external-classpath-main-module.xq
  test/src/org/exist/xquery/external-classpath-module.xqm
Labels: enhancement

#2033 (4.x.x) Test for importing a main module from the classpath
  test/src/org/exist/xquery/XQueryTest.java
  test/src/org/exist/xquery/external-classpath-library-module.xqm
  test/src/org/exist/xquery/external-classpath-main-module.xq
  test/src/org/exist/xquery/external-classpath-module.xqm
Labels: enhancement

#2024 Test for importing a main module from the classpath
  test/src/org/exist/xquery/XQueryTest.java
  test/src/org/exist/xquery/external-classpath-library-module.xqm
  test/src/org/exist/xquery/external-classpath-main-module.xq
  test/src/org/exist/xquery/external-classpath-module.xqm
Labels: enhancement

#2021 Fix an error when loading conf.xml from a Jar
  src/org/exist/util/ConfigurationHelper.java
Labels: bug

#2022 (5.0.0) Fix an error when loading conf.xml from a Jar
  src/org/exist/util/ConfigurationHelper.java
Labels: bug

#2023 (4.x.x) Fix an error when loading conf.xml from a Jar
  src/org/exist/util/ConfigurationHelper.java
Labels: bug

#2035 Revert "(4.x.x) Upgrade Xerces to latest version"
  .classpath
  build/scripts/junit.xml
  lib/endorsed/cupv10k-runtime-LICENSE.txt
  lib/endorsed/cupv10k-runtime.jar
  lib/endorsed/org.eclipse.wst.xml.xpath2.processor-1.2.0.jar
  lib/endorsed/xercesImpl-2.11.0.jar
  lib/endorsed/xercesImpl-2.12.0.jar
  nbproject/project.properties
  test/src/xquery/validation/ValidationTests.java
  test/src/xquery/validation/jaxv.xql
Labels: regression

#2037 Cache dependencies between builds
  .travis.yml
Labels: enhancement, needs 4.xx backport, needs 5.0.0 backport

#2039 (4.x.x) Fixes another issue with zero byte binary resources in the XML:DB Remote API
  src/org/exist/xmldb/RemoteCollection.java
  test/src/org/exist/xmldb/RemoteCollectionTest.java
Labels: bug

#2041 Improve reporting of xar downloads from package repo during build process
  build/scripts/setup.xml
Labels: enhancement, needs 4.xx backport, needs 5.0.0 backport

#2045 (5.0.0) Removes unnecessary logging behind fn:doc and fn:doc-available
  .classpath
  lib/core/j8fu-1.18.jar
  lib/core/j8fu-1.20.jar
  nbproject/project.properties
  src/org/exist/xquery/util/DocUtils.java
Labels: bug

#2046 (4.x.x) Removes unnecessary logging behind fn:doc and fn:doc-available
  .classpath
  lib/core/j8fu-1.16.jar
  lib/core/j8fu-1.20.jar
  nbproject/project.properties
  src/org/exist/xquery/util/DocUtils.java
Labels: bug

#2044 Removes unnecessary logging behind fn:doc and fn:doc-available
  .classpath
  lib/core/j8fu-1.18.jar
  lib/core/j8fu-1.20.jar
  nbproject/project.properties
  src/org/exist/xquery/util/DocUtils.java
Labels: bug

#2038 Fixes another issue with zero byte binary resources in the XML:DB Remote API
  src/org/exist/xmldb/RemoteCollection.java
  test/src/org/exist/xmldb/RemoteCollectionTest.java
Labels: bug

#2057 (4.x.x) Add further JDK's to Travis
  .classpath
  .travis.yml
  lib/optional/jaxb-api-2.3.0.jar
  nbproject/project.properties
  src/org/exist/start/start.config
Labels: enhancement

#2058 (5.0.0) Add further JDK's to Travis
  .classpath
  .travis.yml
  lib/optional/jaxb-api-2.3.0.jar
  nbproject/project.properties
  src/org/exist/start/start.config
Labels: enhancement

#2016 Add further JDK's to Travis
  .classpath
  .travis.yml
  lib/optional/jaxb-api-2.3.0.jar
  nbproject/project.properties
  src/org/exist/start/start.config
Labels: enhancement

#2062 Updated the function defintions for scheduling jobs via XQuery
  extensions/modules/src/org/exist/xquery/modules/scheduler/ScheduleFunctions.java
Labels: needs 4.xx backport, needs 5.0.0 backport

#2067 (5.0.0) Fixes the dist targets
  build/scripts/build-impl.xml
  build/scripts/dist.xml
Labels: bug

#2068 (4.x.x) Updated the function defintions for scheduling jobs via XQuery
  extensions/modules/src/org/exist/xquery/modules/scheduler/ScheduleFunctions.java
Labels: enhancement

#2069 (5.0.0) Updated the function defintions for scheduling jobs via XQuery
  extensions/modules/src/org/exist/xquery/modules/scheduler/ScheduleFunctions.java
Labels: enhancement

#2071 (4.x.x) Test backup/restore over both Local and Remote XML:DB APIs
  test/src/org/exist/backup/XMLDBBackupTest.java
Labels: enhancement

#2072 Fixes a problem with restoring a backup over the XML:DB Remote API
  src/org/exist/backup/restore/RestoreHandler.java
  test/src/org/exist/backup/XMLDBBackupTest.java
Labels: bug

#2073 (5.0.0) Fixes a problem with restoring a backup over the XML:DB Remote API
  src/org/exist/backup/restore/RestoreHandler.java
  test/src/org/exist/backup/XMLDBBackupTest.java
Labels: bug

#2077 (4.x.x) Fix an issue with IzPack on Windows
  installer/install.xml.tmpl
  installer/scripts/setup.bat
Labels: bug, windows
