Repository eXist-db/exist, pull requests merged in 2018-10, with the labels that each got.

#2207 Fix for preemptive authentication in the EXPath HTTP Client
  extensions/expath/lib/http-client-java-1.0-SNAPSHOT.jar
  extensions/expath/src/org/expath/exist/SendRequestFunction.java
Labels: bug

#2210 Fix a concurrency issue in ContextUpdateListener
  src/org/exist/storage/NotificationService.java
  src/org/exist/xquery/XQueryContext.java
Labels: bug

#2211 (4.x.x) Fix a concurrency issue in ContextUpdateListener
  src/org/exist/storage/NotificationService.java
  src/org/exist/xquery/XQueryContext.java
Labels: bug

#2212 (5.0.0) Fix a concurrency issue in ContextUpdateListener
  src/org/exist/storage/NotificationService.java
  src/org/exist/xquery/XQueryContext.java
Labels: bug

#2208 (4.x.x) Fix for preemptive authentication in the EXPath HTTP Client
  extensions/expath/lib/http-client-java-1.0-SNAPSHOT.jar
  extensions/expath/src/org/expath/exist/SendRequestFunction.java
Labels: bug

#2209 (5.0.0) Fix for preemptive authentication in the EXPath HTTP Client
  extensions/expath/lib/http-client-java-1.0-SNAPSHOT.jar
  extensions/expath/src/org/expath/exist/SendRequestFunction.java
Labels: bug

#2213 Map Constructor should not allow duplicate keys
  src/org/exist/xquery/ErrorCodes.java
  src/org/exist/xquery/functions/map/MapExpr.java
Labels: bug

#2214 (4.x.x) Map Constructor should not allow duplicate keys
  src/org/exist/xquery/ErrorCodes.java
  src/org/exist/xquery/functions/map/MapExpr.java
Labels: bug

#2215 (5.0.0) Map Constructor should not allow duplicate keys
  src/org/exist/xquery/ErrorCodes.java
  src/org/exist/xquery/functions/map/MapExpr.java
Labels: bug

#2196 Fixes an issue with mixed types in a subsequence
  src/org/exist/xquery/value/SubSequence.java
  test/src/org/exist/xquery/functions/fn/FunSubSequenceTest.java
Labels: bug

#2198 (4.x.x) Fixes an issue with mixed types in a subsequence
  src/org/exist/xquery/value/SubSequence.java
  test/src/org/exist/xquery/functions/fn/FunSubSequenceTest.java
Labels: bug

#2197 (5.0.0) Fixes an issue with mixed types in a subsequence
  src/org/exist/xquery/value/SubSequence.java
  test/src/org/exist/xquery/functions/fn/FunSubSequenceTest.java
Labels: bug

#2221 fixes an NPE resulting from expression using range index not being pr…
  src/org/exist/xquery/OrderByClause.java
  test/src/xquery/xquery3/flwor.xql
Labels: bug, needs 4.x.x backport, needs 5.0.0 backport

#2229 remove non lts oracle java versions
  .travis.yml
Labels: cleanup

#2231 remove non lts oracle java versions
  .travis.yml
Labels: cleanup

#2232 remove non lts oracle java versions
  .travis.yml
Labels: cleanup

#2247 (4.x.x) Secure the XMLReader processing
  extensions/debuggee/src/org/exist/debugger/Utils.java
  extensions/debuggee/src/org/exist/debugger/dbgp/ResponseImpl.java
  extensions/indexes/spatial/src/org/exist/indexing/spatial/AbstractGMLJDBCIndexWorker.java
  extensions/indexes/spatial/test/src/org/exist/indexing/spatial/GMLIndexTest.java
  extensions/modules/src/org/exist/xquery/modules/sql/ExecuteFunction.java
  src/org/exist/backup/AbstractBackupDescriptor.java
  src/org/exist/backup/BackupDescriptor.java
  src/org/exist/backup/Restore.java
  src/org/exist/backup/SystemExport.java
  src/org/exist/backup/SystemImport.java
  src/org/exist/backup/restore/RestoreHandler.java
  src/org/exist/backup/restore/SystemImportHandler.java
  src/org/exist/collections/CollectionConfigurationManager.java
  src/org/exist/config/Configurator.java
  src/org/exist/http/Descriptor.java
  src/org/exist/http/RESTServer.java
  src/org/exist/http/urlrewrite/RewriteConfig.java
  src/org/exist/storage/serializers/XIncludeFilter.java
  src/org/exist/util/Configuration.java
  src/org/exist/util/ExistSAXParserFactory.java
  src/org/exist/util/MimeTable.java
  src/org/exist/validation/Validator.java
  src/org/exist/xmldb/RemoteXMLResource.java
  src/org/exist/xquery/functions/fn/ParsingFunctions.java
  src/org/exist/xquery/functions/util/Eval.java
  src/org/exist/xquery/functions/util/Parse.java
  src/org/exist/xquery/functions/validation/Jaxp.java
  test/src/org/exist/config/ConfigurableTest.java
  test/src/org/exist/dom/memtree/DOMTest.java
  test/src/org/exist/dom/memtree/DocumentImplTest.java
  test/src/org/exist/dom/memtree/MemtreeBuilderTest.java
  test/src/org/exist/http/RESTServiceTest.java
  test/src/org/exist/test/runner/XMLTestRunner.java
  test/src/org/exist/w3c/tests/TestCase.java
  test/src/org/exist/xmldb/ResourceTest.java
Labels: bug, security

#2246 (5.0.0) Secure the XMLReader processing
  extensions/debuggee/src/org/exist/debugger/Utils.java
  extensions/debuggee/src/org/exist/debugger/dbgp/ResponseImpl.java
  extensions/indexes/spatial/src/org/exist/indexing/spatial/AbstractGMLJDBCIndexWorker.java
  extensions/indexes/spatial/test/src/org/exist/indexing/spatial/GMLIndexTest.java
  extensions/modules/src/org/exist/xquery/modules/sql/ExecuteFunction.java
  src/org/exist/backup/AbstractBackupDescriptor.java
  src/org/exist/backup/BackupDescriptor.java
  src/org/exist/backup/Restore.java
  src/org/exist/backup/SystemExport.java
  src/org/exist/backup/SystemImport.java
  src/org/exist/backup/restore/RestoreHandler.java
  src/org/exist/backup/restore/SystemImportHandler.java
  src/org/exist/collections/CollectionConfigurationManager.java
  src/org/exist/config/Configurator.java
  src/org/exist/http/Descriptor.java
  src/org/exist/http/RESTServer.java
  src/org/exist/http/urlrewrite/RewriteConfig.java
  src/org/exist/storage/serializers/XIncludeFilter.java
  src/org/exist/util/Configuration.java
  src/org/exist/util/ExistSAXParserFactory.java
  src/org/exist/util/MimeTable.java
  src/org/exist/validation/Validator.java
  src/org/exist/xmldb/RemoteXMLResource.java
  src/org/exist/xquery/functions/fn/ParsingFunctions.java
  src/org/exist/xquery/functions/util/Eval.java
  src/org/exist/xquery/functions/util/Parse.java
  src/org/exist/xquery/functions/validation/Jaxp.java
  test/src/org/exist/config/ConfigurableTest.java
  test/src/org/exist/dom/memtree/DOMTest.java
  test/src/org/exist/dom/memtree/DocumentImplTest.java
  test/src/org/exist/dom/memtree/MemtreeBuilderTest.java
  test/src/org/exist/http/RESTServiceTest.java
  test/src/org/exist/test/runner/XMLTestRunner.java
  test/src/org/exist/w3c/tests/TestCase.java
  test/src/org/exist/xmldb/ResourceTest.java
  test/src/org/exist/xquery/functions/fn/CollectionTest.java
  test/src/org/exist/xquery/functions/fn/DocTest.java
Labels: bug, security

#2243 Secure the XMLReader processing
  extensions/debuggee/src/org/exist/debugger/Utils.java
  extensions/debuggee/src/org/exist/debugger/dbgp/ResponseImpl.java
  extensions/indexes/spatial/src/org/exist/indexing/spatial/AbstractGMLJDBCIndexWorker.java
  extensions/indexes/spatial/test/src/org/exist/indexing/spatial/GMLIndexTest.java
  extensions/modules/src/org/exist/xquery/modules/sql/ExecuteFunction.java
  src/org/exist/backup/AbstractBackupDescriptor.java
  src/org/exist/backup/BackupDescriptor.java
  src/org/exist/backup/Restore.java
  src/org/exist/backup/SystemExport.java
  src/org/exist/backup/SystemImport.java
  src/org/exist/backup/restore/RestoreHandler.java
  src/org/exist/backup/restore/SystemImportHandler.java
  src/org/exist/collections/CollectionConfigurationManager.java
  src/org/exist/config/Configurator.java
  src/org/exist/http/Descriptor.java
  src/org/exist/http/RESTServer.java
  src/org/exist/http/urlrewrite/RewriteConfig.java
  src/org/exist/storage/serializers/XIncludeFilter.java
  src/org/exist/util/Configuration.java
  src/org/exist/util/ExistSAXParserFactory.java
  src/org/exist/util/MimeTable.java
  src/org/exist/validation/Validator.java
  src/org/exist/xmldb/RemoteXMLResource.java
  src/org/exist/xquery/functions/fn/ParsingFunctions.java
  src/org/exist/xquery/functions/util/Eval.java
  src/org/exist/xquery/functions/util/Parse.java
  src/org/exist/xquery/functions/validation/Jaxp.java
  test/src/org/exist/config/ConfigurableTest.java
  test/src/org/exist/dom/memtree/DOMTest.java
  test/src/org/exist/dom/memtree/DocumentImplTest.java
  test/src/org/exist/dom/memtree/MemtreeBuilderTest.java
  test/src/org/exist/http/RESTServiceTest.java
  test/src/org/exist/test/runner/XMLTestRunner.java
  test/src/org/exist/w3c/tests/TestCase.java
  test/src/org/exist/xmldb/ResourceTest.java
  test/src/org/exist/xquery/functions/fn/CollectionTest.java
  test/src/org/exist/xquery/functions/fn/DocTest.java
Labels: bug, high prio, security

#2244 Fix an issue with lock lifetime when changing permissions
  src/org/exist/management/impl/LockTable.java
  src/org/exist/management/impl/LockTableMXBean.java
  src/org/exist/security/PermissionFactory.java
  src/org/exist/storage/lock/LockTable.java
  src/org/exist/storage/lock/LockTableUtils.java
  src/org/exist/storage/txn/Txn.java
Labels: bug, enhancement

#2245 (5.0.0) Fix an issue with lock lifetime when changing permissions
  src/org/exist/management/impl/LockTable.java
  src/org/exist/management/impl/LockTableMXBean.java
  src/org/exist/security/PermissionFactory.java
  src/org/exist/storage/lock/LockTable.java
  src/org/exist/storage/lock/LockTableUtils.java
  src/org/exist/storage/txn/Txn.java
Labels: bug, enhancement

#2249 (5.0.0) Fix several Journalling and Recovery issues for XML and Binary documents
  build/scripts/junit.xml
  extensions/indexes/lucene/test/src/org/exist/indexing/lucene/ConcurrencyTest.java
  src/org/exist/collections/MutableCollection.java
  src/org/exist/management/impl/Database.java
  src/org/exist/management/impl/DatabaseMXBean.java
  src/org/exist/storage/AbstractBinaryLoggable.java
  src/org/exist/storage/BrokerPool.java
  src/org/exist/storage/BrokerPools.java
  src/org/exist/storage/CreateBinaryLoggable.java
  src/org/exist/storage/DBBroker.java
  src/org/exist/storage/DeleteBinaryLoggable.java
  src/org/exist/storage/NativeBroker.java
  src/org/exist/storage/RenameBinaryLoggable.java
  src/org/exist/storage/ReplaceBinaryLoggable.java
  src/org/exist/storage/UpdateBinaryLoggable.java
  src/org/exist/storage/btree/Paged.java
  src/org/exist/storage/dom/AddMovedValueLoggable.java
  src/org/exist/storage/dom/AddValueLoggable.java
  src/org/exist/storage/dom/CreatePageLoggable.java
  src/org/exist/storage/dom/DOMFile.java
  src/org/exist/storage/dom/RemovePageLoggable.java
  src/org/exist/storage/dom/UpdateHeaderLoggable.java
  src/org/exist/storage/dom/WriteOverflowPageLoggable.java
  src/org/exist/storage/index/AbstractBFileLoggable.java
  src/org/exist/storage/index/BFile.java
  src/org/exist/storage/index/RemoveValueLoggable.java
  src/org/exist/storage/index/StoreValueLoggable.java
  src/org/exist/storage/journal/Journal.java
  src/org/exist/storage/journal/JournalReader.java
  src/org/exist/storage/journal/Loggable.java
  src/org/exist/storage/recovery/RecoveryManager.java
  src/org/exist/util/FileUtils.java
  test/src/org/exist/storage/AbstractRecoverTest.java
  test/src/org/exist/storage/AllStorageTests.java
  test/src/org/exist/storage/RecoverBinaryTest.java
  test/src/org/exist/storage/RecoverXmlTest.java
  test/src/org/exist/storage/journal/AbstractJournalTest.java
  test/src/org/exist/storage/journal/JournalBinaryTest.java
  test/src/org/exist/storage/journal/JournalXmlTest.java
  test/src/org/exist/test/ExistEmbeddedServer.java
Labels: bug

#2248 Fix several Journalling and Recovery issues for XML and Binary documents
  build/scripts/junit.xml
  extensions/indexes/lucene/test/src/org/exist/indexing/lucene/ConcurrencyTest.java
  src/org/exist/collections/MutableCollection.java
  src/org/exist/management/impl/Database.java
  src/org/exist/management/impl/DatabaseMXBean.java
  src/org/exist/storage/AbstractBinaryLoggable.java
  src/org/exist/storage/BrokerPool.java
  src/org/exist/storage/BrokerPools.java
  src/org/exist/storage/CreateBinaryLoggable.java
  src/org/exist/storage/DBBroker.java
  src/org/exist/storage/DeleteBinaryLoggable.java
  src/org/exist/storage/NativeBroker.java
  src/org/exist/storage/RenameBinaryLoggable.java
  src/org/exist/storage/ReplaceBinaryLoggable.java
  src/org/exist/storage/UpdateBinaryLoggable.java
  src/org/exist/storage/btree/Paged.java
  src/org/exist/storage/dom/AddMovedValueLoggable.java
  src/org/exist/storage/dom/AddValueLoggable.java
  src/org/exist/storage/dom/CreatePageLoggable.java
  src/org/exist/storage/dom/DOMFile.java
  src/org/exist/storage/dom/RemovePageLoggable.java
  src/org/exist/storage/dom/UpdateHeaderLoggable.java
  src/org/exist/storage/dom/WriteOverflowPageLoggable.java
  src/org/exist/storage/index/AbstractBFileLoggable.java
  src/org/exist/storage/index/BFile.java
  src/org/exist/storage/index/RemoveValueLoggable.java
  src/org/exist/storage/index/StoreValueLoggable.java
  src/org/exist/storage/journal/Journal.java
  src/org/exist/storage/journal/JournalReader.java
  src/org/exist/storage/journal/Loggable.java
  src/org/exist/storage/recovery/RecoveryManager.java
  src/org/exist/util/FileUtils.java
  test/src/org/exist/storage/AbstractRecoverTest.java
  test/src/org/exist/storage/AllStorageTests.java
  test/src/org/exist/storage/RecoverBinaryTest.java
  test/src/org/exist/storage/RecoverXmlTest.java
  test/src/org/exist/storage/journal/AbstractJournalTest.java
  test/src/org/exist/storage/journal/JournalBinaryTest.java
  test/src/org/exist/storage/journal/JournalXmlTest.java
  test/src/org/exist/test/ExistEmbeddedServer.java
Labels: bug

#2251 (4.x.x) Fix an issue with lock lifetime when changing permissions
  src/org/exist/security/PermissionFactory.java
Labels: bug

#2250 Develop: Update location of JAI downloads
  extensions/images/README
Labels: bug
