Repository eXist-db/exist, pull requests merged in 2018-03, with the labels that each got.

#1755 Remove reference to old Webdav interface
  tools/jetty/etc/standalone/WEB-INF/web.xml
Labels: bug

#1759 Fix parsing of qnames in XQuery
  src/org/exist/xquery/parser/DeclScanner.java
  src/org/exist/xquery/parser/DeclScannerTokenTypes.java
  src/org/exist/xquery/parser/DeclScannerTokenTypes.txt
  src/org/exist/xquery/parser/XQuery.g
  src/org/exist/xquery/parser/XQueryLexer.java
  src/org/exist/xquery/parser/XQueryLexer.smap
  src/org/exist/xquery/parser/XQueryParser.java
  src/org/exist/xquery/parser/XQueryParser.smap
  src/org/exist/xquery/parser/XQueryTokenTypes.java
  src/org/exist/xquery/parser/XQueryTokenTypes.txt
  src/org/exist/xquery/parser/XQueryTreeParser.java
  src/org/exist/xquery/parser/XQueryTreeParserTokenTypes.java
  src/org/exist/xquery/parser/XQueryTreeParserTokenTypes.txt
  test/src/xquery/maps/maps.xql
Labels: bug, needs documentation

#1760 Some further test fixes
  extensions/indexes/range/test/src/xquery/field-type.xql
  extensions/indexes/range/test/src/xquery/index-keys.xql
  src/org/exist/xquery/functions/map/AbstractMapType.java
  src/org/exist/xquery/lib/xqsuite/xqsuite.xql
  test/src/org/exist/test/runner/ExtTestErrorFunction.java
Labels: bug, enhancement

#1751 Further removal of test logging to StdOut/StdErr
  test/src/org/exist/storage/RecoveryTest.java
  test/src/org/exist/storage/RecoveryTest3.java
  test/src/org/exist/storage/ReindexTest.java
  test/src/org/exist/storage/ShutdownTest.java
  test/src/org/exist/xmldb/ResourceTest.java
Labels: cleanup

#1774 [bugfix] Close input stream in fn:json-doc
  src/org/exist/xquery/functions/fn/JSON.java
Labels: high prio

#1776 Add more Travis CI JDKs (including Java 9)
  .travis.yml
Labels: enhancement

#1770 Some small fixes to BrokerPool shutdown
  src/org/exist/plugin/PluginsManager.java
  src/org/exist/plugin/PluginsManagerImpl.java
  src/org/exist/storage/BrokerPool.java
Labels: bug, enhancement

#1763 Range index returns invalid results
  extensions/indexes/range/src/org/exist/indexing/range/NodesFilter.java
  extensions/indexes/range/src/org/exist/indexing/range/RangeIndexWorker.java
Labels: bug, high prio

#1775 Random 0-byte XML docs in db
  src/org/exist/Indexer.java
  src/org/exist/repo/Deployment.java
Labels: bug, high prio

#1766 Explicitly set TMP directory for wrapper
  tools/yajsw/conf/wrapper.conf.in
Labels: enhancement, in progress

#1777 Closing inputstreams and improve ByteArrayOutputStream usage
  extensions/contentextraction/src/org/exist/contentextraction/ContentExtraction.java
  extensions/exiftool/src/org/exist/exiftool/xquery/MetadataFunctions.java
  extensions/expath/src/org/expath/exist/ZipFileFunctions.java
  extensions/fluent/src/org/exist/fluent/Source.java
  extensions/fluent/test/src/org/exist/fluent/XMLDocumentTest.java
  extensions/modules/src/org/exist/xquery/modules/compression/GZipFunction.java
  extensions/modules/src/org/exist/xquery/modules/exi/DecodeExiFunction.java
  extensions/modules/src/org/exist/xquery/modules/exi/EXIUtils.java
  extensions/modules/src/org/exist/xquery/modules/exi/EncodeExiFunction.java
  extensions/modules/src/org/exist/xquery/modules/file/FileRead.java
  extensions/modules/src/org/exist/xquery/modules/ftpclient/SendFileFunction.java
  extensions/modules/src/org/exist/xquery/modules/httpclient/BaseHTTPClientFunction.java
  extensions/modules/src/org/exist/xquery/modules/image/CropFunction.java
  extensions/modules/src/org/exist/xquery/modules/image/GetHeightFunction.java
  extensions/modules/src/org/exist/xquery/modules/image/GetMetadataFunction.java
  extensions/modules/src/org/exist/xquery/modules/image/GetWidthFunction.java
  extensions/modules/src/org/exist/xquery/modules/image/ScaleFunction.java
  extensions/modules/src/org/exist/xquery/modules/mail/MessageFunctions.java
  extensions/modules/src/org/exist/xquery/modules/mail/SendEmailFunction.java
  samples/src/org/exist/examples/http/PostExample.java
  samples/src/org/exist/examples/http/PutExample.java
  src/org/exist/backup/ZipArchiveBackupDescriptor.java
  src/org/exist/dom/persistent/ElementImpl.java
  src/org/exist/dom/persistent/XMLUtil.java
  src/org/exist/protocolhandler/embedded/InMemoryInputStream.java
  src/org/exist/protocolhandler/embedded/InMemoryOutputStream.java
  src/org/exist/util/io/MemoryFilterInputStreamCache.java
  src/org/exist/xquery/value/BinaryValueFromBinaryString.java
  test/src/org/exist/security/RestApiSecurityTest.java
  test/src/org/exist/storage/RecoverBinaryTest.java
  test/src/org/exist/util/io/CachingFilterInputStreamTest_NonMarkableByteArrayInputStream.java
  test/src/org/exist/xmldb/CreateCollectionsTest.java
  test/src/org/exist/xquery/EmbeddedBinariesTest.java
  test/src/org/exist/xquery/RestBinariesTest.java
  test/src/org/exist/xquery/value/Base64BinaryValueTypeTest.java
  test/src/org/exist/xquery/value/BinaryValueFromBinaryStringTest.java
  test/src/org/exist/xquery/value/BinaryValueFromInputStreamTest.java
Labels: enhancement

#1787 [ignore] Improve error message
  src/org/exist/backup/restore/RestoreHandler.java
  src/org/exist/backup/restore/SystemImportHandler.java
Labels: enhancement

#1784 Some improvements to the XML RPC code
  src/org/exist/xmldb/DatabaseImpl.java
  src/org/exist/xmlrpc/ExistRpcTypeFactory.java
  src/org/exist/xmlrpc/RpcAPI.java
  src/org/exist/xmlrpc/RpcConnection.java
  src/org/exist/xmlrpc/RpcServlet.java
  src/org/exist/xmlrpc/TupleParser.java
  src/org/exist/xmlrpc/TupleSerializer.java
  test/src/org/exist/xmlrpc/XmlRpcTest.java
Labels: bug, enhancement

#1791 [bugfix] Update IntelliJ Idea files for latest AspectJ
  .idea/compiler.xml
Labels: bug

#1783 [doc] Correct typo in method signature
  extensions/modules/src/org/exist/xquery/modules/compression/UnZipFunction.java
Labels: bug
