Repository eXist-db/exist, pull requests merged in 2018-09, with the labels that each got.

#2125 (4.x.x) Repair output JMX servlet to contain all eXist-db specific information.
  src/org/exist/management/impl/JMXAgent.java
  test/src/org/exist/management/JmxRemoteTest.java
Labels: bug, needs 5.0.0 backport, needs develop port, regression

#2117 Correct jmx option parsing
  bin/functions.d/getopt-settings.sh
Labels: bug

#2128 Fix bugs in CropFunction
  extensions/modules/src/org/exist/xquery/modules/image/CropFunction.java
Labels: bug

#2135 Fix bugs in CropFunction
  extensions/modules/src/org/exist/xquery/modules/image/CropFunction.java
Labels: bug

#2133 (5.0.0) Correct jmx option parsing
  bin/functions.d/getopt-settings.sh
Labels: bug

#2130 Add option to use MultiLock for Documents
  lib/core/multilock-1.0-SNAPSHOT.jar
  src/org/exist/storage/lock/LockManager.java
  test/src/org/exist/storage/lock/LockManagerTest.java
Labels: enhancement

#2144 Bugfix: Fixes in SQL module (#2139)
  extensions/modules/src/org/exist/xquery/modules/sql/ExecuteFunction.java
  test/src/org/exist/xquery/modules/sql/ExecuteFunctionTest.java
Labels: needs 4.x.x backport, needs 5.0.0 backport

#2161 Fix a regression for loading modules from non-XMLDB URI
  src/org/exist/source/SourceFactory.java
Labels: bug, regression

#2162 (4.x.x) Fix a regression for loading modules from non-XMLDB URI
  src/org/exist/source/SourceFactory.java
Labels: bug, regression

#2167 Don't forget to clean before build
  exist-versioning-release.md
Labels: enhancement

#2164 Add some missing files to the dist
  build/scripts/dist.xml
Labels: bug

#2165 (5.0.0) Add some missing files to the dist
  build/scripts/dist.xml
Labels: bug

#2166 (4.x.x) Add some missing files to the dist
  build/scripts/dist.xml
Labels: bug

#2145 Add options for securing the XML Parser
  conf.xml.tmpl
  src/org/exist/util/Configuration.java
  src/org/exist/util/XMLReaderPool.java
  test/src/org/exist/util/XMLReaderSecurityTest.java
Labels: enhancement, needs documentation

#2147 (4.x.x) Add options for securing the XML Parser
  conf.xml.tmpl
  src/org/exist/util/Configuration.java
  src/org/exist/util/XMLReaderPool.java
  test/src/org/exist/util/XMLReaderSecurityTest.java
Labels: enhancement

#2146 (5.0.0) Add options for securing the XML Parser
  conf.xml.tmpl
  src/org/exist/util/Configuration.java
  src/org/exist/util/XMLReaderPool.java
  test/src/org/exist/util/XMLReaderSecurityTest.java
Labels: enhancement
