Repository eXist-db/exist, pull requests merged in 2018-05, with the labels that each got.

#1852 Fixup of PR #1668
  src/org/exist/source/ClassLoaderSource.java
  test/src/org/exist/source/SourceFactoryTest.java
Labels: enhancement

#1859 Load XSuite resources from classpath
  test/src/org/exist/test/runner/XMLTestRunner.java
  test/src/org/exist/test/runner/XQueryTestRunner.java
Labels: bug, enhancement

#1865 Test for a module stored in the DB importing a module from the classpath
  test/src/org/exist/xquery/XQueryTest.java
  test/src/org/exist/xquery/external-classpath-module.xqm
Labels: enhancement

#1860 Replaced reflective construction with Constructor functions
  extensions/indexes/lucene/src/org/exist/indexing/lucene/AnalyzerConfig.java
  extensions/indexes/lucene/src/org/exist/indexing/lucene/ClassicQueryParserWrapper.java
  extensions/indexes/lucene/src/org/exist/indexing/lucene/QueryParserWrapper.java
  extensions/indexes/range/src/org/exist/indexing/range/RangeIndexAnalyzer.java
  src/org/exist/config/Configurator.java
  src/org/exist/config/mapper/Constructor.java
  src/org/exist/http/RESTServer.java
  src/org/exist/plugin/PluginsManagerImpl.java
  src/org/exist/repo/ExistRepository.java
  src/org/exist/storage/BrokerFactory.java
  src/org/exist/util/io/FilterInputStreamCacheFactory.java
  src/org/exist/xquery/Function.java
  src/org/exist/xquery/XQueryContext.java
  src/org/exist/xquery/util/NumberFormatter.java
  src/org/exist/xquery/value/BinaryValueType.java
Labels: enhancement

#1857 Fixup PR-1679
  src/org/exist/indexing/IndexManager.java
  src/org/exist/storage/BrokerPool.java
  src/org/exist/storage/DBBroker.java
  src/org/exist/storage/NativeBroker.java
  src/org/exist/util/TimestampedReference.java
  test/src/org/exist/storage/IndexManagerTest.java
  test/src/org/exist/storage/MoveOverwriteResourceTest.java
  test/src/org/exist/util/TimestampedReferenceTest.java
  test/src/org/exist/xquery/update/IndexIntegrationTest.java
Labels: enhancement

#1829 set timeout via util:eval-with-context
  src/org/exist/xquery/functions/util/Eval.java
  test/src/xquery/util/eval-with-context.xql
Labels: enhancement

#1883 Fix NPE when uploading (large) document from Java client
  src/org/exist/xmldb/RemoteCollection.java
  test/src/org/exist/xmldb/RemoteCollectionTest.java
Labels: bug, high prio, regression

#1885 Written day of week was off by +1
  src/org/exist/xquery/functions/fn/FnFormatDates.java
  src/org/exist/xquery/value/AbstractDateTimeValue.java
  test/src/xquery/dates/format-dates.xql
Labels: bug

#1886 Added %test:assumeInternetAccess to XQSuite
  src/org/exist/xquery/lib/xqsuite/xqsuite.xql
  test/src/org/exist/test/runner/ExtTestAssumptionFailedFunction.java
  test/src/xquery/unparsed-text.xql
Labels: bug, enhancement

#1890 Fix isolation between tests on Windows
  test/src/org/exist/storage/AllStorageTests.java
  test/src/org/exist/storage/CopyCollectionRecoveryTest.java
  test/src/org/exist/storage/CopyResourceRecoveryTest.java
  test/src/org/exist/storage/MoveCollectionRecoveryTest.java
  test/src/org/exist/storage/MoveResourceRecoveryTest.java
Labels: bug
