Repository eXist-db/exist, pull requests merged in 2018-04, with the labels that each got.

#1794 Small fixes and cleanup in Lucene index code
  extensions/indexes/lucene/src/org/exist/indexing/lucene/LuceneIndexWorker.java
  extensions/indexes/lucene/src/org/exist/indexing/lucene/LuceneMatchListener.java
  extensions/indexes/lucene/src/org/exist/indexing/lucene/LuceneUtil.java
  extensions/indexes/lucene/src/org/exist/indexing/lucene/PlainTextHighlighter.java
  extensions/indexes/lucene/src/org/exist/xquery/modules/lucene/Score.java
Labels: bug, cleanup

#1795 Cleanup XQueryURLRewrite
  src/org/exist/http/urlrewrite/ControllerForward.java
  src/org/exist/http/urlrewrite/Forward.java
  src/org/exist/http/urlrewrite/ModuleCall.java
  src/org/exist/http/urlrewrite/PassThrough.java
  src/org/exist/http/urlrewrite/PathForward.java
  src/org/exist/http/urlrewrite/Redirect.java
  src/org/exist/http/urlrewrite/RewriteConfig.java
  src/org/exist/http/urlrewrite/URLRewrite.java
  src/org/exist/http/urlrewrite/XQueryURLRewrite.java
Labels: cleanup, enhancement

#1797 Fix a regression introduced in PR #1795
  src/org/exist/http/urlrewrite/XQueryURLRewrite.java
Labels: bug

#1798 Small improvements and cleanup to binary handling
  extensions/exquery/restxq/src/main/java/org/exist/extensions/exquery/restxq/impl/RestXqServiceRegistryPersistence.java
  extensions/modules/src/org/exist/xquery/modules/expathrepo/Deploy.java
  extensions/modules/src/org/exist/xquery/modules/file/FileReadBinary.java
  src/org/exist/backup/ZipArchiveBackupDescriptor.java
  src/org/exist/http/RESTServer.java
  src/org/exist/http/servlets/HttpRequestWrapper.java
  src/org/exist/http/servlets/HttpServletRequestWrapper.java
  src/org/exist/http/servlets/RequestWrapper.java
  src/org/exist/protocolhandler/embedded/EmbeddedUpload.java
  src/org/exist/repo/RepoBackup.java
  src/org/exist/util/IterableEnumeration.java
  src/org/exist/util/VirtualTempFile.java
  src/org/exist/util/VirtualTempFileInputSource.java
  src/org/exist/util/io/Resource.java
  src/org/exist/util/io/TemporaryFileManager.java
  src/org/exist/xmldb/AbstractRemoteResource.java
  src/org/exist/xmldb/RemoteBinaryResource.java
  src/org/exist/xmldb/RemoteResourceSet.java
  src/org/exist/xmldb/RemoteXMLResource.java
  src/org/exist/xmlrpc/RpcConnection.java
  src/org/exist/xquery/functions/request/GetUploadedFile.java
  src/org/exist/xquery/functions/request/GetUploadedFileSize.java
  src/org/exist/xquery/functions/validation/Jaxp.java
  src/org/exist/xquery/functions/xmldb/XMLDBStore.java
  src/org/exist/xquery/value/BinaryValue.java
  src/org/exist/xquery/value/BinaryValueFromFile.java
  test/src/org/exist/util/VirtualTempFileTest.java
Labels: cleanup

#1800 Fix EXPath HTTP Client socket-closed regression
  extensions/expath/lib/http-client-java-1.0-SNAPSHOT.jar
  extensions/expath/src/org/expath/httpclient/model/exist/EXistResult.java
  extensions/expath/test/src/org/expath/exist/HttpClientTest.java
  src/org/exist/xquery/value/BinaryValueFromFile.java
Labels: regression

#1805 Fix regression with Binary values from Files and Strings
  src/org/exist/xquery/value/BinaryValueFromBinaryString.java
  src/org/exist/xquery/value/BinaryValueFromFile.java
  test/src/xquery/modules/file/read-binary.xql
Labels: bug

#1804 Atomic Move cannot be used where src and dest are on different fs
  extensions/exquery/restxq/src/main/java/org/exist/extensions/exquery/restxq/impl/RestXqServiceRegistryPersistence.java
  extensions/modules/src/org/exist/xquery/modules/file/FileMove.java
Labels: bug

#1806 Small test fix for parallel execution
  test/src/org/exist/dom/persistent/SymbolTableTest.java
  test/src/org/exist/storage/lock/ProtectedModeTest.java
Labels: bug

#1808 Fix regression in chunked transfer of XML-RPC
  src/org/exist/xmlrpc/RpcConnection.java
  test/src/org/exist/xmlrpc/XmlRpcTest.java
Labels: bug

#1807 Some small fixes to XML:DB management of XmlRpcClient and cleanup
  src/org/exist/util/Leasable.java
  src/org/exist/xmldb/AbstractRemoteResource.java
  src/org/exist/xmldb/DatabaseImpl.java
  src/org/exist/xmldb/RemoteBinaryResource.java
  src/org/exist/xmldb/RemoteCollection.java
  src/org/exist/xmldb/RemoteCollectionManagementService.java
  src/org/exist/xmldb/RemoteResourceIterator.java
  src/org/exist/xmldb/RemoteResourceSet.java
  src/org/exist/xmldb/RemoteUserManagementService.java
  src/org/exist/xmldb/RemoteXMLResource.java
  src/org/exist/xmldb/RemoteXPathQueryService.java
  src/org/exist/xmldb/RemoteXUpdateQueryService.java
Labels: bug

#1809 [bugfix] Align xml:id handling with saxon and basex
  src/org/exist/Indexer.java
  src/org/exist/xquery/DynamicAttributeConstructor.java
  test/src/xquery/xmlid.xql
Labels: bug

#1812 Ensure that finalize does not call close for a second time
  src/org/exist/start/ServiceDaemon.java
  src/org/exist/xmldb/AbstractEXistResource.java
  src/org/exist/xmldb/AbstractRemoteResource.java
  src/org/exist/xmldb/EXistResource.java
  src/org/exist/xmldb/LocalBinaryResource.java
  src/org/exist/xmldb/LocalXMLResource.java
  src/org/exist/xmldb/RemoteResourceSet.java
  src/org/exist/xmlrpc/AbstractCachedResult.java
  src/org/exist/xmlrpc/QueryResult.java
  src/org/exist/xmlrpc/SerializedResult.java
  tools/jsvc/commons-daemon.jar
  tools/jsvc/exist-init.d.sh
  tools/jsvc/exist.sh
  tools/jsvc/jsvc.tar.gz
Labels: bug

#1814 Add functx XAR for usermanager
  build.properties
Labels: high prio

#1818 Fix java.lang.IllegalArgumentException thrown by FastByteArrayOutputStream
  extensions/modules/src/org/exist/xquery/modules/compression/AbstractCompressFunction.java
Labels: bug

#1819 Fix the DMG build on newer versions of OSX
  build/scripts/macosx.xml
Labels: bug

#1825 Added XQSuite to exist-testkit.jar
  build/scripts/build-impl.xml
Labels: enhancement

#1835 [bugfix] Fix AppVeyor builds on branches
  appveyor.yml
Labels: bug

#1837 Fix a regression in RESTXQ registry
  extensions/exquery/restxq/src/main/java/org/exist/extensions/exquery/restxq/impl/RestXqServiceRegistryPersistence.java
Labels: bug

#1839 A few small cleanups
  src/org/exist/dom/persistent/SymbolTable.java
  src/org/exist/indexing/AbstractIndex.java
  src/org/exist/indexing/Index.java
  src/org/exist/storage/btree/Paged.java
  src/org/exist/util/EXistInputSource.java
  src/org/exist/xquery/functions/xmldb/XMLDBSize.java
  src/org/exist/xquery/functions/xmldb/XMLDBTouch.java
  test/src/org/exist/http/RESTServiceTest.java
Labels: cleanup

#1846 [bugfix] repair xmlunit functions
  src/org/exist/start/start.config
Labels: bug, regression
