Repository eXist-db/exist, pull requests merged in 2018-12, with the labels that each got.

#2319 4xx: Repair of missing webstart jar file.
  src/org/exist/webstart/JnlpJarFiles.java
Labels: bug

#2321 Develop: Repair of missing webstart jar file.
  src/org/exist/webstart/JnlpJarFiles.java
Labels: bug

#2326 Develop: Remove JAR file as version v3.0.2 is already present
  lib/core/jsr305-3.0.1.jar
Labels: cleanup

#2325 5xx: Remove JAR file as version v3.0.2 is already present
  lib/core/jsr305-3.0.1.jar
Labels: cleanup

#2344 Compress the JUnit logs from Travis before uploading
  .travis.yml
Labels: bug

#2345 (4.x.x) Compress the JUnit logs from Travis before uploading
  .travis.yml
Labels: bug

#2346 (5.0.0) Compress the JUnit logs from Travis before uploading
  .travis.yml
Labels: bug

#2347 [doc] Acknowledge BinTray's generous service
  README.md
Labels: enhancement

#2348 Move from Ubuntu Trusty to Xenial on Travis-CI
  .travis.yml
Labels: enhancement, high prio

#2350 (5.0.0) Move from Ubuntu Trusty to Xenial on Travis-CI
  .travis.yml
Labels: enhancement, high prio

#2349 (4.x.x) Move from Ubuntu Trusty to Xenial on Travis-CI
  .travis.yml
Labels: enhancement, high prio

#2329 (4.x.x) Fix an ArrayOutOfBoundException with array:get
  src/org/exist/xquery/functions/array/ArrayFunction.java
  src/org/exist/xquery/functions/array/ArrayType.java
  test/src/xquery/arrays/arrays.xql
Labels: bug

#2328 Fix an ArrayOutOfBoundException with array:get
  src/org/exist/xquery/functions/array/ArrayFunction.java
  src/org/exist/xquery/functions/array/ArrayType.java
  test/src/xquery/arrays/arrays.xql
Labels: bug

#2330 (5.0.0) Fix an ArrayOutOfBoundException with array:get
  src/org/exist/xquery/functions/array/ArrayFunction.java
  src/org/exist/xquery/functions/array/ArrayType.java
  test/src/xquery/arrays/arrays.xql
Labels: bug

#2337 Improve Java Admin Client Shell
  .classpath
  lib/core/jansi-1.17.1.jar
  lib/core/jansi-LICENSE.txt
  lib/core/jline-0.9.94.jar
  lib/core/jline-3.9.0.jar
  lib/core/jline-LICENSE.txt
  nbproject/project.properties
  src/org/exist/client/ClientFrame.java
  src/org/exist/client/InteractiveClient.java
  src/org/exist/start/start.config
  src/org/exist/webstart/JnlpJarFiles.java
Labels: bug, enhancement

#2336 (4.x.x) Improve Java Admin Client Shell
  .classpath
  lib/core/jansi-1.17.1.jar
  lib/core/jansi-LICENSE.txt
  lib/core/jline-0.9.94.jar
  lib/core/jline-3.9.0.jar
  lib/core/jline-LICENSE.txt
  nbproject/project.properties
  src/org/exist/client/ClientFrame.java
  src/org/exist/client/InteractiveClient.java
  src/org/exist/start/start.config
  src/org/exist/webstart/JnlpJarFiles.java
Labels: bug, enhancement

#2338 (5.0.0) Improve Java Admin Client Shell
  .classpath
  lib/core/jansi-1.17.1.jar
  lib/core/jansi-LICENSE.txt
  lib/core/jline-0.9.94.jar
  lib/core/jline-3.9.0.jar
  lib/core/jline-LICENSE.txt
  nbproject/project.properties
  src/org/exist/client/ClientFrame.java
  src/org/exist/client/InteractiveClient.java
  src/org/exist/start/start.config
  src/org/exist/webstart/JnlpJarFiles.java
Labels: bug, enhancement
