Repository eXist-db/exist, pull requests merged in 2018-06, with the labels that each got.

#1905 EXPath HTTP Client must respect character encoding
  extensions/expath/lib/http-client-java-1.0-SNAPSHOT.jar
Labels: bug

#1904 Small improvements to XML:DB Remote Collection
  src/org/exist/xmldb/RemoteCollection.java
Labels: enhancement

#1900 Fix an issue with recycling of temp files.
  src/org/exist/util/io/TemporaryFileManager.java
Labels: bug, windows

#1902 Set the HTTP response character encoding for XML-RPC
  src/org/exist/xmlrpc/RpcServlet.java
  webapp/WEB-INF/web.xml.tmpl
Labels: enhancement

#1897 Security fixes to mitigate Zip/Tar file exit attacks when decompressing archives.
  extensions/modules/src/org/exist/xquery/modules/compression/AbstractExtractFunction.java
  extensions/modules/src/org/exist/xquery/modules/compression/CompressionModule.java
  extensions/modules/src/org/exist/xquery/modules/compression/EntryFunctions.java
  extensions/modules/src/org/exist/xquery/modules/compression/UnTarFunction.java
  extensions/modules/src/org/exist/xquery/modules/compression/UnZipFunction.java
  extensions/modules/src/org/exist/xquery/modules/file/DirectoryCreate.java
  src/org/exist/backup/ZipArchiveBackupDescriptor.java
  src/org/exist/client/InteractiveClient.java
  src/org/exist/repo/RepoBackup.java
  src/org/exist/util/Compressor.java
Labels: bug, enhancement, security

#1907 Memory leak in higher-order functions
  extensions/exquery/restxq/src/main/java/org/exist/extensions/exquery/restxq/impl/ResourceFunctionExecutorImpl.java
  extensions/indexes/ngram/src/org/exist/xquery/modules/ngram/HighlightMatches.java
  extensions/indexes/range/src/org/exist/xquery/modules/range/IndexKeys.java
  extensions/modules/src/org/exist/xquery/modules/compression/AbstractExtractFunction.java
  extensions/modules/src/org/exist/xquery/modules/persistentlogin/PersistentLoginFunctions.java
  src/org/exist/xquery/ArrowOperator.java
  src/org/exist/xquery/DynamicFunctionCall.java
  src/org/exist/xquery/InlineFunction.java
  src/org/exist/xquery/UserDefinedFunction.java
  src/org/exist/xquery/XQueryContext.java
  src/org/exist/xquery/functions/array/ArrayFunction.java
  src/org/exist/xquery/functions/fn/FunHigherOrderFun.java
  src/org/exist/xquery/functions/fn/FunSort.java
  src/org/exist/xquery/functions/map/MapFunction.java
  src/org/exist/xquery/functions/util/CallFunction.java
  src/org/exist/xquery/functions/util/IndexKeys.java
  src/org/exist/xquery/value/FunctionReference.java
Labels: bug, high prio

#1909 Allow JAVA_HOME or java from the PATH for YAJSW build
  tools/yajsw/build.xml
Labels: enhancement

#1910 XQueryURLRewrite challenge is now configurable
  src/org/exist/http/urlrewrite/XQueryURLRewrite.java
  webapp/WEB-INF/web.xml.tmpl
Labels: enhancement, needs documentation

#1911 Fix empty namespace serialization issues
  extensions/webdav/src/org/exist/webdav/ExistDocument.java
  src/org/exist/http/RESTServer.java
  src/org/exist/storage/NativeBroker.java
  src/org/exist/storage/serializers/NativeSerializer.java
  src/org/exist/util/serializer/IndentingXMLWriter.java
  src/org/exist/util/serializer/MicroXmlWriter.java
  src/org/exist/util/serializer/SAXSerializer.java
  src/org/exist/util/serializer/TEXTWriter.java
  src/org/exist/util/serializer/XMLWriter.java
  src/org/exist/util/serializer/json/JSONWriter.java
  src/org/exist/xmldb/LocalXMLResource.java
  src/org/exist/xmlrpc/RpcConnection.java
  test/src/org/exist/test/ExistEmbeddedServer.java
  test/src/org/exist/test/ExistXmldbEmbeddedServer.java
  test/src/org/exist/xmldb/SerializationTest.java
  test/src/org/exist/xmldb/XmldbLocalTests.java
Labels: bug

#1888 Fix security issues with doc/collection mode/owner during copy
  src/org/exist/collections/MutableCollection.java
  src/org/exist/dom/persistent/BinaryDocument.java
  src/org/exist/dom/persistent/DocumentImpl.java
  src/org/exist/security/Permission.java
  src/org/exist/security/SimpleACLPermission.java
  src/org/exist/security/UnixStylePermission.java
  src/org/exist/security/internal/aider/UnixStylePermissionAider.java
  src/org/exist/storage/NativeBroker.java
  test/src/org/exist/dom/persistent/DocumentImplTest.java
  test/src/org/exist/storage/AllStorageTests.java
  test/src/org/exist/storage/CopyCollectionTest.java
  test/src/org/exist/storage/CopyResourceTest.java
Labels: bug, security

#1903 Compressor now uses GZip encoding
  src/org/exist/util/Compressor.java
Labels: enhancement, needs documentation

#1893 Fix security issues with chown/chmod
  conf.xml.tmpl
  extensions/fluent/src/org/exist/fluent/Document.java
  extensions/fluent/src/org/exist/fluent/Folder.java
  extensions/fluent/src/org/exist/fluent/NamedResource.java
  extensions/scheduler/src/main/java/org/exist/scheduler/SchedulerManager.java
  src/org/exist/backup/restore/SystemImportHandler.java
  src/org/exist/collections/Collection.java
  src/org/exist/collections/MutableCollection.java
  src/org/exist/collections/triggers/XQueryStartupTrigger.java
  src/org/exist/config/Configurator.java
  src/org/exist/dom/persistent/DocumentImpl.java
  src/org/exist/plugin/PluginsManagerImpl.java
  src/org/exist/security/ACLPermission.java
  src/org/exist/security/AbstractUnixStylePermission.java
  src/org/exist/security/Permission.java
  src/org/exist/security/PermissionFactory.java
  src/org/exist/security/PermissionRequired.java
  src/org/exist/security/PermissionRequiredAspect.java
  src/org/exist/security/SimpleACLPermission.java
  src/org/exist/security/UnixStylePermission.java
  src/org/exist/security/internal/SecurityManagerImpl.java
  src/org/exist/security/internal/aider/SimpleACLPermissionAider.java
  src/org/exist/security/internal/aider/UnixStylePermissionAider.java
  src/org/exist/security/utils/Utils.java
  src/org/exist/storage/BrokerPool.java
  src/org/exist/storage/DBBroker.java
  src/org/exist/storage/NativeBroker.java
  src/org/exist/util/Configuration.java
  src/org/exist/util/io/Resource.java
  src/org/exist/xmldb/LocalUserManagementService.java
  src/org/exist/xmlrpc/RpcAPI.java
  src/org/exist/xmlrpc/RpcConnection.java
  src/org/exist/xquery/functions/securitymanager/PermissionsFunction.java
  test/src/org/exist/security/XMLDBSecurityTest.java
  test/src/org/exist/storage/CopyCollectionRecoveryTest.java
  test/src/org/exist/storage/CopyCollectionTest.java
  test/src/org/exist/storage/CopyResourceTest.java
  test/src/org/exist/xmldb/XmldbLocalTests.java
  test/src/org/exist/xquery/functions/securitymanager/PermissionsFunctionChmodTest.java
  test/src/org/exist/xquery/functions/securitymanager/PermissionsFunctionChownTest.java
  test/src/org/exist/xquery/functions/securitymanager/PermissionsFunctionModeConversionTest.java
Labels: bug, security

#1894 Implement preserve for copy
  conf.xml.tmpl
  src/org/exist/collections/Collection.java
  src/org/exist/collections/MutableCollection.java
  src/org/exist/repo/Deployment.java
  src/org/exist/security/PermissionFactory.java
  src/org/exist/storage/DBBroker.java
  src/org/exist/storage/NativeBroker.java
  src/org/exist/util/Configuration.java
  src/org/exist/xmldb/EXistCollectionManagementService.java
  src/org/exist/xmldb/LocalCollectionManagementService.java
  src/org/exist/xmldb/RemoteCollectionManagementService.java
  src/org/exist/xmlrpc/RpcAPI.java
  src/org/exist/xmlrpc/RpcConnection.java
  src/org/exist/xquery/functions/securitymanager/PermissionsFunction.java
  src/org/exist/xquery/functions/xmldb/XMLDBCopy.java
  src/org/exist/xquery/functions/xmldb/XMLDBModule.java
  test/src/org/exist/storage/CopyCollectionTest.java
  test/src/org/exist/storage/CopyResourceTest.java
Labels: enhancement

#1914 [feature] Implement xmldb:copy-resource and xmldb:copy-collection whi…
  src/org/exist/xquery/functions/xmldb/XMLDBCopy.java
  src/org/exist/xquery/functions/xmldb/XMLDBModule.java
Labels: enhancement

#1920 Fix an issue with uploading compressed zip entries with XML:DB Remote API
  src/org/exist/util/EXistInputSource.java
  src/org/exist/xmldb/AbstractRemoteResource.java
  src/org/exist/xmldb/EXistResource.java
  src/org/exist/xmldb/ExtendedResource.java
  src/org/exist/xmldb/RemoteCollection.java
Labels: bug

#1921 Fix an issue with uploading compressed zip entries with XML:DB Remote API
  src/org/exist/util/EXistInputSource.java
  src/org/exist/xmldb/AbstractRemoteResource.java
  src/org/exist/xmldb/EXistResource.java
  src/org/exist/xmldb/ExtendedResource.java
  src/org/exist/xmldb/RemoteCollection.java
Labels: bug

#1919 Do not restrict the XML:DB API Local nodes
  src/org/exist/xmldb/LocalXMLResource.java
  test/src/org/exist/xmldb/LocalXMLResourceDOMTest.java
  test/src/org/exist/xmldb/XmldbLocalTests.java
Labels: bug, enhancement

#1929 Align function signatures with XQuery 3.1 F&O
  src/org/exist/xquery/functions/array/ArrayFunction.java
  src/org/exist/xquery/functions/fn/FnFormatDates.java
  src/org/exist/xquery/functions/fn/FnFormatNumbers.java
  src/org/exist/xquery/functions/fn/FunAbs.java
  src/org/exist/xquery/functions/fn/FunCeiling.java
  src/org/exist/xquery/functions/fn/FunConcat.java
  src/org/exist/xquery/functions/fn/FunCurrentDateTime.java
  src/org/exist/xquery/functions/fn/FunEndsWith.java
  src/org/exist/xquery/functions/fn/FunEnvironment.java
  src/org/exist/xquery/functions/fn/FunError.java
  src/org/exist/xquery/functions/fn/FunFloor.java
  src/org/exist/xquery/functions/fn/FunGetDurationComponent.java
  src/org/exist/xquery/functions/fn/FunLast.java
  src/org/exist/xquery/functions/fn/FunMatches.java
  src/org/exist/xquery/functions/fn/FunName.java
  src/org/exist/xquery/functions/fn/FunPosition.java
  src/org/exist/xquery/functions/fn/FunReplace.java
  src/org/exist/xquery/functions/fn/FunResolveQName.java
  src/org/exist/xquery/functions/fn/FunRound.java
  src/org/exist/xquery/functions/fn/FunRoundHalfToEven.java
  src/org/exist/xquery/functions/fn/FunStartsWith.java
  src/org/exist/xquery/functions/fn/FunStrLength.java
  src/org/exist/xquery/functions/fn/FunStringJoin.java
  src/org/exist/xquery/functions/fn/FunSubstring.java
  src/org/exist/xquery/functions/fn/FunSubstringAfter.java
  src/org/exist/xquery/functions/fn/FunSubstringBefore.java
  src/org/exist/xquery/functions/fn/FunSum.java
  src/org/exist/xquery/functions/fn/FunUnparsedText.java
  src/org/exist/xquery/functions/fn/ParsingFunctions.java
  src/org/exist/xquery/functions/map/MapFunction.java
  src/org/exist/xquery/functions/math/OneParamFunctions.java
  src/org/exist/xquery/functions/math/TwoParamFunctions.java
  src/org/exist/xquery/value/Type.java
Labels: enhancement

#1931 Make Http Servlets Transaction aware
  src/org/exist/http/RESTServer.java
  src/org/exist/http/servlets/EXistServlet.java
  src/org/exist/xmldb/AbstractLocal.java
Labels: bug

#1934 Make sure that Source Factory correctly and safely resolves sources
  extensions/exiftool/src/org/exist/exiftool/xquery/MetadataFunctions.java
  extensions/xqdoc/src/org/exist/xqdoc/xquery/Scan.java
  src/org/exist/collections/triggers/XQueryStartupTrigger.java
  src/org/exist/http/servlets/XQueryServlet.java
  src/org/exist/source/SourceFactory.java
  src/org/exist/xquery/XQueryContext.java
  src/org/exist/xquery/functions/fn/FunUnparsedText.java
  src/org/exist/xquery/functions/inspect/ModuleFunctions.java
  src/org/exist/xquery/functions/util/Eval.java
  src/org/exist/xquery/util/DocUtils.java
  test/src/org/exist/source/SourceFactoryTest.java
Labels: bug

#1935 (5.0.0) Make sure that Source Factory correctly and safely resolves sources
  build.properties
  extensions/exiftool/src/org/exist/exiftool/xquery/MetadataFunctions.java
  extensions/xqdoc/src/org/exist/xqdoc/xquery/Scan.java
  src/org/exist/collections/triggers/XQueryStartupTrigger.java
  src/org/exist/http/servlets/XQueryServlet.java
  src/org/exist/source/SourceFactory.java
  src/org/exist/util/serializer/HTML5Writer.java
  src/org/exist/xquery/XQueryContext.java
  src/org/exist/xquery/functions/fn/FunUnparsedText.java
  src/org/exist/xquery/functions/inspect/ModuleFunctions.java
  src/org/exist/xquery/functions/util/Eval.java
  src/org/exist/xquery/util/DocUtils.java
  test/src/org/exist/source/SourceFactoryTest.java
  test/src/org/exist/util/serializer/HTML5WriterTest.java
Labels: bug

#1936 (4.x.x) Make sure that Source Factory correctly and safely resolves sources
  extensions/exiftool/src/org/exist/exiftool/xquery/MetadataFunctions.java
  extensions/xqdoc/src/org/exist/xqdoc/xquery/Scan.java
  src/org/exist/collections/triggers/XQueryStartupTrigger.java
  src/org/exist/http/servlets/XQueryServlet.java
  src/org/exist/source/SourceFactory.java
  src/org/exist/xquery/XQueryContext.java
  src/org/exist/xquery/functions/fn/FunUnparsedText.java
  src/org/exist/xquery/functions/inspect/ModuleFunctions.java
  src/org/exist/xquery/functions/util/Eval.java
  src/org/exist/xquery/util/DocUtils.java
  test/src/org/exist/source/SourceFactoryTest.java
Labels: bug

#1937 (4.x.x) [bugfix] Only omit values for attributes which are considered boolean in HTML5Writer
  src/org/exist/util/serializer/HTML5Writer.java
  test/src/org/exist/util/serializer/HTML5WriterTest.java
Labels: bug

#1953 (4.x.x) Use ErrorCodes for XQuery Errors
  extensions/indexes/ngram/src/org/exist/xquery/modules/ngram/NGramSearch.java
  src/org/exist/xquery/FunctionCall.java
  src/org/exist/xquery/VariableDeclaration.java
  src/org/exist/xquery/XQueryContext.java
  src/org/exist/xquery/functions/fn/FunReplace.java
  src/org/exist/xquery/parser/XQuery.g
  src/org/exist/xquery/parser/XQueryParser.java
  src/org/exist/xquery/parser/XQueryTree.g
  src/org/exist/xquery/parser/XQueryTreeParser.java
  src/org/exist/xquery/value/AbstractSequence.java
  src/org/exist/xquery/value/OrderedDurationValue.java
Labels: bug

#1952 Fix an NPE with XQuery Update and in-memory documents
  src/org/exist/xquery/update/Modification.java
  test/src/org/exist/xquery/update/UpdateInsertTest.java
Labels: bug

#1949 (4.x.x) Fix an NPE with XQuery Update and in-memory documents
  src/org/exist/xquery/update/Modification.java
  test/src/org/exist/xquery/update/UpdateInsertTest.java
Labels: bug

#1954 (5.0.0) Use ErrorCodes for XQuery Errors
  extensions/indexes/ngram/src/org/exist/xquery/modules/ngram/NGramSearch.java
  src/org/exist/xquery/FunctionCall.java
  src/org/exist/xquery/VariableDeclaration.java
  src/org/exist/xquery/XQueryContext.java
  src/org/exist/xquery/functions/fn/FunReplace.java
  src/org/exist/xquery/parser/XQuery.g
  src/org/exist/xquery/parser/XQueryParser.java
  src/org/exist/xquery/parser/XQueryTree.g
  src/org/exist/xquery/parser/XQueryTreeParser.java
  src/org/exist/xquery/value/AbstractSequence.java
  src/org/exist/xquery/value/OrderedDurationValue.java
Labels: bug

#1948 Use ErrorCodes for XQuery Errors
  extensions/indexes/ngram/src/org/exist/xquery/modules/ngram/NGramSearch.java
  src/org/exist/xquery/FunctionCall.java
  src/org/exist/xquery/VariableDeclaration.java
  src/org/exist/xquery/XQueryContext.java
  src/org/exist/xquery/functions/fn/FunReplace.java
  src/org/exist/xquery/parser/XQuery.g
  src/org/exist/xquery/parser/XQueryParser.java
  src/org/exist/xquery/parser/XQueryTree.g
  src/org/exist/xquery/parser/XQueryTreeParser.java
  src/org/exist/xquery/value/AbstractSequence.java
  src/org/exist/xquery/value/OrderedDurationValue.java
Labels: bug

#1951 (5.0.0) Fix an NPE with XQuery Update and in-memory documents
  src/org/exist/xquery/update/Modification.java
  test/src/org/exist/xquery/update/UpdateInsertTest.java
Labels: bug

#1943 [doc] Added steps for Wikipedia and make Homebrew explicit
  exist-versioning-release.md
Labels: enhancement

#1950 (4.x.x) Fixes an issue with restoring zero byte binaries via XML:DB Remote API
  src/org/exist/backup/ZipArchiveBackupDescriptor.java
  src/org/exist/backup/restore/RestoreHandler.java
  src/org/exist/util/Compressor.java
  src/org/exist/xmldb/RemoteCollection.java
  src/org/exist/xmlrpc/RpcConnection.java
Labels: bug, needs 5.0.0 backport, needs develop port

#1955 Fixes an issue with restoring zero byte binaries via XML:DB Remote API
  src/org/exist/backup/ZipArchiveBackupDescriptor.java
  src/org/exist/backup/restore/RestoreHandler.java
  src/org/exist/util/Compressor.java
  src/org/exist/xmldb/RemoteCollection.java
  src/org/exist/xmlrpc/RpcConnection.java
Labels: bug

#1956 (5.0.0) Fixes an issue with restoring zero byte binaries via XML:DB Remote API
  src/org/exist/backup/ZipArchiveBackupDescriptor.java
  src/org/exist/backup/restore/RestoreHandler.java
  src/org/exist/util/Compressor.java
  src/org/exist/xmldb/RemoteCollection.java
  src/org/exist/xmlrpc/RpcConnection.java
Labels: bug

#1961 Fix an XML:DB Local document lock issue
  src/org/exist/xmldb/LocalCollection.java
Labels: bug

#1962 (5.0.0) Fix an XML:DB Local document lock issue
  src/org/exist/xmldb/LocalCollection.java
Labels: bug

#1958 (5.0.0) Replace eXist-db specific util:parse with XPath function
  extensions/indexes/lucene/test/src/org/exist/indexing/lucene/LuceneIndexTest.java
  extensions/xprocxq/main/src/xquery/util.xqm
  src/org/exist/http/run-xproc.xq
  src/org/exist/xquery/functions/util/Parse.java
  src/org/exist/xquery/lib/xqsuite/xqsuite.xql
  test/src/xquery/util/util.xml
  webapp/xqts/xqts.xql
Labels: cleanup, deprecation

#1959 Replace eXist-db specific util:parse with XPath function
  extensions/indexes/lucene/test/src/org/exist/indexing/lucene/LuceneIndexTest.java
  extensions/xprocxq/main/src/xquery/util.xqm
  src/org/exist/http/run-xproc.xq
  src/org/exist/xquery/functions/util/Parse.java
  src/org/exist/xquery/lib/xqsuite/xqsuite.xql
  test/src/xquery/util/util.xml
  webapp/xqts/xqts.xql
Labels: cleanup, deprecation

#1880 Enabled JDK 9 on AppVeyor Ubuntu
  appveyor.yml
Labels: enhancement

#1966 (4.x.x) Fix Java10 signing problem
  build/scripts/jarsigner.xml
Labels: bug

#1967 (5.0.0) Fix Java10 signing problem
  build/scripts/jarsigner.xml
Labels: bug

#1974 Basic support for available documents of Dynamic Context
  src/org/exist/xquery/XQueryContext.java
  src/org/exist/xquery/util/DocUtils.java
  test/src/org/exist/dom/memtree/DocumentImplTest.java
  test/src/org/exist/xquery/functions/fn/DocTest.java
Labels: enhancement

#1978 Summarize errors in the XQSuite testsuite output
  src/org/exist/xquery/lib/xqsuite/xqsuite.xql
Labels: enhancement, needs documentation

#1979 (4.x.x) Summarize errors in the XQSuite testsuite output
  src/org/exist/xquery/lib/xqsuite/xqsuite.xql
Labels: enhancement

#1973 Fixes an issue when constructing MemTrees via SAX parsers
  src/org/exist/dom/memtree/MemTreeBuilder.java
  test/src/org/exist/dom/memtree/MemtreeBuilderTest.java
Labels: bug

#1983 (5.0.0) Fixes an issue when constructing MemTrees via SAX parsers
  src/org/exist/dom/memtree/MemTreeBuilder.java
  test/src/org/exist/dom/memtree/MemtreeBuilderTest.java
Labels: bug

#1982 (4.x.x) Fixes an issue when constructing MemTrees via SAX parsers
  src/org/exist/dom/memtree/MemTreeBuilder.java
  test/src/org/exist/dom/memtree/MemtreeBuilderTest.java
Labels: bug

#1980 (5.0.0) Summarize errors in the XQSuite testsuite output
  src/org/exist/xquery/lib/xqsuite/xqsuite.xql
Labels: enhancement

#1969 (4.x.x) Upgrade Xerces to latest version
  .classpath
  build/scripts/junit.xml
  lib/endorsed/cupv10k-runtime-LICENSE.txt
  lib/endorsed/cupv10k-runtime.jar
  lib/endorsed/org.eclipse.wst.xml.xpath2.processor-1.2.0.jar
  lib/endorsed/xercesImpl-2.11.0.jar
  lib/endorsed/xercesImpl-2.12.0.jar
  nbproject/project.properties
  test/src/xquery/validation/ValidationTests.java
  test/src/xquery/validation/jaxv.xql
Labels: enhancement, security

#1970 (5.0.0) Upgrade Xerces to latest version
  .classpath
  build/scripts/junit.xml
  lib/endorsed/cupv10k-runtime-LICENSE.txt
  lib/endorsed/cupv10k-runtime.jar
  lib/endorsed/org.eclipse.wst.xml.xpath2.processor-1.2.0.jar
  lib/endorsed/xercesImpl-2.11.0.jar
  lib/endorsed/xercesImpl-2.12.0.jar
  nbproject/project.properties
  test/src/xquery/validation/ValidationTests.java
  test/src/xquery/validation/jaxv.xql
Labels: enhancement, security

#1984 (develop) Upgrade Xerces to latest version
  .classpath
  build/scripts/junit.xml
  lib/endorsed/cupv10k-runtime-LICENSE.txt
  lib/endorsed/cupv10k-runtime.jar
  lib/endorsed/org.eclipse.wst.xml.xpath2.processor-1.2.0.jar
  lib/endorsed/xercesImpl-2.11.0.jar
  lib/endorsed/xercesImpl-2.12.0.jar
  nbproject/project.properties
  test/src/xquery/validation/ValidationTests.java
  test/src/xquery/validation/jaxv.xql
Labels: enhancement, security

#1981 (5.0.0) Basic support for available documents of Dynamic Context
  src/org/exist/xquery/XQueryContext.java
  src/org/exist/xquery/util/DocUtils.java
  test/src/org/exist/dom/memtree/DocumentImplTest.java
  test/src/org/exist/xquery/functions/fn/DocTest.java
Labels: enhancement
