Repository eXist-db/exist, pull requests merged in 2018-08, with the labels that each got.

#2087 Fix variables used by installer for wrapper.conf.
  tools/yajsw/build.xml
Labels: bug

#2088 (5.0.0) Fix variables used by installer for wrapper.conf.
  tools/yajsw/build.xml
Labels: bug

#2076 (5.0.0) Fix issues with IzPack and shutdown on Windows
  installer/install.xml.tmpl
  installer/scripts/setup.bat
  src/org/exist/management/client/JMXtoXML.java
  src/org/exist/management/impl/JMXAgent.java
  src/org/exist/management/impl/LockTable.java
  src/org/exist/management/impl/LockTableMXBean.java
  src/org/exist/storage/BrokerPool.java
  src/org/exist/storage/lock/LockManager.java
  src/org/exist/storage/lock/LockTable.java
  test/src/org/exist/storage/NativeBrokerLockingTest.java
  test/src/org/exist/storage/StartupLockingTest.java
  test/src/org/exist/storage/lock/LockManagerTest.java
  test/src/org/exist/xmldb/ShutdownTest.java
  test/src/org/exist/xmldb/concurrent/ComplexUpdateTest.java
  test/src/org/exist/xmldb/concurrent/ConcurrentAttrUpdateTest.java
  test/src/org/exist/xmldb/concurrent/ConcurrentQueryTest.java
  test/src/org/exist/xmldb/concurrent/ConcurrentQueryUpdateTest.java
  test/src/org/exist/xmldb/concurrent/ConcurrentResourceTest.java
  test/src/org/exist/xmldb/concurrent/ConcurrentResourceTest2.java
  test/src/org/exist/xmldb/concurrent/ConcurrentResourceTest3.java
  test/src/org/exist/xmldb/concurrent/ConcurrentTestBase.java
  test/src/org/exist/xmldb/concurrent/ConcurrentXUpdateTest.java
  test/src/org/exist/xmldb/concurrent/DBUtils.java
  test/src/org/exist/xmldb/concurrent/FragmentsTest.java
  test/src/org/exist/xmldb/concurrent/TextUpdateTest.java
  test/src/org/exist/xmldb/concurrent/ValueIndexUpdateTest.java
  test/src/org/exist/xmldb/concurrent/action/Action.java
  test/src/org/exist/xmldb/concurrent/action/AttributeUpdateAction.java
  test/src/org/exist/xmldb/concurrent/action/ComplexUpdateAction.java
  test/src/org/exist/xmldb/concurrent/action/CreateCollectionAction.java
  test/src/org/exist/xmldb/concurrent/action/MultiResourcesAction.java
  test/src/org/exist/xmldb/concurrent/action/RemoveAppendAction.java
  test/src/org/exist/xmldb/concurrent/action/ReplaceResourceAction.java
  test/src/org/exist/xmldb/concurrent/action/RetrieveResourceAction.java
  test/src/org/exist/xmldb/concurrent/action/TextUpdateAction.java
  test/src/org/exist/xmldb/concurrent/action/ValueAppendAction.java
  test/src/org/exist/xmldb/concurrent/action/XQueryAction.java
  test/src/org/exist/xmldb/concurrent/action/XQueryUpdateAction.java
  test/src/org/exist/xupdate/RemoveAppendTest.java
  test/src/org/exist/xupdate/StressTest.java
Labels: bug, windows

#2084 Fix an issue with logging and some documentation
  build.properties
  src/org/exist/plugin/PluginsManagerImpl.java
Labels: enhancement

#2085 (4.x.x) Fix an issue with logging and some documentation
  build.properties
  src/org/exist/plugin/PluginsManagerImpl.java
Labels: enhancement

#2086 (5.0.0) Fix an issue with logging and some documentation
  build.properties
  src/org/exist/plugin/PluginsManagerImpl.java
Labels: enhancement

#2083 (4.x.x) Cleanup and Improve concurrent test code
  test/src/org/exist/xmldb/ShutdownTest.java
  test/src/org/exist/xmldb/concurrent/ComplexUpdateTest.java
  test/src/org/exist/xmldb/concurrent/ConcurrentAttrUpdateTest.java
  test/src/org/exist/xmldb/concurrent/ConcurrentQueryTest.java
  test/src/org/exist/xmldb/concurrent/ConcurrentQueryUpdateTest.java
  test/src/org/exist/xmldb/concurrent/ConcurrentResourceTest.java
  test/src/org/exist/xmldb/concurrent/ConcurrentResourceTest2.java
  test/src/org/exist/xmldb/concurrent/ConcurrentResourceTest3.java
  test/src/org/exist/xmldb/concurrent/ConcurrentTestBase.java
  test/src/org/exist/xmldb/concurrent/ConcurrentXUpdateTest.java
  test/src/org/exist/xmldb/concurrent/DBUtils.java
  test/src/org/exist/xmldb/concurrent/FragmentsTest.java
  test/src/org/exist/xmldb/concurrent/TextUpdateTest.java
  test/src/org/exist/xmldb/concurrent/ValueIndexUpdateTest.java
  test/src/org/exist/xmldb/concurrent/action/Action.java
  test/src/org/exist/xmldb/concurrent/action/AttributeUpdateAction.java
  test/src/org/exist/xmldb/concurrent/action/ComplexUpdateAction.java
  test/src/org/exist/xmldb/concurrent/action/CreateCollectionAction.java
  test/src/org/exist/xmldb/concurrent/action/MultiResourcesAction.java
  test/src/org/exist/xmldb/concurrent/action/RemoveAppendAction.java
  test/src/org/exist/xmldb/concurrent/action/ReplaceResourceAction.java
  test/src/org/exist/xmldb/concurrent/action/RetrieveResourceAction.java
  test/src/org/exist/xmldb/concurrent/action/TextUpdateAction.java
  test/src/org/exist/xmldb/concurrent/action/ValueAppendAction.java
  test/src/org/exist/xmldb/concurrent/action/XQueryAction.java
  test/src/org/exist/xmldb/concurrent/action/XQueryUpdateAction.java
  test/src/org/exist/xupdate/RemoveAppendTest.java
  test/src/org/exist/xupdate/StressTest.java
Labels: enhancement

#2075 Fix issues with IzPack and shutdown on Windows
  installer/install.xml.tmpl
  installer/scripts/setup.bat
  src/org/exist/management/client/JMXtoXML.java
  src/org/exist/management/impl/JMXAgent.java
  src/org/exist/management/impl/LockTable.java
  src/org/exist/management/impl/LockTableMXBean.java
  src/org/exist/storage/BrokerPool.java
  src/org/exist/storage/lock/LockManager.java
  src/org/exist/storage/lock/LockTable.java
  test/src/org/exist/storage/NativeBrokerLockingTest.java
  test/src/org/exist/storage/StartupLockingTest.java
  test/src/org/exist/storage/lock/LockManagerTest.java
  test/src/org/exist/xmldb/ShutdownTest.java
  test/src/org/exist/xmldb/concurrent/ComplexUpdateTest.java
  test/src/org/exist/xmldb/concurrent/ConcurrentAttrUpdateTest.java
  test/src/org/exist/xmldb/concurrent/ConcurrentQueryTest.java
  test/src/org/exist/xmldb/concurrent/ConcurrentQueryUpdateTest.java
  test/src/org/exist/xmldb/concurrent/ConcurrentResourceTest.java
  test/src/org/exist/xmldb/concurrent/ConcurrentResourceTest2.java
  test/src/org/exist/xmldb/concurrent/ConcurrentResourceTest3.java
  test/src/org/exist/xmldb/concurrent/ConcurrentTestBase.java
  test/src/org/exist/xmldb/concurrent/ConcurrentXUpdateTest.java
  test/src/org/exist/xmldb/concurrent/DBUtils.java
  test/src/org/exist/xmldb/concurrent/FragmentsTest.java
  test/src/org/exist/xmldb/concurrent/TextUpdateTest.java
  test/src/org/exist/xmldb/concurrent/ValueIndexUpdateTest.java
  test/src/org/exist/xmldb/concurrent/action/Action.java
  test/src/org/exist/xmldb/concurrent/action/AttributeUpdateAction.java
  test/src/org/exist/xmldb/concurrent/action/ComplexUpdateAction.java
  test/src/org/exist/xmldb/concurrent/action/CreateCollectionAction.java
  test/src/org/exist/xmldb/concurrent/action/MultiResourcesAction.java
  test/src/org/exist/xmldb/concurrent/action/RemoveAppendAction.java
  test/src/org/exist/xmldb/concurrent/action/ReplaceResourceAction.java
  test/src/org/exist/xmldb/concurrent/action/RetrieveResourceAction.java
  test/src/org/exist/xmldb/concurrent/action/TextUpdateAction.java
  test/src/org/exist/xmldb/concurrent/action/ValueAppendAction.java
  test/src/org/exist/xmldb/concurrent/action/XQueryAction.java
  test/src/org/exist/xmldb/concurrent/action/XQueryUpdateAction.java
  test/src/org/exist/xupdate/RemoveAppendTest.java
  test/src/org/exist/xupdate/StressTest.java
Labels: bug, windows

#2080 (4.x.x) Add DEFLATE compression (RFC 1950 / 1951) to compression module
  extensions/modules/src/org/exist/xquery/modules/compression/CompressionModule.java
  extensions/modules/src/org/exist/xquery/modules/compression/DeflateFunction.java
  extensions/modules/src/org/exist/xquery/modules/compression/InflateFunction.java
  extensions/modules/src/org/exist/xquery/modules/compression/example-deflate.xql
Labels: enhancement

#2094 (5.0.0) Add DEFLATE compression (RFC 1950 / 1951) to compression module
  extensions/modules/src/org/exist/xquery/modules/compression/CompressionModule.java
  extensions/modules/src/org/exist/xquery/modules/compression/DeflateFunction.java
  extensions/modules/src/org/exist/xquery/modules/compression/InflateFunction.java
  extensions/modules/src/org/exist/xquery/modules/compression/example-deflate.xql
Labels: enhancement

#2093 Add DEFLATE compression (RFC 1950 / 1951) to compression module
  extensions/modules/src/org/exist/xquery/modules/compression/CompressionModule.java
  extensions/modules/src/org/exist/xquery/modules/compression/DeflateFunction.java
  extensions/modules/src/org/exist/xquery/modules/compression/InflateFunction.java
  extensions/modules/src/org/exist/xquery/modules/compression/example-deflate.xql
Labels: enhancement

#2109 (5.0.0) Remove legacy XQTS support
  .gitignore
  build.properties
  build/scripts/build-impl.xml
  build/scripts/dist.xml
  build/scripts/junit.xml
  build/scripts/macosx.xml
  installer/install.xml.tmpl
  test/src/org/exist/xquery/xqts/QT3TS_To_junit.java
  test/src/org/exist/xquery/xqts/QT3TS_case.java
  test/src/org/exist/xquery/xqts/XQTS_To_junit.java
  test/src/org/exist/xquery/xqts/XQTS_case.java
  webapp/xqts/build.xml
  webapp/xqts/collection.xconf
  webapp/xqts/collectresults.xql
  webapp/xqts/config.xml.tmpl
  webapp/xqts/hacked-tests.xml
  webapp/xqts/images/lm.gif
  webapp/xqts/images/lmh.gif
  webapp/xqts/images/ln.gif
  webapp/xqts/images/loading.gif
  webapp/xqts/images/lp.gif
  webapp/xqts/images/lph.gif
  webapp/xqts/images/tm.gif
  webapp/xqts/images/tmh.gif
  webapp/xqts/images/tn.gif
  webapp/xqts/images/tp.gif
  webapp/xqts/images/tph.gif
  webapp/xqts/images/vline.gif
  webapp/xqts/progress.xql
  webapp/xqts/report.xql
  webapp/xqts/scripts/connection.js
  webapp/xqts/scripts/container.js
  webapp/xqts/scripts/dom.js
  webapp/xqts/scripts/event.js
  webapp/xqts/scripts/report.js
  webapp/xqts/scripts/shBrushXQuery.js
  webapp/xqts/scripts/shBrushXml.js
  webapp/xqts/scripts/shCore.js
  webapp/xqts/scripts/treeview.js
  webapp/xqts/scripts/yahoo.js
  webapp/xqts/skip.xml
  webapp/xqts/styles/SyntaxHighlighter.css
  webapp/xqts/styles/container.css
  webapp/xqts/styles/report.css
  webapp/xqts/styles/tableft1.gif
  webapp/xqts/styles/tabright1.gif
  webapp/xqts/styles/tree.css
  webapp/xqts/styles/xml2html.css
  webapp/xqts/stylesheets/xml-highlight.xsl
  webapp/xqts/xqts.xql
Labels: enhancement

#2103 Consistency check should check the entire document
  src/org/exist/backup/ConsistencyCheck.java
Labels: bug

#2100 (4.x.x) Consistency check should check the entire document
  src/org/exist/backup/ConsistencyCheck.java
Labels: bug

#2110 Allow the password to be provided to the Client GUI via the command line args
  src/org/exist/client/ConnectionDialog.java
  src/org/exist/client/InteractiveClient.java
Labels: enhancement

#2111 (5.0.0) Allow the password to be provided to the Client GUI via the command line args
  src/org/exist/client/ConnectionDialog.java
  src/org/exist/client/InteractiveClient.java
Labels: enhancement

#2112 (4.x.x) Allow the password to be provided to the Client GUI via the command line args
  src/org/exist/client/ConnectionDialog.java
  src/org/exist/client/InteractiveClient.java
Labels: enhancement

#2116 (5.0.0) Various fixes for preceding-sibling and following-sibling axis
  extensions/indexes/lucene/src/org/exist/indexing/lucene/LuceneMatchListener.java
  extensions/indexes/lucene/src/org/exist/xquery/modules/lucene/Query.java
  extensions/indexes/ngram/src/org/exist/indexing/ngram/NGramIndexWorker.java
  extensions/indexes/ngram/src/org/exist/xquery/modules/ngram/AddMatch.java
  extensions/modules/src/org/exist/xquery/modules/process/Execute.java
  log4j2.xml
  src/org/exist/backup/SystemExport.java
  src/org/exist/dom/memtree/NodeImpl.java
  src/org/exist/dom/persistent/DocumentImpl.java
  src/org/exist/dom/persistent/ElementImpl.java
  src/org/exist/dom/persistent/NewArrayNodeSet.java
  src/org/exist/dom/persistent/NodeProxy.java
  src/org/exist/dom/persistent/StoredNode.java
  src/org/exist/dom/persistent/VirtualNodeSet.java
  src/org/exist/stax/AbstractEmbeddedXMLStreamReader.java
  src/org/exist/stax/EmbeddedXMLStreamReader.java
  src/org/exist/stax/StaXUtil.java
  src/org/exist/storage/NativeBroker.java
  src/org/exist/storage/dom/DOMFile.java
  src/org/exist/storage/statistics/IndexStatisticsWorker.java
  src/org/exist/util/sanity/SanityCheck.java
  src/org/exist/xmldb/RemoteResourceSet.java
  src/org/exist/xmldb/RemoteXMLResource.java
  src/org/exist/xquery/LocationStep.java
  src/org/exist/xquery/util/SerializerUtils.java
  src/org/exist/xquery/value/ValueSequence.java
  test/src/org/exist/dom/persistent/PersistentDomTest.java
  test/src/org/exist/stax/EmbeddedXMLStreamReaderTest.java
  test/src/org/exist/storage/AllStorageTests.java
  test/src/org/exist/storage/ReindexRecoveryTest.java
  test/src/org/exist/storage/ReindexTest.java
  test/src/org/exist/xquery/XPathQueryTest.java
  test/src/org/exist/xquery/functions/transform/TransformTest.java
  test/src/org/exist/xquery/update/IndexIntegrationTest.java
  test/src/xquery/positional-nested.xql
Labels: bug

#2113 Various fixes for preceding-sibling and following-sibling axis
  extensions/indexes/lucene/src/org/exist/indexing/lucene/LuceneMatchListener.java
  extensions/indexes/lucene/src/org/exist/xquery/modules/lucene/Query.java
  extensions/indexes/ngram/src/org/exist/indexing/ngram/NGramIndexWorker.java
  extensions/indexes/ngram/src/org/exist/xquery/modules/ngram/AddMatch.java
  extensions/modules/src/org/exist/xquery/modules/process/Execute.java
  log4j2.xml
  src/org/exist/backup/SystemExport.java
  src/org/exist/dom/memtree/NodeImpl.java
  src/org/exist/dom/persistent/DocumentImpl.java
  src/org/exist/dom/persistent/ElementImpl.java
  src/org/exist/dom/persistent/NewArrayNodeSet.java
  src/org/exist/dom/persistent/NodeProxy.java
  src/org/exist/dom/persistent/StoredNode.java
  src/org/exist/dom/persistent/VirtualNodeSet.java
  src/org/exist/stax/AbstractEmbeddedXMLStreamReader.java
  src/org/exist/stax/EmbeddedXMLStreamReader.java
  src/org/exist/stax/StaXUtil.java
  src/org/exist/storage/NativeBroker.java
  src/org/exist/storage/dom/DOMFile.java
  src/org/exist/storage/statistics/IndexStatisticsWorker.java
  src/org/exist/util/sanity/SanityCheck.java
  src/org/exist/xmldb/RemoteResourceSet.java
  src/org/exist/xmldb/RemoteXMLResource.java
  src/org/exist/xquery/LocationStep.java
  src/org/exist/xquery/util/SerializerUtils.java
  src/org/exist/xquery/value/ValueSequence.java
  test/src/org/exist/dom/persistent/PersistentDomTest.java
  test/src/org/exist/stax/EmbeddedXMLStreamReaderTest.java
  test/src/org/exist/storage/AllStorageTests.java
  test/src/org/exist/storage/ReindexRecoveryTest.java
  test/src/org/exist/storage/ReindexTest.java
  test/src/org/exist/xquery/XPathQueryTest.java
  test/src/org/exist/xquery/functions/transform/TransformTest.java
  test/src/org/exist/xquery/update/IndexIntegrationTest.java
  test/src/xquery/positional-nested.xql
Labels: bug

#2115 (4.x.x) Various fixes for preceding-sibling and following-sibling axis
  extensions/indexes/lucene/src/org/exist/indexing/lucene/LuceneMatchListener.java
  extensions/indexes/lucene/src/org/exist/xquery/modules/lucene/Query.java
  extensions/indexes/ngram/src/org/exist/indexing/ngram/NGramIndexWorker.java
  extensions/indexes/ngram/src/org/exist/xquery/modules/ngram/AddMatch.java
  extensions/modules/src/org/exist/xquery/modules/process/Execute.java
  log4j2.xml
  src/org/exist/backup/SystemExport.java
  src/org/exist/dom/memtree/NodeImpl.java
  src/org/exist/dom/persistent/DocumentImpl.java
  src/org/exist/dom/persistent/ElementImpl.java
  src/org/exist/dom/persistent/NewArrayNodeSet.java
  src/org/exist/dom/persistent/NodeProxy.java
  src/org/exist/dom/persistent/StoredNode.java
  src/org/exist/dom/persistent/VirtualNodeSet.java
  src/org/exist/stax/AbstractEmbeddedXMLStreamReader.java
  src/org/exist/stax/EmbeddedXMLStreamReader.java
  src/org/exist/stax/StaXUtil.java
  src/org/exist/storage/NativeBroker.java
  src/org/exist/storage/dom/DOMFile.java
  src/org/exist/storage/statistics/IndexStatisticsWorker.java
  src/org/exist/util/sanity/SanityCheck.java
  src/org/exist/xmldb/RemoteResourceSet.java
  src/org/exist/xmldb/RemoteXMLResource.java
  src/org/exist/xquery/LocationStep.java
  src/org/exist/xquery/util/SerializerUtils.java
  src/org/exist/xquery/value/ValueSequence.java
  test/src/org/exist/dom/persistent/PersistentDomTest.java
  test/src/org/exist/stax/EmbeddedXMLStreamReaderTest.java
  test/src/org/exist/storage/AllStorageTests.java
  test/src/org/exist/storage/ReindexRecoveryTest.java
  test/src/org/exist/storage/ReindexTest.java
  test/src/org/exist/test/ExistEmbeddedServer.java
  test/src/org/exist/xquery/XPathQueryTest.java
  test/src/org/exist/xquery/functions/transform/TransformTest.java
  test/src/org/exist/xquery/update/IndexIntegrationTest.java
  test/src/xquery/positional-nested.xql
Labels: bug

#2119 Various small improvements
  .travis.yml
  test/src/org/exist/validation/TestTools.java
Labels: enhancement

#2120 (4.x.x) Various small improvements
  .travis.yml
  test/src/org/exist/validation/TestTools.java
Labels: enhancement

#2121 (5.0.0) Various small improvements
  .travis.yml
  test/src/org/exist/validation/TestTools.java
Labels: enhancement
