Repository eXist-db/exist, pull requests merged in 2018-11, with the labels that each got.

#2256 (5.0.0) Journal Checksums
  .classpath
  lib/core/lz4-java-1.5.0.jar
  nbproject/project.properties
  src/org/exist/start/start.config
  src/org/exist/storage/dom/WriteOverflowPageLoggable.java
  src/org/exist/storage/journal/Journal.java
  src/org/exist/storage/journal/JournalReader.java
  src/org/exist/util/StringInputSource.java
  test/src/org/exist/storage/AbstractRecoverTest.java
  test/src/org/exist/storage/RecoverBinaryTest.java
  test/src/org/exist/storage/RecoverXmlTest.java
  test/src/org/exist/storage/journal/AbstractJournalTest.java
  test/src/org/exist/storage/journal/JournalBinaryTest.java
  test/src/org/exist/storage/journal/JournalXmlTest.java
Labels: enhancement

#2255 (4.x.x) Journal Checksums
  .classpath
  lib/core/lz4-java-1.5.0.jar
  nbproject/project.properties
  src/org/exist/start/start.config
  src/org/exist/storage/dom/WriteOverflowPageLoggable.java
  src/org/exist/storage/journal/Journal.java
  src/org/exist/storage/journal/JournalReader.java
  src/org/exist/util/StringInputSource.java
  test/src/org/exist/storage/AbstractRecoverTest.java
  test/src/org/exist/storage/RecoverBinaryTest.java
  test/src/org/exist/storage/RecoverXmlTest.java
  test/src/org/exist/storage/journal/AbstractJournalTest.java
  test/src/org/exist/storage/journal/JournalBinaryTest.java
  test/src/org/exist/storage/journal/JournalXmlTest.java
Labels: enhancement

#2254 Journal Checksums
  .classpath
  lib/core/lz4-java-1.5.0.jar
  nbproject/project.properties
  src/org/exist/start/start.config
  src/org/exist/storage/dom/WriteOverflowPageLoggable.java
  src/org/exist/storage/journal/Journal.java
  src/org/exist/storage/journal/JournalReader.java
  src/org/exist/util/StringInputSource.java
  test/src/org/exist/storage/AbstractRecoverTest.java
  test/src/org/exist/storage/RecoverBinaryTest.java
  test/src/org/exist/storage/RecoverXmlTest.java
  test/src/org/exist/storage/journal/AbstractJournalTest.java
  test/src/org/exist/storage/journal/JournalBinaryTest.java
  test/src/org/exist/storage/journal/JournalXmlTest.java
Labels: enhancement

#2257 enable oracleJDK11 on travis
  .travis.yml
Labels: enhancement

#2258 enable oracleJDK11 on travis
  .travis.yml
Labels: enhancement

#2259 enable oracleJDK11 on travis
  .travis.yml
Labels: enhancement

#2262 Improve the provenance of the XML:DB API dependency
  .classpath
  lib/core/xmldb-api-1.1-patched.jar
  lib/core/xmldb-api-LICENSE.txt
  lib/core/xmldb.jar
  nbproject/project.properties
  src/org/exist/start/start.config
  src/org/exist/xmldb/LocalResourceSet.java
  src/org/exist/xmldb/MapResourceSet.java
  src/org/exist/xmldb/RemoteResourceSet.java
Labels: enhancement

#2263 (4.x.x) Improve the provenance of the XML:DB API dependency
  .classpath
  lib/core/xmldb-api-1.1-patched.jar
  lib/core/xmldb-api-LICENSE.txt
  lib/core/xmldb.jar
  nbproject/project.properties
  src/org/exist/start/start.config
  src/org/exist/xmldb/LocalResourceSet.java
  src/org/exist/xmldb/MapResourceSet.java
  src/org/exist/xmldb/RemoteResourceSet.java
Labels: enhancement

#2264 (5.0.0) Improve the provenance of the XML:DB API dependency
  .classpath
  lib/core/xmldb-api-1.1-patched.jar
  lib/core/xmldb-api-LICENSE.txt
  lib/core/xmldb.jar
  nbproject/project.properties
  src/org/exist/start/start.config
  src/org/exist/xmldb/LocalResourceSet.java
  src/org/exist/xmldb/MapResourceSet.java
  src/org/exist/xmldb/RemoteResourceSet.java
Labels: enhancement

#2265 (5.0.0) Journal Binary Checksums
  .classpath
  conf.xml.tmpl
  extensions/indexes/ngram/src/org/exist/indexing/ngram/NGramIndex.java
  extensions/indexes/sort/src/org/exist/indexing/sort/SortIndex.java
  lib/core/bcprov-jdk15on-1.60.jar
  lib/core/bcprov-jdk15on-LICENSE.txt
  lib/core/gnu-crypto-2.0.1.jar
  lib/core/gnu-crypto-COPYING.txt
  lib/core/gnu-crypto-LICENSE.txt
  nbproject/project.properties
  src/org/exist/BTreeTest.java
  src/org/exist/dom/persistent/BinaryDocument.java
  src/org/exist/security/BouncyCastleJceProviderStartupTrigger.java
  src/org/exist/security/internal/Password.java
  src/org/exist/start/start.config
  src/org/exist/storage/AbstractBinaryLoggable.java
  src/org/exist/storage/CreateBinaryLoggable.java
  src/org/exist/storage/DeleteBinaryLoggable.java
  src/org/exist/storage/NativeBroker.java
  src/org/exist/storage/NativeValueIndex.java
  src/org/exist/storage/RenameBinaryLoggable.java
  src/org/exist/storage/ReplaceBinaryLoggable.java
  src/org/exist/storage/btree/BTree.java
  src/org/exist/storage/btree/Paged.java
  src/org/exist/storage/dom/DOMFile.java
  src/org/exist/storage/index/BFile.java
  src/org/exist/storage/index/BTreeStore.java
  src/org/exist/storage/index/CollectionStore.java
  src/org/exist/storage/journal/Journal.java
  src/org/exist/storage/structural/NativeStructuralIndex.java
  src/org/exist/util/FileUtils.java
  src/org/exist/util/crypto/digest/Blake256StreamableDigest.java
  src/org/exist/util/crypto/digest/DigestInputStream.java
  src/org/exist/util/crypto/digest/DigestOutputStream.java
  src/org/exist/util/crypto/digest/DigestType.java
  src/org/exist/util/crypto/digest/MessageDigest.java
  src/org/exist/util/crypto/digest/StreamableDigest.java
  test/src/org/exist/storage/BinaryDocumentTest.java
  test/src/org/exist/storage/ConcurrentBrokerPoolTest.conf.xml
  test/src/org/exist/storage/btree/BTreeTest.java
Labels: enhancement

#2266 Journal Binary Checksums
  .classpath
  conf.xml.tmpl
  extensions/indexes/ngram/src/org/exist/indexing/ngram/NGramIndex.java
  extensions/indexes/sort/src/org/exist/indexing/sort/SortIndex.java
  lib/core/bcprov-jdk15on-1.60.jar
  lib/core/bcprov-jdk15on-LICENSE.txt
  lib/core/gnu-crypto-2.0.1.jar
  lib/core/gnu-crypto-COPYING.txt
  lib/core/gnu-crypto-LICENSE.txt
  nbproject/project.properties
  src/org/exist/BTreeTest.java
  src/org/exist/dom/persistent/BinaryDocument.java
  src/org/exist/security/BouncyCastleJceProviderStartupTrigger.java
  src/org/exist/security/internal/Password.java
  src/org/exist/start/start.config
  src/org/exist/storage/AbstractBinaryLoggable.java
  src/org/exist/storage/CreateBinaryLoggable.java
  src/org/exist/storage/DeleteBinaryLoggable.java
  src/org/exist/storage/NativeBroker.java
  src/org/exist/storage/NativeValueIndex.java
  src/org/exist/storage/RenameBinaryLoggable.java
  src/org/exist/storage/ReplaceBinaryLoggable.java
  src/org/exist/storage/btree/BTree.java
  src/org/exist/storage/btree/Paged.java
  src/org/exist/storage/dom/DOMFile.java
  src/org/exist/storage/index/BFile.java
  src/org/exist/storage/index/BTreeStore.java
  src/org/exist/storage/index/CollectionStore.java
  src/org/exist/storage/journal/Journal.java
  src/org/exist/storage/structural/NativeStructuralIndex.java
  src/org/exist/util/FileUtils.java
  src/org/exist/util/crypto/digest/Blake256StreamableDigest.java
  src/org/exist/util/crypto/digest/DigestInputStream.java
  src/org/exist/util/crypto/digest/DigestOutputStream.java
  src/org/exist/util/crypto/digest/DigestType.java
  src/org/exist/util/crypto/digest/MessageDigest.java
  src/org/exist/util/crypto/digest/StreamableDigest.java
  test/src/org/exist/storage/BinaryDocumentTest.java
  test/src/org/exist/storage/ConcurrentBrokerPoolTest.conf.xml
  test/src/org/exist/storage/btree/BTreeTest.java
Labels: enhancement

#2260 (4.x.x) Journal Binary Checksums
  .classpath
  conf.xml.tmpl
  extensions/indexes/ngram/src/org/exist/indexing/ngram/NGramIndex.java
  extensions/indexes/sort/src/org/exist/indexing/sort/SortIndex.java
  lib/core/bcprov-jdk15on-1.60.jar
  lib/core/bcprov-jdk15on-LICENSE.txt
  lib/core/gnu-crypto-2.0.1.jar
  lib/core/gnu-crypto-COPYING.txt
  lib/core/gnu-crypto-LICENSE.txt
  nbproject/project.properties
  src/org/exist/BTreeTest.java
  src/org/exist/dom/persistent/BinaryDocument.java
  src/org/exist/security/BouncyCastleJceProviderStartupTrigger.java
  src/org/exist/security/internal/Password.java
  src/org/exist/start/start.config
  src/org/exist/storage/AbstractBinaryLoggable.java
  src/org/exist/storage/CreateBinaryLoggable.java
  src/org/exist/storage/DeleteBinaryLoggable.java
  src/org/exist/storage/NativeBroker.java
  src/org/exist/storage/NativeValueIndex.java
  src/org/exist/storage/RenameBinaryLoggable.java
  src/org/exist/storage/ReplaceBinaryLoggable.java
  src/org/exist/storage/btree/BTree.java
  src/org/exist/storage/btree/Paged.java
  src/org/exist/storage/dom/DOMFile.java
  src/org/exist/storage/index/BFile.java
  src/org/exist/storage/index/BTreeStore.java
  src/org/exist/storage/index/CollectionStore.java
  src/org/exist/storage/journal/Journal.java
  src/org/exist/storage/structural/NativeStructuralIndex.java
  src/org/exist/util/FileUtils.java
  src/org/exist/util/crypto/digest/Blake256StreamableDigest.java
  src/org/exist/util/crypto/digest/DigestInputStream.java
  src/org/exist/util/crypto/digest/DigestOutputStream.java
  src/org/exist/util/crypto/digest/DigestType.java
  src/org/exist/util/crypto/digest/MessageDigest.java
  src/org/exist/util/crypto/digest/StreamableDigest.java
  test/src/org/exist/storage/BinaryDocumentTest.java
  test/src/org/exist/storage/ConcurrentBrokerPoolTest.conf.xml
  test/src/org/exist/storage/btree/BTreeTest.java
Labels: enhancement

#2270 (5.0.0) Fix a regression with loading the XML:DB API Jar via bin/startup
  src/org/exist/start/LatestFileResolver.java
Labels: bug

#2269 Fix a regression with loading the XML:DB API Jar via bin/startup
  src/org/exist/start/LatestFileResolver.java
Labels: bug

#2268 (4.x.x.) Fix a regression with loading the XML:DB API Jar via bin/startup
  src/org/exist/start/LatestFileResolver.java
Labels: bug

#2271 Fix verbose logging regression in ExistSAXParserFactory
  src/org/exist/util/ExistSAXParserFactory.java
Labels: bug, regression

#2273 (4.x.x) Fix verbose logging regression in ExistSAXParserFactory
  src/org/exist/util/ExistSAXParserFactory.java
Labels: bug, regression

#2272 (5.x.x) Fix verbose logging regression in ExistSAXParserFactory
  src/org/exist/util/ExistSAXParserFactory.java
Labels: bug, regression

#2275 (4.x.x) Fix a regression in ExportGUI
  src/org/exist/backup/ExportGUI.java
Labels: bug, regression

#2276 Fix a regression in ExportGUI
  src/org/exist/backup/ExportGUI.java
Labels: bug, regression

#2277 (5.x.x) Fix a regression in ExportGUI
  src/org/exist/backup/ExportGUI.java
Labels: bug, regression

#2292 (4.x.x) Remove the 2GB log file limit for the Journal
  extensions/indexes/ngram/src/org/exist/indexing/ngram/NGramIndex.java
  extensions/indexes/sort/src/org/exist/indexing/sort/SortIndex.java
  src/org/exist/storage/NativeValueIndex.java
  src/org/exist/storage/btree/BTree.java
  src/org/exist/storage/btree/Paged.java
  src/org/exist/storage/dom/DOMFile.java
  src/org/exist/storage/index/BFile.java
  src/org/exist/storage/index/CollectionStore.java
  src/org/exist/storage/journal/AbstractLoggable.java
  src/org/exist/storage/journal/Journal.java
  src/org/exist/storage/journal/JournalManager.java
  src/org/exist/storage/journal/JournalReader.java
  src/org/exist/storage/journal/Loggable.java
  src/org/exist/storage/journal/Lsn.java
  src/org/exist/storage/recovery/RecoveryManager.java
  src/org/exist/storage/structural/NativeStructuralIndex.java
  src/org/exist/storage/txn/Checkpoint.java
  test/src/org/exist/storage/RemoveCollectionTest.java
  test/src/org/exist/storage/journal/LsnTest.java
Labels: bug, high prio, needs 4.x.x backport, needs 5.0.0 backport

#2288 RestXQ was not releasing binary file handles
  extensions/exquery/lib/exquery-annotations-common-0.1.33.jar
  extensions/exquery/lib/exquery-annotations-common-1.0-SNAPSHOT.jar
  extensions/exquery/lib/exquery-annotations-common-api-0.1.33.jar
  extensions/exquery/lib/exquery-annotations-common-api-1.0-SNAPSHOT.jar
  extensions/exquery/lib/exquery-common-0.1.33.jar
  extensions/exquery/lib/exquery-common-1.0-SNAPSHOT.jar
  extensions/exquery/lib/exquery-serialization-annotations-0.1.33.jar
  extensions/exquery/lib/exquery-serialization-annotations-1.0-SNAPSHOT.jar
  extensions/exquery/lib/exquery-serialization-annotations-api-0.1.33.jar
  extensions/exquery/lib/exquery-serialization-annotations-api-1.0-SNAPSHOT.jar
  extensions/exquery/lib/exquery-xquery-0.1.33.jar
  extensions/exquery/lib/exquery-xquery-1.0-SNAPSHOT.jar
  extensions/exquery/lib/exquery-xquery3-0.1.33.jar
  extensions/exquery/lib/exquery-xquery3-1.0-SNAPSHOT.jar
  extensions/exquery/restxq/lib/exquery-restxq-0.1.33.jar
  extensions/exquery/restxq/lib/exquery-restxq-1.0-SNAPSHOT.jar
  extensions/exquery/restxq/lib/exquery-restxq-api-0.1.33.jar
  extensions/exquery/restxq/lib/exquery-restxq-api-1.0-SNAPSHOT.jar
  extensions/exquery/restxq/src/main/java/org/exist/extensions/exquery/restxq/impl/ResourceFunctionExecutorImpl.java
  extensions/exquery/restxq/src/main/java/org/exist/extensions/exquery/restxq/impl/RestXqServiceCompiledXQueryCacheImpl.java
  extensions/exquery/restxq/src/main/java/org/exist/extensions/exquery/restxq/impl/adapters/SequenceAdapter.java
Labels: bug

#2289 (4.x.x) RestXQ was not releasing binary file handles
  extensions/exquery/lib/exquery-annotations-common-0.1.33.jar
  extensions/exquery/lib/exquery-annotations-common-1.0-SNAPSHOT.jar
  extensions/exquery/lib/exquery-annotations-common-api-0.1.33.jar
  extensions/exquery/lib/exquery-annotations-common-api-1.0-SNAPSHOT.jar
  extensions/exquery/lib/exquery-common-0.1.33.jar
  extensions/exquery/lib/exquery-common-1.0-SNAPSHOT.jar
  extensions/exquery/lib/exquery-serialization-annotations-0.1.33.jar
  extensions/exquery/lib/exquery-serialization-annotations-1.0-SNAPSHOT.jar
  extensions/exquery/lib/exquery-serialization-annotations-api-0.1.33.jar
  extensions/exquery/lib/exquery-serialization-annotations-api-1.0-SNAPSHOT.jar
  extensions/exquery/lib/exquery-xquery-0.1.33.jar
  extensions/exquery/lib/exquery-xquery-1.0-SNAPSHOT.jar
  extensions/exquery/lib/exquery-xquery3-0.1.33.jar
  extensions/exquery/lib/exquery-xquery3-1.0-SNAPSHOT.jar
  extensions/exquery/restxq/lib/exquery-restxq-0.1.33.jar
  extensions/exquery/restxq/lib/exquery-restxq-1.0-SNAPSHOT.jar
  extensions/exquery/restxq/lib/exquery-restxq-api-0.1.33.jar
  extensions/exquery/restxq/lib/exquery-restxq-api-1.0-SNAPSHOT.jar
  extensions/exquery/restxq/src/main/java/org/exist/extensions/exquery/restxq/impl/ResourceFunctionExecutorImpl.java
  extensions/exquery/restxq/src/main/java/org/exist/extensions/exquery/restxq/impl/RestXqServiceCompiledXQueryCacheImpl.java
  extensions/exquery/restxq/src/main/java/org/exist/extensions/exquery/restxq/impl/adapters/SequenceAdapter.java
Labels: bug

#2290 (5.0.0) RestXQ was not releasing binary file handles
  extensions/exquery/lib/exquery-annotations-common-0.1.33.jar
  extensions/exquery/lib/exquery-annotations-common-1.0-SNAPSHOT.jar
  extensions/exquery/lib/exquery-annotations-common-api-0.1.33.jar
  extensions/exquery/lib/exquery-annotations-common-api-1.0-SNAPSHOT.jar
  extensions/exquery/lib/exquery-common-0.1.33.jar
  extensions/exquery/lib/exquery-common-1.0-SNAPSHOT.jar
  extensions/exquery/lib/exquery-serialization-annotations-0.1.33.jar
  extensions/exquery/lib/exquery-serialization-annotations-1.0-SNAPSHOT.jar
  extensions/exquery/lib/exquery-serialization-annotations-api-0.1.33.jar
  extensions/exquery/lib/exquery-serialization-annotations-api-1.0-SNAPSHOT.jar
  extensions/exquery/lib/exquery-xquery-0.1.33.jar
  extensions/exquery/lib/exquery-xquery-1.0-SNAPSHOT.jar
  extensions/exquery/lib/exquery-xquery3-0.1.33.jar
  extensions/exquery/lib/exquery-xquery3-1.0-SNAPSHOT.jar
  extensions/exquery/restxq/lib/exquery-restxq-0.1.33.jar
  extensions/exquery/restxq/lib/exquery-restxq-1.0-SNAPSHOT.jar
  extensions/exquery/restxq/lib/exquery-restxq-api-0.1.33.jar
  extensions/exquery/restxq/lib/exquery-restxq-api-1.0-SNAPSHOT.jar
  extensions/exquery/restxq/src/main/java/org/exist/extensions/exquery/restxq/impl/ResourceFunctionExecutorImpl.java
  extensions/exquery/restxq/src/main/java/org/exist/extensions/exquery/restxq/impl/RestXqServiceCompiledXQueryCacheImpl.java
  extensions/exquery/restxq/src/main/java/org/exist/extensions/exquery/restxq/impl/adapters/SequenceAdapter.java
Labels: bug

#2293 Remove the 2GB log file limit for the Journal
  extensions/indexes/ngram/src/org/exist/indexing/ngram/NGramIndex.java
  extensions/indexes/sort/src/org/exist/indexing/sort/SortIndex.java
  src/org/exist/storage/NativeValueIndex.java
  src/org/exist/storage/btree/BTree.java
  src/org/exist/storage/btree/Paged.java
  src/org/exist/storage/dom/DOMFile.java
  src/org/exist/storage/index/BFile.java
  src/org/exist/storage/index/CollectionStore.java
  src/org/exist/storage/journal/AbstractLoggable.java
  src/org/exist/storage/journal/Journal.java
  src/org/exist/storage/journal/JournalManager.java
  src/org/exist/storage/journal/JournalReader.java
  src/org/exist/storage/journal/Loggable.java
  src/org/exist/storage/journal/Lsn.java
  src/org/exist/storage/recovery/RecoveryManager.java
  src/org/exist/storage/structural/NativeStructuralIndex.java
  src/org/exist/storage/txn/Checkpoint.java
  test/src/org/exist/storage/RemoveCollectionTest.java
  test/src/org/exist/storage/journal/LsnTest.java
Labels: bug, high prio

#2294 (5.0.0) Remove the 2GB log file limit for the Journal
  extensions/indexes/ngram/src/org/exist/indexing/ngram/NGramIndex.java
  extensions/indexes/sort/src/org/exist/indexing/sort/SortIndex.java
  src/org/exist/storage/NativeValueIndex.java
  src/org/exist/storage/btree/BTree.java
  src/org/exist/storage/btree/Paged.java
  src/org/exist/storage/dom/DOMFile.java
  src/org/exist/storage/index/BFile.java
  src/org/exist/storage/index/CollectionStore.java
  src/org/exist/storage/journal/AbstractLoggable.java
  src/org/exist/storage/journal/Journal.java
  src/org/exist/storage/journal/JournalManager.java
  src/org/exist/storage/journal/JournalReader.java
  src/org/exist/storage/journal/Loggable.java
  src/org/exist/storage/journal/Lsn.java
  src/org/exist/storage/recovery/RecoveryManager.java
  src/org/exist/storage/structural/NativeStructuralIndex.java
  src/org/exist/storage/txn/Checkpoint.java
  test/src/org/exist/storage/RemoveCollectionTest.java
  test/src/org/exist/storage/journal/LsnTest.java
Labels: bug, high prio

#2285 Improve the provenance of our EXPath Pkg Repo fork dependency
  .classpath
  extensions/modules/src/org/exist/xquery/modules/expathrepo/InstallFunction.java
  lib/core/pkg-java-1.1.jar
  lib/core/pkg-java-fork.jar
  nbproject/project.properties
  src/org/exist/repo/ClasspathHelper.java
  src/org/exist/repo/Deployment.java
  src/org/exist/repo/ExistPkgExtension.java
  src/org/exist/repo/ExistRepository.java
  src/org/exist/start/start.config
Labels: enhancement

#2286 (5.0.0) Improve the provenance of our EXPath Pkg Repo fork dependency
  .classpath
  extensions/modules/src/org/exist/xquery/modules/expathrepo/InstallFunction.java
  lib/core/pkg-java-1.1.jar
  lib/core/pkg-java-fork.jar
  nbproject/project.properties
  src/org/exist/repo/ClasspathHelper.java
  src/org/exist/repo/Deployment.java
  src/org/exist/repo/ExistPkgExtension.java
  src/org/exist/repo/ExistRepository.java
  src/org/exist/start/start.config
Labels: enhancement

#2284 (4.x.x) Improve the provenance of our EXPath Pkg Repo fork dependency
  .classpath
  extensions/modules/src/org/exist/xquery/modules/expathrepo/InstallFunction.java
  lib/core/pkg-java-1.1.jar
  lib/core/pkg-java-fork.jar
  nbproject/project.properties
  src/org/exist/repo/ClasspathHelper.java
  src/org/exist/repo/Deployment.java
  src/org/exist/repo/ExistPkgExtension.java
  src/org/exist/repo/ExistRepository.java
  src/org/exist/start/start.config
Labels: enhancement

#2299 Don't unsign the Bouncy Castle jar file
  build/scripts/jarsigner.xml
Labels: bug

#2298 (4.x.x) Don't unsign the Bouncy Castle jar file
  build/scripts/jarsigner.xml
Labels: bug

#2301 (4.x.x) Journal must write-ahead
  src/org/exist/storage/BrokerPool.java
  src/org/exist/storage/journal/FileSyncRunnable.java
  src/org/exist/storage/journal/Journal.java
Labels: bug, high prio

#2303 (5.0.0) Journal must write-ahead
  src/org/exist/storage/BrokerPool.java
  src/org/exist/storage/journal/FileSyncRunnable.java
  src/org/exist/storage/journal/Journal.java
Labels: bug, high prio

#2302 Journal must write-ahead
  src/org/exist/storage/BrokerPool.java
  src/org/exist/storage/journal/FileSyncRunnable.java
  src/org/exist/storage/journal/Journal.java
Labels: bug, high prio
