Repository eXist-db/exist, pull requests merged in 2019-07, with the labels that each got.

#2857 feat (xquery): implement fn:parse-ietf-date()
  exist-core/src/main/java/org/exist/xquery/ErrorCodes.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FnModule.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FunParseIetfDate.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FunString.java
  exist-core/src/test/xquery/xquery3/parseIetfDate.xqm
Labels: needs 5.0.0 backport

#2883 Dockerfile copy errors
  exist-docker/src/main/resources-filtered/Dockerfile
Labels: bug

#2884 (5.0.0) Dockerfile copy errors
  exist-docker/src/main/resources-filtered/Dockerfile
Labels: bug

#2876 Fix a number of security issues around user groups
  exist-ant/src/main/java/org/exist/ant/UserPasswordTask.java
  exist-core/src/main/java/org/exist/client/security/UserDialog.java
  exist-core/src/main/java/org/exist/config/ConfigurationDocumentTrigger.java
  exist-core/src/main/java/org/exist/security/AbstractAccount.java
  exist-core/src/main/java/org/exist/security/AbstractRealm.java
  exist-core/src/main/java/org/exist/security/PermissionFactory.java
  exist-core/src/main/java/org/exist/security/SecurityManager.java
  exist-core/src/main/java/org/exist/security/internal/RealmImpl.java
  exist-core/src/main/java/org/exist/security/internal/SecurityManagerImpl.java
  exist-core/src/main/java/org/exist/security/internal/aider/UserAider.java
  exist-core/src/main/java/org/exist/xquery/functions/securitymanager/FindGroupFunction.java
  exist-core/src/main/java/org/exist/xquery/functions/securitymanager/GroupManagementFunction.java
  exist-core/src/main/java/org/exist/xquery/functions/securitymanager/SecurityManagerModule.java
  exist-core/src/test/java/org/exist/backup/XMLDBRestoreTest.java
  exist-core/src/test/java/org/exist/security/AbstractAccountTest.java
  exist-core/src/test/java/org/exist/security/AbstractSecurityManagerRoundtripTest.java
  exist-core/src/test/java/org/exist/xquery/functions/securitymanager/AccountManagementFunctionRemoveAccountTest.java
  exist-core/src/test/java/org/exist/xquery/functions/securitymanager/GroupManagementFunctionRemoveGroupTest.java
  exist-core/src/test/java/org/exist/xquery/functions/securitymanager/GroupMembershipFunctionRemoveGroupMemberTest.java
  exist-core/src/test/java/org/exist/xquery/functions/securitymanager/PermissionsFunctionChownTest.java
Labels: bug, security

#2878 (5.0.0) Fix a number of security issues around user groups
  exist-ant/src/main/java/org/exist/ant/UserPasswordTask.java
  exist-core/src/main/java/org/exist/client/security/UserDialog.java
  exist-core/src/main/java/org/exist/config/ConfigurationDocumentTrigger.java
  exist-core/src/main/java/org/exist/security/AbstractAccount.java
  exist-core/src/main/java/org/exist/security/AbstractRealm.java
  exist-core/src/main/java/org/exist/security/PermissionFactory.java
  exist-core/src/main/java/org/exist/security/SecurityManager.java
  exist-core/src/main/java/org/exist/security/internal/RealmImpl.java
  exist-core/src/main/java/org/exist/security/internal/SecurityManagerImpl.java
  exist-core/src/main/java/org/exist/security/internal/aider/UserAider.java
  exist-core/src/main/java/org/exist/xquery/functions/securitymanager/FindGroupFunction.java
  exist-core/src/main/java/org/exist/xquery/functions/securitymanager/GroupManagementFunction.java
  exist-core/src/main/java/org/exist/xquery/functions/securitymanager/SecurityManagerModule.java
  exist-core/src/test/java/org/exist/backup/XMLDBRestoreTest.java
  exist-core/src/test/java/org/exist/security/AbstractAccountTest.java
  exist-core/src/test/java/org/exist/security/AbstractSecurityManagerRoundtripTest.java
  exist-core/src/test/java/org/exist/xquery/functions/securitymanager/AccountManagementFunctionRemoveAccountTest.java
  exist-core/src/test/java/org/exist/xquery/functions/securitymanager/GroupManagementFunctionRemoveGroupTest.java
  exist-core/src/test/java/org/exist/xquery/functions/securitymanager/GroupMembershipFunctionRemoveGroupMemberTest.java
  exist-core/src/test/java/org/exist/xquery/functions/securitymanager/PermissionsFunctionChownTest.java
Labels: bug, security

#2886 (5.0.0) Update the native Binaries for Apache Commons Daemon to 1.2.0
  exist-service/bin/jsvc-linux-x86_64
  exist-service/bin/jsvc-mac-x86_64
  exist-service/bin/prunsrv-x86_64.exe
Labels: enhancement

#2885 Update the native Binaries for Apache Commons Daemon to 1.2.0
  exist-service/bin/jsvc-linux-x86_64
  exist-service/bin/jsvc-mac-x86_64
  exist-service/bin/prunsrv-x86_64.exe
Labels: enhancement

#2890 Remove XQuery draft Map constructor
  exist-core/src/main/antlr/org/exist/xquery/parser/XQuery.g
  exist-core/src/test/xquery/maps/maps.xql
  exist-core/src/test/xquery/optimizer/optimizer.xql
  exist-core/src/test/xquery/xquery3/inline.xml
  exist-core/src/test/xquery/xquery3/recursion_calls.xml
  extensions/modules/cache/src/test/xquery/modules/cache/cache.xqm
Labels: deprecation

#2892 (5.0.0) Remove XQuery draft Map constructor
  exist-core/src/main/antlr/org/exist/xquery/parser/XQuery.g
  exist-core/src/test/xquery/maps/maps.xql
  exist-core/src/test/xquery/optimizer/optimizer.xql
  exist-core/src/test/xquery/xquery3/inline.xml
  exist-core/src/test/xquery/xquery3/recursion_calls.xml
  extensions/modules/cache/src/test/xquery/modules/cache/cache.xqm
Labels: deprecation

#2898 Further javadoc fixes
  exist-ant/src/main/java/org/exist/ant/AbstractXMLDBTask.java
  exist-ant/src/main/java/org/exist/ant/XMLDBExtractTask.java
Labels: bug

#2899 (5.0.0) Further javadoc fixes
  exist-ant/src/main/java/org/exist/ant/AbstractXMLDBTask.java
  exist-ant/src/main/java/org/exist/ant/XMLDBExtractTask.java
Labels: bug

#2900 (5.0.0) Remove OSS parent
  exist-core/pom.xml
  exist-parent/pom.xml
Labels: enhancement

#2901 Remove OSS Parent
  exist-core/pom.xml
  exist-parent/pom.xml
Labels: enhancement

#2906 (5.0.0) Fix release process
  exist-distribution/pom.xml
  exist-installer/pom.xml
  exist-parent/pom.xml
Labels: bug

#2907 Fix release process
  exist-distribution/pom.xml
  exist-installer/pom.xml
  exist-parent/pom.xml
Labels: bug

#2904 Small code improvement with Object.equals
  extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/NodePathPattern.java
Labels: enhancement

#2903 (4.x.x) Small code improvement with Object.equals
  extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/NodePathPattern.java
Labels: needs 5.0.0 backport
