Repository eXist-db/exist, pull requests merged in 2019-04, with the labels that each got.

#2279 Feature/lucene search leading wildcard
  extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/LuceneIndexWorker.java
  extensions/indexes/lucene/src/main/java/org/exist/xquery/modules/lucene/Query.java
  extensions/indexes/lucene/src/main/java/org/exist/xquery/modules/lucene/QueryField.java
  extensions/indexes/lucene/src/main/java/org/exist/xquery/modules/lucene/Search.java
  extensions/indexes/lucene/src/test/xquery/lucene/binary.xql
Labels: enhancement

#2447 fix context sequence for higher order functions and sorting
  exist-core/src/main/java/org/exist/xquery/ArrowOperator.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FunHigherOrderFun.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FunSort.java
  exist-core/src/test/xquery/xquery3/arrowop.xql
  exist-core/src/test/xquery/xquery3/fnSort.xql
Labels: bug

#2448 (5.0.0) fix context sequence for higher order functions and sorting
  exist-core/src/main/java/org/exist/xquery/ArrowOperator.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FunHigherOrderFun.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FunSort.java
  exist-core/src/test/xquery/xquery3/arrowop.xql
  exist-core/src/test/xquery/xquery3/fnSort.xql
Labels: bug

#2623 Fix XQuery Update insert following
  build/scripts/junit.xml
  exist-core/src/main/java/org/exist/dom/persistent/StoredNode.java
  exist-core/src/test/java/org/exist/xquery/XQueryUpdateTest.java
Labels: bug

#2624 (5.0.0) Fix XQuery Update insert following
  build/scripts/junit.xml
  exist-core/src/main/java/org/exist/dom/persistent/StoredNode.java
  exist-core/src/test/java/org/exist/xquery/XQueryUpdateTest.java
Labels: bug

#2625 (4.x.x) Fix XQuery Update insert following
  build/scripts/junit.xml
  exist-core/src/main/java/org/exist/dom/persistent/StoredNode.java
  exist-core/src/test/java/org/exist/xquery/XQueryUpdateTest.java
Labels: bug

#2601 (5.0.0) Fix the Spatial Index
  .idea/compiler.xml
  build/scripts/extensions-common.xml
  exist-core/src/main/java/org/exist/storage/structural/NativeStructuralIndexWorker.java
  exist-core/src/main/java/org/exist/xquery/functions/util/IndexKeys.java
  extensions/indexes/spatial/extension.xml
  extensions/indexes/spatial/ivy.xml
  extensions/indexes/spatial/ivysettings.xml
  extensions/indexes/spatial/src/main/java/org/exist/indexing/spatial/AbstractGMLJDBCIndexWorker.java
  extensions/indexes/spatial/src/main/java/org/exist/indexing/spatial/GMLHSQLIndex.java
  extensions/indexes/spatial/src/main/java/org/exist/indexing/spatial/GMLHSQLIndexWorker.java
  extensions/indexes/spatial/src/main/java/org/exist/xquery/modules/spatial/FunGMLProducers.java
  extensions/indexes/spatial/src/main/java/org/exist/xquery/modules/spatial/FunGeometricProperties.java
  extensions/indexes/spatial/src/main/java/org/exist/xquery/modules/spatial/FunSpatialSearch.java
  extensions/indexes/spatial/src/test/java/org/exist/indexing/spatial/GMLIndexTest.java
  extensions/indexes/spatial/src/test/resources/README.txt
  extensions/indexes/spatial/src/test/resources/conf.xml
Labels: bug

#2602 (4.x.x) Fix the Spatial Index
  .idea/compiler.xml
  build/scripts/extensions-common.xml
  exist-core/src/main/java/org/exist/plugin/PluginsManagerImpl.java
  exist-core/src/main/java/org/exist/storage/structural/NativeStructuralIndexWorker.java
  exist-core/src/main/java/org/exist/xquery/functions/util/IndexKeys.java
  extensions/indexes/spatial/extension.xml
  extensions/indexes/spatial/ivy.xml
  extensions/indexes/spatial/ivysettings.xml
  extensions/indexes/spatial/src/main/java/org/exist/indexing/spatial/AbstractGMLJDBCIndexWorker.java
  extensions/indexes/spatial/src/main/java/org/exist/indexing/spatial/GMLHSQLIndex.java
  extensions/indexes/spatial/src/main/java/org/exist/indexing/spatial/GMLHSQLIndexWorker.java
  extensions/indexes/spatial/src/main/java/org/exist/xquery/modules/spatial/FunGMLProducers.java
  extensions/indexes/spatial/src/main/java/org/exist/xquery/modules/spatial/FunGeometricProperties.java
  extensions/indexes/spatial/src/main/java/org/exist/xquery/modules/spatial/FunSpatialSearch.java
  extensions/indexes/spatial/src/test/java/org/exist/indexing/spatial/GMLIndexTest.java
  extensions/indexes/spatial/src/test/resources/README.txt
  extensions/indexes/spatial/src/test/resources/conf.xml
Labels: bug

#2600 Fix the Spatial Index
  .idea/compiler.xml
  build/scripts/extensions-common.xml
  exist-core/src/main/java/org/exist/storage/structural/NativeStructuralIndexWorker.java
  exist-core/src/main/java/org/exist/xquery/functions/util/IndexKeys.java
  extensions/indexes/spatial/extension.xml
  extensions/indexes/spatial/ivy.xml
  extensions/indexes/spatial/ivysettings.xml
  extensions/indexes/spatial/src/main/java/org/exist/indexing/spatial/AbstractGMLJDBCIndexWorker.java
  extensions/indexes/spatial/src/main/java/org/exist/indexing/spatial/GMLHSQLIndex.java
  extensions/indexes/spatial/src/main/java/org/exist/indexing/spatial/GMLHSQLIndexWorker.java
  extensions/indexes/spatial/src/main/java/org/exist/xquery/modules/spatial/FunGMLProducers.java
  extensions/indexes/spatial/src/main/java/org/exist/xquery/modules/spatial/FunGeometricProperties.java
  extensions/indexes/spatial/src/main/java/org/exist/xquery/modules/spatial/FunSpatialSearch.java
  extensions/indexes/spatial/src/test/java/org/exist/indexing/spatial/GMLIndexTest.java
  extensions/indexes/spatial/src/test/resources/README.txt
  extensions/indexes/spatial/src/test/resources/conf.xml
Labels: bug

#2605 (4.x.x) Fix an issue with XQSuite serialization of expected CData
  exist-core/src/main/resources/org/exist/xquery/lib/test.xq
  exist-core/src/test/xquery/json.xml
Labels: bug

#2629 (5.0.0) Fast faceted search
  exist-core/src/main/resources/org/exist/xquery/lib/xqsuite/xqsuite.xql
  extensions/indexes/lucene/ivy.xml
  extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/AbstractFieldConfig.java
  extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/AnalyzerConfig.java
  extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/FieldType.java
  extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/LuceneConfig.java
  extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/LuceneFacetConfig.java
  extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/LuceneFieldConfig.java
  extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/LuceneIndex.java
  extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/LuceneIndexConfig.java
  extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/LuceneIndexWorker.java
  extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/LuceneMatch.java
  extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/LuceneMatchListener.java
  extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/LuceneUtil.java
  extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/XMLToQuery.java
  extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/analyzers/MetaAnalyzer.java
  extensions/indexes/lucene/src/main/java/org/exist/xquery/modules/lucene/Facets.java
  extensions/indexes/lucene/src/main/java/org/exist/xquery/modules/lucene/Field.java
  extensions/indexes/lucene/src/main/java/org/exist/xquery/modules/lucene/GetField.java
  extensions/indexes/lucene/src/main/java/org/exist/xquery/modules/lucene/LuceneIndexKeys.java
  extensions/indexes/lucene/src/main/java/org/exist/xquery/modules/lucene/LuceneModule.java
  extensions/indexes/lucene/src/main/java/org/exist/xquery/modules/lucene/Query.java
  extensions/indexes/lucene/src/main/java/org/exist/xquery/modules/lucene/QueryField.java
  extensions/indexes/lucene/src/main/java/org/exist/xquery/modules/lucene/QueryOptions.java
  extensions/indexes/lucene/src/main/java/org/exist/xquery/modules/lucene/Score.java
  extensions/indexes/lucene/src/main/java/org/exist/xquery/modules/lucene/Search.java
  extensions/indexes/lucene/src/test/java/xquery/lucene/LuceneTests.java
  extensions/indexes/lucene/src/test/xquery/lucene/facets.xql
  extensions/indexes/range/src/main/java/org/exist/indexing/range/RangeIndexWorker.java
  schema/collection.xconf.xsd
Labels: enhancement

#2647 (4.x.x) Fix ArrayOutOfBoundsException with fn:id
  exist-core/src/main/java/org/exist/dom/memtree/DocumentImpl.java
  exist-core/src/test/xquery/xmlid.xql
Labels: bug

#2646 (5.0.0) Fix ArrayOutOfBoundsException with fn:id
  exist-core/src/main/java/org/exist/dom/memtree/DocumentImpl.java
  exist-core/src/test/xquery/xmlid.xql
Labels: bug

#2645 Fix ArrayOutOfBoundsException with fn:id
  exist-core/src/main/java/org/exist/dom/memtree/DocumentImpl.java
  exist-core/src/test/xquery/xmlid.xql
Labels: bug

#2632 Fix use of deprecated functions to restore dashboard etc.
  build/scripts/extensions-common.xml
  eXist-db.iml
  extensions/modules/persistentlogin/src/main/resources/org/exist/xquery/modules/persistentlogin/login.xql
  extensions/modules/persistentlogin/src/test/java/org/exist/xquery/modules/persistentlogin/LoginModuleTest.java
Labels: needs 4.x.x backport

#2650 (4.x.x) Fix the Ant dist target for releases
  build/scripts/dist.xml
Labels: bug

#2649 (5.0.0) Fix the Ant dist target for releases
  build/scripts/dist.xml
Labels: bug

#2648 Fix the Ant dist target for releases
  build/scripts/dist.xml
Labels: bug

#2653 (4.x.x) EXPath HTTP should respect charset in override-media-type
  extensions/expath/lib/http-client-java-1.0-SNAPSHOT.jar
Labels: bug

#2652 (5.0.0) EXPath HTTP should respect charset in override-media-type
  extensions/expath/lib/http-client-java-1.0-SNAPSHOT.jar
Labels: bug

#2651 EXPath HTTP should respect charset in override-media-type
  extensions/expath/lib/http-client-java-1.0-SNAPSHOT.jar
Labels: bug

#2655 Small cleanups
  exist-core/src/main/java/org/exist/storage/md/Meta.java
  exist-core/src/main/java/org/exist/storage/md/MetaData.java
  exist-core/src/main/java/org/exist/storage/md/Metas.java
  exist-core/src/main/java/org/exist/xmldb/LocalCollection.java.orig
  exist-core/src/test/xquery/literals-in-curlies.xql
Labels: bug

#2656 (5.0.0) Small cleanups
  exist-core/src/main/java/org/exist/storage/md/Meta.java
  exist-core/src/main/java/org/exist/storage/md/MetaData.java
  exist-core/src/main/java/org/exist/storage/md/Metas.java
  exist-core/src/main/java/org/exist/xmldb/LocalCollection.java.orig
Labels: bug
