Repository eXist-db/exist, pull requests merged in 2019-11, with the labels that each got.

#3064 Fix a race condition in WeakLazyStripes
  .travis.yml
  appveyor.yml
  exist-ant/src/test/resources/log4j2.xml
  exist-core-jcstress/pom.xml
  exist-core-jcstress/src/main/java/org/exist/util/WeakLazyStripesStressTest.java
  exist-core/src/main/java/org/exist/util/WeakLazyStripes.java
  exist-core/src/test/resources/log4j2.xml
  extensions/debuggee/src/test/resources/log4j2.xml
  extensions/expath/src/test/resources/log4j2.xml
  extensions/exquery/restxq/src/test/resources/log4j2.xml
  extensions/indexes/lucene/src/test/resources/log4j2.xml
  extensions/indexes/ngram/src/test/resources/log4j2.xml
  extensions/indexes/range/src/test/resources/log4j2.xml
  extensions/indexes/sort/src/test/resources/log4j2.xml
  extensions/indexes/spatial/src/test/resources/log4j2.xml
  extensions/modules/cache/src/test/resources/log4j2.xml
  extensions/modules/compression/src/test/resources/log4j2.xml
  extensions/modules/counter/src/test/resources/log4j2.xml
  extensions/modules/expathrepo/src/test/resources/log4j2.xml
  extensions/modules/file/src/test/resources/log4j2.xml
  extensions/modules/persistentlogin/src/test/resources/log4j2.xml
  extensions/security/activedirectory/src/test/resources/log4j2.xml
  extensions/xqdoc/src/test/resources/log4j2.xml
  pom.xml
Labels: bug

#3112 Fix a StackOverflowError caused by lost type into
  exist-core/src/main/java/org/exist/xquery/UnaryExpr.java
  exist-core/src/test/xquery/treatAs.xq
  exist-core/src/test/xquery/xquery3/bang.xql
Labels: bug

#3113 Avoid ConcurrentModificationException at shutdown
  exist-core/src/main/java/org/exist/storage/ProcessMonitor.java
Labels: bug

#3107 Lucene: add support for minimum-must-match on BooleanQuery
  extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/XMLToQuery.java
  extensions/indexes/lucene/src/test/xquery/lucene/queries.xml
Labels: enhancement

#3126 Fix an NPE with Apache FOP XSL:FO rendering
  extensions/modules/xslfo/pom.xml
  extensions/modules/xslfo/src/main/java/org/exist/xquery/modules/xslfo/ApacheFopProcessorAdapter.java
  extensions/modules/xslfo/src/test/java/org/exist/xquery/modules/xslfo/ApacheFopTest.java
  extensions/modules/xslfo/src/test/resources-filtered/conf.xml
  extensions/modules/xslfo/src/test/resources/log4j2.xml
Labels: bug, regression

#3127 Remove unused config settings
  exist-ant/src/test/resources-filtered/conf.xml
  exist-core/src/main/java/org/exist/collections/CollectionConfiguration.java
  exist-core/src/main/java/org/exist/config/Configurator.java
  exist-core/src/main/java/org/exist/security/Permission.java
  exist-core/src/main/java/org/exist/storage/BrokerPool.java
  exist-core/src/main/java/org/exist/storage/BrokerPoolConstants.java
  exist-core/src/main/java/org/exist/storage/sync/SyncTask.java
  exist-core/src/main/java/org/exist/util/Configuration.java
  exist-core/src/test/resources-filtered/conf.xml
  exist-distribution/src/main/config/conf.xml
  extensions/debuggee/src/test/resources-filtered/conf.xml
  extensions/expath/src/test/resources-filtered/conf.xml
  extensions/exquery/restxq/src/test/resources-filtered/conf.xml
  extensions/indexes/lucene/src/test/resources-filtered/conf.xml
  extensions/indexes/ngram/src/test/resources-filtered/conf.xml
  extensions/indexes/range/src/test/resources-filtered/conf.xml
  extensions/indexes/sort/src/test/resources-filtered/conf.xml
  extensions/indexes/spatial/src/test/resources-filtered/conf.xml
  extensions/modules/cache/src/test/resources-filtered/conf.xml
  extensions/modules/compression/src/test/resources-filtered/conf.xml
  extensions/modules/counter/src/test/resources-filtered/conf.xml
  extensions/modules/expathrepo/src/test/resources-filtered/conf.xml
  extensions/modules/file/src/test/resources-filtered/conf.xml
  extensions/modules/persistentlogin/src/test/resources-filtered/conf.xml
  extensions/xqdoc/src/test/resources-filtered/conf.xml
  schema/conf.xsd
Labels: enhancement
