Repository eXist-db/exist, pull requests merged in 2019-06, with the labels that each got.

#2773 Don't quieten Maven output on Travis-CI
  .travis.yml
Labels: bug

#2774 (5.0.0) Don't quieten Maven output on Travis-CI
  .travis.yml
Labels: bug

#2775 Small cleanup
  exist-core/src/main/java/org/exist/storage/lock/LockTable.java
  exist-core/src/main/java/org/exist/storage/lock/LockTableUtils.java
  exist-core/src/test/java/org/exist/backup/SystemExportFiltersTest.java
  exist-core/src/test/java/org/exist/xmldb/ContentAsDOMTest.java
  exist-core/src/test/java/org/exist/xmldb/IndexingTest.java
  exist-core/src/test/java/org/exist/xmldb/MultiDBTest.java
  exist-core/src/test/java/org/exist/xmldb/concurrent/ConcurrentTestBase.java
  exist-distribution/pom.xml
  extensions/exquery/restxq/pom.xml
  extensions/indexes/ngram/src/test/java/org/exist/indexing/ngram/AllIndexTests.java
  extensions/modules/expathrepo/pom.xml
  extensions/modules/file/pom.xml
  extensions/modules/persistentlogin/pom.xml
Labels: bug, enhancement

#2776 (5.0.0) Small cleanup
  exist-core/src/main/java/org/exist/storage/lock/LockTable.java
  exist-core/src/main/java/org/exist/storage/lock/LockTableUtils.java
  exist-core/src/test/java/org/exist/backup/SystemExportFiltersTest.java
  exist-core/src/test/java/org/exist/xmldb/ContentAsDOMTest.java
  exist-core/src/test/java/org/exist/xmldb/IndexingTest.java
  exist-core/src/test/java/org/exist/xmldb/MultiDBTest.java
  exist-core/src/test/java/org/exist/xmldb/concurrent/ConcurrentTestBase.java
  exist-distribution/pom.xml
  extensions/exquery/restxq/pom.xml
  extensions/indexes/ngram/src/test/java/org/exist/indexing/ngram/AllIndexTests.java
  extensions/modules/expathrepo/pom.xml
  extensions/modules/file/pom.xml
  extensions/modules/persistentlogin/pom.xml
Labels: bug, enhancement

#2788 Fix wrong lock taken in WebDAV delete document code
  extensions/webdav/src/main/java/org/exist/webdav/ExistDocument.java
Labels: bug

#2789 (5.0.0) Fix wrong lock taken in WebDAV delete document code
  extensions/webdav/src/main/java/org/exist/webdav/ExistDocument.java
Labels: bug

#2793 (5.0.0) Bump appbundler-maven-plugin from 1.0.1 to 1.0.4
  exist-distribution/pom.xml
Labels: dependencies

#2809 Fix descriptor.xml lookup
  exist-core/src/main/java/org/exist/http/Descriptor.java
Labels: bug

#2810 (5.0.0) Fix descriptor.xml lookup
  exist-core/src/main/java/org/exist/http/Descriptor.java
Labels: bug

#2813 Update the EXPath HTTP Client
  extensions/expath/pom.xml
Labels: bug, enhancement

#2814 (5.0.0) Update the EXPath HTTP Client
  extensions/expath/pom.xml
Labels: bug, enhancement

#2821 Make sure to close the stream to avoid leaking file handles
  exist-core/src/main/java/org/exist/repo/ExistRepository.java
Labels: bug

#2822 (4.x.x) Make sure to close the stream to avoid leaking file handles
  exist-core/src/main/java/org/exist/repo/ExistRepository.java
Labels: bug

#2823 (5.0.0) Make sure to close the stream to avoid leaking file handles
  exist-core/src/main/java/org/exist/repo/ExistRepository.java
Labels: bug

#2825 Make the `mvn package` phase repeatable
  exist-distribution/pom.xml
  exist-distribution/src/main/scripts/create-dmg-mac.sh
  exist-distribution/src/main/scripts/create-dmg-unix.sh
Labels: bug

#2824 Fix IntelliJ shared run target for Jetty Server
  .idea/runConfigurations/Java_Admin_Client.xml
  .idea/runConfigurations/Jetty_Server.xml
Labels: bug

#2826 (5.0.0) Make the `mvn package` phase repeatable
  exist-distribution/pom.xml
  exist-distribution/src/main/scripts/create-dmg-mac.sh
  exist-distribution/src/main/scripts/create-dmg-unix.sh
Labels: bug

#2831 (5.0.0) Improve the performance of WeakLazyStripes
  exist-core/src/main/java/org/exist/util/Holder.java
  exist-core/src/main/java/org/exist/util/WeakLazyStripes.java
Labels: enhancement

#2830 Improve the performance of WeakLazyStripes
  exist-core/src/main/java/org/exist/util/Holder.java
  exist-core/src/main/java/org/exist/util/WeakLazyStripes.java
Labels: enhancement

#2832 [ignore] Delete legacy code
  exist-core/src/main/java/org/exist/Database.java
  exist-core/src/main/java/org/exist/indexing/IndexController.java
  exist-core/src/main/java/org/exist/storage/BrokerPool.java
  exist-core/src/main/java/org/exist/storage/MetaStorage.java
  exist-core/src/main/java/org/exist/storage/MetaStreamListener.java
  extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/LuceneIndexWorker.java
Labels: bug

#2833 [ignore] Delete legacy code
  exist-core/src/main/java/org/exist/Database.java
  exist-core/src/main/java/org/exist/indexing/IndexController.java
  exist-core/src/main/java/org/exist/storage/BrokerPool.java
  exist-core/src/main/java/org/exist/storage/MetaStorage.java
  exist-core/src/main/java/org/exist/storage/MetaStreamListener.java
  extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/LuceneIndexWorker.java
Labels: bug

#2843 (4.x.x) Disable bad optimization
  exist-core/src/main/java/org/exist/xquery/Optimizer.java
  extensions/indexes/range/src/test/xquery/range/optimizer.xql
Labels: bug

#2836 Disable bad optimization
  exist-core/src/main/java/org/exist/xquery/Optimizer.java
  extensions/indexes/range/src/test/xquery/range/optimizer.xql
Labels: bug

#2845 (4.x.x) Adds VirtualTempPath on set content methods
  exist-core/src/main/java/org/exist/util/io/ByteArrayContent.java
  exist-core/src/main/java/org/exist/util/io/ContentFile.java
  exist-core/src/main/java/org/exist/util/io/VirtualTempPath.java
  exist-core/src/main/java/org/exist/xmldb/AbstractRemoteResource.java
  exist-core/src/main/java/org/exist/xmldb/RemoteCollection.java
  exist-core/src/main/java/org/exist/xmldb/RemoteResourceSet.java
  exist-core/src/main/java/org/exist/xmldb/RemoteXMLResource.java
  exist-core/src/test/java/org/exist/util/io/ByteArrayContentTest.java
Labels: enhancement

#2844 (5.0.0) Adds VirtualTempPath on set content methods
  exist-core/src/main/java/org/exist/util/io/ByteArrayContent.java
  exist-core/src/main/java/org/exist/util/io/ContentFile.java
  exist-core/src/main/java/org/exist/util/io/VirtualTempPath.java
  exist-core/src/main/java/org/exist/xmldb/AbstractRemoteResource.java
  exist-core/src/main/java/org/exist/xmldb/RemoteCollection.java
  exist-core/src/main/java/org/exist/xmldb/RemoteResourceSet.java
  exist-core/src/main/java/org/exist/xmldb/RemoteXMLResource.java
  exist-core/src/test/java/org/exist/util/io/ByteArrayContentTest.java
Labels: enhancement

#2842 Adds VirtualTempPath on set content methods
  exist-core/src/main/java/org/exist/util/io/ByteArrayContent.java
  exist-core/src/main/java/org/exist/util/io/ContentFile.java
  exist-core/src/main/java/org/exist/util/io/VirtualTempPath.java
  exist-core/src/main/java/org/exist/xmldb/AbstractRemoteResource.java
  exist-core/src/main/java/org/exist/xmldb/RemoteCollection.java
  exist-core/src/main/java/org/exist/xmldb/RemoteResourceSet.java
  exist-core/src/main/java/org/exist/xmldb/RemoteXMLResource.java
  exist-core/src/test/java/org/exist/util/io/ByteArrayContentTest.java
Labels: enhancement

#2838 Added system:get-product-name()
  exist-core/src/main/java/org/exist/xquery/functions/system/GetProductName.java
  exist-core/src/main/java/org/exist/xquery/functions/system/SystemModule.java
Labels: enhancement

#2840 (4.x.x) Added system:get-product-name()
  exist-core/src/main/java/org/exist/xquery/functions/system/GetProductName.java
  exist-core/src/main/java/org/exist/xquery/functions/system/SystemModule.java
Labels: enhancement

#2839 (5.x.x) Added system:get-product-name()
  exist-core/src/main/java/org/exist/xquery/functions/system/GetProductName.java
  exist-core/src/main/java/org/exist/xquery/functions/system/SystemModule.java
Labels: enhancement

#2847 (5.0.0) Fix the DMG build on Unix
  exist-distribution/src/main/scripts/create-dmg-unix.sh
Labels: bug

#2846 Fix the DMG build on Unix
  exist-distribution/src/main/scripts/create-dmg-unix.sh
Labels: bug

#2855 (5.0.0) Update Multilock to the released version
  exist-core/pom.xml
Labels: enhancement

#2854 Update Multilock to the released version
  exist-core/pom.xml
Labels: enhancement
