Repository eXist-db/exist, pull requests merged in 2019-02, with the labels that each got.

#2457 Improve serializer performance
  src/org/exist/storage/serializers/Serializer.java
Labels: enhancement

#2458 (4.x.x) Improve serializer performance
  src/org/exist/storage/serializers/Serializer.java
Labels: enhancement

#2453 (4.x.x) Fix a serialization issue with util:eval-and-serialize
  src/org/exist/xquery/functions/util/Eval.java
  test/src/org/exist/xquery/functions/util/EvalTest.java
Labels: bug

#2454 (5.0.0) Fix a serialization issue with util:eval-and-serialize
  src/org/exist/xquery/functions/util/Eval.java
  test/src/org/exist/xquery/functions/util/EvalTest.java
Labels: bug

#2455 Fix a serialization issue with util:eval-and-serialize
  src/org/exist/xquery/functions/util/Eval.java
  test/src/org/exist/xquery/functions/util/EvalTest.java
Labels: bug

#2472 Send Travis notifications to Slack
  .travis.yml
Labels: needs 4.x.x backport, needs 5.0.0 backport

#2489 (develop) Change github path to reflect new situation
  src/test/xquery/unparsed-text.xql
Labels: bug

#2487 (4xx) Change github path to reflect new situation
  src/test/xquery/unparsed-text.xql
Labels: bug

#2488 (5xx) Change github path to reflect new situation
  src/test/xquery/unparsed-text.xql
Labels: bug

#2490 (develop) Prevent NPE in unparsed-text-available for GitHub URL
  src/main/java/org/exist/xquery/functions/fn/FunUnparsedText.java
  src/test/xquery/unparsed-text.xql
Labels: bug, needs 4.x.x backport, needs 5.0.0 backport

#2507 (4xx) Make sure mime-types.xml is in jar file
  build/scripts/build-impl.xml
  exist-core/src/main/resources/org/exist/xquery/parser/DeclScanner.smap
  exist-core/src/main/resources/org/exist/xquery/parser/DeclScannerTokenTypes.txt
  exist-core/src/main/resources/org/exist/xquery/parser/XQueryLexer.smap
  exist-core/src/main/resources/org/exist/xquery/parser/XQueryParser.smap
  exist-core/src/main/resources/org/exist/xquery/parser/XQueryTokenTypes.txt
  exist-core/src/main/resources/org/exist/xquery/parser/XQueryTreeParser.smap
  exist-core/src/main/resources/org/exist/xquery/parser/XQueryTreeParserTokenTypes.txt
Labels: bug, high prio, regression, tomcat

#2508 (5xx) Make sure mime-types.xml is in jar file
  build/scripts/build-impl.xml
  exist-core/src/main/resources/org/exist/xquery/parser/DeclScanner.smap
  exist-core/src/main/resources/org/exist/xquery/parser/DeclScannerTokenTypes.txt
  exist-core/src/main/resources/org/exist/xquery/parser/XQueryLexer.smap
  exist-core/src/main/resources/org/exist/xquery/parser/XQueryParser.smap
  exist-core/src/main/resources/org/exist/xquery/parser/XQueryTokenTypes.txt
  exist-core/src/main/resources/org/exist/xquery/parser/XQueryTreeParser.smap
  exist-core/src/main/resources/org/exist/xquery/parser/XQueryTreeParserTokenTypes.txt
Labels: bug, high prio, regression, tomcat

#2509 (develop) Make sure mime-types.xml is in jar file
  build/scripts/build-impl.xml
  exist-core/src/main/resources/org/exist/xquery/parser/DeclScanner.smap
  exist-core/src/main/resources/org/exist/xquery/parser/DeclScannerTokenTypes.txt
  exist-core/src/main/resources/org/exist/xquery/parser/XQueryLexer.smap
  exist-core/src/main/resources/org/exist/xquery/parser/XQueryParser.smap
  exist-core/src/main/resources/org/exist/xquery/parser/XQueryTokenTypes.txt
  exist-core/src/main/resources/org/exist/xquery/parser/XQueryTreeParser.smap
  exist-core/src/main/resources/org/exist/xquery/parser/XQueryTreeParserTokenTypes.txt
Labels: bug, high prio

#2516 Remove whitespace from jar entry (4xx only)
  exist-core/src/main/java/org/exist/webstart/JnlpJarFiles.java
Labels: bug, high prio, regression
