Repository eXist-db/exist, pull requests merged in 2019-12, with the labels that each got.

#3134 Update IntelliJ run configurations for 5.2.0-SNAPSHOT
  .idea/runConfigurations/Java_Admin_Client.xml
  .idea/runConfigurations/Jetty_Server.xml
Labels: bug

#3130 [bugfix] New implementation of fn:format-number
  exist-core/src/main/java/org/exist/dom/QName.java
  exist-core/src/main/java/org/exist/util/CodePointString.java
  exist-core/src/main/java/org/exist/xquery/DecimalFormat.java
  exist-core/src/main/java/org/exist/xquery/ErrorCodes.java
  exist-core/src/main/java/org/exist/xquery/Function.java
  exist-core/src/main/java/org/exist/xquery/XQueryContext.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FnFormatNumbers.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FnModule.java
  exist-core/src/test/java/org/exist/util/CodePointStringTest.java
  exist-core/src/test/xquery/numbers/format-numbers.xql
Labels: enhancement, in progress

#3140 Remove extraneous logging of stack traces
  exist-core/src/main/java/org/exist/source/URLSource.java
Labels: bug

#3155 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#3147 Small fixes to fix the site build
  exist-core/src/main/java/org/exist/security/SimpleACLPermission.java
  exist-core/src/main/java/org/exist/security/internal/aider/SimpleACLPermissionAider.java
  exist-core/src/main/java/org/exist/storage/SystemTaskManager.java
  exist-core/src/main/java/org/exist/util/CodePointString.java
  exist-core/src/main/java/org/exist/xquery/DecimalFormat.java
  exist-core/src/main/java/org/exist/xquery/Step.java
  exist-parent/pom.xml
Labels: bug

#3156 Fix a livelock in TransactionManager
  exist-core/src/main/java/org/exist/storage/txn/TransactionManager.java
Labels: bug

#3149 Test should override default config
  exist-core/src/test/java/org/exist/storage/BrokerPoolsTest.java
Labels: bug, windows
