Repository eXist-db/exist, pull requests merged in 2019-08, with the labels that each got.

#2915 [doc] Add a badge for Maven Central
  README.md
Labels: enhancement

#2924 (5.0.0) Fix user leak in XQuery User Switching functions
  exist-core/src/main/java/org/exist/xquery/UserSwitchingBasicFunction.java
Labels: bug, high prio, security

#2925 (4.x.x) Fix user leak in XQuery User Switching functions
  exist-core/src/main/java/org/exist/xquery/UserSwitchingBasicFunction.java
Labels: bug, high prio, security

#2923 Fix user leak in XQuery User Switching functions
  exist-core/src/main/java/org/exist/xquery/UserSwitchingBasicFunction.java
Labels: bug, high prio, security

#2909 Mac artifact should be named eXist-db-$ver.dmg
  exist-distribution/pom.xml
Labels: bug

#2910 (5.0.0) Mac artifact should be named eXist-db-$ver.dmg
  exist-distribution/pom.xml
Labels: bug

#2926 Make sure embedded restore chooses correct data dir
  exist-core/src/main/java/org/exist/util/Configuration.java
Labels: bug

#2927 (5.0.0) Make sure embedded restore chooses correct data dir
  exist-core/src/main/java/org/exist/util/Configuration.java
Labels: bug

#2935 (4.x.x) Java Admin Client should be able to change logged in account password
  exist-core/src/main/java/org/exist/client/ClientFrame.java
  exist-core/src/main/java/org/exist/client/InteractiveClient.java
Labels: bug

#2934 (5.0.0) Java Admin Client should be able to change logged in account password
  exist-core/src/main/java/org/exist/client/ClientFrame.java
  exist-core/src/main/java/org/exist/client/InteractiveClient.java
Labels: bug

#2933 Java Admin Client should be able to change logged in account password
  exist-core/src/main/java/org/exist/client/ClientFrame.java
  exist-core/src/main/java/org/exist/client/InteractiveClient.java
Labels: bug

#2930 Reinstate the bin scripts in the App produced for Mac platforms
  exist-distribution/pom.xml
Labels: bug

#2931 (5.0.0) Reinstate the bin scripts in the App produced for Mac platforms
  exist-distribution/pom.xml
Labels: bug

#2902 Disambiguate develop and develop-5.0.0 branch versions
  .idea/runConfigurations/Java_Admin_Client.xml
  .idea/runConfigurations/Jetty_Server.xml
  exist-ant/pom.xml
  exist-core-jmh/pom.xml
  exist-core/pom.xml
  exist-deb/pom.xml
  exist-distribution/pom.xml
  exist-docker/pom.xml
  exist-installer/pom.xml
  exist-jetty-config/pom.xml
  exist-parent/pom.xml
  exist-samples/pom.xml
  exist-service/pom.xml
  exist-start/pom.xml
  extensions/contentextraction/pom.xml
  extensions/debuggee/pom.xml
  extensions/exiftool/pom.xml
  extensions/expath/pom.xml
  extensions/exquery/modules/pom.xml
  extensions/exquery/modules/request/pom.xml
  extensions/exquery/pom.xml
  extensions/exquery/restxq/pom.xml
  extensions/images/pom.xml
  extensions/indexes/lucene/pom.xml
  extensions/indexes/ngram/pom.xml
  extensions/indexes/pom.xml
  extensions/indexes/range/pom.xml
  extensions/indexes/sort/pom.xml
  extensions/indexes/spatial/pom.xml
  extensions/modules/cache/pom.xml
  extensions/modules/compression/pom.xml
  extensions/modules/counter/pom.xml
  extensions/modules/cqlparser/pom.xml
  extensions/modules/example/pom.xml
  extensions/modules/exi/pom.xml
  extensions/modules/expathrepo/pom.xml
  extensions/modules/file/pom.xml
  extensions/modules/image/pom.xml
  extensions/modules/jndi/pom.xml
  extensions/modules/mail/pom.xml
  extensions/modules/persistentlogin/pom.xml
  extensions/modules/pom.xml
  extensions/modules/process/pom.xml
  extensions/modules/scheduler/pom.xml
  extensions/modules/simpleql/pom.xml
  extensions/modules/sql-oracle/pom.xml
  extensions/modules/sql/pom.xml
  extensions/modules/xmldiff/pom.xml
  extensions/modules/xslfo/pom.xml
  extensions/pom.xml
  extensions/security/activedirectory/pom.xml
  extensions/security/iprange/pom.xml
  extensions/security/ldap/pom.xml
  extensions/security/pom.xml
  extensions/webdav/pom.xml
  extensions/xqdoc/pom.xml
  pom.xml
Labels: enhancement

#2913 Make sure to sign Git tags
  exist-parent/pom.xml
Labels: bug

#2928 Fix the WebSocket server when run from Uber Jar (e.g. Docker)
  exist-docker/pom.xml
Labels: bug

#2929 (5.0.0) Fix the WebSocket server when run from Uber Jar (e.g. Docker)
  exist-docker/pom.xml
Labels: bug

#2327 Fix a couple of issues in LDAP
  exist-core/src/main/java/org/exist/security/AbstractRealm.java
  exist-core/src/main/java/org/exist/security/internal/SecurityManagerImpl.java
  exist-core/src/main/java/org/exist/security/management/AccountsManagement.java
  exist-core/src/main/java/org/exist/security/management/GroupsManagement.java
  extensions/security/ldap/src/main/java/org/exist/security/realm/ldap/LDAPRealm.java
Labels: bug

#2937 (5.0.0) Fix a couple of issues in LDAP
  exist-core/src/main/java/org/exist/security/AbstractRealm.java
  exist-core/src/main/java/org/exist/security/internal/SecurityManagerImpl.java
  exist-core/src/main/java/org/exist/security/management/AccountsManagement.java
  exist-core/src/main/java/org/exist/security/management/GroupsManagement.java
  extensions/security/ldap/src/main/java/org/exist/security/realm/ldap/LDAPRealm.java
Labels: bug

#2938 (4.x.x) Fix a couple of issues in LDAP
  exist-core/src/main/java/org/exist/security/AbstractRealm.java
  exist-core/src/main/java/org/exist/security/internal/SecurityManagerImpl.java
  exist-core/src/main/java/org/exist/security/management/AccountsManagement.java
  exist-core/src/main/java/org/exist/security/management/GroupsManagement.java
  extensions/security/ldap/src/main/java/org/exist/security/realm/ldap/LDAPRealm.java
Labels: bug

#2954 Update Tika to avoid security issues
  extensions/contentextraction/pom.xml
Labels: security

#2955 (5.0.0) Update Tika to avoid security issues
  extensions/contentextraction/pom.xml
Labels: security

#2960 Improve product details available over JMX
  exist-core/src/main/java/org/exist/management/impl/SystemInfo.java
  exist-core/src/main/java/org/exist/management/impl/SystemInfoMXBean.java
Labels: enhancement

#2961 (5.0.0) Improve product details available over JMX
  exist-core/src/main/java/org/exist/management/impl/SystemInfo.java
  exist-core/src/main/java/org/exist/management/impl/SystemInfoMXBean.java
Labels: enhancement

#2953 Update to the latest version of jline to avoid an issue with linux terminal types
  exist-core/pom.xml
Labels: bug

#2615 (5.0.0) Add tests for question marks in contains function
  exist-core/src/test/xquery/question-marks-in-contains-function.xql
Labels: enhancement

#2962 Improve Lock Table lease recording performance
  exist-core-jmh/src/main/java/org/exist/storage/lock/LockTableBenchmark.java
  exist-core/src/main/java/org/exist/dom/persistent/DocumentImpl.java
  exist-core/src/main/java/org/exist/storage/BrokerPool.java
  exist-core/src/main/java/org/exist/storage/lock/LockManager.java
  exist-core/src/main/java/org/exist/storage/lock/LockTable.java
  exist-core/src/main/java/org/exist/util/Configuration.java
  exist-core/src/main/java/org/exist/util/WeakLazyStripes.java
  exist-core/src/main/java/org/exist/xmldb/XmldbURI.java
  exist-core/src/main/java/org/exist/xquery/RootNode.java
  exist-distribution/src/main/config/conf.xml
  schema/conf.xsd
Labels: enhancement

#2963 (5.0.0) Improve Lock Table lease recording performance
  exist-core/src/main/java/org/exist/dom/persistent/DocumentImpl.java
  exist-core/src/main/java/org/exist/storage/BrokerPool.java
  exist-core/src/main/java/org/exist/storage/lock/LockManager.java
  exist-core/src/main/java/org/exist/storage/lock/LockTable.java
  exist-core/src/main/java/org/exist/util/Configuration.java
  exist-core/src/main/java/org/exist/util/WeakLazyStripes.java
  exist-core/src/main/java/org/exist/xmldb/XmldbURI.java
  exist-core/src/main/java/org/exist/xquery/RootNode.java
  exist-distribution/src/main/config/conf.xml
  schema/conf.xsd
Labels: enhancement

#2968 (5.0.0) Bump pkg-java from 1.4.0 to 1.4.1
  exist-parent/pom.xml
Labels: bug

#2969 Fix an NPE under load recently introduced in WeakLazyStripes
  exist-core/src/main/java/org/exist/util/WeakLazyStripes.java
Labels: bug, high prio, regression

#2970 (5.0.0) Fix an NPE under load recently introduced in WeakLazyStripes
  exist-core/src/main/java/org/exist/util/WeakLazyStripes.java
Labels: bug, high prio, regression

#2971 Improve the concurrent performance of the Compiled XQuery Pool
  exist-core/pom.xml
  exist-core/src/main/java/org/exist/storage/XQueryPool.java
Labels: enhancement

#2972 (5.0.0) Improve the concurrent performance of the Compiled XQuery Pool
  exist-core/pom.xml
  exist-core/src/main/java/org/exist/storage/XQueryPool.java
Labels: enhancement

#2966 Fix collation comparison on empty strings
  exist-core/src/main/java/org/exist/util/Collations.java
  exist-core/src/test/xquery/collations.xq
Labels: bug

#2967 (5.0.0) Fix collation comparison on empty strings
  exist-core/src/main/java/org/exist/util/Collations.java
  exist-core/src/test/xquery/collations.xq
Labels: bug

#2975 (5.0.0) Add missing Semver.xq to autodeploy
  exist-core/src/main/java/org/exist/repo/Deployment.java
  exist-distribution/pom.xml
  exist-distribution/src/main/config/log4j2.xml
Labels: bug

#2974 Add missing Semver.xq to autodeploy
  exist-core/src/main/java/org/exist/repo/Deployment.java
  exist-distribution/pom.xml
  exist-distribution/src/main/config/log4j2.xml
Labels: bug

#2977 Make sure collection.xconf.init is deployed
  exist-core/src/main/java/org/exist/storage/NativeBroker.java
  exist-core/src/test/java/org/exist/collections/InitCollectionConfigurationTest.java
  exist-core/src/test/java/org/exist/storage/journal/AbstractJournalTest.java
  exist-core/src/test/resources/collection.xconf.init
Labels: bug

#2978 (5.0.0) Make sure collection.xconf.init is deployed
  exist-core/src/main/java/org/exist/storage/NativeBroker.java
  exist-core/src/test/java/org/exist/collections/InitCollectionConfigurationTest.java
  exist-core/src/test/java/org/exist/storage/journal/AbstractJournalTest.java
  exist-core/src/test/resources/collection.xconf.init
Labels: bug

#2981 Improve warning messages when deploying packages
  exist-core/src/main/java/org/exist/repo/Deployment.java
Labels: enhancement

#2982 (5.0.0) Improve warning messages when deploying packages
  exist-core/src/main/java/org/exist/repo/Deployment.java
Labels: enhancement

#2983 Fix deadlock which can occur with System Tasks
  exist-core/src/main/java/org/exist/backup/ConsistencyCheck.java
  exist-core/src/main/java/org/exist/backup/ExportGUI.java
  exist-core/src/main/java/org/exist/backup/ExportMain.java
  exist-core/src/main/java/org/exist/backup/SystemExport.java
  exist-core/src/main/java/org/exist/scheduler/impl/ShutdownTask.java
  exist-core/src/main/java/org/exist/storage/BackupSystemTask.java
  exist-core/src/main/java/org/exist/storage/BrokerPool.java
  exist-core/src/main/java/org/exist/storage/ConsistencyCheckTask.java
  exist-core/src/main/java/org/exist/storage/DBBroker.java
  exist-core/src/main/java/org/exist/storage/DataBackup.java
  exist-core/src/main/java/org/exist/storage/NativeBroker.java
  exist-core/src/main/java/org/exist/storage/SystemTask.java
  exist-core/src/main/java/org/exist/storage/SystemTaskManager.java
  exist-core/src/main/java/org/exist/storage/statistics/IndexStatisticsWorker.java
  exist-core/src/main/java/org/exist/storage/sync/SyncTask.java
  exist-core/src/main/java/org/exist/storage/txn/TransactionManager.java
  exist-core/src/main/java/org/exist/xquery/functions/system/FnExport.java
  exist-core/src/main/java/org/exist/xquery/functions/system/UpdateStatistics.java
  exist-core/src/test/java/org/exist/backup/SystemExportFiltersTest.java
  exist-core/src/test/java/org/exist/backup/SystemExportImportTest.java
  exist-core/src/test/java/org/exist/storage/DataBackupTest.java
  exist-core/src/test/java/org/exist/storage/blob/BlobStoreRecoveryTest.java
Labels: bug

#2984 (5.0.0) Fix a deadlock which can occur with System Tasks
  exist-core/src/main/java/org/exist/backup/ConsistencyCheck.java
  exist-core/src/main/java/org/exist/backup/ExportGUI.java
  exist-core/src/main/java/org/exist/backup/ExportMain.java
  exist-core/src/main/java/org/exist/backup/SystemExport.java
  exist-core/src/main/java/org/exist/scheduler/impl/ShutdownTask.java
  exist-core/src/main/java/org/exist/storage/BackupSystemTask.java
  exist-core/src/main/java/org/exist/storage/BrokerPool.java
  exist-core/src/main/java/org/exist/storage/ConsistencyCheckTask.java
  exist-core/src/main/java/org/exist/storage/DBBroker.java
  exist-core/src/main/java/org/exist/storage/DataBackup.java
  exist-core/src/main/java/org/exist/storage/NativeBroker.java
  exist-core/src/main/java/org/exist/storage/SystemTask.java
  exist-core/src/main/java/org/exist/storage/SystemTaskManager.java
  exist-core/src/main/java/org/exist/storage/statistics/IndexStatisticsWorker.java
  exist-core/src/main/java/org/exist/storage/sync/SyncTask.java
  exist-core/src/main/java/org/exist/storage/txn/TransactionManager.java
  exist-core/src/main/java/org/exist/xquery/functions/system/FnExport.java
  exist-core/src/main/java/org/exist/xquery/functions/system/UpdateStatistics.java
  exist-core/src/test/java/org/exist/backup/SystemExportFiltersTest.java
  exist-core/src/test/java/org/exist/backup/SystemExportImportTest.java
  exist-core/src/test/java/org/exist/storage/DataBackupTest.java
  exist-core/src/test/java/org/exist/storage/blob/BlobStoreRecoveryTest.java
Labels: bug

#2988 Small fixes to the IzPack installer
  exist-installer/src/main/izpack/install.xml
Labels: bug

#2989 (5.0.0) Small fixes to the IzPack installer
  exist-installer/src/main/izpack/install.xml
Labels: bug

#2990 (5.0.0) Update dependencies inline with 'develop' branch
  exist-core/pom.xml
  exist-distribution/pom.xml
  exist-docker/pom.xml
  exist-parent/pom.xml
  exist-service/pom.xml
  extensions/indexes/spatial/pom.xml
  extensions/modules/cqlparser/pom.xml
Labels: enhancement

#2944 Restore should not overwrite newer apps by default
  exist-ant/src/main/java/org/exist/ant/RestoreTask.java
  exist-core/src/main/java/org/exist/backup/Main.java
  exist-core/src/main/java/org/exist/backup/Restore.java
  exist-core/src/main/java/org/exist/backup/restore/AppRestoreUtils.java
  exist-core/src/main/java/org/exist/backup/restore/RestoreHandler.java
  exist-core/src/main/java/org/exist/client/ClientFrame.java
  exist-core/src/main/java/org/exist/xmldb/EXistRestoreService.java
  exist-core/src/main/java/org/exist/xmldb/LocalRestoreService.java
  exist-core/src/main/java/org/exist/xmldb/RemoteRestoreService.java
  exist-core/src/main/java/org/exist/xmlrpc/RpcAPI.java
  exist-core/src/main/java/org/exist/xmlrpc/RpcConnection.java
  exist-core/src/main/java/org/exist/xquery/functions/system/Restore.java
  exist-core/src/main/java/org/exist/xquery/functions/system/SystemModule.java
  exist-core/src/main/resources/org/exist/client/messages.properties
  exist-core/src/test/java/org/exist/backup/RestoreAppsTest.java
  exist-core/src/test/java/org/exist/backup/XMLDBBackupTest.java
  exist-core/src/test/java/org/exist/backup/XMLDBRestoreTest.java
  exist-core/src/test/java/org/exist/security/internal/BackupRestoreSecurityPrincipalsTest.java
  extensions/modules/expathrepo/src/main/resources/org/exist/xquery/modules/expathrepo/repair.xql
Labels: enhancement

#2985 (5.0.0) Restore should not overwrite newer apps by default
  exist-ant/src/main/java/org/exist/ant/RestoreTask.java
  exist-core/src/main/java/org/exist/backup/Main.java
  exist-core/src/main/java/org/exist/backup/Restore.java
  exist-core/src/main/java/org/exist/backup/restore/AppRestoreUtils.java
  exist-core/src/main/java/org/exist/backup/restore/RestoreHandler.java
  exist-core/src/main/java/org/exist/client/ClientFrame.java
  exist-core/src/main/java/org/exist/xmldb/EXistRestoreService.java
  exist-core/src/main/java/org/exist/xmldb/LocalRestoreService.java
  exist-core/src/main/java/org/exist/xmldb/RemoteRestoreService.java
  exist-core/src/main/java/org/exist/xmlrpc/RpcAPI.java
  exist-core/src/main/java/org/exist/xmlrpc/RpcConnection.java
  exist-core/src/main/java/org/exist/xquery/functions/system/Restore.java
  exist-core/src/main/java/org/exist/xquery/functions/system/SystemModule.java
  exist-core/src/main/resources/org/exist/client/messages.properties
  exist-core/src/test/java/org/exist/backup/RestoreAppsTest.java
  exist-core/src/test/java/org/exist/backup/XMLDBBackupTest.java
  exist-core/src/test/java/org/exist/backup/XMLDBRestoreTest.java
  exist-core/src/test/java/org/exist/security/internal/BackupRestoreSecurityPrincipalsTest.java
  extensions/modules/expathrepo/src/main/resources/org/exist/xquery/modules/expathrepo/repair.xql
Labels: enhancement

#2996 (5.0.0) Fix eXist-db Service on Windows
  exist-core/src/main/java/org/exist/launcher/WindowsServiceManager.java
  exist-distribution/src/main/config/log4j2.xml
Labels: bug

#2995 Fix eXist-db Service on Windows
  exist-core/src/main/java/org/exist/launcher/WindowsServiceManager.java
  exist-distribution/src/main/config/log4j2.xml
Labels: bug
