Repository eXist-db/exist, pull requests merged in 2019-01, with the labels that each got.

#2357 4xx: Implement adaptive serialisation for fn:trace and util:log* functions
  src/org/exist/xquery/functions/fn/FunTrace.java
  src/org/exist/xquery/functions/fn/JSON.java
  src/org/exist/xquery/functions/util/LogFunction.java
Labels: enhancement

#2359 develop: Implement adaptive serialisation for fn:trace and util:log* functions
  src/org/exist/xquery/functions/fn/FunTrace.java
  src/org/exist/xquery/functions/fn/JSON.java
  src/org/exist/xquery/functions/util/LogFunction.java
Labels: enhancement

#2358 5xx: Implement adaptive serialisation for fn:trace and util:log* functions
  src/org/exist/xquery/functions/fn/FunTrace.java
  src/org/exist/xquery/functions/fn/JSON.java
  src/org/exist/xquery/functions/util/LogFunction.java
Labels: enhancement

#2351 Remove legacy backup conversion code
  src/org/exist/config/ConfigurationDocumentTrigger.java
  src/org/exist/security/utils/ConverterFrom1_0.java
Labels: cleanup

#2352 (5.x.x) Remove legacy backup conversion code
  src/org/exist/config/ConfigurationDocumentTrigger.java
  src/org/exist/security/utils/ConverterFrom1_0.java
Labels: cleanup

#2361 (5.0.0) Improve classpath modules resolution
  src/org/exist/source/SourceFactory.java
  test/src/org/exist/source/SourceFactoryTest.java
Labels: bug

#2360 Improve classpath modules resolution
  src/org/exist/source/SourceFactory.java
  test/src/org/exist/source/SourceFactoryTest.java
Labels: bug

#2362 (4.x.x) Improve classpath modules resolution
  src/org/exist/source/SourceFactory.java
  test/src/org/exist/source/SourceFactoryTest.java
Labels: bug

#2305 (4.x.x) New implementation of the Transaction Manager
  src/org/exist/storage/BrokerPool.java
  src/org/exist/storage/SystemTaskManager.java
  src/org/exist/storage/journal/Journal.java
  src/org/exist/storage/txn/TransactionManager.java
  src/org/exist/storage/txn/Txn.java
  test/src/org/exist/storage/txn/TxnTest.java
Labels: bug, enhancement, high prio

#2306 New implementation of the Transaction Manager
  src/org/exist/storage/BrokerPool.java
  src/org/exist/storage/SystemTaskManager.java
  src/org/exist/storage/journal/Journal.java
  src/org/exist/storage/txn/TransactionManager.java
  src/org/exist/storage/txn/Txn.java
  test/src/org/exist/storage/txn/TransactionManagerTestHelper.java
Labels: bug, enhancement, high prio

#2307 (5.0.0) New implementation of the Transaction Manager
  src/org/exist/storage/BrokerPool.java
  src/org/exist/storage/SystemTaskManager.java
  src/org/exist/storage/journal/Journal.java
  src/org/exist/storage/txn/TransactionManager.java
  src/org/exist/storage/txn/Txn.java
  test/src/org/exist/storage/txn/TransactionManagerTestHelper.java
Labels: bug, enhancement, high prio

#2380 Add coverage for new range index features to collection.xconf.xsd
  schema/collection.xconf.xsd
Labels: enhancement, needs 4.x.x backport, needs 5.0.0 backport

#2396 (5.0.0) Add coverage for new range index features to collection.xconf.xsd
  schema/collection.xconf.xsd
Labels: enhancement

#2395 (4.x.x) Add coverage for new range index features to collection.xconf.xsd
  schema/collection.xconf.xsd
Labels: enhancement

#2403 (5.0.0) Fix CDATA handling and implement output:cdata-section-elements
  src/org/exist/collections/CollectionConfigurationManager.java
  src/org/exist/config/Configurator.java
  src/org/exist/dom/QName.java
  src/org/exist/dom/memtree/InMemoryXMLStreamReader.java
  src/org/exist/dom/memtree/SAXAdapter.java
  src/org/exist/http/Descriptor.java
  src/org/exist/http/RESTServer.java
  src/org/exist/storage/serializers/EXistOutputKeys.java
  src/org/exist/storage/serializers/XIncludeFilter.java
  src/org/exist/util/Configuration.java
  src/org/exist/util/serializer/XMLWriter.java
  src/org/exist/util/serializer/XQuerySerializer.java
  src/org/exist/xmldb/LocalXPathQueryService.java
  src/org/exist/xmldb/RemoteXPathQueryService.java
  src/org/exist/xquery/CDATAConstructor.java
  src/org/exist/xquery/XQueryContext.java
  src/org/exist/xquery/modules/ModuleUtils.java
  src/org/exist/xquery/util/DocUtils.java
  src/org/exist/xquery/util/SerializerUtils.java
  test/src/org/exist/dom/persistent/CDataIntergationTest.java
  test/src/org/exist/dom/persistent/PersistentDomTest.java
  test/src/org/exist/xquery/XPathQueryTest.java
  test/src/org/exist/xquery/XQueryTest.java
Labels: bug, enhancement

#2402 Fix CDATA handling and implement output:cdata-section-elements
  src/org/exist/collections/CollectionConfigurationManager.java
  src/org/exist/config/Configurator.java
  src/org/exist/dom/QName.java
  src/org/exist/dom/memtree/InMemoryXMLStreamReader.java
  src/org/exist/dom/memtree/SAXAdapter.java
  src/org/exist/http/Descriptor.java
  src/org/exist/http/RESTServer.java
  src/org/exist/storage/serializers/EXistOutputKeys.java
  src/org/exist/storage/serializers/XIncludeFilter.java
  src/org/exist/util/Configuration.java
  src/org/exist/util/serializer/XMLWriter.java
  src/org/exist/util/serializer/XQuerySerializer.java
  src/org/exist/xmldb/LocalXPathQueryService.java
  src/org/exist/xmldb/RemoteXPathQueryService.java
  src/org/exist/xquery/CDATAConstructor.java
  src/org/exist/xquery/XQueryContext.java
  src/org/exist/xquery/modules/ModuleUtils.java
  src/org/exist/xquery/util/DocUtils.java
  src/org/exist/xquery/util/SerializerUtils.java
  test/src/org/exist/dom/persistent/CDataIntergationTest.java
  test/src/org/exist/dom/persistent/PersistentDomTest.java
  test/src/org/exist/xquery/XPathQueryTest.java
  test/src/org/exist/xquery/XQueryTest.java
Labels: bug, enhancement

#2398 (4.x.x) Add util:eval-and-serialize function
  src/org/exist/xquery/functions/fn/FunSerialize.java
  src/org/exist/xquery/functions/fn/FunSubSequence.java
  src/org/exist/xquery/functions/util/Eval.java
  src/org/exist/xquery/functions/util/UtilModule.java
  test/src/org/exist/xquery/functions/util/EvalTest.java
Labels: enhancement

#2401 (5.0.0) Add util:eval-and-serialize function
  src/org/exist/xquery/functions/fn/FunSerialize.java
  src/org/exist/xquery/functions/fn/FunSubSequence.java
  src/org/exist/xquery/functions/util/Eval.java
  src/org/exist/xquery/functions/util/UtilModule.java
  test/src/org/exist/xquery/functions/util/EvalTest.java
Labels: enhancement

#2400 Add util:eval-and-serialize function
  src/org/exist/xquery/functions/fn/FunSerialize.java
  src/org/exist/xquery/functions/fn/FunSubSequence.java
  src/org/exist/xquery/functions/util/Eval.java
  src/org/exist/xquery/functions/util/UtilModule.java
  test/src/org/exist/xquery/functions/util/EvalTest.java
Labels: enhancement

#2405 Copying an XML Resource must remove the nodes of any XML resource it overwrites!
  src/org/exist/storage/NativeBroker.java
Labels: bug

#2406 (5.0.0) Copying an XML Resource must remove the nodes of any XML resource it overwrites!
  src/org/exist/storage/NativeBroker.java
Labels: bug

#2374 (4.x.x) Fix CDATA handling and implement output:cdata-section-elements
  src/org/exist/collections/CollectionConfigurationManager.java
  src/org/exist/config/Configurator.java
  src/org/exist/dom/QName.java
  src/org/exist/dom/memtree/InMemoryXMLStreamReader.java
  src/org/exist/dom/memtree/SAXAdapter.java
  src/org/exist/http/Descriptor.java
  src/org/exist/http/RESTServer.java
  src/org/exist/storage/serializers/EXistOutputKeys.java
  src/org/exist/storage/serializers/XIncludeFilter.java
  src/org/exist/util/Configuration.java
  src/org/exist/util/serializer/XMLWriter.java
  src/org/exist/util/serializer/XQuerySerializer.java
  src/org/exist/xmldb/LocalXPathQueryService.java
  src/org/exist/xmldb/RemoteXPathQueryService.java
  src/org/exist/xquery/CDATAConstructor.java
  src/org/exist/xquery/XQueryContext.java
  src/org/exist/xquery/modules/ModuleUtils.java
  src/org/exist/xquery/util/DocUtils.java
  src/org/exist/xquery/util/SerializerUtils.java
  test/src/org/exist/dom/persistent/CDataIntergationTest.java
  test/src/org/exist/dom/persistent/PersistentDomTest.java
  test/src/org/exist/xquery/XPathQueryTest.java
  test/src/org/exist/xquery/XQueryTest.java
Labels: bug, enhancement

#2296 (4.x.x) Fix failing xml:id tests by using proper checks for xs:NCName
  src/org/exist/Indexer.java
  src/org/exist/dom/QName.java
  src/org/exist/dom/memtree/MemTreeBuilder.java
  src/org/exist/util/XMLNames.java
  src/org/exist/xquery/DynamicAttributeConstructor.java
  src/org/exist/xquery/DynamicPIConstructor.java
  src/org/exist/xquery/ElementConstructor.java
  src/org/exist/xquery/NamespaceConstructor.java
  src/org/exist/xquery/functions/fn/FunId.java
  src/org/exist/xquery/functions/fn/FunIdRef.java
  src/org/exist/xquery/functions/fn/FunQName.java
  src/org/exist/xquery/value/StringValue.java
  test/src/xquery/xmlid.xql
Labels: bug

#2386 (4.x.x) Fix lucene term range queries
  extensions/indexes/lucene/src/org/exist/indexing/lucene/LuceneUtil.java
  extensions/indexes/lucene/test/src/xquery/lucene/plain-ft-functions.xml
  extensions/indexes/lucene/test/src/xquery/lucene/queries.xml
Labels: bug

#2391 Fix lucene term range queries
  extensions/indexes/lucene/src/org/exist/indexing/lucene/LuceneUtil.java
  extensions/indexes/lucene/test/src/xquery/lucene/plain-ft-functions.xml
  extensions/indexes/lucene/test/src/xquery/lucene/queries.xml
Labels: bug

#2392 (5.0.0) Fix lucene term range queries
  extensions/indexes/lucene/src/org/exist/indexing/lucene/LuceneUtil.java
  extensions/indexes/lucene/test/src/xquery/lucene/plain-ft-functions.xml
  extensions/indexes/lucene/test/src/xquery/lucene/queries.xml
Labels: bug

#2201 (5.0.0) If downloading XARs fails, the build should fail
  build/scripts/installer.xml
  build/scripts/setup.xml
Labels: bug

#2202 (4.x.x) If downloading XARs fails, the build should fail
  build/scripts/installer.xml
  build/scripts/setup.xml
Labels: bug

#2412 (4.x.x) Unattended Installation
  tools/yajsw/bin/installDaemon.sh
Labels: enhancement

#2413 (5.0.0) Unattended Installation
  tools/yajsw/bin/installDaemon.sh
Labels: enhancement

#2409 Fix Jar files for JNLP Web Start of Java Admin Client
  src/org/exist/webstart/JnlpJarFiles.java
Labels: bug

#2410 (5.0.0) Fix Jar files for JNLP Web Start of Java Admin Client
  src/org/exist/webstart/JnlpJarFiles.java
Labels: bug

#2411 (4.x.x) Fix Jar files for JNLP Web Start of Java Admin Client
  src/org/exist/webstart/JnlpJarFiles.java
Labels: bug

#2425 Pr 2399
  .classpath
  extensions/commands/src/org/exist/commands/info/Lock.java
  extensions/commands/src/org/exist/commands/info/Transactions.java
  extensions/commands/src/org/exist/commands/threads/Deadlock.java
  extensions/debuggee/src/org/exist/debuggee/ScriptRunner.java
  extensions/debuggee/src/org/exist/debugger/DebuggerImpl.java
  extensions/debuggee/src/org/exist/debugger/Utils.java
  extensions/debuggee/src/org/exist/debugger/client/DebugClient.java
  lib/core/xmldb-api-1.1-patched.jar
  lib/core/xmldb-api-1.7.0.jar
  nbproject/project.properties
  test/src/org/exist/dom/memtree/NodeImplTest.java
Labels: enhancement

#2426 (4.x.x) Rebased - Uses new XML:DB api binary as available on maven central
  .classpath
  extensions/commands/src/org/exist/commands/info/Lock.java
  extensions/commands/src/org/exist/commands/info/Transactions.java
  extensions/commands/src/org/exist/commands/threads/Deadlock.java
  extensions/debuggee/src/org/exist/debuggee/ScriptRunner.java
  extensions/debuggee/src/org/exist/debugger/DebuggerImpl.java
  extensions/debuggee/src/org/exist/debugger/Utils.java
  extensions/debuggee/src/org/exist/debugger/client/DebugClient.java
  lib/core/xmldb-api-1.1-patched.jar
  lib/core/xmldb-api-1.7.0.jar
  nbproject/project.properties
  test/src/org/exist/dom/memtree/NodeImplTest.java
Labels: enhancement

#2427 (5.0.0) Rebased - Uses new XML:DB api binary as available on maven central
  .classpath
  extensions/commands/src/org/exist/commands/info/Lock.java
  extensions/commands/src/org/exist/commands/info/Transactions.java
  extensions/commands/src/org/exist/commands/threads/Deadlock.java
  extensions/debuggee/src/org/exist/debuggee/ScriptRunner.java
  extensions/debuggee/src/org/exist/debugger/DebuggerImpl.java
  extensions/debuggee/src/org/exist/debugger/Utils.java
  extensions/debuggee/src/org/exist/debugger/client/DebugClient.java
  lib/core/xmldb-api-1.1-patched.jar
  lib/core/xmldb-api-1.7.0.jar
  nbproject/project.properties
  test/src/org/exist/dom/memtree/NodeImplTest.java
Labels: enhancement

#2422 (5.0.0) Tiny bug fix in fn:eval-and-serialize
  src/org/exist/xquery/functions/util/Eval.java
Labels: bug

#2414 Fix failing xml:id tests by using proper checks for xs:NCName
  src/org/exist/Indexer.java
  src/org/exist/dom/QName.java
  src/org/exist/dom/memtree/MemTreeBuilder.java
  src/org/exist/util/XMLNames.java
  src/org/exist/xquery/DynamicAttributeConstructor.java
  src/org/exist/xquery/DynamicPIConstructor.java
  src/org/exist/xquery/ElementConstructor.java
  src/org/exist/xquery/NamespaceConstructor.java
  src/org/exist/xquery/functions/fn/FunId.java
  src/org/exist/xquery/functions/fn/FunIdRef.java
  src/org/exist/xquery/functions/fn/FunQName.java
  src/org/exist/xquery/value/StringValue.java
  test/src/xquery/xmlid.xql
Labels: bug

#2421 Tiny bug fix in fn:eval-and-serialize
  src/org/exist/xquery/functions/util/Eval.java
Labels: bug

#2420 (4.x.x) Tiny bug fix in fn:eval-and-serialize
  src/org/exist/xquery/functions/util/Eval.java
Labels: bug

#2430 Fixes OOM by adding memory options and GC tweaks
  build/scripts/junit.xml
Labels: bug

#2436 (5.0.0) Fixes OOM by adding memory options and GC tweaks
  build/scripts/junit.xml
Labels: bug

#2435 (4.x.x) Fixes OOM by adding memory options and GC tweaks
  build/scripts/junit.xml
Labels: bug

#2432 (4xx) Improve restore progress window
  src/org/exist/backup/RestoreDialog.java
Labels: enhancement

#2433 (5xx) Improve restore progress window
  src/org/exist/backup/RestoreDialog.java
Labels: enhancement
