Repository eXist-db/exist, pull requests merged in 2019-03, with the labels that each got.

#2531 (4.x.x) XMLWriter is leaking instances of QName
  exist-core/src/main/java/org/exist/util/serializer/XMLWriter.java
Labels: bug

#2536 XMLWriter is leaking instances of QName
  exist-core/src/main/java/org/exist/util/serializer/XMLWriter.java
Labels: bug

#2537 (develop-5.0.0) XMLWriter is leaking instances of QName
  exist-core/src/main/java/org/exist/util/serializer/XMLWriter.java
Labels: bug

#2538 Start fine with recovery disabled (Fixes issue #2533)
  build/scripts/junit.xml
  exist-core/src/main/java/org/exist/storage/BrokerPool.java
  exist-core/src/test/java/org/exist/storage/BrokerPoolNoRecoveryTest.java
Labels: bug

#2535 (4.x.x) Start fine with recovery disabled (Fixes issue #2533 on develop-4.x.x)
  build/scripts/junit.xml
  exist-core/src/main/java/org/exist/storage/BrokerPool.java
  exist-core/src/test/java/org/exist/storage/BrokerPoolNoRecoveryTest.java
Labels: bug

#2539 (5.0.0) Start fine with recovery disabled (Fixes issue #2533 on develop-5.0.0)
  build/scripts/junit.xml
  exist-core/src/main/java/org/exist/storage/BrokerPool.java
  exist-core/src/test/java/org/exist/storage/BrokerPoolNoRecoveryTest.java
Labels: bug

#2540 Small code cleanup
  exist-core/src/main/java/org/exist/SystemProperties.java
  exist-core/src/main/java/org/exist/Version.java
  exist-core/src/main/java/org/exist/repo/Deployment.java
Labels: enhancement

#2541 (5.0.0) Small code cleanup
  exist-core/src/main/java/org/exist/SystemProperties.java
  exist-core/src/main/java/org/exist/Version.java
  exist-core/src/main/java/org/exist/repo/Deployment.java
Labels: enhancement

#2542 (4.x.x) Small code cleanup
  exist-core/src/main/java/org/exist/SystemProperties.java
  exist-core/src/main/java/org/exist/Version.java
  exist-core/src/main/java/org/exist/repo/Deployment.java
Labels: enhancement

#2543 Fix some issues with equality in the EnsureLockingAspect
  exist-core/src/main/java/org/exist/storage/lock/EnsureLockingAspect.java
Labels: bug

#2544 (5.0.0) Fix some issues with equality in the EnsureLockingAspect
  exist-core/src/main/java/org/exist/storage/lock/EnsureLockingAspect.java
Labels: bug

#2551 Fix the YAJSW installation
  tools/yajsw/bin/installDaemon.sh
Labels: bug

#2553 (5.0.0) Fix the YAJSW installation
  tools/yajsw/bin/installDaemon.sh
Labels: bug

#2552 (4.x.x) Fix the YAJSW installation
  tools/yajsw/bin/installDaemon.sh
Labels: bug

#2548 Fix source code location in built installer
  installer/install.xml.tmpl
Labels: bug

#2549 (4.x.x) Fix source code location in built installer
  installer/install.xml.tmpl
Labels: bug

#2550 (5.0.0) Fix source code location in built installer
  installer/install.xml.tmpl
Labels: bug

#2545 Fix transaction issue in EXPath Deployment
  extensions/modules/expathrepo/src/main/java/org/exist/xquery/modules/expathrepo/Deploy.java
Labels: bug

#2546 (5.0.0) Fix transaction issue in EXPath Deployment
  extensions/modules/expathrepo/src/main/java/org/exist/xquery/modules/expathrepo/Deploy.java
Labels: bug

#2554 Fix the contentextraction:get-metadata function
  extensions/contentextraction/src/main/java/org/exist/contentextraction/AbortAfterMetadataContentHandler.java
  extensions/contentextraction/src/main/java/org/exist/contentextraction/AbortedAfterMetadataException.java
  extensions/contentextraction/src/main/java/org/exist/contentextraction/ContentExtraction.java
  extensions/contentextraction/src/main/java/org/exist/contentextraction/xquery/ContentFunctions.java
Labels: bug

#2555 (4.x.x) Fix the contentextraction:get-metadata function
  extensions/contentextraction/src/main/java/org/exist/contentextraction/AbortAfterMetadataContentHandler.java
  extensions/contentextraction/src/main/java/org/exist/contentextraction/AbortedAfterMetadataException.java
  extensions/contentextraction/src/main/java/org/exist/contentextraction/ContentExtraction.java
  extensions/contentextraction/src/main/java/org/exist/contentextraction/xquery/ContentFunctions.java
Labels: bug

#2557 (5.0.0) Fix the contentextraction:get-metadata function
  extensions/contentextraction/src/main/java/org/exist/contentextraction/AbortAfterMetadataContentHandler.java
  extensions/contentextraction/src/main/java/org/exist/contentextraction/AbortedAfterMetadataException.java
  extensions/contentextraction/src/main/java/org/exist/contentextraction/ContentExtraction.java
  extensions/contentextraction/src/main/java/org/exist/contentextraction/xquery/ContentFunctions.java
Labels: bug

#2561 Fix an issue with util:serialize params
  exist-core/src/main/java/org/exist/xquery/functions/util/Serialize.java
  exist-core/src/test/java/org/exist/xquery/functions/util/SerializeTest.java
Labels: bug

#2562 (4.x.x) Fix an issue with util:serialize params
  exist-core/src/main/java/org/exist/xquery/functions/util/Serialize.java
  exist-core/src/test/java/org/exist/xquery/functions/util/SerializeTest.java
Labels: bug

#2563 (5.0.0) Fix an issue with util:serialize params
  exist-core/src/main/java/org/exist/xquery/functions/util/Serialize.java
  exist-core/src/test/java/org/exist/xquery/functions/util/SerializeTest.java
Labels: bug

#2564 Avoid NPE when empty string is given as Primary Group
  exist-core/src/main/java/org/exist/xquery/functions/securitymanager/AccountManagementFunction.java
Labels: bug

#2565 (4.x.x) Avoid NPE when empty string is given as Primary Group
  exist-core/src/main/java/org/exist/xquery/functions/securitymanager/AccountManagementFunction.java
Labels: bug

#2566 (5.0.0) Avoid NPE when empty string is given as Primary Group
  exist-core/src/main/java/org/exist/xquery/functions/securitymanager/AccountManagementFunction.java
Labels: bug

#2567 Fix some CharArrayPool and ByteArrayPool leaks
  exist-core/src/main/java/org/exist/Indexer.java
  exist-core/src/main/java/org/exist/dom/persistent/AbstractCharacterData.java
  exist-core/src/main/java/org/exist/dom/persistent/AttrImpl.java
  exist-core/src/main/java/org/exist/dom/persistent/CDATASectionImpl.java
  exist-core/src/main/java/org/exist/dom/persistent/ElementImpl.java
  exist-core/src/main/java/org/exist/dom/persistent/TextImpl.java
  exist-core/src/main/java/org/exist/storage/NativeBroker.java
  exist-core/src/main/java/org/exist/storage/NativeValueIndex.java
  exist-core/src/main/java/org/exist/util/CharArrayPool.java
  exist-core/src/main/java/org/exist/util/CharSlice.java
  exist-core/src/main/java/org/exist/util/UTF8.java
  exist-core/src/main/java/org/exist/util/XMLString.java
  exist-core/src/main/java/org/exist/util/serializer/TEXTWriter.java
  exist-core/src/main/java/org/exist/util/serializer/XMLWriter.java
  exist-core/src/test/java/org/exist/storage/btree/BTreeTest.java
  exist-core/src/test/java/org/exist/util/XMLStringTest.java
  extensions/indexes/ngram/src/main/java/org/exist/indexing/ngram/NGramIndexWorker.java
  extensions/indexes/range/src/main/java/org/exist/indexing/range/ComplexTextCollector.java
  extensions/indexes/range/src/main/java/org/exist/indexing/range/TextCollector.java
Labels: bug

#2569 (4.x.x) Fix some CharArrayPool and ByteArrayPool leaks
  exist-core/src/main/java/org/exist/Indexer.java
  exist-core/src/main/java/org/exist/dom/persistent/AbstractCharacterData.java
  exist-core/src/main/java/org/exist/dom/persistent/AttrImpl.java
  exist-core/src/main/java/org/exist/dom/persistent/CDATASectionImpl.java
  exist-core/src/main/java/org/exist/dom/persistent/ElementImpl.java
  exist-core/src/main/java/org/exist/dom/persistent/TextImpl.java
  exist-core/src/main/java/org/exist/storage/NativeBroker.java
  exist-core/src/main/java/org/exist/storage/NativeValueIndex.java
  exist-core/src/main/java/org/exist/util/CharArrayPool.java
  exist-core/src/main/java/org/exist/util/CharSlice.java
  exist-core/src/main/java/org/exist/util/UTF8.java
  exist-core/src/main/java/org/exist/util/XMLString.java
  exist-core/src/main/java/org/exist/util/serializer/TEXTWriter.java
  exist-core/src/main/java/org/exist/util/serializer/XMLWriter.java
  exist-core/src/test/java/org/exist/storage/btree/BTreeTest.java
  exist-core/src/test/java/org/exist/util/XMLStringTest.java
  extensions/indexes/ngram/src/main/java/org/exist/indexing/ngram/NGramIndexWorker.java
  extensions/indexes/range/src/main/java/org/exist/indexing/range/ComplexTextCollector.java
  extensions/indexes/range/src/main/java/org/exist/indexing/range/TextCollector.java
Labels: bug

#2568 (5.0.0) Fix some CharArrayPool and ByteArrayPool leaks
  exist-core/src/main/java/org/exist/Indexer.java
  exist-core/src/main/java/org/exist/dom/persistent/AbstractCharacterData.java
  exist-core/src/main/java/org/exist/dom/persistent/AttrImpl.java
  exist-core/src/main/java/org/exist/dom/persistent/CDATASectionImpl.java
  exist-core/src/main/java/org/exist/dom/persistent/ElementImpl.java
  exist-core/src/main/java/org/exist/dom/persistent/TextImpl.java
  exist-core/src/main/java/org/exist/storage/NativeBroker.java
  exist-core/src/main/java/org/exist/storage/NativeValueIndex.java
  exist-core/src/main/java/org/exist/util/CharArrayPool.java
  exist-core/src/main/java/org/exist/util/CharSlice.java
  exist-core/src/main/java/org/exist/util/UTF8.java
  exist-core/src/main/java/org/exist/util/XMLString.java
  exist-core/src/main/java/org/exist/util/serializer/TEXTWriter.java
  exist-core/src/main/java/org/exist/util/serializer/XMLWriter.java
  exist-core/src/test/java/org/exist/storage/btree/BTreeTest.java
  exist-core/src/test/java/org/exist/util/XMLStringTest.java
  extensions/indexes/ngram/src/main/java/org/exist/indexing/ngram/NGramIndexWorker.java
  extensions/indexes/range/src/main/java/org/exist/indexing/range/ComplexTextCollector.java
  extensions/indexes/range/src/main/java/org/exist/indexing/range/TextCollector.java
Labels: bug

#2558 Update to Tika version 1.20
  extensions/contentextraction/ivy.xml
  extensions/modules/xslfo/ivy.xml
Labels: enhancement

#2559 (5.0.0) Update to Tika version 1.20
  extensions/contentextraction/ivy.xml
  extensions/modules/xslfo/ivy.xml
Labels: enhancement

#2560 (4.x.x) Update to Tika version 1.20
  extensions/contentextraction/ivy.xml
  extensions/modules/xslfo/ivy.xml
Labels: enhancement

#2573 JMH Benchmark
  .idea/libraries/jmh.xml
  build.properties
  build/scripts/build-impl.xml
  build/scripts/jmh.xml
  eXist-db.iml
  exist-core-jmh/ivy.xml
  exist-core-jmh/src/main/java/org/exist/storage/lock/LockTableBenchmark.java
Labels: enhancement

#2140 XQSuite+XSuite was not correctly reporting all test failures
  exist-core/src/main/java/org/exist/dom/persistent/NewArrayNodeSet.java
  exist-core/src/main/java/org/exist/repo/AutoDeploymentTrigger.java
  exist-core/src/main/java/org/exist/xquery/ElementConstructor.java
  exist-core/src/main/java/org/exist/xquery/NamespaceConstructor.java
  exist-core/src/main/java/org/exist/xquery/XQueryContext.java
  exist-core/src/main/resources/org/exist/xquery/lib/xqsuite/xqsuite.xql
  exist-core/src/test/xquery/namespaces.xql
  exist-core/src/test/xquery/positional-nested.xql
  exist-core/src/test/xquery/xquery3/load-xquery-module.xql
Labels: bug, high prio

#2142 (4.x.x) XQSuite+XSuite was not correctly reporting all test failures
  exist-core/src/main/java/org/exist/dom/persistent/NewArrayNodeSet.java
  exist-core/src/main/java/org/exist/repo/AutoDeploymentTrigger.java
  exist-core/src/main/java/org/exist/xquery/ElementConstructor.java
  exist-core/src/main/java/org/exist/xquery/NamespaceConstructor.java
  exist-core/src/main/java/org/exist/xquery/XQueryContext.java
  exist-core/src/main/resources/org/exist/xquery/lib/xqsuite/xqsuite.xql
  exist-core/src/test/xquery/namespaces.xql
  exist-core/src/test/xquery/positional-nested.xql
  exist-core/src/test/xquery/xquery3/load-xquery-module.xql
Labels: bug, high prio

#2141 (5.0.0) XQSuite+XSuite was not correctly reporting all test failures
  exist-core/src/main/java/org/exist/dom/persistent/NewArrayNodeSet.java
  exist-core/src/main/java/org/exist/repo/AutoDeploymentTrigger.java
  exist-core/src/main/java/org/exist/xquery/ElementConstructor.java
  exist-core/src/main/java/org/exist/xquery/NamespaceConstructor.java
  exist-core/src/main/java/org/exist/xquery/XQueryContext.java
  exist-core/src/main/resources/org/exist/xquery/lib/xqsuite/xqsuite.xql
  exist-core/src/test/xquery/namespaces.xql
  exist-core/src/test/xquery/positional-nested.xql
  exist-core/src/test/xquery/xquery3/load-xquery-module.xql
Labels: bug, high prio

#2582 Fix an issue with the Namespace Constructor and empty prefix
  exist-core/src/main/java/org/exist/xquery/NamespaceConstructor.java
  exist-core/src/test/xquery/namespaces.xql
Labels: bug

#2583 (4.x.x) Fix an issue with the Namespace Constructor and empty prefix
  exist-core/src/main/java/org/exist/xquery/NamespaceConstructor.java
  exist-core/src/test/xquery/namespaces.xql
Labels: bug

#2584 (5.0.0) Fix an issue with the Namespace Constructor and empty prefix
  exist-core/src/main/java/org/exist/xquery/NamespaceConstructor.java
  exist-core/src/test/xquery/namespaces.xql
Labels: bug

#2570 Fix standard project layout for SortIndex tests
  eXist-db.iml
  extensions/indexes/sort/src/test/java/xquery/sort/SortTests.java
Labels: bug

#2571 (5.0.0) Fix standard project layout for SortIndex tests
  eXist-db.iml
  extensions/indexes/sort/src/test/java/xquery/sort/SortTests.java
Labels: bug

#2572 (4.x.x) Fix standard project layout for SortIndex tests
  eXist-db.iml
  extensions/indexes/sort/src/test/java/xquery/sort/SortTests.java
Labels: bug

#2586 [bugfix] Make sure to release BTREE locks in Benchmark
  exist-core-jmh/src/main/java/org/exist/storage/lock/LockTableBenchmark.java
Labels: bug

#2593 Appveyor failed test data
  appveyor.yml
Labels: enhancement

#2598 (4.x.x) Appveyor failed test data
  appveyor.yml
Labels: enhancement

#2599 (5.0.0) Appveyor failed test data
  appveyor.yml
Labels: enhancement

#2587 Adopt FastUtil primitive maps
  .classpath
  exist-core/src/main/java/org/exist/dom/NamedNodeMapImpl.java
  exist-core/src/main/java/org/exist/dom/memtree/InMemoryXMLStreamReader.java
  exist-core/src/main/java/org/exist/dom/persistent/ExtArrayNodeSet.java
  exist-core/src/main/java/org/exist/dom/persistent/SymbolTable.java
  exist-core/src/main/java/org/exist/security/internal/SecurityManagerImpl.java
  exist-core/src/main/java/org/exist/storage/cache/GClockCache.java
  exist-core/src/main/java/org/exist/storage/dom/DOMFile.java
  exist-core/src/main/java/org/exist/storage/journal/LogEntryTypes.java
  exist-core/src/main/java/org/exist/storage/recovery/RecoveryManager.java
  exist-core/src/main/java/org/exist/util/hashtable/Int2ObjectHashMap.java
  exist-core/src/main/java/org/exist/util/hashtable/Long2ObjectHashMap.java
  exist-core/src/main/java/org/exist/util/hashtable/Object2IntHashMap.java
  exist-core/src/main/java/org/exist/util/hashtable/Object2LongHashMap.java
  exist-core/src/main/java/org/exist/util/hashtable/Object2LongIdentityHashMap.java
  exist-core/src/main/java/org/exist/util/hashtable/Object2ObjectHashMap.java
  exist-core/src/main/java/org/exist/util/hashtable/ObjectHashSet.java
  exist-core/src/main/java/org/exist/util/pool/NodePool.java
  exist-core/src/main/java/org/exist/util/serializer/HTML5Writer.java
  exist-core/src/main/java/org/exist/util/serializer/XHTML5Writer.java
  exist-core/src/main/java/org/exist/util/serializer/XHTMLWriter.java
  exist-core/src/main/java/org/exist/webstart/JnlpJarFiles.java
  exist-core/src/main/java/org/exist/xquery/regex/CaseVariants.java
  exist-core/src/main/java/org/exist/xquery/update/Modification.java
  exist-core/src/main/java/org/exist/xquery/value/Type.java
  exist-core/src/main/java/org/exist/xupdate/Modification.java
  exist-core/src/test/java/org/exist/util/hashtable/AllTests.java
  exist-core/src/test/java/org/exist/util/hashtable/HashtableTest.java
  exist-core/src/test/java/org/exist/util/hashtable/Int2ObjectHashMapTest.java
  exist-core/src/test/java/org/exist/util/hashtable/Long2ObjectHashMapTest.java
  exist-core/src/test/java/org/exist/util/hashtable/Object2IntHashMapTest.java
  exist-core/src/test/java/org/exist/util/hashtable/Object2LongHashMapTest.java
  exist-core/src/test/java/org/exist/util/hashtable/Object2LongIdentityHashMapTest.java
  exist-core/src/test/java/org/exist/util/hashtable/Object2ObjectHashMapTest.java
  exist-core/src/test/java/org/exist/util/hashtable/ObjectHashSetTest.java
  exist-core/src/test/java/org/exist/util/hashtable/SequencedLongHashMapTest.java
  exist-start/src/main/resources/org/exist/start/start.config
  lib/core/fastutil-8.2.2-min.jar
  lib/core/fastutil-8.2.2-min.jar.md
Labels: bug

#2588 (5.0.0) Adopt FastUtil primitive maps
  .classpath
  exist-core/src/main/java/org/exist/dom/NamedNodeMapImpl.java
  exist-core/src/main/java/org/exist/dom/memtree/InMemoryXMLStreamReader.java
  exist-core/src/main/java/org/exist/dom/persistent/ExtArrayNodeSet.java
  exist-core/src/main/java/org/exist/dom/persistent/SymbolTable.java
  exist-core/src/main/java/org/exist/security/internal/SecurityManagerImpl.java
  exist-core/src/main/java/org/exist/storage/cache/GClockCache.java
  exist-core/src/main/java/org/exist/storage/dom/DOMFile.java
  exist-core/src/main/java/org/exist/storage/journal/LogEntryTypes.java
  exist-core/src/main/java/org/exist/storage/recovery/RecoveryManager.java
  exist-core/src/main/java/org/exist/util/hashtable/Int2ObjectHashMap.java
  exist-core/src/main/java/org/exist/util/hashtable/Long2ObjectHashMap.java
  exist-core/src/main/java/org/exist/util/hashtable/Object2IntHashMap.java
  exist-core/src/main/java/org/exist/util/hashtable/Object2LongHashMap.java
  exist-core/src/main/java/org/exist/util/hashtable/Object2LongIdentityHashMap.java
  exist-core/src/main/java/org/exist/util/hashtable/Object2ObjectHashMap.java
  exist-core/src/main/java/org/exist/util/hashtable/ObjectHashSet.java
  exist-core/src/main/java/org/exist/util/pool/NodePool.java
  exist-core/src/main/java/org/exist/util/serializer/HTML5Writer.java
  exist-core/src/main/java/org/exist/util/serializer/XHTML5Writer.java
  exist-core/src/main/java/org/exist/util/serializer/XHTMLWriter.java
  exist-core/src/main/java/org/exist/webstart/JnlpJarFiles.java
  exist-core/src/main/java/org/exist/xquery/regex/CaseVariants.java
  exist-core/src/main/java/org/exist/xquery/update/Modification.java
  exist-core/src/main/java/org/exist/xquery/value/Type.java
  exist-core/src/main/java/org/exist/xupdate/Modification.java
  exist-core/src/test/java/org/exist/util/hashtable/AllTests.java
  exist-core/src/test/java/org/exist/util/hashtable/HashtableTest.java
  exist-core/src/test/java/org/exist/util/hashtable/Int2ObjectHashMapTest.java
  exist-core/src/test/java/org/exist/util/hashtable/Long2ObjectHashMapTest.java
  exist-core/src/test/java/org/exist/util/hashtable/Object2IntHashMapTest.java
  exist-core/src/test/java/org/exist/util/hashtable/Object2LongHashMapTest.java
  exist-core/src/test/java/org/exist/util/hashtable/Object2LongIdentityHashMapTest.java
  exist-core/src/test/java/org/exist/util/hashtable/Object2ObjectHashMapTest.java
  exist-core/src/test/java/org/exist/util/hashtable/ObjectHashSetTest.java
  exist-core/src/test/java/org/exist/util/hashtable/SequencedLongHashMapTest.java
  exist-start/src/main/resources/org/exist/start/start.config
  lib/core/fastutil-8.2.2-min.jar
  lib/core/fastutil-8.2.2-min.jar.md
Labels: bug

#2589 (4.x.x) Adopt FastUtil primitive maps
  .classpath
  exist-core/src/main/java/org/exist/collections/CollectionCache.java
  exist-core/src/main/java/org/exist/collections/MutableCollection.java
  exist-core/src/main/java/org/exist/dom/NamedNodeMapImpl.java
  exist-core/src/main/java/org/exist/dom/memtree/InMemoryXMLStreamReader.java
  exist-core/src/main/java/org/exist/dom/persistent/DefaultDocumentSet.java
  exist-core/src/main/java/org/exist/dom/persistent/ExtArrayNodeSet.java
  exist-core/src/main/java/org/exist/dom/persistent/SymbolTable.java
  exist-core/src/main/java/org/exist/security/internal/SecurityManagerImpl.java
  exist-core/src/main/java/org/exist/storage/cache/GClockCache.java
  exist-core/src/main/java/org/exist/storage/dom/DOMFile.java
  exist-core/src/main/java/org/exist/storage/journal/LogEntryTypes.java
  exist-core/src/main/java/org/exist/storage/lock/LockedDocumentMap.java
  exist-core/src/main/java/org/exist/storage/recovery/RecoveryManager.java
  exist-core/src/main/java/org/exist/util/hashtable/Int2ObjectHashMap.java
  exist-core/src/main/java/org/exist/util/hashtable/Long2ObjectHashMap.java
  exist-core/src/main/java/org/exist/util/hashtable/Object2IntHashMap.java
  exist-core/src/main/java/org/exist/util/hashtable/Object2LongHashMap.java
  exist-core/src/main/java/org/exist/util/hashtable/Object2LongIdentityHashMap.java
  exist-core/src/main/java/org/exist/util/hashtable/Object2ObjectHashMap.java
  exist-core/src/main/java/org/exist/util/hashtable/ObjectHashSet.java
  exist-core/src/main/java/org/exist/util/pool/NodePool.java
  exist-core/src/main/java/org/exist/util/serializer/HTML5Writer.java
  exist-core/src/main/java/org/exist/util/serializer/XHTML5Writer.java
  exist-core/src/main/java/org/exist/util/serializer/XHTMLWriter.java
  exist-core/src/main/java/org/exist/webstart/JnlpJarFiles.java
  exist-core/src/main/java/org/exist/xquery/regex/CaseVariants.java
  exist-core/src/main/java/org/exist/xquery/update/Modification.java
  exist-core/src/main/java/org/exist/xquery/value/Type.java
  exist-core/src/main/java/org/exist/xupdate/Modification.java
  exist-core/src/test/java/org/exist/util/hashtable/AllTests.java
  exist-core/src/test/java/org/exist/util/hashtable/HashtableTest.java
  exist-core/src/test/java/org/exist/util/hashtable/Int2ObjectHashMapTest.java
  exist-core/src/test/java/org/exist/util/hashtable/Long2ObjectHashMapTest.java
  exist-core/src/test/java/org/exist/util/hashtable/Object2IntHashMapTest.java
  exist-core/src/test/java/org/exist/util/hashtable/Object2LongHashMapTest.java
  exist-core/src/test/java/org/exist/util/hashtable/Object2LongIdentityHashMapTest.java
  exist-core/src/test/java/org/exist/util/hashtable/Object2ObjectHashMapTest.java
  exist-core/src/test/java/org/exist/util/hashtable/ObjectHashSetTest.java
  exist-core/src/test/java/org/exist/util/hashtable/SequencedLongHashMapTest.java
  exist-start/src/main/resources/org/exist/start/start.config
  lib/core/fastutil-8.2.2-min.jar
  lib/core/fastutil-8.2.2-min.jar.md
Labels: bug

#2590 Improve the performance of the LockTable
  exist-core-jmh/src/main/java/org/exist/storage/lock/LockTableBenchmark.java
  exist-core/src/main/java/org/exist/collections/MutableCollection.java
  exist-core/src/main/java/org/exist/storage/BrokerPool.java
  exist-core/src/main/java/org/exist/storage/lock/Lock.java
  exist-core/src/main/java/org/exist/storage/lock/LockEventJsonListener.java
  exist-core/src/main/java/org/exist/storage/lock/LockEventLogListener.java
  exist-core/src/main/java/org/exist/storage/lock/LockEventXmlListener.java
  exist-core/src/main/java/org/exist/storage/lock/LockManager.java
  exist-core/src/main/java/org/exist/storage/lock/LockTable.java
  exist-core/src/main/java/org/exist/util/RingBuffer.java
  exist-core/src/test/java/org/exist/storage/NativeBrokerLockingTest.java
  exist-core/src/test/java/org/exist/storage/StartupLockingTest.java
  exist-core/src/test/java/org/exist/storage/lock/CollectionLocksTest.java
  exist-core/src/test/java/org/exist/storage/lock/DocumentLocksTest.java
  exist-core/src/test/java/org/exist/storage/lock/LockManagerTest.java
Labels: bug

#2591 (5.0.0) Improve the performance of the LockTable
  exist-core/src/main/java/org/exist/collections/MutableCollection.java
  exist-core/src/main/java/org/exist/storage/BrokerPool.java
  exist-core/src/main/java/org/exist/storage/lock/Lock.java
  exist-core/src/main/java/org/exist/storage/lock/LockEventJsonListener.java
  exist-core/src/main/java/org/exist/storage/lock/LockEventLogListener.java
  exist-core/src/main/java/org/exist/storage/lock/LockEventXmlListener.java
  exist-core/src/main/java/org/exist/storage/lock/LockManager.java
  exist-core/src/main/java/org/exist/storage/lock/LockTable.java
  exist-core/src/main/java/org/exist/util/RingBuffer.java
  exist-core/src/test/java/org/exist/storage/NativeBrokerLockingTest.java
  exist-core/src/test/java/org/exist/storage/StartupLockingTest.java
  exist-core/src/test/java/org/exist/storage/lock/CollectionLocksTest.java
  exist-core/src/test/java/org/exist/storage/lock/DocumentLocksTest.java
  exist-core/src/test/java/org/exist/storage/lock/LockManagerTest.java
Labels: bug

#2594 Fix a permissions issue with replacing binary resources
  exist-core/src/main/java/org/exist/collections/MutableCollection.java
  exist-core/src/main/java/org/exist/dom/persistent/DocumentImpl.java
  exist-core/src/test/java/org/exist/storage/AllStorageTests.java
  exist-core/src/test/java/org/exist/storage/CopyResourceTest.java
  exist-core/src/test/java/org/exist/storage/StoreBinaryTest.java
  exist-core/src/test/java/org/exist/storage/StoreResourceTest.java
Labels: bug

#2595 (5.0.0) Fix a permissions issue with replacing binary resources
  exist-core/src/main/java/org/exist/collections/MutableCollection.java
  exist-core/src/main/java/org/exist/dom/persistent/DocumentImpl.java
  exist-core/src/test/java/org/exist/storage/AllStorageTests.java
  exist-core/src/test/java/org/exist/storage/CopyResourceTest.java
  exist-core/src/test/java/org/exist/storage/StoreBinaryTest.java
  exist-core/src/test/java/org/exist/storage/StoreResourceTest.java
Labels: bug

#2596 (4.x.x) Fix a permissions issue with replacing binary resources
  exist-core/src/main/java/org/exist/collections/MutableCollection.java
  exist-core/src/test/java/org/exist/storage/AllStorageTests.java
  exist-core/src/test/java/org/exist/storage/StoreBinaryTest.java
  exist-core/src/test/java/org/exist/storage/StoreResourceTest.java
Labels: bug

#2423 [feature] Switch to the new dashboard
  build.properties
  installer/apps.properties
Labels: enhancement, in progress

#2438 (5.0.0) [feature] switch to new dashboard
  build.properties
  installer/apps.properties
Labels: enhancement, in progress

#2578 (4.x.x) Update Eclipse classpath to fix compilation
  .classpath
  extensions/xqdoc/src/test/java/xqdoc/XQDocTests.java
Labels: needs 5.0.0 backport

#2577 Dynamically loaded module vars not analyzed
  exist-core/src/main/java/org/exist/xquery/ExternalModule.java
  exist-core/src/main/java/org/exist/xquery/ExternalModuleImpl.java
  exist-core/src/main/java/org/exist/xquery/VariableDeclaration.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/LoadXQueryModule.java
  exist-core/src/main/java/org/exist/xquery/functions/inspect/ModuleFunctions.java
  exist-core/src/main/java/org/exist/xquery/functions/util/PrologFunctions.java
  exist-core/src/test/xquery/xquery3/closure-in-maps.xql
  exist-core/src/test/xquery/xquery3/dynamically-declared-vars.xql
  exist-core/src/test/xquery/xquery3/load-xquery-module.xql
Labels: bug

#2579 (4.x.x) Dynamically loaded module vars not analyzed
  exist-core/src/main/java/org/exist/xquery/ExternalModule.java
  exist-core/src/main/java/org/exist/xquery/ExternalModuleImpl.java
  exist-core/src/main/java/org/exist/xquery/VariableDeclaration.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/LoadXQueryModule.java
  exist-core/src/main/java/org/exist/xquery/functions/inspect/ModuleFunctions.java
  exist-core/src/main/java/org/exist/xquery/functions/util/PrologFunctions.java
  exist-core/src/test/xquery/xquery3/closure-in-maps.xql
  exist-core/src/test/xquery/xquery3/dynamically-declared-vars.xql
  exist-core/src/test/xquery/xquery3/load-xquery-module.xql
Labels: bug

#2580 (5.0.0) Dynamically loaded module vars not analyzed
  exist-core/src/main/java/org/exist/xquery/ExternalModule.java
  exist-core/src/main/java/org/exist/xquery/ExternalModuleImpl.java
  exist-core/src/main/java/org/exist/xquery/VariableDeclaration.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/LoadXQueryModule.java
  exist-core/src/main/java/org/exist/xquery/functions/inspect/ModuleFunctions.java
  exist-core/src/main/java/org/exist/xquery/functions/util/PrologFunctions.java
  exist-core/src/test/xquery/xquery3/closure-in-maps.xql
  exist-core/src/test/xquery/xquery3/dynamically-declared-vars.xql
  exist-core/src/test/xquery/xquery3/load-xquery-module.xql
Labels: bug

#2606 Fix RecoveryTest determinism
  exist-core/src/test/java/org/exist/storage/RecoveryTest.java
Labels: bug

#2607 (5.0.0) Fix RecoveryTest determinism
  exist-core/src/test/java/org/exist/storage/RecoveryTest.java
Labels: bug

#2608 (4.x.x) Fix RecoveryTest determinism
  exist-core/src/test/java/org/exist/storage/RecoveryTest.java
Labels: bug

#2585 Fix purging of old zip backups
  exist-core/src/main/java/org/exist/storage/BackupSystemTask.java
  exist-core/src/main/java/org/exist/util/FileUtils.java
Labels: bug

#2610 (4.x.x) Fix purging of old zip backups
  exist-core/src/main/java/org/exist/storage/BackupSystemTask.java
  exist-core/src/main/java/org/exist/util/FileUtils.java
Labels: bug

#2609 (5.0.0) Fix purging of old zip backups
  exist-core/src/main/java/org/exist/storage/BackupSystemTask.java
  exist-core/src/main/java/org/exist/util/FileUtils.java
Labels: bug

#2581 Update Eclipse classpath to fix compilation
  .classpath
  extensions/xqdoc/src/test/java/xqdoc/XQDocTests.java
Labels: bug

#2611 (5.0.0) Update Eclipse classpath to fix compilation
  .classpath
  extensions/xqdoc/src/test/java/xqdoc/XQDocTests.java
Labels: bug

#2617 Fix NPE in LDAPRealm when seraching for group members
  extensions/security/ldap/src/main/java/org/exist/security/realm/ldap/LDAPRealm.java
Labels: bug

#2618 (5.0.0) Fix NPE in LDAPRealm when seraching for group members
  extensions/security/ldap/src/main/java/org/exist/security/realm/ldap/LDAPRealm.java
Labels: bug

#2619 (4.x.x) Fix NPE in LDAPRealm when seraching for group members
  extensions/security/ldap/src/main/java/org/exist/security/realm/ldap/LDAPRealm.java
Labels: bug

#2612 (5.0.0) add tests for except operator
  exist-core/src/test/xquery/exceptOperator.xql
  exist-core/src/test/xquery/literals-in-curlies.xql
Labels: enhancement

#2613 (4.x.x) add tests for except operator
  exist-core/src/test/xquery/exceptOperator.xql
  exist-core/src/test/xquery/literals-in-curlies.xql
Labels: enhancement
