Repository eXist-db/exist, pull requests merged in 2019-10, with the labels that each got.

#3035 Avoid failing macOS builds on travis
  .travis.yml
Labels: enhancement, macOS

#3034 Allow multiple transactions per broker
  exist-core/src/main/java/org/exist/storage/DBBroker.java
  exist-core/src/main/java/org/exist/storage/txn/TransactionManager.java
  exist-core/src/main/java/org/exist/storage/txn/Txn.java
  exist-core/src/test/java/org/exist/storage/AbstractRecoverTest.java
  exist-core/src/test/java/org/exist/storage/journal/AbstractJournalTest.java
  exist-core/src/test/java/org/exist/storage/txn/ReusableTxnTest.java
  exist-core/src/test/java/org/exist/storage/txn/TransactionManagerTestHelper.java
  exist-core/src/test/java/org/exist/storage/txn/TxnTest.java
Labels: enhancement

#3047 Fix util:parse-html dependency
  exist-core/pom.xml
  exist-core/src/test/java/org/exist/xquery/functions/util/ParseHtmlTest.java
Labels: bug

#3059 Fix a security issue with collection access
  exist-core/src/main/java/org/exist/security/SimpleACLPermission.java
  exist-core/src/main/java/org/exist/security/internal/aider/SimpleACLPermissionAider.java
  exist-core/src/main/java/org/exist/storage/NativeBroker.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/ExtCollection.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FunDoc.java
  exist-core/src/test/java/org/exist/security/AbstractApiSecurityTest.java
  exist-core/src/test/java/org/exist/security/ApiException.java
  exist-core/src/test/java/org/exist/security/FnCollectionSecurityTest.java
  exist-core/src/test/java/org/exist/security/FnDocSecurityTest.java
  exist-core/src/test/java/org/exist/security/RestApiSecurityTest.java
  exist-core/src/test/java/org/exist/security/XmldbApiSecurityTest.java
  exist-core/src/test/java/org/exist/security/XqueryApiTest.java
  extensions/indexes/lucene/src/test/java/org/exist/indexing/lucene/OptimizerTest.java
Labels: bug, high prio, security

#3060 (4.x.x) Fix a security issue with collection access
  exist-core/src/main/java/org/exist/security/SimpleACLPermission.java
  exist-core/src/main/java/org/exist/security/internal/aider/SimpleACLPermissionAider.java
  exist-core/src/main/java/org/exist/storage/NativeBroker.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/ExtCollection.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FunDoc.java
  exist-core/src/test/java/org/exist/security/AbstractApiSecurityTest.java
  exist-core/src/test/java/org/exist/security/ApiException.java
  exist-core/src/test/java/org/exist/security/FnCollectionSecurityTest.java
  exist-core/src/test/java/org/exist/security/FnDocSecurityTest.java
  exist-core/src/test/java/org/exist/security/RestApiSecurityTest.java
  exist-core/src/test/java/org/exist/security/XmldbApiSecurityTest.java
  exist-core/src/test/java/org/exist/security/XqueryApiTest.java
Labels: bug, high prio, security

#3065 Make sure that compiled queries are returned to the pool
  exist-core/src/main/java/org/exist/http/RESTServer.java
  exist-core/src/main/java/org/exist/storage/serializers/XIncludeFilter.java
Labels: bug

#3079 (4.x.x) Avoid NPE when reporting error
  exist-core/src/main/java/org/exist/storage/NativeBroker.java
Labels: bug

#3081 Some small improvements to the SQL Module
  extensions/modules/sql/pom.xml
  extensions/modules/sql/src/main/java/org/exist/xquery/modules/sql/ExecuteFunction.java
  extensions/modules/sql/src/main/java/org/exist/xquery/modules/sql/GetConnectionFunction.java
  extensions/modules/sql/src/main/java/org/exist/xquery/modules/sql/GetJNDIConnectionFunction.java
  extensions/modules/sql/src/main/java/org/exist/xquery/modules/sql/PrepareFunction.java
  extensions/modules/sql/src/main/java/org/exist/xquery/modules/sql/PreparedStatementWithSQL.java
  extensions/modules/sql/src/main/java/org/exist/xquery/modules/sql/SQLModule.java
  extensions/modules/sql/src/main/java/org/exist/xquery/modules/sql/SQLUtils.java
  extensions/modules/sql/src/test/java/org/exist/xquery/modules/sql/ExecuteFunctionTest.java
Labels: bug
