Repository eXist-db/exist, pull requests merged in 2019-05, with the labels that each got.

#2667 Fix sorting sequences of more than 8192 items with collations
  exist-core/src/main/java/org/exist/util/Collations.java
  exist-core/src/main/java/org/exist/xquery/value/OrderedValueSequence.java
Labels: bug

#2669 (5.0.0) Fix sorting sequences of more than 8192 items with collations
  exist-core/src/main/java/org/exist/util/Collations.java
  exist-core/src/main/java/org/exist/xquery/value/OrderedValueSequence.java
Labels: bug

#2668 (4.x.x) Fix sorting sequences of more than 8192 items with collations
  .idea/misc.xml
  exist-core/src/main/java/org/exist/util/Collations.java
  exist-core/src/main/java/org/exist/xquery/value/OrderedValueSequence.java
Labels: bug

#2672 (4.x.x) Fix a problem with collation comparison on empty strings
  exist-core/src/main/java/org/exist/util/Collations.java
  exist-core/src/test/xquery/collations.xq
Labels: bug

#2671 (5.0.0) Fix a problem with collation comparison on empty strings
  exist-core/src/main/java/org/exist/util/Collations.java
  exist-core/src/test/xquery/collations.xq
Labels: bug

#2670 Fix a problem with collation comparison on empty strings
  exist-core/src/main/java/org/exist/util/Collations.java
  exist-core/src/test/xquery/collations.xq
Labels: bug

#2676 Minor cleanup
  exist-core/src/main/java/org/exist/plugin/PluginsManagerImpl.java
  log4j2.xml
Labels: bug

#2677 (5.0.0) Minor cleanup
  exist-core/src/main/java/org/exist/plugin/PluginsManagerImpl.java
  log4j2.xml
Labels: bug

#2683 (4.x.x) Descendant nodes wrongly indexed, fix PR #2367
  exist-core/src/main/java/org/exist/storage/NativeBroker.java
  exist-core/src/main/java/org/exist/storage/NodePath.java
  exist-core/src/test/java/org/exist/storage/ShutdownTest.java
  extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/NodePathPattern.java
  extensions/indexes/lucene/src/test/java/org/exist/indexing/lucene/LuceneIndexTest.java
Labels: bug

#2680 Descendant nodes wrongly indexed, fix PR #2367
  exist-core/src/main/java/org/exist/storage/NativeBroker.java
  exist-core/src/main/java/org/exist/storage/NodePath.java
  exist-core/src/test/java/org/exist/storage/ShutdownTest.java
  extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/NodePathPattern.java
  extensions/indexes/lucene/src/test/java/org/exist/indexing/lucene/LuceneIndexTest.java
Labels: bug

#2682 (5.0.0) Descendant nodes wrongly indexed, fix PR #2367
  exist-core/src/main/java/org/exist/storage/NativeBroker.java
  exist-core/src/main/java/org/exist/storage/NodePath.java
  exist-core/src/test/java/org/exist/storage/ShutdownTest.java
  extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/NodePathPattern.java
  extensions/indexes/lucene/src/test/java/org/exist/indexing/lucene/LuceneIndexTest.java
Labels: bug

#2689 Fix an issue with LockTable Entries#unmerge under high concurrency
  exist-core/src/main/java/org/exist/storage/lock/LockTable.java
Labels: bug

#2690 (5.0.0) Fix an issue with LockTable Entries#unmerge under high concurrency
  exist-core/src/main/java/org/exist/storage/lock/LockTable.java
Labels: bug

#2692 Opening a collection using full XmldbURI (with scheme) fails.
  exist-core/src/main/java/org/exist/storage/NativeBroker.java
  exist-core/src/test/java/org/exist/collections/AllCollectionTests.java
  exist-core/src/test/java/org/exist/collections/OpenCollectionTest.java
Labels: bug

#2693 (5.0.0) Opening a collection using full XmldbURI (with scheme) fails.
  exist-core/src/main/java/org/exist/storage/NativeBroker.java
  exist-core/src/test/java/org/exist/collections/AllCollectionTests.java
  exist-core/src/test/java/org/exist/collections/OpenCollectionTest.java
Labels: bug

#2699 (4.x.x) Fix deadlock
  exist-core/src/main/java/org/exist/collections/Collection.java
  exist-core/src/main/java/org/exist/collections/CollectionCache.java
  exist-core/src/main/java/org/exist/collections/MutableCollection.java
Labels: bug

#2687 Reduce mutable state in MutableCollection
  exist-core/src/main/java/org/exist/ant/RestoreTask.java
  exist-core/src/main/java/org/exist/backup/GuiRestoreServiceTaskListener.java
  exist-core/src/main/java/org/exist/backup/Main.java
  exist-core/src/main/java/org/exist/backup/Restore.java
  exist-core/src/main/java/org/exist/backup/SystemImport.java
  exist-core/src/main/java/org/exist/backup/restore/AbstractDefferedPermission.java
  exist-core/src/main/java/org/exist/backup/restore/CollectionDeferredPermission.java
  exist-core/src/main/java/org/exist/backup/restore/DeferredPermission.java
  exist-core/src/main/java/org/exist/backup/restore/ResourceDeferredPermission.java
  exist-core/src/main/java/org/exist/backup/restore/RestoreHandler.java
  exist-core/src/main/java/org/exist/backup/restore/SkippedEntryDeferredPermission.java
  exist-core/src/main/java/org/exist/backup/restore/SystemImportHandler.java
  exist-core/src/main/java/org/exist/backup/restore/listener/AbstractRestoreListener.java
  exist-core/src/main/java/org/exist/backup/restore/listener/ConsoleRestoreListener.java
  exist-core/src/main/java/org/exist/backup/restore/listener/GuiRestoreListener.java
  exist-core/src/main/java/org/exist/backup/restore/listener/LogRestoreListener.java
  exist-core/src/main/java/org/exist/backup/restore/listener/RestoreListener.java
  exist-core/src/main/java/org/exist/client/ClientFrame.java
  exist-core/src/main/java/org/exist/collections/Collection.java
  exist-core/src/main/java/org/exist/collections/LockedCollection.java
  exist-core/src/main/java/org/exist/collections/MutableCollection.java
  exist-core/src/main/java/org/exist/collections/triggers/DocumentTriggers.java
  exist-core/src/main/java/org/exist/security/PermissionFactory.java
  exist-core/src/main/java/org/exist/storage/DBBroker.java
  exist-core/src/main/java/org/exist/storage/NativeBroker.java
  exist-core/src/main/java/org/exist/xmldb/AbstractRestoreServiceTaskListener.java
  exist-core/src/main/java/org/exist/xmldb/ConsoleRestoreServiceTaskListener.java
  exist-core/src/main/java/org/exist/xmldb/EXistCollection.java
  exist-core/src/main/java/org/exist/xmldb/EXistRestoreService.java
  exist-core/src/main/java/org/exist/xmldb/LocalCollection.java
  exist-core/src/main/java/org/exist/xmldb/LocalRestoreService.java
  exist-core/src/main/java/org/exist/xmldb/NullRestoreServiceTaskListener.java
  exist-core/src/main/java/org/exist/xmldb/RemoteCollection.java
  exist-core/src/main/java/org/exist/xmldb/RemoteRestoreService.java
  exist-core/src/main/java/org/exist/xmldb/RestoreServiceTaskListener.java
  exist-core/src/main/java/org/exist/xmlrpc/RpcAPI.java
  exist-core/src/main/java/org/exist/xmlrpc/RpcConnection.java
  exist-core/src/main/java/org/exist/xmlrpc/XmldbRequestProcessorFactory.java
  exist-core/src/main/java/org/exist/xquery/functions/system/FnImport.java
  exist-core/src/main/java/org/exist/xquery/functions/system/Restore.java
  exist-core/src/test/java/org/exist/backup/SystemExportFiltersTest.java
  exist-core/src/test/java/org/exist/backup/SystemExportImportTest.java
  exist-core/src/test/java/org/exist/backup/XMLDBBackupTest.java
  exist-core/src/test/java/org/exist/backup/XMLDBRestoreTest.java
  exist-core/src/test/java/org/exist/collections/triggers/TestTrigger.java
  exist-core/src/test/java/org/exist/security/internal/BackupRestoreSecurityPrincipalsTest.java
  exist-core/src/test/java/org/exist/xquery/SAXStorageTest.java
  samples/src/main/java/org/exist/examples/triggers/ExampleTrigger.java
Labels: enhancement

#2688 (5.0.0) Reduce mutable state in MutableCollection
  exist-core/src/main/java/org/exist/ant/RestoreTask.java
  exist-core/src/main/java/org/exist/backup/GuiRestoreServiceTaskListener.java
  exist-core/src/main/java/org/exist/backup/Main.java
  exist-core/src/main/java/org/exist/backup/Restore.java
  exist-core/src/main/java/org/exist/backup/SystemImport.java
  exist-core/src/main/java/org/exist/backup/restore/AbstractDefferedPermission.java
  exist-core/src/main/java/org/exist/backup/restore/CollectionDeferredPermission.java
  exist-core/src/main/java/org/exist/backup/restore/DeferredPermission.java
  exist-core/src/main/java/org/exist/backup/restore/ResourceDeferredPermission.java
  exist-core/src/main/java/org/exist/backup/restore/RestoreHandler.java
  exist-core/src/main/java/org/exist/backup/restore/SkippedEntryDeferredPermission.java
  exist-core/src/main/java/org/exist/backup/restore/SystemImportHandler.java
  exist-core/src/main/java/org/exist/backup/restore/listener/AbstractRestoreListener.java
  exist-core/src/main/java/org/exist/backup/restore/listener/ConsoleRestoreListener.java
  exist-core/src/main/java/org/exist/backup/restore/listener/GuiRestoreListener.java
  exist-core/src/main/java/org/exist/backup/restore/listener/LogRestoreListener.java
  exist-core/src/main/java/org/exist/backup/restore/listener/RestoreListener.java
  exist-core/src/main/java/org/exist/client/ClientFrame.java
  exist-core/src/main/java/org/exist/collections/Collection.java
  exist-core/src/main/java/org/exist/collections/LockedCollection.java
  exist-core/src/main/java/org/exist/collections/MutableCollection.java
  exist-core/src/main/java/org/exist/collections/triggers/DocumentTriggers.java
  exist-core/src/main/java/org/exist/security/PermissionFactory.java
  exist-core/src/main/java/org/exist/storage/DBBroker.java
  exist-core/src/main/java/org/exist/storage/NativeBroker.java
  exist-core/src/main/java/org/exist/xmldb/AbstractRestoreServiceTaskListener.java
  exist-core/src/main/java/org/exist/xmldb/ConsoleRestoreServiceTaskListener.java
  exist-core/src/main/java/org/exist/xmldb/EXistCollection.java
  exist-core/src/main/java/org/exist/xmldb/EXistRestoreService.java
  exist-core/src/main/java/org/exist/xmldb/LocalCollection.java
  exist-core/src/main/java/org/exist/xmldb/LocalRestoreService.java
  exist-core/src/main/java/org/exist/xmldb/NullRestoreServiceTaskListener.java
  exist-core/src/main/java/org/exist/xmldb/RemoteCollection.java
  exist-core/src/main/java/org/exist/xmldb/RemoteRestoreService.java
  exist-core/src/main/java/org/exist/xmldb/RestoreServiceTaskListener.java
  exist-core/src/main/java/org/exist/xmlrpc/RpcAPI.java
  exist-core/src/main/java/org/exist/xmlrpc/RpcConnection.java
  exist-core/src/main/java/org/exist/xmlrpc/XmldbRequestProcessorFactory.java
  exist-core/src/main/java/org/exist/xquery/functions/system/FnImport.java
  exist-core/src/main/java/org/exist/xquery/functions/system/Restore.java
  exist-core/src/test/java/org/exist/backup/SystemExportFiltersTest.java
  exist-core/src/test/java/org/exist/backup/SystemExportImportTest.java
  exist-core/src/test/java/org/exist/backup/XMLDBBackupTest.java
  exist-core/src/test/java/org/exist/backup/XMLDBRestoreTest.java
  exist-core/src/test/java/org/exist/collections/triggers/TestTrigger.java
  exist-core/src/test/java/org/exist/security/internal/BackupRestoreSecurityPrincipalsTest.java
  exist-core/src/test/java/org/exist/xquery/SAXStorageTest.java
  samples/src/main/java/org/exist/examples/triggers/ExampleTrigger.java
Labels: enhancement

#2707 Update the public-xar-repo-plugin
  exist-distribution/pom.xml
Labels: bug

#2708 (5.0.0) Update the public-xar-repo-plugin
  exist-distribution/pom.xml
Labels: bug

#2703 Lucene: fix AlreadyClosedException
  extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/LuceneIndexWorker.java
  extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/LuceneMatch.java
  extensions/indexes/lucene/src/main/java/org/exist/xquery/modules/lucene/Facets.java
Labels: bug

#2704 (5.0.0) Lucene: fix AlreadyClosedException
  extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/LuceneIndexWorker.java
  extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/LuceneMatch.java
  extensions/indexes/lucene/src/main/java/org/exist/xquery/modules/lucene/Facets.java
Labels: bug

#2706 Fix the logo image path in README.md
  README.md
Labels: bug

#2709 (5.0.0) Fix the logo image path in README.md
  README.md
Labels: bug

#2715 Don't deploy the IzPack Jar to the Maven repo
  exist-installer/pom.xml
  exist-parent/pom.xml
Labels: bug

#2716 (5.0.0) Don't deploy the IzPack Jar to the Maven repo
  exist-installer/pom.xml
  exist-parent/pom.xml
Labels: bug

#2729 LauncherWrapper not exiting after first start
  exist-core/src/main/java/org/exist/launcher/LauncherWrapper.java
Labels: bug

#2730 (5.0.0) LauncherWrapper not exiting after first start
  exist-core/src/main/java/org/exist/launcher/LauncherWrapper.java
Labels: bug

#2742 (5.0.0) fn:tokenize should be case sensitive by default
  exist-core/src/main/java/org/exist/xquery/functions/fn/FunTokenize.java
  exist-core/src/test/java/org/exist/xquery/XQueryFunctionsTest.java
Labels: bug

#2739 The content of comments should not be escaped
  exist-core/src/main/java/org/exist/dom/persistent/CommentImpl.java
  exist-core/src/test/java/org/exist/dom/persistent/CommentTest.java
Labels: bug

#2740 (5.0.0) The content of comments should not be escaped
  exist-core/src/main/java/org/exist/dom/persistent/CommentImpl.java
  exist-core/src/test/java/org/exist/dom/persistent/CommentTest.java
Labels: bug

#2737 Installing service fails with OpenJDK
  exist-core/src/main/java/org/exist/launcher/WindowsServiceManager.java
Labels: bug

#2738 (5.0.0) Installing service fails with OpenJDK
  exist-core/src/main/java/org/exist/launcher/WindowsServiceManager.java
Labels: bug

#2759 Fixes getBytes() method returning wrong data if switched to file
  exist-core/src/main/java/org/exist/util/io/VirtualTempPath.java
  exist-core/src/test/java/org/exist/util/io/VirtualTempPathTest.java
Labels: bug, needs 5.0.0 backport

#2751 Very small fixes
  exist-core/src/main/java/org/exist/TestUtils.java
  exist-core/src/main/java/org/exist/collections/MutableCollection.java
  exist-core/src/main/java/org/exist/security/PermissionFactory.java
  exist-core/src/main/java/org/exist/storage/NativeBroker.java
  exist-core/src/main/java/org/exist/xmldb/XmldbURI.java
  exist-core/src/test/java/org/exist/config/TwoDatabasesTest.java
  exist-core/src/test/java/org/exist/storage/CopyCollectionTest.java
  exist-core/src/test/java/org/exist/storage/CopyResourceTest.java
  exist-core/src/test/java/org/exist/storage/ModificationTimeTest.java
  exist-core/src/test/java/org/exist/storage/StoreResourceTest.java
  exist-core/src/test/java/org/exist/storage/lock/ProtectedModeTest.java
  exist-core/src/test/java/org/exist/storage/txn/ConcurrentTransactionsTest.java
  exist-core/src/test/java/org/exist/xquery/functions/securitymanager/PermissionsFunctionChmodTest.java
  exist-core/src/test/java/org/exist/xquery/functions/securitymanager/PermissionsFunctionChownTest.java
Labels: bug, enhancement

#2752 (5.0.0) Very small fixes
  exist-core/src/main/java/org/exist/TestUtils.java
  exist-core/src/main/java/org/exist/collections/MutableCollection.java
  exist-core/src/main/java/org/exist/security/PermissionFactory.java
  exist-core/src/main/java/org/exist/storage/NativeBroker.java
  exist-core/src/main/java/org/exist/xmldb/XmldbURI.java
  exist-core/src/test/java/org/exist/config/TwoDatabasesTest.java
  exist-core/src/test/java/org/exist/storage/CopyCollectionTest.java
  exist-core/src/test/java/org/exist/storage/CopyResourceTest.java
  exist-core/src/test/java/org/exist/storage/ModificationTimeTest.java
  exist-core/src/test/java/org/exist/storage/StoreResourceTest.java
  exist-core/src/test/java/org/exist/storage/lock/ProtectedModeTest.java
  exist-core/src/test/java/org/exist/storage/txn/ConcurrentTransactionsTest.java
  exist-core/src/test/java/org/exist/xquery/functions/securitymanager/PermissionsFunctionChmodTest.java
  exist-core/src/test/java/org/exist/xquery/functions/securitymanager/PermissionsFunctionChownTest.java
Labels: bug, enhancement
