Repository eXist-db/exist, pull requests merged in 2020-03, with the labels that each got.

#3227 [wip] [feat] distinct analyzers for indexing and querying with Lucene
  extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/LuceneConfig.java
  extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/LuceneIndexWorker.java
  extensions/indexes/lucene/src/main/java/org/exist/xquery/modules/lucene/QueryOptions.java
  extensions/indexes/lucene/src/test/xquery/lucene/analyzers.xml
Labels: needs documentation

#3260 Switch README.md link for JDK from Oracle to AdoptOpenJDK
  README.md
Labels: enhancement

#3261 Reinstate code for a historical Jetty bugfix
  exist-core/src/main/java/org/exist/xquery/functions/request/GetData.java
Labels: bug

#3265 Make sure the context is preserved when dynamically compiling a query
  exist-core/src/main/java/org/exist/xquery/FunctionFactory.java
  exist-core/src/main/java/org/exist/xquery/functions/util/Compile.java
Labels: bug

#3262 Make sure the Memtree in the query context is correctly used
  exist-core/src/main/java/org/exist/xquery/XPathUtil.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FunAnalyzeString.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/JSON.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/ParsingFunctions.java
  exist-core/src/main/java/org/exist/xquery/functions/inspect/InspectFunction.java
  exist-core/src/main/java/org/exist/xquery/functions/inspect/InspectModule.java
  exist-core/src/main/java/org/exist/xquery/functions/securitymanager/IdFunction.java
  exist-core/src/main/java/org/exist/xquery/functions/securitymanager/PermissionsFunction.java
  exist-core/src/main/java/org/exist/xquery/functions/system/FnExport.java
  exist-core/src/main/java/org/exist/xquery/functions/system/FnImport.java
  exist-core/src/main/java/org/exist/xquery/functions/system/FunctionTrace.java
  exist-core/src/main/java/org/exist/xquery/functions/system/GetRunningJobs.java
  exist-core/src/main/java/org/exist/xquery/functions/system/GetRunningXQueries.java
  exist-core/src/main/java/org/exist/xquery/functions/system/GetScheduledJobs.java
  exist-core/src/main/java/org/exist/xquery/functions/system/Restore.java
  exist-core/src/main/java/org/exist/xquery/functions/transform/Transform.java
  exist-core/src/main/java/org/exist/xquery/functions/util/Compile.java
  exist-core/src/main/java/org/exist/xquery/functions/util/DeepCopyFunction.java
  exist-core/src/main/java/org/exist/xquery/functions/util/DescribeFunction.java
  exist-core/src/main/java/org/exist/xquery/functions/util/Parse.java
  exist-core/src/main/java/org/exist/xquery/functions/validation/GrammarTooling.java
  exist-core/src/main/java/org/exist/xquery/functions/validation/Jaxp.java
  exist-core/src/main/java/org/exist/xquery/functions/validation/Jaxv.java
  exist-core/src/main/java/org/exist/xquery/functions/validation/Jing.java
  exist-core/src/test/java/org/exist/xquery/functions/securitymanager/GetPermissionsTest.java
  exist-core/src/test/java/org/exist/xquery/functions/securitymanager/IdFunctionTest.java
  extensions/contentextraction/src/main/java/org/exist/contentextraction/xquery/ContentFunctions.java
  extensions/expath/src/main/java/org/expath/exist/ZipFileFunctions.java
  extensions/expath/src/main/java/org/expath/httpclient/model/exist/EXistTreeBuilder.java
  extensions/exquery/restxq/src/main/java/org/exist/extensions/exquery/restxq/impl/xquery/RegistryFunctions.java
  extensions/exquery/restxq/src/main/java/org/exist/extensions/exquery/restxq/impl/xquery/exist/RegistryFunctions.java
  extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/LuceneIndexWorker.java
  extensions/indexes/lucene/src/main/java/org/exist/xquery/modules/lucene/Search.java
  extensions/indexes/ngram/src/main/java/org/exist/xquery/modules/ngram/HighlightMatches.java
  extensions/modules/exi/src/main/java/org/exist/xquery/modules/exi/DecodeExiFunction.java
  extensions/modules/file/src/main/java/org/exist/xquery/modules/file/Directory.java
  extensions/modules/file/src/main/java/org/exist/xquery/modules/file/DirectoryList.java
  extensions/modules/jndi/src/main/java/org/exist/xquery/modules/jndi/SearchFunction.java
  extensions/modules/mail/src/main/java/org/exist/xquery/modules/mail/MessageFunctions.java
  extensions/modules/mail/src/main/java/org/exist/xquery/modules/mail/MessageListFunctions.java
  extensions/modules/process/src/main/java/org/exist/xquery/modules/process/Execute.java
  extensions/modules/sql/src/main/java/org/exist/xquery/modules/sql/ExecuteFunction.java
Labels: bug

#3270 Correctly set the sticky bit when using a simple symbolic mode string
  exist-core/src/main/java/org/exist/security/AbstractUnixStylePermission.java
  exist-core/src/test/java/org/exist/security/UnixStylePermissionTest.java
Labels: bug

#3268 Include the path of any file that could not be restored in the log
  exist-core/src/main/java/org/exist/backup/restore/RestoreHandler.java
Labels: bug

#3267 Descriptor file should be read from $EXIST_HOME/etc
  exist-core/src/main/java/org/exist/http/Descriptor.java
Labels: bug, regression

#3263 Multiple resources can have their permissions set in the JAC
  exist-core/src/main/java/org/exist/client/CheckboxTableCellEditor.java
  exist-core/src/main/java/org/exist/client/CheckboxTableCellRenderer.java
  exist-core/src/main/java/org/exist/client/ClientFrame.java
  exist-core/src/main/java/org/exist/client/InteractiveClient.java
  exist-core/src/main/java/org/exist/client/LabelledBoolean.java
  exist-core/src/main/java/org/exist/client/LabelledBooleanEditor.java
  exist-core/src/main/java/org/exist/client/LabelledBooleanRenderer.java
  exist-core/src/main/java/org/exist/client/ResourceDescriptor.java
  exist-core/src/main/java/org/exist/client/security/BasicPermissionsTableModel.java
  exist-core/src/main/java/org/exist/client/security/EditPropertiesDialog.java
  exist-core/src/main/java/org/exist/client/security/ModeDisplay.java
  exist-core/src/main/java/org/exist/client/tristatecheckbox/TristateCheckBox.java
  exist-core/src/main/java/org/exist/client/tristatecheckbox/TristateCheckBoxTableCellRenderer.java
  exist-core/src/main/java/org/exist/client/tristatecheckbox/TristateCheckboxTableCellEditor.java
  exist-core/src/main/java/org/exist/client/tristatecheckbox/TristateState.java
  exist-core/src/main/java/org/exist/security/Permission.java
  exist-core/src/main/java/org/exist/security/internal/aider/ACEAider.java
  exist-core/src/main/java/org/exist/security/internal/aider/SimpleACLPermissionAider.java
  exist-core/src/main/java/org/exist/security/internal/aider/UnixStylePermissionAider.java
  exist-core/src/main/java/org/exist/util/FileUtils.java
  exist-core/src/test/java/org/exist/client/security/BasicPermissionsTableModelTest.java
Labels: bug, enhancement

#3266 Fix type conversion of xs:positiveInteger and xs:negativeInteger types
  exist-core/src/main/java/org/exist/xquery/CastExpression.java
  exist-core/src/main/java/org/exist/xquery/UntypedValueCheck.java
  exist-core/src/main/java/org/exist/xquery/functions/array/ArrayType.java
  exist-core/src/main/java/org/exist/xquery/value/IntegerValue.java
  exist-core/src/test/java/org/exist/xquery/value/DoubleValueTest.java
  exist-core/src/test/xquery/integers.xq
Labels: bug

#3269 Document URI was incorrectly cached during a Collection Move
  exist-core/src/main/java/org/exist/collections/Collection.java
  exist-core/src/main/java/org/exist/collections/LockedCollection.java
  exist-core/src/main/java/org/exist/collections/MutableCollection.java
  exist-core/src/main/java/org/exist/storage/NativeBroker.java
  exist-core/src/test/xquery/indexing/indexes-base-uri.xq
Labels: bug

#3274 Make Quartz Scheduler properties easily configurable
  exist-core/src/main/java/org/exist/scheduler/impl/QuartzSchedulerImpl.java
  exist-distribution/src/main/config/quartz.properties
Labels: enhancement

#3271 Fix reporting of Restored Documents when restoring a backup
  exist-core/src/main/java/org/exist/backup/DescriptorResourceCounter.java
  exist-core/src/main/java/org/exist/backup/FileSystemBackupDescriptor.java
  exist-core/src/main/java/org/exist/backup/GuiRestoreServiceTaskListener.java
  exist-core/src/main/java/org/exist/backup/Main.java
  exist-core/src/main/java/org/exist/backup/Restore.java
  exist-core/src/main/java/org/exist/backup/RestoreDialog.java
  exist-core/src/main/java/org/exist/backup/ZipArchiveBackupDescriptor.java
  exist-core/src/main/java/org/exist/backup/restore/RestoreHandler.java
  exist-core/src/main/java/org/exist/backup/restore/listener/AbstractRestoreListener.java
  exist-core/src/main/java/org/exist/backup/restore/listener/RestoreListener.java
  exist-core/src/main/java/org/exist/client/ClientFrame.java
  exist-core/src/main/java/org/exist/util/FileUtils.java
  exist-core/src/main/java/org/exist/xmldb/AbstractRestoreServiceTaskListener.java
  exist-core/src/main/java/org/exist/xmldb/LocalRestoreService.java
  exist-core/src/main/java/org/exist/xmldb/RemoteRestoreService.java
  exist-core/src/main/java/org/exist/xmldb/RestoreServiceTaskListener.java
  exist-core/src/main/java/org/exist/xmlrpc/RpcAPI.java
  exist-core/src/main/java/org/exist/xmlrpc/RpcConnection.java
  exist-core/src/test/java/org/exist/backup/RestoreAppsTest.java
Labels: bug, enhancement

#3290 fn:parse-xml-fragment should return a document-node()
  exist-core/src/main/java/org/exist/xquery/functions/fn/ParsingFunctions.java
  exist-core/src/test/xquery/xquery3/parse-xml.xq
Labels: bug

#3286 fn:concat requires an arity of at least two when making a function reference
  exist-core/src/main/java/org/exist/xquery/NamedFunctionReference.java
  exist-core/src/test/xquery/xquery3/fnRefs.xql
Labels: bug

#3285 With fn:unparsed-text#1 non-dba users should only be restricted from filesystem
  exist-core/src/main/java/org/exist/xquery/functions/fn/FunUnparsedText.java
Labels: bug

#3282 Fix restoring folder backups on Windows via XML:RPC
  exist-core/src/main/java/org/exist/util/FileUtils.java
  exist-core/src/main/java/org/exist/xmldb/RemoteRestoreService.java
  exist-core/src/test/java/org/exist/backup/XMLDBRestoreTest.java
Labels: bug, regression

#3283 Fix some small Windows Service issues
  exist-core/src/main/java/org/exist/launcher/ConfigurationDialog.java
  exist-core/src/main/java/org/exist/launcher/ConfigurationUtility.java
  exist-core/src/main/java/org/exist/launcher/Launcher.java
  exist-core/src/main/java/org/exist/launcher/LauncherWrapper.java
  exist-core/src/main/java/org/exist/launcher/WindowsServiceManager.java
Labels: bug

#3287 Fix some issues with document-node type checks
  exist-core/src/main/java/org/exist/dom/persistent/NodeProxy.java
  exist-core/src/main/java/org/exist/xquery/InstanceOfExpression.java
  exist-core/src/main/java/org/exist/xquery/LetExpr.java
  exist-core/src/main/java/org/exist/xquery/VariableImpl.java
  exist-core/src/main/java/org/exist/xquery/value/SequenceType.java
  exist-core/src/test/xquery/document-nodes.xq
Labels: bug

#3288 Docker HEALTHCHECK should use `guest` account not `admin`
  exist-docker/src/main/resources-filtered/Dockerfile
Labels: docker, enhancement

#3291 Switch to nonblocking free ids processing algorithms
  exist-core/src/main/java/org/exist/storage/index/CollectionStore.java
Labels: enhancement

#3159 (4.x.x) Add a test to assert the integrity of installer/jobs.xml
  exist-core/src/test/java/org/exist/installer/JobsXmlConfigurationTest.java
Labels: needs develop port

#3292 boolean-sequences.xql Test was in the wrong location
  exist-core/src/test/xquery/boolean-sequences.xq
Labels: bug

#3298 Update Jing and switch to official artifact
  exist-core/pom.xml
Labels: enhancement

#3297 Ensure Inspect Module functions throws errors appropriately
  exist-core/src/main/java/org/exist/interpreter/Context.java
  exist-core/src/main/java/org/exist/repo/ExistRepository.java
  exist-core/src/main/java/org/exist/xquery/ErrorCodes.java
  exist-core/src/main/java/org/exist/xquery/XQueryContext.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/LoadXQueryModule.java
  exist-core/src/main/java/org/exist/xquery/functions/inspect/InspectionModule.java
  exist-core/src/main/java/org/exist/xquery/functions/inspect/ModuleFunctions.java
  exist-core/src/main/java/org/exist/xquery/value/AnyURIValue.java
Labels: bug

#3303 Refactor system:export
  exist-core/src/main/java/org/exist/xquery/functions/system/FnExport.java
Labels: enhancement

#3302 Take the XQJ API dependency from Maven Central
  exist-core/pom.xml
Labels: enhancement

#3306 Add missing test names
  exist-core/src/test/xquery/xquery3/forwhere.xml
Labels: enhancement

#3317 Fix the UTF8 decoding of Node Values
  exist-core/src/main/java/org/exist/dom/persistent/NodeProxy.java
  exist-core/src/main/java/org/exist/storage/dom/DOMFile.java
  exist-core/src/main/java/org/exist/test/runner/ExtTestErrorFunction.java
  exist-core/src/main/java/org/exist/test/runner/JUnitIntegrationFunction.java
  exist-core/src/test/xquery/unicode.xqm
Labels: bug, high prio

#3315 Don't keep the splash screen in front of everything else
  exist-core/src/main/java/org/exist/launcher/SplashScreen.java
Labels: bug

#3314 Fix renaming a Collection
  exist-core/src/main/java/org/exist/client/ClientFrame.java
  exist-core/src/main/java/org/exist/storage/NativeBroker.java
  exist-core/src/main/java/org/exist/xmldb/EXistCollectionManagementService.java
  exist-core/src/main/java/org/exist/xmldb/LocalCollectionManagementService.java
  exist-core/src/main/java/org/exist/xmldb/RemoteCollectionManagementService.java
  exist-core/src/test/java/org/exist/xmldb/DeleteCollectionTest.java
  exist-core/src/test/java/org/exist/xmldb/MoveCollectionTest.java
  exist-core/src/test/java/org/exist/xmldb/RenameCollectionTest.java
Labels: bug, regression

#3320 Make builds runtime compatible with Java 8 when built on JDK9+
  exist-parent/pom.xml
Labels: enhancement

#3325 Fix polluted context when dynamically compiling query
  exist-core/src/main/java/org/exist/xquery/FunctionFactory.java
  exist-core/src/main/java/org/exist/xquery/functions/util/Compile.java
  exist-core/src/test/xquery/errors.xql
Labels: regression

#1520 A more performant implementation of immutable maps
  exist-core/pom.xml
  exist-core/src/main/java/org/exist/util/serializer/AdaptiveWriter.java
  exist-core/src/main/java/org/exist/util/serializer/json/JSONSerializer.java
  exist-core/src/main/java/org/exist/xquery/Lookup.java
  exist-core/src/main/java/org/exist/xquery/XQueryContext.java
  exist-core/src/main/java/org/exist/xquery/functions/array/ArrayType.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FnRandomNumberGenerator.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FunDeepEqual.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FunSerialize.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/LoadXQueryModule.java
  exist-core/src/main/java/org/exist/xquery/functions/map/AbstractMapType.java
  exist-core/src/main/java/org/exist/xquery/functions/map/MapExpr.java
  exist-core/src/main/java/org/exist/xquery/functions/map/MapFunction.java
  exist-core/src/main/java/org/exist/xquery/functions/map/MapType.java
  exist-core/src/main/java/org/exist/xquery/functions/map/SingleKeyMapType.java
  exist-core/src/main/java/org/exist/xquery/util/SerializerUtils.java
  exist-core/src/main/java/org/exist/xquery/value/ArrayListValueSequence.java
  exist-core/src/test/xquery/maps/maps.xql
  exist-core/src/test/xquery/maps/mapsLookup.xql
  exist-core/src/test/xquery/xquery3/arrowop.xql
  exist-parent/pom.xml
  extensions/indexes/lucene/pom.xml
  extensions/indexes/lucene/src/main/java/org/exist/xquery/modules/lucene/Facets.java
  extensions/indexes/lucene/src/main/java/org/exist/xquery/modules/lucene/QueryOptions.java
  extensions/indexes/lucene/src/test/xquery/lucene/facets.xql
Labels: enhancement

#3324 Fix casting integers as union type xs:numeric
  exist-core/src/main/java/org/exist/xquery/value/IntegerValue.java
  exist-core/src/test/xquery/integers.xq
Labels: regression

#3326 Allow disabling building of the IzPack installer
  pom.xml
Labels: enhancement

#3327 Avoid an NPE when reconstructing nested stack traces
  exist-core/src/main/java/org/exist/test/runner/ExtTestErrorFunction.java
Labels: bug

#3328 Fix an issue with Java equality of DLN
  exist-core/src/main/java/org/exist/numbering/DLN.java
  exist-core/src/main/java/org/exist/numbering/DLNBase.java
  exist-core/src/main/java/org/exist/numbering/NodeId.java
  exist-core/src/main/java/org/exist/xquery/functions/util/GetFragmentBetween.java
  exist-core/src/test/xquery/util/get-fragment-between.xqm
Labels: bug

#3332 Group managers should be loaded from security database at startup
  exist-core/src/main/java/org/exist/config/Configurator.java
  exist-core/src/main/java/org/exist/security/AbstractGroup.java
  exist-core/src/main/java/org/exist/security/AbstractRealm.java
  exist-core/src/test/java/org/exist/security/AbstractSecurityManagerRoundtripTest.java
  exist-core/src/test/java/org/exist/security/LocalSecurityManagerRoundtripTest.java
  exist-core/src/test/java/org/exist/security/RemoteSecurityManagerRoundtripTest.java
Labels: bug, security
