Repository eXist-db/exist, pull requests merged in 2020-02, with the labels that each got.

#3141 [feature] Implement fn:xml-to-json()
  exist-core/src/main/java/org/exist/xquery/ErrorCodes.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FnModule.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FunXmlToJson.java
  exist-core/src/test/xquery/xquery3/xml-to-json.xql
Labels: needs documentation

#3072 [bugfix] spec compliant random-number-generator
  exist-core/src/main/java/org/exist/xquery/functions/fn/FnRandomNumberGenerator.java
  exist-core/src/test/xquery/xquery3/fnRandomNumberGenerator.xql
Labels: bug

#3248 Fix an issue with jetty closing sockets
  exist-core/src/main/java/org/exist/storage/BrokerPool.java
  exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty-bytebufferpool.xml
  exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty-gzip.xml
  exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty-http.xml
  exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty-https.xml
  exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty-jaas.xml
  exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty-jmx.xml
  exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty-plus.xml
  exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty-requestlog.xml
  exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty-ssl-context.xml
  exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty-ssl.xml
  exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty-threadpool.xml
  exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty.xml
  exist-jetty-config/src/main/resources/org/exist/jetty/etc/standalone-jetty-http.xml
  exist-jetty-config/src/main/resources/org/exist/jetty/etc/standalone-jetty-ssl.xml
  exist-jetty-config/src/main/resources/org/exist/jetty/etc/standalone-jetty.xml
  exist-jetty-config/src/main/resources/org/exist/jetty/etc/standalone.enabled-jetty-configs
  exist-jetty-config/src/main/resources/org/exist/jetty/etc/standard.enabled-jetty-configs
  exist-jetty-config/src/main/resources/org/exist/jetty/etc/webdefault.xml
  extensions/modules/xslfo/pom.xml
Labels: bug, in progress

#3249 Fix the cardinality of fn:random-number-generator#1
  exist-core/src/main/java/org/exist/xquery/functions/fn/FnRandomNumberGenerator.java
Labels: bug
