Repository eXist-db/exist, pull requests merged in 2020-11, with the labels that each got.

#3603 Enable conf.xml option document/@use-path-locks
  exist-core/src/main/java/org/exist/util/Configuration.java
Labels: bug

#3588 [feature] Add a parameter to util:eval to preserve the original erro…
  exist-core/pom.xml
  exist-core/src/main/java/org/exist/xquery/functions/util/Eval.java
  exist-core/src/main/java/org/exist/xquery/functions/util/UtilModule.java
  exist-core/src/test/java/org/exist/xquery/functions/fn/DocTest.java
  exist-core/src/test/java/org/exist/xquery/functions/util/EvalTest.java
Labels: bug

#3604 REST API should not always complain about aborted transactions
  exist-core/src/main/java/org/exist/http/servlets/EXistServlet.java
  exist-core/src/main/java/org/exist/storage/NativeBroker.java
Labels: bug

#3597 Feature/add missing fn trace
  exist-core/src/main/java/org/exist/xquery/functions/fn/FnModule.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FunTrace.java
  exist-core/src/test/xquery/trace.xql
Labels: enhancement, xquery

#3612 Avoid IllegalStateException in Http Session functions
  exist-core/pom.xml
  exist-core/src/main/java/org/exist/http/servlets/HttpRequestWrapper.java
  exist-core/src/main/java/org/exist/http/servlets/HttpResponseWrapper.java
  exist-core/src/main/java/org/exist/http/servlets/HttpSessionWrapper.java
  exist-core/src/main/java/org/exist/http/servlets/RequestWrapper.java
  exist-core/src/main/java/org/exist/http/servlets/ResponseWrapper.java
  exist-core/src/main/java/org/exist/http/servlets/SessionWrapper.java
  exist-core/src/main/java/org/exist/xquery/XQueryContext.java
  exist-core/src/main/java/org/exist/xquery/functions/session/Clear.java
  exist-core/src/main/java/org/exist/xquery/functions/session/Create.java
  exist-core/src/main/java/org/exist/xquery/functions/session/GetAttribute.java
  exist-core/src/main/java/org/exist/xquery/functions/session/GetAttributeNames.java
  exist-core/src/main/java/org/exist/xquery/functions/session/GetCreationTime.java
  exist-core/src/main/java/org/exist/xquery/functions/session/GetID.java
  exist-core/src/main/java/org/exist/xquery/functions/session/GetLastAccessedTime.java
  exist-core/src/main/java/org/exist/xquery/functions/session/GetMaxInactiveInterval.java
  exist-core/src/main/java/org/exist/xquery/functions/session/Invalidate.java
  exist-core/src/main/java/org/exist/xquery/functions/session/RemoveAttribute.java
  exist-core/src/main/java/org/exist/xquery/functions/session/SessionFunction.java
  exist-core/src/main/java/org/exist/xquery/functions/session/SetAttribute.java
  exist-core/src/main/java/org/exist/xquery/functions/session/SetCurrentUser.java
  exist-core/src/main/java/org/exist/xquery/functions/session/SetMaxInactiveInterval.java
  exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBAuthenticate.java
  exist-core/src/test/java/org/exist/xquery/functions/session/AbstractSessionTest.java
  exist-core/src/test/java/org/exist/xquery/functions/session/AttributeTest.java
  exist-core/src/test/java/org/exist/xquery/functions/xmldb/AbstractXMLDBTest.java
  exist-core/src/test/java/org/exist/xquery/functions/xmldb/XMLDBAuthenticateTest.java
Labels: bug

#3613 Log a warning if a collection.xconf is binary
  exist-core/src/main/java/org/exist/client/CollectionXConf.java
  exist-core/src/main/java/org/exist/collections/CollectionConfigurationManager.java
  exist-core/src/main/java/org/exist/dom/persistent/DocumentImpl.java
  exist-core/src/main/java/org/exist/storage/NativeBroker.java
  exist-core/src/test/java/org/exist/collections/triggers/TriggerConfigTest.java
  exist-core/src/test/java/org/exist/validation/CollectionConfigurationTest.java
  exist-core/src/test/java/org/exist/validation/CollectionConfigurationValidationModeTest.java
  exist-core/src/test/java/org/exist/xmldb/CollectionConfigurationTest.java
  exist-core/src/test/java/org/exist/xquery/UnionTest.java
  exist-core/src/test/java/org/exist/xquery/functions/validate/JaxpDtdCatalogTest.java
  exist-core/src/test/java/org/exist/xquery/functions/validate/JaxpParseTest.java
  exist-core/src/test/java/org/exist/xquery/functions/validate/JaxpXsdCatalogTest.java
  exist-core/src/test/java/org/exist/xquery/functions/validate/JaxvTest.java
  exist-core/src/test/java/org/exist/xquery/functions/validate/JingRelaxNgTest.java
  exist-core/src/test/java/org/exist/xquery/functions/validate/JingSchematronTest.java
  exist-core/src/test/java/org/exist/xquery/functions/validate/JingXsdTest.java
  exist-core/src/test/java/org/exist/xquery/functions/validate/ParseDtdTestNOK.java
  exist-core/src/test/java/org/exist/xquery/functions/validate/ParseXsdTestNOK.java
  extensions/indexes/range/src/test/java/org/exist/indexing/range/RangeIndexConfigTest.java
  extensions/modules/expathrepo/src/test/java/org/exist/repo/PackageTriggerTest.java
Labels: enhancement

#3621 Remove code which duplicates Commons IO
  extensions/webdav/src/main/java/org/exist/webdav/ByteCountOutputStream.java
  extensions/webdav/src/main/java/org/exist/webdav/MiltonDocument.java
Labels: enhancement

#3622 Fix NPE and Deadlock when Path Locks are used for Documents
  exist-core/src/main/java/org/exist/storage/NativeBroker.java
  exist-core/src/main/java/org/exist/storage/lock/LockManager.java
  exist-core/src/main/java/org/exist/xmlrpc/RpcConnection.java
  exist-core/src/test/java/org/exist/collections/CollectionRemovalTest.java
  exist-core/src/test/java/org/exist/collections/triggers/HistoryTriggerTest.java
  exist-core/src/test/java/org/exist/config/TwoDatabasesTest.java
  exist-core/src/test/java/org/exist/util/XMLReaderSecurityTest.java
  exist-core/src/test/java/org/exist/xquery/functions/securitymanager/PermissionsFunctionChownTest.java
  exist-core/src/test/resources-filtered/conf.xml
  exist-core/src/test/resources-filtered/org/exist/storage/statistics/conf.xml
  exist-core/src/test/resources-filtered/org/exist/xquery/functions/transform/conf.xml
  extensions/indexes/lucene/src/test/resources-filtered/conf.xml
  extensions/indexes/ngram/src/test/resources-filtered/conf.xml
  extensions/indexes/range/src/test/resources-filtered/conf.xml
  extensions/indexes/sort/src/test/resources-filtered/conf.xml
  extensions/indexes/spatial/src/test/resources-filtered/conf.xml
Labels: bug

#3496 allow function types in context item
  exist-core/src/main/antlr/org/exist/xquery/parser/XQuery.g
  exist-core/src/main/antlr/org/exist/xquery/parser/XQueryTree.g
  exist-core/src/main/java/org/exist/xquery/ContextItemExpression.java
  exist-core/src/main/java/org/exist/xquery/ValueComparison.java
  exist-core/src/test/xquery/xquery3/bang.xql
  exist-core/src/test/xquery/xquery3/filter-function-items-in-context.xql
Labels: bug, parser, xquery
