Repository eXist-db/exist, pull requests merged in 2020-04, with the labels that each got.

#3335 [Feature] Add memory and nr of processors information to startup log.
  exist-core/src/main/java/org/exist/jetty/JettyStart.java
  exist-core/src/main/java/org/exist/util/FileUtils.java
Labels: enhancement

#3350 Fix util:get-resource-by-absolute-id
  exist-core/src/main/java/org/exist/storage/NativeBroker.java
  exist-core/src/main/java/org/exist/xquery/functions/util/DocumentNameOrId.java
  exist-core/src/main/java/org/exist/xquery/functions/util/UtilModule.java
  exist-core/src/main/java/org/exist/xquery/value/Sequence.java
  exist-core/src/main/java/org/exist/xquery/value/ValueSequence.java
  exist-core/src/test/xquery/util/document-id.xqm
Labels: bug

#3351 Remove system.out message for debugging
  exist-core/src/main/java/org/exist/client/DocumentView.java
Labels: enhancement

#3348 Fix bounds issues with group separators in fn:format-number
  exist-core/src/main/java/org/exist/xquery/functions/fn/FnFormatNumbers.java
  exist-core/src/test/xquery/numbers/format-numbers.xql
Labels: bug, xquery

#3349 fn:collection should only return XML documents
  exist-core/src/main/java/org/exist/xquery/functions/fn/ExtCollection.java
Labels: bug, xquery

#3355 Context Item should not be atomized when used as argument for fn:string-length
  exist-core/src/main/java/org/exist/xquery/Function.java
  exist-core/src/main/java/org/exist/xquery/PathExpr.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FunHigherOrderFun.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FunReverse.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FunStrLength.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FunSubSequence.java
  exist-core/src/test/xquery/xquery3/bang.xql
Labels: bug, xquery

#3354 Prohibit duplicate function declarations
  exist-core/src/main/java/org/exist/dom/QName.java
  exist-core/src/main/java/org/exist/interpreter/Context.java
  exist-core/src/main/java/org/exist/xquery/FunctionId.java
  exist-core/src/main/java/org/exist/xquery/XQueryContext.java
  exist-core/src/test/xquery/last.xql
  exist-core/src/test/xquery/unparsed-text.xql
  exist-core/src/test/xquery/xquery3/arrowop.xql
  exist-core/src/test/xquery/xquery3/fnSort.xql
  exist-core/src/test/xquery/xquery3/serialize.xql
  extensions/indexes/lucene/src/test/xquery/lucene/facets.xql
  extensions/indexes/range/src/test/xquery/range/conditions.xql
  extensions/indexes/range/src/test/xquery/range/types.xql
Labels: bug, xquery

#3359 Small Travis config improvements
  .travis.yml
Labels: enhancement, in progress

#3368 Improve XQuery test naming
  exist-core/src/main/java/org/exist/test/runner/XMLTestRunner.java
  exist-core/src/main/java/org/exist/test/runner/XQueryTestRunner.java
  exist-core/src/main/resources/org/exist/xquery/lib/test.xq
  extensions/indexes/range/src/test/xquery/range/field-type.xql
Labels: enhancement

#3353 Avoid IndexOutOfBounds when selecting combo box items in JAC
  exist-core/src/main/java/org/exist/client/QueryDialog.java
Labels: bug

#3379 Update collection.xconf.xsd for eXist 5
  schema/collection.xconf.xsd
Labels: enhancement

#3377 Fix an NPE with Security Context in dynamically loaded modules
  exist-core/src/main/java/org/exist/test/runner/ExtTestErrorFunction.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/LoadXQueryModule.java
  exist-core/src/main/java/org/exist/xquery/functions/inspect/ModuleFunctions.java
  exist-core/src/test/java/xquery/securitymanager/SecurityManagerTests.java
  exist-core/src/test/xquery/securitymanager/id.xqm
Labels: bug

#3386 Offer further build profiles
  exist-distribution/pom.xml
  pom.xml
Labels: enhancement
