Repository eXist-db/exist, pull requests merged in 2020-12, with the labels that each got.

#3643 Fix compilation issue with JAXB dependencies on JDK 11+
  exist-core/pom.xml
  exist-core/src/main/java/org/exist/http/jaxb/Collection.java
  exist-core/src/main/java/org/exist/http/jaxb/ObjectFactory.java
  exist-core/src/main/java/org/exist/http/jaxb/Query.java
  exist-core/src/main/java/org/exist/http/jaxb/Result.java
  exist-core/src/main/java/org/exist/http/jaxb/Sequence.java
  exist-core/src/main/java/org/exist/http/jaxb/YesNo.java
  exist-core/src/main/java/org/exist/http/jaxb/package-info.java
  exist-core/src/main/xjb/rest-api.xjb
  exist-core/src/main/xsd/rest-api.xsd
  exist-core/src/main/xsd/rest-serialized-sequence.xsd
  exist-core/src/test/java/org/exist/xquery/RestBinariesTest.java
  exist-parent/pom.xml
  extensions/modules/file/pom.xml
  extensions/modules/file/src/test/java/org/exist/xquery/modules/file/RestBinariesTest.java
  schema/rest-serialized-sequence.xsd
Labels: bug, enhancement

#3605 Fix root node handling and implicit context in functions
  exist-core/pom.xml
  exist-core/src/main/antlr/org/exist/xquery/parser/XQuery.g
  exist-core/src/main/java/org/exist/test/DiffMatcher.java
  exist-core/src/main/java/org/exist/test/XQueryAssertions.java
  exist-core/src/main/java/org/exist/test/XQueryCompilationTest.java
  exist-core/src/main/java/org/exist/xquery/RootNode.java
  exist-core/src/main/java/org/exist/xquery/UserDefinedFunction.java
  exist-core/src/test/java/org/exist/xquery/AbsolutePathTests.java
  exist-core/src/test/java/org/exist/xquery/DeferredFunctionCallTest.java
  exist-core/src/test/java/org/exist/xquery/UnknownAtomicTypeTest.java
  exist-core/src/test/xquery/xquery3/bang.xql
  exist-parent/pom.xml
  extensions/indexes/lucene/src/main/java/org/exist/xquery/modules/lucene/Query.java
  extensions/indexes/range/src/test/xquery/range/optimizer.xql
  extensions/indexes/range/src/test/xquery/range/range.xql
Labels: parser, xquery

#3648 Preserve original error message when using util:eval
  exist-core/src/main/resources/org/exist/xquery/lib/test.xq
  exist-core/src/main/resources/org/exist/xquery/lib/xqsuite/xqsuite.xql
Labels: bug

#3529 Make sure the correct context sequence is used with util:eval-with-context
  exist-core/src/main/java/org/exist/xquery/RootNode.java
  exist-core/src/test/java/org/exist/storage/ShutdownTest.java
  exist-core/src/test/xquery/util/eval-with-context.xql
Labels: bug

#3550 [hotfix] add location info to element content errors
  exist-core/src/main/antlr/org/exist/xquery/parser/XQuery.g
  exist-core/src/main/antlr/org/exist/xquery/parser/XQueryTree.g
  exist-core/src/main/java/org/exist/xquery/EnclosedExpr.java
  exist-core/src/main/java/org/exist/xquery/SequenceConstructor.java
  exist-core/src/test/java/org/exist/xquery/FunctionTypeInElementContentTest.java
  exist-core/src/test/xquery/errors.xql
Labels: parser, xquery

#3670 [fix] basic authentication
  exist-core/src/main/java/org/exist/http/servlets/BasicAuthenticator.java
Labels: bug

#3671 Concept: Make servlets pluggable
  exist-core/src/main/java/org/exist/http/servlets/ExistExtensionServlet.java
  exist-core/src/main/java/org/exist/jetty/JettyStart.java
  extensions/security/iprange/pom.xml
  extensions/security/iprange/src/main/java/org/exist/security/realm/iprange/IPRangeServlet.java
  extensions/security/iprange/src/main/resources/META-INF/services/org.exist.http.servlets.ExistExtensionServlet
Labels: enhancement
