Repository eXist-db/exist, pull requests merged in 2020-10, with the labels that each got.

#3567 Proposed fix for NPE with empty case expression. Fixes 3560
  exist-core/src/main/java/org/exist/xquery/SwitchExpression.java
  exist-core/src/test/xquery/xquery3/xq3_switch.xml
Labels: bug

#3570 Fix QName comparison Namepool.
  exist-core/src/main/java/org/exist/util/hashtable/NamePool.java
  exist-core/src/test/java/org/exist/util/hashtable/NamePoolTest.java
Labels: bug

#3571 [refactor]: more improvements
  exist-core/src/main/java/org/exist/collections/CollectionConfigurationManager.java
  exist-core/src/main/java/org/exist/collections/CollectionURI.java
  exist-core/src/main/java/org/exist/collections/MutableCollection.java
  exist-core/src/main/java/org/exist/collections/triggers/CSVExtractingTrigger.java
  exist-core/src/main/java/org/exist/collections/triggers/CollectionTrigger.java
  exist-core/src/main/java/org/exist/collections/triggers/CollectionTriggerProxy.java
  exist-core/src/main/java/org/exist/collections/triggers/CollectionTriggersVisitor.java
  exist-core/src/main/java/org/exist/collections/triggers/DocumentTrigger.java
  exist-core/src/main/java/org/exist/collections/triggers/STXTemplatesCache.java
  exist-core/src/main/java/org/exist/collections/triggers/Trigger.java
  exist-core/src/main/java/org/exist/collections/triggers/TriggerEvents.java
  exist-core/src/main/java/org/exist/collections/triggers/TriggerProxies.java
  exist-core/src/main/java/org/exist/collections/triggers/TriggersVisitor.java
  exist-core/src/main/java/org/exist/collections/triggers/XQueryTrigger.java
  exist-core/src/main/java/org/exist/numbering/DLNBase.java
  exist-core/src/main/java/org/exist/numbering/DLNFactory.java
  exist-core/src/main/java/org/exist/numbering/NodeId.java
  exist-core/src/main/java/org/exist/security/AbstractAccount.java
  exist-core/src/main/java/org/exist/security/AbstractPrincipal.java
  exist-core/src/main/java/org/exist/security/AbstractRealm.java
  exist-core/src/main/java/org/exist/security/AbstractUnixStylePermission.java
  exist-core/src/main/java/org/exist/security/Account.java
  exist-core/src/main/java/org/exist/security/Credential.java
  exist-core/src/main/java/org/exist/security/Group.java
  exist-core/src/main/java/org/exist/security/Principal.java
  exist-core/src/main/java/org/exist/security/SchemaType.java
  exist-core/src/main/java/org/exist/security/SimpleACLPermission.java
  exist-core/src/main/java/org/exist/security/Subject.java
  exist-core/src/main/java/org/exist/security/UnixStylePermission.java
  exist-core/src/main/java/org/exist/security/User.java
  exist-core/src/main/java/org/exist/security/XmldbPrincipal.java
  exist-core/src/main/java/org/exist/security/internal/AccountImpl.java
  exist-core/src/main/java/org/exist/security/internal/EXistDBLoginModule.java
  exist-core/src/main/java/org/exist/security/internal/Password.java
  exist-core/src/main/java/org/exist/security/internal/SMEvents.java
  exist-core/src/main/java/org/exist/security/internal/aider/SimpleACLPermissionAider.java
  exist-core/src/main/java/org/exist/security/internal/aider/UnixStylePermissionAider.java
  exist-core/src/main/java/org/exist/security/internal/aider/UserAider.java
  exist-core/src/main/java/org/exist/storage/BackupSystemTask.java
  exist-core/src/main/java/org/exist/storage/BrokerPool.java
  exist-core/src/main/java/org/exist/storage/ContentLoadingObserver.java
  exist-core/src/main/java/org/exist/storage/DBBroker.java
  exist-core/src/main/java/org/exist/storage/IndexSpec.java
  exist-core/src/main/java/org/exist/storage/NativeValueIndex.java
  exist-core/src/main/java/org/exist/storage/SystemTaskManager.java
  exist-core/src/main/java/org/exist/storage/ValueIndexFactory.java
  exist-core/src/main/java/org/exist/storage/btree/BTree.java
  exist-core/src/main/java/org/exist/storage/dom/DOMFile.java
  exist-core/src/main/java/org/exist/storage/dom/DOMTransaction.java
  exist-core/src/main/java/org/exist/storage/index/BFile.java
  exist-core/src/main/java/org/exist/storage/index/FreeList.java
  exist-core/src/main/java/org/exist/storage/serializers/Serializer.java
  exist-core/src/main/java/org/exist/storage/structural/NativeStructuralIndexWorker.java
  exist-core/src/main/java/org/exist/storage/txn/Txn.java
  exist-core/src/main/java/org/exist/xupdate/Modification.java
  exist-core/src/main/java/org/exist/xupdate/Remove.java
  exist-core/src/main/java/org/exist/xupdate/XUpdateProcessor.java
Labels: enhancement

#3566 Bugfix: make sure 0 byte sized binary resources can be included in ZiPfile
  extensions/modules/compression/src/main/java/org/exist/xquery/modules/compression/AbstractCompressFunction.java
  extensions/modules/compression/src/test/xquery/modules/compression/zip-tests.xql
Labels: bug

#3574 Integration tests for SQL Module Connection Functions
  exist-core/pom.xml
  exist-core/src/main/java/org/exist/xquery/modules/ModuleUtils.java
  exist-parent/FDB-backport-LGPL-21-ONLY-license.template.txt
  exist-parent/pom.xml
  extensions/modules/sql/pom.xml
  extensions/modules/sql/src/test/java/org/exist/xquery/modules/sql/ConnectionIT.java
  extensions/modules/sql/src/test/java/org/exist/xquery/modules/sql/H2DatabaseResource.java
  extensions/modules/sql/src/test/java/org/exist/xquery/modules/sql/JndiConnectionIT.java
  extensions/modules/sql/src/test/resources-filtered/conf.xml
  extensions/modules/sql/src/test/resources/jndi.properties
  extensions/modules/sql/src/test/resources/log4j2.xml
Labels: enhancement

#3576 Fix an NPE in XQuery Update Replace
  exist-core/src/main/java/org/exist/dom/persistent/ElementImpl.java
  exist-core/src/main/java/org/exist/storage/NodePath.java
  exist-core/src/main/java/org/exist/storage/NodePath2.java
  exist-core/src/test/java/org/exist/storage/NodePathTest.java
  exist-core/src/test/java/org/exist/xquery/update/AbstractTestUpdate.java
  exist-core/src/test/java/org/exist/xquery/update/UpdateReplaceTest.java
  exist-core/src/test/java/org/exist/xquery/update/UpdateValueTest.java
  extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/NodePathPattern.java
Labels: bug

#3579 Improve Module Source
  exist-core/src/main/java/org/exist/management/impl/RunningQuery.java
  exist-core/src/main/java/org/exist/source/AbstractSource.java
  exist-core/src/main/java/org/exist/source/BinarySource.java
  exist-core/src/main/java/org/exist/source/ClassLoaderSource.java
  exist-core/src/main/java/org/exist/source/DBSource.java
  exist-core/src/main/java/org/exist/source/FileSource.java
  exist-core/src/main/java/org/exist/source/Source.java
  exist-core/src/main/java/org/exist/source/StringSource.java
  exist-core/src/main/java/org/exist/source/StringSourceWithMapKey.java
  exist-core/src/main/java/org/exist/source/URLSource.java
  exist-core/src/main/java/org/exist/storage/ProcessMonitor.java
  exist-core/src/main/java/org/exist/storage/XQueryPool.java
  exist-core/src/main/java/org/exist/test/runner/AbstractTestRunner.java
  exist-core/src/main/java/org/exist/util/FileUtils.java
  exist-core/src/main/java/org/exist/xquery/FunctionFactory.java
  exist-core/src/main/java/org/exist/xquery/ModuleContext.java
  exist-core/src/main/java/org/exist/xquery/Profiler.java
  exist-core/src/main/java/org/exist/xquery/TryCatchExpression.java
  exist-core/src/main/java/org/exist/xquery/VariableDeclaration.java
  exist-core/src/main/java/org/exist/xquery/VariableReference.java
  exist-core/src/main/java/org/exist/xquery/XPathException.java
  exist-core/src/main/java/org/exist/xquery/functions/system/GetRunningXQueries.java
  exist-core/src/main/java/org/exist/xquery/functions/util/Eval.java
  exist-core/src/main/java/org/exist/xquery/functions/util/LogFunction.java
  exist-core/src/main/java/org/exist/xquery/functions/util/ModuleInfo.java
  exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBAuthenticate.java
  exist-core/src/test/java/org/exist/source/SourceFactoryTest.java
  exist-core/src/test/java/org/exist/xquery/StoredModuleTest.java
  exist-core/src/test/xquery/xquery3/xq3_trycatch.xml
  extensions/exquery/restxq/src/main/java/org/exist/extensions/exquery/restxq/impl/XQueryCompiler.java
  extensions/exquery/restxq/src/main/java/org/exist/extensions/exquery/restxq/impl/XQueryInspector.java
Labels: bug, enhancement

#3546 line and column numbers in unknown-atomic-type errors
  exist-core/src/main/antlr/org/exist/xquery/parser/XQuery.g
  exist-core/src/main/antlr/org/exist/xquery/parser/XQueryTree.g
  exist-core/src/test/java/org/exist/xquery/UnknownAtomicTypeTest.java
Labels: parser, xquery

#3530 fn:replace and fn:analyze-string are now implemented with Saxon
  exist-core/src/main/java/org/exist/storage/BrokerPool.java
  exist-core/src/main/java/org/exist/storage/RegexMatcher.java
  exist-core/src/main/java/org/exist/util/PatternFactory.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FunAnalyzeString.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FunReplace.java
  exist-core/src/main/java/org/exist/xquery/regex/RegexUtil.java
  exist-core/src/test/xquery/regex.xml
  exist-core/src/test/xquery/xquery3/forwhere.xml
Labels: bug, discuss, enhancement
