Repository eXist-db/exist, pull requests merged in 2020-01, with the labels that each got.

#3200 Make sure to log at the correct level
  exist-core/src/main/java/org/exist/xquery/PathExpr.java
Labels: bug

#3201 Make sure to create the stats index before writing if it does not exist
  exist-core/src/main/java/org/exist/storage/statistics/IndexStatistics.java
  exist-core/src/test/java/org/exist/storage/statistics/StatisticsIndexTest.java
  exist-core/src/test/resources-filtered/org/exist/storage/statistics/conf.xml
Labels: bug

#3171 Memory leak on shutdown
  exist-core/src/main/java/org/exist/management/AgentFactory.java
  exist-core/src/main/java/org/exist/management/impl/JMXAgent.java
  exist-core/src/main/java/org/exist/storage/BrokerPool.java
  exist-core/src/main/java/org/exist/storage/BrokerPoolServicesManager.java
  exist-core/src/main/java/org/exist/storage/ContentLoadingObserver.java
  exist-core/src/main/java/org/exist/storage/DefaultCacheManager.java
  exist-core/src/main/java/org/exist/storage/NativeBroker.java
  exist-core/src/main/java/org/exist/storage/NativeValueIndex.java
  exist-core/src/main/java/org/exist/storage/btree/BTree.java
  exist-core/src/main/java/org/exist/storage/btree/Paged.java
  exist-core/src/main/java/org/exist/storage/dom/DOMFile.java
  exist-core/src/main/java/org/exist/storage/index/BFile.java
  exist-core/src/main/java/org/exist/util/Lockable.java
Labels: bug

#3172 (4.x.x) Memory leak on shutdown
  exist-core/src/main/java/org/exist/management/AgentFactory.java
  exist-core/src/main/java/org/exist/management/impl/JMXAgent.java
  exist-core/src/main/java/org/exist/storage/BrokerPool.java
  exist-core/src/main/java/org/exist/storage/BrokerPoolServicesManager.java
  exist-core/src/main/java/org/exist/storage/ContentLoadingObserver.java
  exist-core/src/main/java/org/exist/storage/DefaultCacheManager.java
  exist-core/src/main/java/org/exist/storage/NativeBroker.java
  exist-core/src/main/java/org/exist/storage/NativeValueIndex.java
  exist-core/src/main/java/org/exist/storage/btree/BTree.java
  exist-core/src/main/java/org/exist/storage/btree/Paged.java
  exist-core/src/main/java/org/exist/storage/dom/DOMFile.java
  exist-core/src/main/java/org/exist/storage/index/BFile.java
  exist-core/src/main/java/org/exist/util/Lockable.java
Labels: bug

#3199 Fix cast exception in fn:subsequence
  exist-core/src/main/java/org/exist/xquery/value/SubSequence.java
  exist-core/src/test/xquery/subsequence.xq
Labels: bug

#3186 FastStringBuffer improvement
  exist-core/src/main/java/org/exist/util/FastStringBuffer.java
  exist-core/src/main/java/org/exist/xquery/value/DayTimeDurationValue.java
  exist-core/src/main/java/org/exist/xquery/value/DoubleValue.java
  exist-core/src/main/java/org/exist/xquery/value/FloatValue.java
  exist-core/src/test/java/org/exist/util/FastStringBufferTest.java
Labels: enhancement

#3206 Fix contentextraction on 5.x.x
  extensions/contentextraction/pom.xml
  extensions/contentextraction/src/test/java/xquery/contentextraction/ContentExtractionTests.java
  extensions/contentextraction/src/test/resources-filtered/conf.xml
  extensions/contentextraction/src/test/resources/log4j2.xml
  extensions/contentextraction/src/test/xquery/contentextraction/content-extraction.xq
Labels: bug

#3208 Option to make Document locks hierarchical
  exist-core/src/main/java/org/exist/storage/lock/LockManager.java
  exist-core/src/main/java/org/exist/storage/lock/ManagedDocumentLock.java
  exist-core/src/main/java/org/exist/util/Configuration.java
  exist-core/src/test/java/org/exist/storage/lock/GetXMLResourceNoLockTest.java
  exist-core/src/test/java/org/exist/storage/lock/LockManagerTest.java
  exist-distribution/src/main/config/conf.xml
Labels: enhancement

#3219 Fix a concurrency issue in WeakLazyStripes
  exist-core/src/main/java/org/exist/util/WeakLazyStripes.java
Labels: bug

#3182 Multi-valued hierarchical facets
  extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/LuceneFacetConfig.java
  extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/LuceneIndexWorker.java
  extensions/indexes/lucene/src/main/java/org/exist/xquery/modules/lucene/QueryOptions.java
  extensions/indexes/lucene/src/test/resources-filtered/conf.xml
  extensions/indexes/lucene/src/test/xquery/lucene/facets.xql
Labels: enhancement

#3222 Fix broken javadoc
  exist-core/src/main/java/org/exist/xmldb/RemoteXMLResource.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/JSON.java
Labels: bug

#3223 Pass args to release plugin
  exist-versioning-release.md
Labels: bug

#3226 fix(travis): deploy on tagged builds
  .travis.yml
Labels: docker
