Repository eXist-db/exist, pull requests merged in 2021-03, with the labels that each got.

#3751 Improve CI in GitHub Actions
  .github/workflows/build.yml
  .github/workflows/ci.yml
  .travis.yml
  README.md
  exist-core/src/main/java/org/exist/http/jaxb/Collection.java
  exist-core/src/main/java/org/exist/http/jaxb/ObjectFactory.java
  exist-core/src/main/java/org/exist/http/jaxb/Query.java
  exist-core/src/main/java/org/exist/http/jaxb/Result.java
  exist-core/src/main/java/org/exist/http/jaxb/Sequence.java
  exist-core/src/main/java/org/exist/http/servlets/RequestWrapper.java
  exist-core/src/main/java/org/exist/http/servlets/ResponseWrapper.java
  exist-core/src/main/java/org/exist/http/servlets/SessionWrapper.java
  exist-core/src/main/java/org/exist/source/Source.java
  exist-core/src/main/java/org/exist/storage/io/VariableByteOutputStream.java
  exist-core/src/main/java/org/exist/xquery/XQueryContext.java
Labels: ci

#3755 Fix typo in CI config
  .github/workflows/ci.yml
Labels: bug

#3664 Fix GitHub Actions for SonarCloud
  .github/workflows/sonarcloud.yml
  exist-core/src/main/java/org/exist/xquery/functions/inspect/InspectFunction.java
  exist-core/src/main/java/org/exist/xquery/functions/inspect/InspectModule.java
  exist-core/src/main/java/org/exist/xquery/functions/inspect/ModuleFunctions.java
  exist-parent/pom.xml
Labels: ci

#3774 Fix a regression in finding the roots of the type hierarchy
  exist-core/src/main/java/org/exist/xquery/value/Type.java
Labels: bug, regression

#3766 Make CI more manageable
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/ci-build.yml
  .github/workflows/ci-deploy.yml
  .github/workflows/ci-docs.yml
  .github/workflows/ci-test.yml
  .github/workflows/ci.yml
  exist-docker/pom.xml
  exist-docker/src/main/resources-filtered/README.md
  exist-docker/src/test/bats/01-connect-spec.bats
  exist-docker/src/test/bats/02-config-spec.bats
  exist-docker/src/test/bats/03-xquery-spec.bats
  exist-docker/src/test/bats/fixtures/dba-xq.xml
  exist-docker/src/test/bats/fixtures/repo-list.xml
Labels: ci, docker, enhancement, high prio, in progress

#3781 Tests for computed namespace constructor
  exist-core/src/main/java/org/exist/xquery/NamespaceConstructor.java
  exist-core/src/test/xquery/xquery3/computed-namespace-constructor.xql
Labels: enhancement

#3791 Fix incomplete type error reporting
  exist-core/src/main/java/org/exist/xquery/LetExpr.java
  exist-core/src/main/java/org/exist/xquery/value/SequenceType.java
  exist-core/src/test/xquery/errors.xql
Labels: enhancement
