Repository eXist-db/exist, pull requests merged in 2021-05, with the labels that each got.

#3831 Connection Pooling for SQL Module
  exist-core/pom.xml
  exist-core/src/main/java/org/exist/xquery/modules/ModuleUtils.java
  exist-distribution/src/main/config/conf.xml
  extensions/modules/sql/pom.xml
  extensions/modules/sql/src/main/java/org/exist/xquery/modules/sql/GetConnectionFunction.java
  extensions/modules/sql/src/main/java/org/exist/xquery/modules/sql/SQLModule.java
  extensions/modules/sql/src/test/java/org/exist/xquery/modules/sql/ConnectionIT.java
  extensions/modules/sql/src/test/resources-filtered/conf.xml
Labels: enhancement

#3870 [HOTFIX] Avoid unauthorised creation of collections.
  exist-core/src/main/java/org/exist/xmldb/AbstractLocal.java
Labels: bug, high prio, security

#3878 Remove object retained by inner-class via back-reference
  exist-core/src/main/java/org/exist/xquery/CastExpression.java
Labels: bug

#3877 Lazily created caches should be bounded
  exist-distribution/src/main/config/conf.xml
  extensions/modules/cache/pom.xml
  extensions/modules/cache/src/main/java/org/exist/xquery/modules/cache/CacheConfig.java
  extensions/modules/cache/src/main/java/org/exist/xquery/modules/cache/CacheFunctions.java
  extensions/modules/cache/src/main/java/org/exist/xquery/modules/cache/CacheModule.java
  extensions/modules/cache/src/test/resources-filtered/conf.xml
Labels: bug, high prio, security

#3884 Fixes for SSL
  exist-distribution/src/main/xslt/jetty-deploy.xslt
  exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty-ssl-context.xml
  exist-jetty-config/src/main/resources/org/exist/jetty/etc/keystore
  exist-jetty-config/src/main/resources/org/exist/jetty/etc/keystore.p12
Labels: bug, security

#3890 Backport of sql:close-connection from FusionDB
  exist-core/src/main/java/org/exist/xquery/modules/ModuleUtils.java
  extensions/modules/mail/src/main/java/org/exist/xquery/modules/mail/MailModule.java
  extensions/modules/sql/pom.xml
  extensions/modules/sql/src/main/java/org/exist/xquery/modules/sql/CloseConnectionFunction.java
  extensions/modules/sql/src/main/java/org/exist/xquery/modules/sql/GetConnectionFunction.java
  extensions/modules/sql/src/main/java/org/exist/xquery/modules/sql/SQLModule.java
  extensions/modules/sql/src/test/java/org/exist/xquery/modules/sql/ConnectionIT.java
  extensions/modules/sql/src/test/java/org/exist/xquery/modules/sql/ConnectionPoolIT.java
  extensions/modules/sql/src/test/java/org/exist/xquery/modules/sql/H2DatabaseResource.java
  extensions/modules/sql/src/test/java/org/exist/xquery/modules/sql/Util.java
  extensions/modules/sql/src/test/resources-filtered/conf.xml
Labels: enhancement

#3891 Specify the COVERALLS_TOKEN in the correct way for CI
  .github/workflows/ci-test.yml
Labels: bug, ci

#3908 Very Small fixes
  exist-core/src/main/java/org/exist/repo/ExistRepository.java
  extensions/modules/xmldiff/pom.xml
  extensions/modules/xmldiff/src/main/java/org/exist/xquery/modules/xmldiff/Compare.java
Labels: enhancement

#3899 [bugfix] Block creation of collection by guest #3505
  exist-core/src/main/java/org/exist/storage/NativeBroker.java
  exist-core/src/test/xquery/guest.xql
Labels: bug, enhancement, high prio

#3910 Fix arity in XQuery error when there are duplicate functions in a main module
  exist-core/src/main/java/org/exist/xquery/XQueryContext.java
  exist-core/src/test/java/org/exist/xquery/ImportModuleTest.java
Labels: bug
