Repository eXist-db/exist, pull requests merged in 2021-04, with the labels that each got.

#3807 [hotfix] repair build CQL Parser Module
  extensions/modules/cqlparser/pom.xml
Labels: high prio

#3810 Fixes corrupted stream message with maven-surefire-plugin
  exist-core/src/main/java/org/exist/management/impl/SystemInfo.java
  exist-parent/pom.xml
Labels: dependencies

#3757 Look for controller.xq before controller.xql
  exist-core/src/main/java/org/exist/http/urlrewrite/XQueryURLRewrite.java
  exist-core/src/test/java/org/exist/http/AbstractHttpTest.java
  exist-core/src/test/java/org/exist/http/urlrewrite/ControllerTest.java
  exist-core/src/test/java/org/exist/http/urlrewrite/URLRewritingTest.java
Labels: enhancement

#3813 [bugfix] reimplement fn:base-uri()
  exist-core/src/main/java/org/exist/dom/memtree/DocumentImpl.java
  exist-core/src/main/java/org/exist/dom/persistent/ElementImpl.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FnModule.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FunBaseURI.java
  exist-core/src/test/xquery/base-uri.xql
Labels: enhancement

#3782 Eliminate SequencedLongHashMap custom code
  exist-core/src/main/java/org/exist/backup/ConsistencyCheck.java
  exist-core/src/main/java/org/exist/storage/BufferStats.java
  exist-core/src/main/java/org/exist/storage/NativeBroker.java
  exist-core/src/main/java/org/exist/storage/cache/BTreeCache.java
  exist-core/src/main/java/org/exist/storage/cache/LRUCache.java
  exist-core/src/main/java/org/exist/storage/dom/DOMFile.java
  exist-core/src/main/java/org/exist/storage/dom/DOMTransaction.java
  exist-core/src/main/java/org/exist/storage/dom/NodeIterator.java
  exist-core/src/main/java/org/exist/storage/lock/LockManager.java
  exist-core/src/main/java/org/exist/util/hashtable/AbstractHashtable.java
  exist-core/src/main/java/org/exist/util/hashtable/SequencedLongHashMap.java
  exist-core/src/test/java/org/exist/util/hashtable/AbstractHashSetTest.java
  exist-core/src/test/java/org/exist/util/hashtable/AbstractHashtableTest.java
  exist-core/src/test/java/org/exist/util/hashtable/SequencedLongHashMapTest.java
Labels: enhancement

#3814 Import repo logging
  exist-core/src/main/java/org/exist/repo/AutoDeploymentTrigger.java
  exist-docker/src/main/xslt/log4j2-docker.xslt
Labels: enhancement

#3341 Add Code Coverage
  .github/workflows/ci-test.yml
  README.md
  exist-core/pom.xml
  exist-parent/pom.xml
  extensions/debuggee/pom.xml
  extensions/modules/file/pom.xml
  extensions/modules/persistentlogin/pom.xml
Labels: enhancement, high prio, in progress
