Repository eXist-db/exist, pull requests merged in 2021-02, with the labels that each got.

#3721 Remove timeout on Compiled XQuery Pool
  exist-ant/src/test/resources-filtered/conf.xml
  exist-core/src/main/java/org/exist/storage/XQueryPool.java
  exist-core/src/main/java/org/exist/util/Configuration.java
  exist-core/src/test/resources-filtered/conf.xml
  exist-core/src/test/resources-filtered/org/exist/storage/statistics/conf.xml
  exist-core/src/test/resources-filtered/org/exist/xquery/functions/transform/conf.xml
  exist-distribution/src/main/config/conf.xml
  extensions/contentextraction/src/test/resources-filtered/conf.xml
  extensions/debuggee/src/test/resources-filtered/conf.xml
  extensions/expath/src/test/resources-filtered/conf.xml
  extensions/exquery/restxq/src/test/resources-filtered/conf.xml
  extensions/indexes/lucene/src/test/resources-filtered/conf.xml
  extensions/indexes/ngram/src/test/resources-filtered/conf.xml
  extensions/indexes/range/src/test/resources-filtered/conf.xml
  extensions/indexes/sort/src/test/resources-filtered/conf.xml
  extensions/indexes/spatial/src/test/resources-filtered/conf.xml
  extensions/modules/cache/src/test/resources-filtered/conf.xml
  extensions/modules/compression/src/test/resources-filtered/conf.xml
  extensions/modules/counter/src/test/resources-filtered/conf.xml
  extensions/modules/expathrepo/src/test/resources-filtered/conf.xml
  extensions/modules/file/src/test/resources-filtered/conf.xml
  extensions/modules/persistentlogin/src/test/resources-filtered/conf.xml
  extensions/modules/sql/src/test/resources-filtered/conf.xml
  extensions/modules/xslfo/src/test/resources-filtered/conf.xml
  extensions/xqdoc/src/test/resources-filtered/conf.xml
  schema/conf.xsd
Labels: enhancement

#3731 Group membership is not correct immediately after restoring a backup
  exist-core/src/main/java/org/exist/backup/BackupDescriptor.java
  exist-core/src/main/java/org/exist/backup/BackupDirectory.java
  exist-core/src/main/java/org/exist/backup/ExportMain.java
  exist-core/src/main/java/org/exist/backup/FileSystemBackupDescriptor.java
  exist-core/src/main/java/org/exist/backup/Restore.java
  exist-core/src/main/java/org/exist/backup/ZipArchiveBackupDescriptor.java
  exist-core/src/main/java/org/exist/backup/restore/RestoreHandler.java
  exist-core/src/main/java/org/exist/security/AbstractRealm.java
  exist-core/src/main/java/org/exist/security/internal/SecurityManagerImpl.java
  exist-core/src/test/java/org/exist/backup/XMLDBRestoreTest.java
  exist-distribution/pom.xml
Labels: bug

#3743 Creates a build matrix on github actions
  .github/workflows/build.yml
Labels: ci
