Repository eXist-db/exist, pull requests merged in 2021-01, with the labels that each got.

#3692 [Bugfix] Array: extend remove() function to allow multiple deletes in one go. (XQTS)
  exist-core/src/main/java/org/exist/xquery/functions/array/ArrayFunction.java
  exist-core/src/test/xquery/arrays/arrays.xql
Labels: bug

#3691 Prevent NPEs in math:* functions. Tested in XQTS suite
  exist-core/src/main/java/org/exist/xquery/functions/math/NoParamFunctions.java
  exist-core/src/main/java/org/exist/xquery/functions/math/OneParamFunctions.java
  exist-core/src/main/java/org/exist/xquery/functions/math/TwoParamFunctions.java
Labels: bug, xquery

#3693 (Bugfix) misc XQTS reported issues
  exist-core/src/main/java/org/exist/xquery/functions/fn/FunUnparsedText.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FunXmlToJson.java
  exist-core/src/test/java/org/exist/xquery/functions/fn/FunUnparsedTextTest.java
  exist-core/src/test/xquery/xquery3/xml-to-json.xql
Labels: bug

#3669 Use fixed user environment for tests
  .github/workflows/build.yml
  exist-core/pom.xml
  exist-distribution/pom.xml
  exist-parent/pom.xml
  extensions/debuggee/pom.xml
  extensions/modules/file/pom.xml
  extensions/modules/persistentlogin/pom.xml
Labels: ci, enhancement, high prio

#3625 Proposed fix for #3624 NPE at RangeQueryRewriter.rewriteLocationStep
  extensions/indexes/range/src/main/java/org/exist/xquery/modules/range/RangeQueryRewriter.java
Labels: bug

#3705 Broker pool service api
  exist-core/pom.xml
  exist-core/src/main/java/org/exist/LifeCycle.java
  exist-core/src/main/java/org/exist/dom/persistent/SymbolTable.java
  exist-core/src/main/java/org/exist/indexing/IndexManager.java
  exist-core/src/main/java/org/exist/plugin/Plug.java
  exist-core/src/main/java/org/exist/plugin/PluginsManagerImpl.java
  exist-core/src/main/java/org/exist/storage/BrokerPool.java
  exist-core/src/main/java/org/exist/storage/BrokerPoolService.java
  exist-core/src/main/java/org/exist/storage/BrokerPoolServicesManager.java
  exist-core/src/main/java/org/exist/storage/SystemTaskManager.java
  exist-core/src/main/java/org/exist/storage/journal/Journal.java
  exist-core/src/test/java/org/exist/storage/BrokerPoolServiceTest.java
Labels: enhancement

#3710 Add useful switches in the readme
  BUILD.md
Labels: enhancement

#3715 Remove jQuery
  exist-core/src/main/resources/org/exist/xquery/lib/jquery.xql
  exist-jetty-config/src/main/resources/org/exist/jetty/etc/webapps/portal/index.html
  exist-jetty-config/src/main/resources/org/exist/jetty/etc/webapps/portal/resources/Quicksand_Book-webfont.eot
  exist-jetty-config/src/main/resources/org/exist/jetty/etc/webapps/portal/resources/Quicksand_Book-webfont.svg
  exist-jetty-config/src/main/resources/org/exist/jetty/etc/webapps/portal/resources/Quicksand_Book-webfont.ttf
  exist-jetty-config/src/main/resources/org/exist/jetty/etc/webapps/portal/resources/Quicksand_Book-webfont.woff
  exist-jetty-config/src/main/resources/org/exist/jetty/etc/webapps/portal/resources/jquery-1.7.1.min.js
  exist-jetty-config/src/main/resources/org/exist/jetty/etc/webapps/portal/resources/quicksand_book-webfont.woff
  exist-jetty-config/src/main/resources/org/exist/jetty/etc/webapps/portal/resources/quicksand_book-webfont.woff2
Labels: enhancement, security

#3714 Reinstate fix for output directory
  exist-distribution/pom.xml
Labels: regression
