Repository eXist-db/exist, pull requests merged in 2021-08, with the labels that each got.

#3322 Adds JUnit 5 test support
  exist-ant/pom.xml
  exist-core/pom.xml
  exist-core/src/test/java/org/exist/test/runner/AbstractTestRunnerTest.java
  exist-core/src/test/java/org/exist/test/runner/XMLTestRunnerTest.java
  exist-core/src/test/java/org/exist/test/runner/XQueryTestRunnerTest.java
  exist-parent/pom.xml
  extensions/contentextraction/pom.xml
  extensions/debuggee/pom.xml
  extensions/expath/pom.xml
  extensions/exquery/restxq/pom.xml
  extensions/indexes/lucene/pom.xml
  extensions/indexes/ngram/pom.xml
  extensions/indexes/range/pom.xml
  extensions/indexes/sort/pom.xml
  extensions/indexes/spatial/pom.xml
  extensions/modules/cache/pom.xml
  extensions/modules/compression/pom.xml
  extensions/modules/counter/pom.xml
  extensions/modules/expathrepo/pom.xml
  extensions/modules/file/pom.xml
  extensions/modules/sql/pom.xml
  extensions/modules/xslfo/pom.xml
  extensions/security/activedirectory/pom.xml
  extensions/security/ldap/pom.xml
  extensions/xqdoc/pom.xml
Labels: enhancement

#4000 Further Map Immutability Tests
  exist-core/pom.xml
  exist-core/src/test/java/org/exist/xquery/value/BifurcanMapTest.java
  exist-core/src/test/xquery/maps/MapsLookup.xml
  exist-core/src/test/xquery/maps/maps.xql
Labels: enhancement

#3975 Simplify storage of predicates for a step
  exist-core/src/main/java/org/exist/xquery/DefaultExpressionVisitor.java
  exist-core/src/main/java/org/exist/xquery/LocationStep.java
  exist-core/src/main/java/org/exist/xquery/Optimizer.java
  exist-core/src/main/java/org/exist/xquery/Step.java
  exist-core/src/main/java/org/exist/xquery/pragmas/Optimize.java
  exist-core/src/test/java/org/exist/xquery/LocationStepTest.java
  extensions/indexes/range/src/main/java/org/exist/xquery/modules/range/OptimizeFieldPragma.java
  extensions/indexes/range/src/main/java/org/exist/xquery/modules/range/RangeQueryRewriter.java
Labels: enhancement

#3994 [refactor] Update Mail Module to Jakarta Mail 2.0.0
  extensions/modules/mail/pom.xml
  extensions/modules/mail/src/main/java/org/exist/xquery/modules/mail/MailFolderFunctions.java
  extensions/modules/mail/src/main/java/org/exist/xquery/modules/mail/MailModule.java
  extensions/modules/mail/src/main/java/org/exist/xquery/modules/mail/MailSessionFunctions.java
  extensions/modules/mail/src/main/java/org/exist/xquery/modules/mail/MailStoreFunctions.java
  extensions/modules/mail/src/main/java/org/exist/xquery/modules/mail/MessageFunctions.java
  extensions/modules/mail/src/main/java/org/exist/xquery/modules/mail/MessageListFunctions.java
  extensions/modules/mail/src/main/java/org/exist/xquery/modules/mail/SendEmailFunction.java
Labels: bug, enhancement, regression

#4002 Implement map:merge#2
  exist-core/src/main/java/org/exist/xquery/functions/map/MapFunction.java
  exist-core/src/main/java/org/exist/xquery/functions/map/MapModule.java
  exist-core/src/test/xquery/maps/maps.xql
Labels: enhancement

#4012 [library] upgrade to most recent saxon 9.9 version
  exist-parent/pom.xml
Labels: bug
