Repository eXist-db/exist, pull requests merged in 2021-09, with the labels that each got.

#3992 Instead of depending on an external XAR for tests just build it
  extensions/modules/expathrepo/expathrepo-trigger-test/pom.xml
  extensions/modules/expathrepo/expathrepo-trigger-test/src/main/java/org/exist/repo/ExampleFunctions.java
  extensions/modules/expathrepo/expathrepo-trigger-test/src/main/java/org/exist/repo/ExampleModule.java
  extensions/modules/expathrepo/expathrepo-trigger-test/src/main/java/org/exist/repo/ExampleTrigger.java
  extensions/modules/expathrepo/expathrepo-trigger-test/src/main/xar-resources/collection.xconf
  extensions/modules/expathrepo/expathrepo-trigger-test/src/main/xar-resources/controller.xql
  extensions/modules/expathrepo/expathrepo-trigger-test/src/main/xar-resources/icon.png
  extensions/modules/expathrepo/expathrepo-trigger-test/src/main/xar-resources/index.html
  extensions/modules/expathrepo/expathrepo-trigger-test/src/main/xar-resources/post-install.xq
  extensions/modules/expathrepo/expathrepo-trigger-test/src/main/xar-resources/pre-install.xq
  extensions/modules/expathrepo/expathrepo-trigger-test/src/main/xquery/example-module.xqm
  extensions/modules/expathrepo/expathrepo-trigger-test/src/test/java/org/exist/repo/ExampleModuleTest.java
  extensions/modules/expathrepo/expathrepo-trigger-test/src/test/resources/conf.xml
  extensions/modules/expathrepo/expathrepo-trigger-test/xar-assembly.xml
  extensions/modules/expathrepo/pom.xml
  extensions/modules/expathrepo/src/test/java/org/exist/repo/PackageTriggerTest.java
  extensions/modules/expathrepo/src/test/resources/org/exist/repo/README.md
  extensions/modules/expathrepo/src/test/resources/org/exist/repo/triggertest-1.1.0.xar
  extensions/modules/pom.xml
Labels: enhancement

#4013 Small fixes to in-memory DOM
  exist-core/src/main/java/org/exist/dom/memtree/DocumentImpl.java
  exist-core/src/main/java/org/exist/dom/memtree/ElementImpl.java
  exist-core/src/main/java/org/exist/dom/memtree/MemTreeBuilder.java
  exist-core/src/test/java/org/exist/dom/memtree/DocumentImplTest.java
  exist-core/src/test/java/org/exist/dom/memtree/MemtreeTest.java
Labels: bug, enhancement

#4028 fix(Docker): rename dejavu font package
  exist-docker/src/main/resources-filtered/Dockerfile
Labels: bug, high prio, docker

#4033 Switch to Evolved Binary's mirror of nvd.nist.gov
  exist-parent/pom.xml
Labels: enhancement

#3990 Add eXist specific serialization options to fn:serialize
  exist-core/src/main/java/org/exist/storage/serializers/NativeSerializer.java
  exist-core/src/main/java/org/exist/storage/serializers/Serializer.java
  exist-core/src/main/java/org/exist/xquery/util/SerializerUtils.java
  exist-core/src/test/xquery/xquery3/serialize.xql
  extensions/indexes/lucene/src/test/xquery/lucene/serialize.xql
Labels: enhancement, needs documentation
