Repository eXist-db/exist, pull requests merged in 2022-07, with the labels that each got.

#4462 Avoid an NPE when disposing Binary Values
  exist-core/src/main/java/org/exist/dom/memtree/NodeImpl.java
  exist-core/src/main/java/org/exist/dom/persistent/NodeProxy.java
  exist-core/src/main/java/org/exist/xquery/DeferredFunctionCall.java
  exist-core/src/main/java/org/exist/xquery/ModuleContext.java
  exist-core/src/main/java/org/exist/xquery/VariableImpl.java
  exist-core/src/main/java/org/exist/xquery/XQueryContext.java
  exist-core/src/main/java/org/exist/xquery/value/AbstractSequence.java
  exist-core/src/main/java/org/exist/xquery/value/ArrayListValueSequence.java
  exist-core/src/main/java/org/exist/xquery/value/AtomicValue.java
  exist-core/src/main/java/org/exist/xquery/value/BinaryValueFromFile.java
  exist-core/src/main/java/org/exist/xquery/value/BinaryValueFromInputStream.java
  exist-core/src/main/java/org/exist/xquery/value/Item.java
  exist-core/src/main/java/org/exist/xquery/value/Sequence.java
  exist-core/src/main/java/org/exist/xquery/value/SubSequence.java
  exist-core/src/main/java/org/exist/xquery/value/ValueSequence.java
Labels: bug, regression

#4463 [5.x.x] Avoid an NPE when disposing Binary Values
  exist-core/src/main/java/org/exist/dom/memtree/NodeImpl.java
  exist-core/src/main/java/org/exist/dom/persistent/NodeProxy.java
  exist-core/src/main/java/org/exist/xquery/DeferredFunctionCall.java
  exist-core/src/main/java/org/exist/xquery/ModuleContext.java
  exist-core/src/main/java/org/exist/xquery/VariableImpl.java
  exist-core/src/main/java/org/exist/xquery/XQueryContext.java
  exist-core/src/main/java/org/exist/xquery/value/AbstractSequence.java
  exist-core/src/main/java/org/exist/xquery/value/ArrayListValueSequence.java
  exist-core/src/main/java/org/exist/xquery/value/AtomicValue.java
  exist-core/src/main/java/org/exist/xquery/value/BinaryValueFromFile.java
  exist-core/src/main/java/org/exist/xquery/value/BinaryValueFromInputStream.java
  exist-core/src/main/java/org/exist/xquery/value/Item.java
  exist-core/src/main/java/org/exist/xquery/value/Sequence.java
  exist-core/src/main/java/org/exist/xquery/value/SubSequence.java
  exist-core/src/main/java/org/exist/xquery/value/ValueSequence.java
Labels: bug, regression

#4464 [4.x.x] Avoid an NPE when disposing Binary Values
  exist-core/src/main/java/org/exist/dom/memtree/NodeImpl.java
  exist-core/src/main/java/org/exist/dom/persistent/NodeProxy.java
  exist-core/src/main/java/org/exist/xquery/DeferredFunctionCall.java
  exist-core/src/main/java/org/exist/xquery/ModuleContext.java
  exist-core/src/main/java/org/exist/xquery/VariableImpl.java
  exist-core/src/main/java/org/exist/xquery/XQueryContext.java
  exist-core/src/main/java/org/exist/xquery/value/AbstractSequence.java
  exist-core/src/main/java/org/exist/xquery/value/AtomicValue.java
  exist-core/src/main/java/org/exist/xquery/value/BinaryValueFromFile.java
  exist-core/src/main/java/org/exist/xquery/value/BinaryValueFromInputStream.java
  exist-core/src/main/java/org/exist/xquery/value/Item.java
  exist-core/src/main/java/org/exist/xquery/value/Sequence.java
  exist-core/src/main/java/org/exist/xquery/value/SubSequence.java
  exist-core/src/main/java/org/exist/xquery/value/ValueSequence.java
Labels: bug, regression

#4435 Implement the fn:collation-key XQuery function
  exist-core/src/main/java/org/exist/xquery/functions/fn/FnModule.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FunCollationKey.java
  exist-core/src/main/java/org/exist/xquery/value/BinaryValue.java
  exist-core/src/test/xquery/xquery3/fnCodepointEqual.xqm
  exist-core/src/test/xquery/xquery3/fnCollationKey.xqm
  extensions/modules/compression/src/test/xquery/modules/compression/zip-tests.xql
Labels: enhancement

#4477 Implement minus unary operator for xs:dateTimeStamp
  exist-core/src/main/java/org/exist/xquery/value/DateTimeValue.java
  exist-core/src/test/xquery/dates/convert-dates.xqm
Labels: bug

#4488 Report null results instead of throwing NPE
  exist-core/src/main/java/org/exist/client/QueryDialog.java
Labels: bug

#4490 [4.x.x] Report null results instead of throwing NPE
  exist-core/src/main/java/org/exist/client/QueryDialog.java
Labels: bug

#4489 [5.x.x] Report null results instead of throwing NPE
  exist-core/src/main/java/org/exist/client/QueryDialog.java
Labels: bug

#4472 Tests to show that Path expression with nested positional predicate succeeds on database node
  exist-core/src/test/xquery/npt.xqm
Labels: bug

#4491 [4.x.x] Get latest EXPath HTTP Client from Maven Central
  .gitignore
  extensions/expath/ivy.xml
  extensions/expath/lib/apache-mime4j-0.6.jar
  extensions/expath/lib/http-client-java-1.0-SNAPSHOT.jar
  extensions/expath/lib/tagsoup-1.2.1.jar
  extensions/expath/lib/tools-java-1.0-SNAPSHOT.jar
Labels: enhancement

#4456 Bugfix/serialization item separator
  exist-core/src/main/java/org/exist/xquery/functions/fn/FunSerialize.java
  exist-core/src/main/java/org/exist/xquery/functions/util/Eval.java
  exist-core/src/test/xquery/xquery3/serialize.xql
Labels: bug

#4498 Add missing XQuery Reserved Names
  exist-core/src/main/antlr/org/exist/xquery/parser/XQuery.g
  exist-core/src/test/java/org/exist/xquery/ReservedNamesConflictTest.java
  exist-core/src/test/xquery/reserved-names.xqm
Labels: bug

#4485 [feature] Implement the fn:element-with-id function
  exist-core/src/main/java/org/exist/Namespaces.java
  exist-core/src/main/java/org/exist/dom/memtree/DocumentImpl.java
  exist-core/src/main/java/org/exist/dom/memtree/ElementImpl.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FnModule.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FunElementWithId.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FunId.java
  exist-core/src/test/xquery/xquery3/fnElementWithId.xqm
  exist-core/src/test/xquery/xquery3/fnId.xqm
Labels: enhancement

#4444 [bugfix] Add missing location information in errors for functions inside element constructors (err:XQTY0105)
  exist-core/src/main/antlr/org/exist/xquery/parser/XQueryTree.g
  exist-core/src/main/java/org/exist/xquery/DynamicFunctionCall.java
  exist-core/src/main/java/org/exist/xquery/EnclosedExpr.java
  exist-core/src/main/java/org/exist/xquery/value/FunctionReference.java
  exist-core/src/test/xquery/errors.xql
Labels: enhancement

#4405 Implement fn:nillled
  exist-core/src/main/java/org/exist/xquery/functions/fn/FnModule.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FunNilled.java
  exist-core/src/test/xquery/nill.xql
  exist-core/src/test/xquery/xquery3/fnNilled.xqm
Labels: enhancement, xquery

#4465 [4.x.x] Fail the build if the .xar.zip file that was downloaded was invalid
  build/scripts/build-impl.xml
  build/scripts/setup.xml
  tools/ant/lib/asocat-1.1.0.jar
  tools/ant/lib/asocat-exist-1.0.jar
Labels: bug, enhancement
