Repository eXist-db/exist, pull requests merged in 2022-01, with the labels that each got.

#4164 Enforce dependency analysis of exist-core
  exist-core/pom.xml
  exist-core/src/test/java/org/exist/util/CollectionOfArrayIteratorTest.java
  exist-core/src/test/java/org/exist/util/LeasableTest.java
  exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty-annotations.xml
  exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty-plus.xml
  exist-jetty-config/src/main/resources/org/exist/jetty/etc/standalone.enabled-jetty-configs
  exist-jetty-config/src/main/resources/org/exist/jetty/etc/standard.enabled-jetty-configs
Labels: enhancement

#4159 Tests for mail:send-email
  exist-core/pom.xml
  exist-core/src/main/java/org/exist/test/ExistWebServer.java
  exist-core/src/main/java/org/exist/util/IPUtil.java
  extensions/modules/mail/pom.xml
  extensions/modules/mail/src/main/java/org/exist/xquery/modules/mail/SendEmailFunction.java
  extensions/modules/mail/src/test/java/org/exist/xquery/modules/mail/SendEmailIT.java
  extensions/modules/mail/src/test/java/org/exist/xquery/modules/mail/Util.java
  extensions/modules/mail/src/test/resources-filtered/conf.xml
  extensions/modules/mail/src/test/resources/log4j2.xml
Labels: enhancement

#4161 Run JUnit 4 tests via JUnit 5
  exist-ant/pom.xml
  exist-core/pom.xml
  exist-parent/pom.xml
  extensions/contentextraction/pom.xml
  extensions/expath/pom.xml
  extensions/exquery/restxq/pom.xml
  extensions/indexes/lucene/pom.xml
  extensions/indexes/ngram/pom.xml
  extensions/indexes/range/pom.xml
  extensions/indexes/sort/pom.xml
  extensions/indexes/spatial/pom.xml
  extensions/modules/cache/pom.xml
  extensions/modules/compression/pom.xml
  extensions/modules/counter/pom.xml
  extensions/modules/expathrepo/pom.xml
  extensions/modules/file/pom.xml
  extensions/modules/sql/pom.xml
  extensions/modules/xslfo/pom.xml
  extensions/security/activedirectory/pom.xml
  extensions/security/ldap/pom.xml
  extensions/xqdoc/pom.xml
Labels: enhancement

#4168 Update to Tika 2.2.1
  exist-core/src/main/java/org/exist/test/runner/ExtTestErrorFunction.java
  extensions/contentextraction/pom.xml
  extensions/contentextraction/src/main/java/org/exist/contentextraction/ContentExtraction.java
  extensions/contentextraction/src/test/java/org/exist/contentextraction/xquery/ContentFunctionsTest.java
  extensions/contentextraction/src/test/java/org/exist/contentextraction/xquery/Util.java
  extensions/contentextraction/src/test/java/xquery/contentextraction/ContentExtractionTests.java
  extensions/contentextraction/src/test/resources/org/exist/contentextraction/xquery/minimal.pdf
  extensions/contentextraction/src/test/resources/org/exist/contentextraction/xquery/test.xlsx
  extensions/contentextraction/src/test/xquery/contentextraction/content-extraction.xq
Labels: enhancement

#4175 Don't attempt an impossible conversion in NativeValueIndex
  exist-core/src/main/java/org/exist/storage/NativeValueIndex.java
  exist-core/src/test/java/org/exist/storage/NativeValueIndexTest.java
Labels: bug

#4173 Enable previously disabled tests that are now passing
  exist-core/src/test/xquery/axes.xml
  exist-core/src/test/xquery/parenthesizedContext.xml
  exist-core/src/test/xquery/pathExpression_operators.xml
  exist-core/src/test/xquery/persistent_in-memory.xml
  exist-core/src/test/xquery/question-marks-in-contains-function.xql
  exist-core/src/test/xquery/xquery3/xml-to-json.xql
Labels: enhancement

#4172 util:expand must handle Document and Attribute Nodes correctly
  exist-core/src/main/java/org/exist/dom/memtree/MemTreeBuilder.java
  exist-core/src/main/java/org/exist/xmldb/LocalXMLResource.java
  exist-core/src/main/java/org/exist/xquery/functions/util/Expand.java
  exist-core/src/test/java/org/exist/xquery/functions/util/ExpandTest.java
  exist-core/src/test/xquery/serialization.xml
  exist-core/src/test/xquery/util/expand.xqm
Labels: bug

#4167 fn:generate-id must provide unique IDs for unique Nodes
  exist-core/src/main/java/org/exist/dom/memtree/DocumentImpl.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FunGenerateId.java
  exist-core/src/test/java/xquery/xquery3/XQuery3Tests.java
  exist-core/src/test/xquery/xquery3/generate-id.xqm
Labels: bug

#4169 Notarize macOS DMG
  exist-core/pom.xml
  exist-distribution/pom.xml
  exist-distribution/src/app/entitlements.plist
  exist-distribution/src/main/scripts/codesign-jansi-mac.sh
  exist-parent/pom.xml
  exist-versioning-release.md
Labels: enhancement, security

#4178 Use the latest JRE 8 in the Docker Image
  exist-docker/src/main/resources-filtered/Dockerfile
Labels: enhancement, docker

#4108 fix following/preceding axes after predicate on abbreviated step
  exist-core/src/main/java/org/exist/xquery/LocationStep.java
  exist-core/src/test/xquery/axes-persistent-nodes.xqm
Labels: bug, xquery

#4180 A more comprehensive test around deleting accounts
  exist-core/src/test/java/org/exist/security/SecurityManagerTest.java
Labels: security

#4181 [4.x.x] Add a more comprehensive test around deleting accounts
  exist-core/src/main/java/org/exist/security/SecurityManagerTest.java
Labels: security

#4187 Further checks around removed accounts
  exist-core/src/test/java/org/exist/security/SecurityManagerTest.java
Labels: enhancement

#4188 [4.x.x] Fix issue with Collection structures being overwritten during startup
  exist-core/src/main/java/org/exist/collections/CollectionCache.java
  exist-core/src/main/java/org/exist/launcher/ConfigurationDialog.java
  exist-core/src/main/java/org/exist/management/client/JMXtoXML.java
  exist-core/src/main/java/org/exist/management/impl/CollectionCache.java
  exist-core/src/main/java/org/exist/management/impl/CollectionCacheMXBean.java
  exist-core/src/main/java/org/exist/management/impl/Database.java
  exist-core/src/main/java/org/exist/management/impl/JMXAgent.java
  exist-core/src/main/java/org/exist/storage/BrokerPool.java
  exist-core/src/main/java/org/exist/storage/CollectionCacheManager.java
  exist-core/src/main/java/org/exist/storage/NativeBroker.java
  exist-core/src/main/java/org/exist/storage/report/XMLStatistics.java
  exist-core/src/main/java/org/exist/util/Configuration.java
  exist-core/src/test/java/org/exist/security/SecurityManagerTest.java
Labels: bug

#4194 [4.x.x] Fix Journal Bugs
  exist-core/src/main/java/org/exist/storage/blob/BlobStoreImpl.java
  exist-core/src/main/java/org/exist/storage/journal/Journal.java
  exist-core/src/main/java/org/exist/storage/journal/JournalManager.java
  exist-core/src/main/java/org/exist/storage/journal/JournalReader.java
  exist-core/src/main/java/org/exist/storage/recovery/RecoveryManager.java
  exist-core/src/test/java/org/exist/storage/journal/AbstractJournalTest.java
  exist-core/src/test/java/org/exist/storage/journal/JournalTest.java
Labels: bug, high prio

#4193 Fix Journal Bugs
  exist-core/src/main/java/org/exist/storage/blob/BlobStoreImpl.java
  exist-core/src/main/java/org/exist/storage/journal/Journal.java
  exist-core/src/main/java/org/exist/storage/journal/JournalManager.java
  exist-core/src/main/java/org/exist/storage/journal/JournalReader.java
  exist-core/src/main/java/org/exist/storage/recovery/RecoveryManager.java
  exist-core/src/main/java/org/exist/test/runner/XQueryTestRunner.java
  exist-core/src/test/java/org/exist/storage/journal/AbstractJournalTest.java
  exist-core/src/test/java/org/exist/storage/journal/JournalTest.java
Labels: bug, high prio

#4201 [4.x.x] Fix Collection Rename and Move operations
  exist-core/src/main/java/org/exist/storage/NativeBroker.java
  exist-core/src/test/java/org/exist/storage/CopyCollectionTest.java
  exist-core/src/test/java/org/exist/storage/MoveCollectionTest.java
Labels: bug, high prio

#4203 [4.x.x] Remove GeoSpatial Index from IntelliJ project
  eXist-db.iml
Labels: enhancement

#4200 Shell script needs to be executable
  exist-distribution/src/main/scripts/codesign-jansi-mac.sh
Labels: bug

#4202 Test Collection Rename and Move operations
  exist-core/src/test/java/org/exist/storage/CopyCollectionTest.java
  exist-core/src/test/java/org/exist/storage/MoveCollectionTest.java
Labels: bug, enhancement

#4204 Fix NPE in FunctionCall for Deferred Forward Reference
  exist-core/pom.xml
  exist-core/src/main/java/org/exist/xquery/Function.java
  exist-core/src/main/java/org/exist/xquery/FunctionCall.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FunConcat.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FunCurrentDateTime.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FunGetDateComponent.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FunGetDurationComponent.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FunMatches.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FunReplace.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FunReverse.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FunSubSequence.java
  exist-core/src/main/java/org/exist/xquery/functions/map/MapExpr.java
  exist-core/src/main/java/org/exist/xquery/functions/securitymanager/IdFunction.java
  exist-core/src/main/java/org/exist/xquery/functions/securitymanager/IsAuthenticatedFunction.java
  exist-core/src/main/java/org/exist/xquery/functions/system/FnExport.java
  exist-core/src/main/java/org/exist/xquery/functions/system/FnImport.java
  exist-core/src/main/java/org/exist/xquery/functions/util/QNameIndexLookup.java
  exist-core/src/main/java/org/exist/xquery/functions/util/SystemTime.java
  exist-core/src/test/java/org/exist/test/Util.java
  exist-core/src/test/java/org/exist/xquery/ForwardReferenceTest.java
  extensions/indexes/lucene/src/main/java/org/exist/xquery/modules/lucene/Query.java
  extensions/indexes/ngram/src/main/java/org/exist/xquery/modules/ngram/NGramSearch.java
  extensions/indexes/range/src/main/java/org/exist/xquery/modules/range/FieldLookup.java
  extensions/indexes/range/src/main/java/org/exist/xquery/modules/range/Lookup.java
  extensions/indexes/spatial/src/main/java/org/exist/xquery/modules/spatial/FunGeometricProperties.java
Labels: bug

#4081 Improve file:sync
  exist-core/pom.xml
  exist-core/src/main/java/org/exist/xquery/util/SerializerUtils.java
  exist-parent/pom.xml
  extensions/modules/file/pom.xml
  extensions/modules/file/src/main/java/org/exist/xquery/modules/file/Sync.java
  extensions/modules/file/src/test/resources/util/fixtures.xqm
  extensions/modules/file/src/test/resources/util/helper.xqm
  extensions/modules/file/src/test/xquery/modules/file/read-binary.xqm
  extensions/modules/file/src/test/xquery/modules/file/serialize.xqm
  extensions/modules/file/src/test/xquery/modules/file/sync.xqm
  extensions/modules/file/src/test/xquery/modules/file/syncmod.xqm
Labels: enhancement, needs documentation

#3934 Update Apache XML-RPC
  exist-core/pom.xml
  exist-core/src/main/java/org/exist/management/TaskStatus.java
  exist-core/src/main/java/org/exist/security/internal/aider/ACEAider.java
  exist-core/src/main/java/org/exist/xmlrpc/ACEAiderParser.java
  exist-core/src/main/java/org/exist/xmlrpc/ACEAiderSerializer.java
  exist-core/src/main/java/org/exist/xmlrpc/ExistRpcTypeFactory.java
  exist-core/src/main/java/org/exist/xmlrpc/TupleParser.java
  exist-parent/pom.xml
Labels: bug, security, dependencies
