Repository eXist-db/exist, pull requests merged in 2022-10, with the labels that each got.

#4545 [bugfix] - namespace binding conflict errors
  exist-core/src/main/java/org/exist/dom/memtree/NodeImpl.java
  exist-core/src/main/java/org/exist/dom/persistent/AttrImpl.java
  exist-core/src/main/java/org/exist/dom/persistent/ElementImpl.java
  exist-core/src/main/java/org/exist/xquery/ErrorCodes.java
  exist-core/src/main/java/org/exist/xquery/update/Insert.java
  exist-core/src/test/xquery/xquery3/bindingConflict.xqm
Labels: bug

#3940 [hotfix] use DiskFileItemFactory default threshhold
  exist-core/src/main/java/org/exist/http/servlets/HttpRequestWrapper.java
Labels: discuss, performance

#4552 [4.x.x] Change URL for two unparsed-text tests
  exist-core/src/test/xquery/unparsed-text.xql
Labels: bug

#4586 [hotfix] multipart body contents in XQuery
  exist-core/src/main/java/org/exist/http/servlets/HttpRequestWrapper.java
Labels: regression

#4551 [5.x.x] Change URL for two unparsed-text tests
  exist-core/src/test/xquery/unparsed-text.xql
Labels: bug

#4550 [4.x.x] Fix issues with document-node lookups on various axis
  exist-core/src/main/java/org/exist/xquery/LocationStep.java
  exist-core/src/test/xquery/document-nodes.xq
Labels: bug

#4549 [5.x.x] Fix issues with document-node lookups on various axis
  exist-core/src/main/java/org/exist/xquery/LocationStep.java
  exist-core/src/test/xquery/document-nodes.xq
Labels: bug

#4597 Fix issues with SMTP dialogue in the Mail Module when sending emails.
  extensions/modules/mail/pom.xml
  extensions/modules/mail/src/main/java/org/exist/xquery/modules/mail/SendEmailFunction.java
  extensions/modules/mail/src/test/java/org/exist/xquery/modules/mail/SendEmailIT.java
  extensions/modules/mail/src/test/java/org/exist/xquery/modules/mail/WriteMessageTest.java
  extensions/modules/mail/src/test/resources-filtered/conf.xml
Labels: bug

#4589 Fixes an issue with XSuite not being able to run some formulations of XQsuite
  exist-core/pom.xml
  exist-core/src/main/java/org/exist/repo/ExistRepository.java
  exist-core/src/main/java/org/exist/storage/BrokerPool.java
  exist-core/src/main/java/org/exist/test/runner/XQueryTestRunner.java
  exist-core/src/main/java/org/exist/util/MapUtil.java
  exist-core/src/main/java/org/exist/xquery/ModuleContext.java
  exist-core/src/main/java/org/exist/xquery/XQueryContext.java
  exist-core/src/main/java/org/exist/xquery/XQueryWatchDog.java
  exist-core/src/test/resources-filtered/conf.xml
  exist-core/src/test/xquery/xsuite-declare-xqsuite.xqm
  exist-core/src/test/xquery/xsuite-import-xqsuite-location.xqm
  exist-core/src/test/xquery/xsuite-import-xqsuite-no-location.xqm
Labels: bug, regression

#4590 [5.x.x] Fixes an issue with XSuite not being able to run some formulations of XQsuite
  exist-core/pom.xml
  exist-core/src/main/java/org/exist/repo/ExistRepository.java
  exist-core/src/main/java/org/exist/storage/BrokerPool.java
  exist-core/src/main/java/org/exist/test/runner/XQueryTestRunner.java
  exist-core/src/main/java/org/exist/util/MapUtil.java
  exist-core/src/main/java/org/exist/xquery/ModuleContext.java
  exist-core/src/main/java/org/exist/xquery/XQueryContext.java
  exist-core/src/main/java/org/exist/xquery/XQueryWatchDog.java
  exist-core/src/test/resources-filtered/conf.xml
  exist-core/src/test/xquery/xsuite-declare-xqsuite.xqm
  exist-core/src/test/xquery/xsuite-import-xqsuite-location.xqm
  exist-core/src/test/xquery/xsuite-import-xqsuite-no-location.xqm
Labels: bug, regression

#4601 Fix mail:send-email via Java API in Docker
  exist-docker/pom.xml
Labels: bug
