Repository eXist-db/exist, pull requests merged in 2022-05, with the labels that each got.

#4374 [4.x.x] Improve XSLT errors
  exist-core/src/main/java/org/exist/http/servlets/XSLTServlet.java
  exist-core/src/main/java/org/exist/xquery/functions/transform/Transform.java
  exist-core/src/main/java/org/exist/xslt/XSLTErrorsListener.java
Labels: enhancement

#4373 [5.x.x] Improve XSLT errors
  exist-core/src/main/java/org/exist/http/servlets/XSLTServlet.java
  exist-core/src/main/java/org/exist/xquery/functions/transform/Transform.java
  exist-core/src/main/java/org/exist/xslt/XSLTErrorsListener.java
Labels: enhancement

#4371 [4.x.x] Limit the number of hardware threads to a max of 16 in some tests
  extensions/indexes/lucene/src/test/java/org/exist/indexing/lucene/ConcurrencyTest.java
Labels: bug

#4370 [5.x.x] Limit the number of hardware threads to a max of 16 in some tests
  exist-core/src/test/java/org/exist/collections/ConcurrencyTest.java
  extensions/indexes/lucene/src/test/java/org/exist/indexing/lucene/ConcurrencyTest.java
Labels: bug

#4369 Limit the number of hardware threads to a max of 16 in some tests
  exist-core/src/test/java/org/exist/collections/ConcurrencyTest.java
  extensions/indexes/lucene/src/test/java/org/exist/indexing/lucene/ConcurrencyTest.java
Labels: bug

#4377 [4.x.x] Do not override Bearer Authentication with Basic Authentication
  exist-core/src/main/java/org/exist/http/servlets/AbstractExistHttpServlet.java
  exist-core/src/main/java/org/exist/http/servlets/BasicAuthenticator.java
  exist-core/src/main/java/org/exist/http/urlrewrite/XQueryURLRewrite.java
  exist-core/src/test/java/org/exist/http/RESTServiceTest.java
Labels: bug

#4376 [5.x.x] Do not override Bearer Authentication with Basic Authentication
  exist-core/src/main/java/org/exist/http/servlets/AbstractExistHttpServlet.java
  exist-core/src/main/java/org/exist/http/servlets/BasicAuthenticator.java
  exist-core/src/main/java/org/exist/http/urlrewrite/XQueryURLRewrite.java
  exist-core/src/test/java/org/exist/http/RESTServiceTest.java
Labels: bug

#4375 Do not override Bearer Authentication with Basic Authentication
  exist-core/src/main/java/org/exist/http/servlets/AbstractExistHttpServlet.java
  exist-core/src/main/java/org/exist/http/servlets/BasicAuthenticator.java
  exist-core/src/main/java/org/exist/http/urlrewrite/XQueryURLRewrite.java
  exist-core/src/test/java/org/exist/http/RESTServiceTest.java
Labels: bug

#4372 Improve XSLT errors
  exist-core/src/main/java/org/exist/http/servlets/XSLTServlet.java
  exist-core/src/main/java/org/exist/xquery/functions/transform/Transform.java
  exist-core/src/main/java/org/exist/xslt/XSLTErrorsListener.java
Labels: enhancement

#4366 Implement fn:format-integer#2,#3
  exist-core/src/main/java/org/exist/test/runner/XMLTestRunner.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FnFormatIntegers.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FnModule.java
  exist-core/src/main/java/org/exist/xquery/functions/integer/DigitsIntegerPicture.java
  exist-core/src/main/java/org/exist/xquery/functions/integer/FormatModifier.java
  exist-core/src/main/java/org/exist/xquery/functions/integer/IntegerPicture.java
  exist-core/src/main/java/org/exist/xquery/functions/integer/NumberingPicture.java
  exist-core/src/main/java/org/exist/xquery/functions/integer/RomanIntegerPicture.java
  exist-core/src/main/java/org/exist/xquery/functions/integer/RomanNumberHelper.java
  exist-core/src/main/java/org/exist/xquery/functions/integer/SequenceIntegerPicture.java
  exist-core/src/main/java/org/exist/xquery/functions/integer/WordPicture.java
  exist-core/src/test/java/org/exist/xquery/functions/integer/IntegerPictureTest.java
  exist-core/src/test/xquery/numbers/format-integers.xql
Labels: enhancement

#4387 Fix issues with range, precision, and exponent with fn:xml-to-json
  exist-core/src/main/java/org/exist/xquery/functions/fn/FnModule.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FunXmlToJson.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/JSON.java
  exist-core/src/test/xquery/xquery3/xml-to-json.xql
Labels: bug

#4388 [5.x.x] Fix issues with range, precision, and exponent with fn:xml-to-json
  exist-core/src/main/java/org/exist/xquery/functions/fn/FnModule.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FunXmlToJson.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/JSON.java
  exist-core/src/test/xquery/xquery3/xml-to-json.xql
Labels: bug

#4392 Share common code between RestoreHandler and SystemImportHandler
  exist-core/src/main/java/org/exist/backup/restore/AbstractRestoreHandler.java
  exist-core/src/main/java/org/exist/backup/restore/RestoreHandler.java
  exist-core/src/main/java/org/exist/backup/restore/SystemImportHandler.java
Labels: enhancement

#4403 [5.x.x] Share common code between RestoreHandler and SystemImportHandler
  exist-core/src/main/java/org/exist/backup/restore/AbstractRestoreHandler.java
  exist-core/src/main/java/org/exist/backup/restore/RestoreHandler.java
  exist-core/src/main/java/org/exist/backup/restore/SystemImportHandler.java
Labels: enhancement

#4404 [5.x.x] Fix additional issues with ResourceType and MediaType during Restore
  exist-core/src/main/java/org/exist/backup/restore/AbstractRestoreHandler.java
  exist-core/src/test/java/org/exist/backup/XMLDBRestoreTest.java
Labels: bug, regression

#4401 Implement map:find#2
  exist-core/src/main/java/org/exist/xquery/functions/map/MapFunction.java
  exist-core/src/main/java/org/exist/xquery/functions/map/MapModule.java
  exist-core/src/test/java/xquery/maps/MapTests.java
  exist-core/src/test/xquery/maps/maps-find.xql
  exist-core/src/test/xquery/maps/maps.xqm
Labels: enhancement

#4395 Fix the Node Test for document-node(element(name))
  exist-core/src/main/java/org/exist/xquery/DynamicNameCheck.java
  exist-core/src/main/java/org/exist/xquery/NameTest.java
  exist-core/src/test/xquery/node-tests.xqm
Labels: bug

#4396 [5.x.x] Fix the Node Test for document-node(element(name))
  exist-core/src/main/java/org/exist/xquery/DynamicNameCheck.java
  exist-core/src/main/java/org/exist/xquery/NameTest.java
  exist-core/src/test/xquery/node-tests.xqm
Labels: bug

#4400 Implement fn:round#2
  exist-core/src/main/java/org/exist/xquery/functions/fn/FnModule.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FunRound.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FunRoundBase.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FunRoundHalfToEven.java
  exist-core/src/main/java/org/exist/xquery/value/DecimalValue.java
  exist-core/src/main/java/org/exist/xquery/value/DoubleValue.java
  exist-core/src/main/java/org/exist/xquery/value/FloatValue.java
  exist-core/src/main/java/org/exist/xquery/value/IntegerValue.java
  exist-core/src/main/java/org/exist/xquery/value/NumericValue.java
  exist-core/src/test/xquery/numbers/fn-round.xqm
Labels: enhancement

#4411 [upgrade] Upgrade H2 to 2.1.10
  extensions/modules/sql/pom.xml
Labels: security, dependencies

#4393 Add xs:dateTimeStamp datatype
  exist-core/src/main/java/org/exist/xquery/OpNumeric.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FunCurrentDateTime.java
  exist-core/src/main/java/org/exist/xquery/value/DateTimeStampValue.java
  exist-core/src/main/java/org/exist/xquery/value/DateTimeValue.java
  exist-core/src/main/java/org/exist/xquery/value/OrderedDurationValue.java
  exist-core/src/main/java/org/exist/xquery/value/StringValue.java
  exist-core/src/main/java/org/exist/xquery/value/Type.java
  exist-core/src/main/java/org/exist/xquery/value/UntypedAtomicValue.java
  exist-core/src/test/java/org/exist/xquery/value/DateTimeStampTest.java
  exist-core/src/test/xquery/dates/convert-dates.xqm
  extensions/modules/file/src/main/java/org/exist/xquery/modules/file/Sync.java
Labels: enhancement

#4418 Allow BigDecimal and BigInteger values to be declared via XML:DB API
  exist-core/src/main/java/org/exist/xquery/XPathUtil.java
  exist-core/src/test/java/org/exist/xmldb/DeclareVariableTest.java
Labels: bug, enhancement

#4419 [5.x.x] Allow BigDecimal and BigInteger values to be declared via XML:DB API
  exist-core/src/main/java/org/exist/xquery/XPathUtil.java
  exist-core/src/test/java/org/exist/xmldb/DeclareVariableTest.java
Labels: bug, enhancement

#4420 [4.x.x] Allow BigDecimal and BigInteger values to be declared via XML:DB API
  exist-core/src/main/java/org/exist/xquery/XPathUtil.java
  exist-core/src/test/java/org/exist/xmldb/DeclareVariableTest.java
Labels: bug, enhancement

#4417 Update IntelliJ IDEA IDE config for eXist-db 5.5.0-SNAPSHOT
  .idea/runConfigurations/Java_Admin_Client.xml
  .idea/runConfigurations/Jetty_Server.xml
Labels: bug

#4409 Improve out-of-scope detection for binary variables
  exist-core/src/main/java/org/exist/dom/memtree/NodeImpl.java
  exist-core/src/main/java/org/exist/dom/persistent/AVLTreeNodeSet.java
  exist-core/src/main/java/org/exist/dom/persistent/EmptyNodeSet.java
  exist-core/src/main/java/org/exist/dom/persistent/ExtArrayNodeSet.java
  exist-core/src/main/java/org/exist/dom/persistent/NewArrayNodeSet.java
  exist-core/src/main/java/org/exist/dom/persistent/NodeProxy.java
  exist-core/src/main/java/org/exist/dom/persistent/SortedNodeSet.java
  exist-core/src/main/java/org/exist/dom/persistent/VirtualNodeSet.java
  exist-core/src/main/java/org/exist/xquery/FunctionCall.java
  exist-core/src/main/java/org/exist/xquery/RangeSequence.java
  exist-core/src/main/java/org/exist/xquery/functions/array/ArrayType.java
  exist-core/src/main/java/org/exist/xquery/functions/map/MapType.java
  exist-core/src/main/java/org/exist/xquery/value/ArrayListValueSequence.java
  exist-core/src/main/java/org/exist/xquery/value/AtomicValue.java
  exist-core/src/main/java/org/exist/xquery/value/BinaryValueFromFile.java
  exist-core/src/main/java/org/exist/xquery/value/BinaryValueFromInputStream.java
  exist-core/src/main/java/org/exist/xquery/value/EmptySequence.java
  exist-core/src/main/java/org/exist/xquery/value/OrderedValueSequence.java
  exist-core/src/main/java/org/exist/xquery/value/PreorderedValueSequence.java
  exist-core/src/main/java/org/exist/xquery/value/Sequence.java
  exist-core/src/main/java/org/exist/xquery/value/SubSequence.java
  exist-core/src/main/java/org/exist/xquery/value/ValueSequence.java
Labels: bug

#4410 [5.x.x] Improve out-of-scope detection for binary variables
  exist-core/src/main/java/org/exist/dom/memtree/NodeImpl.java
  exist-core/src/main/java/org/exist/dom/persistent/AVLTreeNodeSet.java
  exist-core/src/main/java/org/exist/dom/persistent/EmptyNodeSet.java
  exist-core/src/main/java/org/exist/dom/persistent/ExtArrayNodeSet.java
  exist-core/src/main/java/org/exist/dom/persistent/NewArrayNodeSet.java
  exist-core/src/main/java/org/exist/dom/persistent/NodeProxy.java
  exist-core/src/main/java/org/exist/dom/persistent/SortedNodeSet.java
  exist-core/src/main/java/org/exist/dom/persistent/VirtualNodeSet.java
  exist-core/src/main/java/org/exist/xquery/FunctionCall.java
  exist-core/src/main/java/org/exist/xquery/RangeSequence.java
  exist-core/src/main/java/org/exist/xquery/functions/array/ArrayType.java
  exist-core/src/main/java/org/exist/xquery/functions/map/MapType.java
  exist-core/src/main/java/org/exist/xquery/value/ArrayListValueSequence.java
  exist-core/src/main/java/org/exist/xquery/value/AtomicValue.java
  exist-core/src/main/java/org/exist/xquery/value/BinaryValueFromFile.java
  exist-core/src/main/java/org/exist/xquery/value/BinaryValueFromInputStream.java
  exist-core/src/main/java/org/exist/xquery/value/EmptySequence.java
  exist-core/src/main/java/org/exist/xquery/value/OrderedValueSequence.java
  exist-core/src/main/java/org/exist/xquery/value/PreorderedValueSequence.java
  exist-core/src/main/java/org/exist/xquery/value/Sequence.java
  exist-core/src/main/java/org/exist/xquery/value/SubSequence.java
  exist-core/src/main/java/org/exist/xquery/value/ValueSequence.java
Labels: bug

#4408 [4.x.x] Improve out-of-scope detection for binary variables
  exist-core/src/main/java/org/exist/dom/memtree/DocumentImpl.java
  exist-core/src/main/java/org/exist/dom/memtree/NodeImpl.java
  exist-core/src/main/java/org/exist/dom/persistent/AVLTreeNodeSet.java
  exist-core/src/main/java/org/exist/dom/persistent/EmptyNodeSet.java
  exist-core/src/main/java/org/exist/dom/persistent/ExtArrayNodeSet.java
  exist-core/src/main/java/org/exist/dom/persistent/NewArrayNodeSet.java
  exist-core/src/main/java/org/exist/dom/persistent/NodeProxy.java
  exist-core/src/main/java/org/exist/dom/persistent/SortedNodeSet.java
  exist-core/src/main/java/org/exist/dom/persistent/VirtualNodeSet.java
  exist-core/src/main/java/org/exist/xquery/FunctionCall.java
  exist-core/src/main/java/org/exist/xquery/RangeSequence.java
  exist-core/src/main/java/org/exist/xquery/functions/array/ArrayType.java
  exist-core/src/main/java/org/exist/xquery/functions/map/MapExpr.java
  exist-core/src/main/java/org/exist/xquery/functions/map/MapType.java
  exist-core/src/main/java/org/exist/xquery/value/AtomicValue.java
  exist-core/src/main/java/org/exist/xquery/value/BinaryValueFromFile.java
  exist-core/src/main/java/org/exist/xquery/value/BinaryValueFromInputStream.java
  exist-core/src/main/java/org/exist/xquery/value/EmptySequence.java
  exist-core/src/main/java/org/exist/xquery/value/OrderedValueSequence.java
  exist-core/src/main/java/org/exist/xquery/value/PreorderedValueSequence.java
  exist-core/src/main/java/org/exist/xquery/value/Sequence.java
  exist-core/src/main/java/org/exist/xquery/value/SubSequence.java
  exist-core/src/main/java/org/exist/xquery/value/ValueSequence.java
Labels: bug

#4407 Use Saxon for fn:matches regular expression handling.
  exist-core/src/main/java/org/exist/xquery/functions/fn/FunMatches.java
  exist-core/src/test/xquery/regex.xml
Labels: enhancement, xquery
