Repository eXist-db/exist, pull requests merged in 2022-08, with the labels that each got.

#4483 [feature] Implement the fn:uri-collection function
  exist-core/src/main/java/org/exist/xquery/ErrorCodes.java
  exist-core/src/main/java/org/exist/xquery/XQueryContext.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FnModule.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FunUriCollection.java
  exist-core/src/test/xquery/xquery3/fnUriCollection.xqm
Labels: enhancement

#4474 fix Rest client file encoding
  exist-core/src/main/java/org/exist/http/RESTServer.java
  exist-core/src/main/java/org/exist/http/servlets/EXistServlet.java
  exist-core/src/test/java/org/exist/http/RESTServiceTest.java
Labels: bug

#4264 [enhancement] add serialization option that inserts final newline
  exist-core/src/main/java/org/exist/storage/serializers/EXistOutputKeys.java
  exist-core/src/main/java/org/exist/util/serializer/IndentingXMLWriter.java
  exist-core/src/main/java/org/exist/util/serializer/json/JSONSerializer.java
  exist-core/src/main/java/org/exist/xquery/util/SerializerUtils.java
  exist-core/src/test/xquery/xquery3/serialize.xql
  extensions/modules/file/src/main/java/org/exist/xquery/modules/file/Sync.java
  extensions/modules/file/src/test/xquery/modules/file/serialize.xqm
  extensions/modules/file/src/test/xquery/modules/file/sync-serialize.xqm
Labels: enhancement

#4386 Implement fn:transform
  exist-core/src/main/java/org/exist/storage/DBBroker.java
  exist-core/src/main/java/org/exist/xquery/ErrorCodes.java
  exist-core/src/main/java/org/exist/xquery/XQueryContext.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FnModule.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FnTransform.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/transform/Convert.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/transform/Delivery.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/transform/Options.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/transform/SerializationParameters.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/transform/Transform.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/transform/TreeUtils.java
  exist-core/src/main/java/org/exist/xquery/value/NumericValue.java
  exist-core/src/test/java/org/exist/xquery/XQueryFunctionsTest.java
  exist-core/src/test/java/org/exist/xquery/functions/fn/transform/FunTransformTest.java
  exist-core/src/test/java/xquery/xquery3/XQuery3Tests.java
  exist-core/src/test/xquery/xquery3/transform/fnTransform10.xqm
  exist-core/src/test/xquery/xquery3/transform/fnTransform11.xqm
  exist-core/src/test/xquery/xquery3/transform/fnTransform12.xqm
  exist-core/src/test/xquery/xquery3/transform/fnTransform15.xqm
  exist-core/src/test/xquery/xquery3/transform/fnTransform2-3.xqm
  exist-core/src/test/xquery/xquery3/transform/fnTransform33.xqm
  exist-core/src/test/xquery/xquery3/transform/fnTransform4-5.xqm
  exist-core/src/test/xquery/xquery3/transform/fnTransform5.xqm
  exist-core/src/test/xquery/xquery3/transform/fnTransform52.xqm
  exist-core/src/test/xquery/xquery3/transform/fnTransform53.xqm
  exist-core/src/test/xquery/xquery3/transform/fnTransform63.xqm
  exist-core/src/test/xquery/xquery3/transform/fnTransform66.xqm
  exist-core/src/test/xquery/xquery3/transform/fnTransform67.xqm
  exist-core/src/test/xquery/xquery3/transform/fnTransform68.xqm
  exist-core/src/test/xquery/xquery3/transform/fnTransform71.xqm
  exist-core/src/test/xquery/xquery3/transform/fnTransform74.xqm
  exist-core/src/test/xquery/xquery3/transform/fnTransform79.xqm
  exist-core/src/test/xquery/xquery3/transform/fnTransform7c.xqm
  exist-core/src/test/xquery/xquery3/transform/fnTransform7e.xqm
  exist-core/src/test/xquery/xquery3/transform/fnTransform82e.xqm
  exist-core/src/test/xquery/xquery3/transform/fnTransform84.xqm
  exist-core/src/test/xquery/xquery3/transform/fnTransform87.xqm
  exist-core/src/test/xquery/xquery3/transform/fnTransformErr16.xqm
  exist-core/src/test/xquery/xquery3/transform/fnTransformErr18.xqm
  exist-core/src/test/xquery/xquery3/transform/fnTransformErr6.xqm
  exist-core/src/test/xquery/xquery3/transform/fnTransformErr9.xqm
  exist-core/src/test/xquery/xquery3/transform/fnTransformParams.xqm
Labels: enhancement, xquery

#4525 [4.x.x] fix resource leak (and file lock)
  exist-core/src/main/java/org/exist/xquery/value/BinaryValueFromFile.java
Labels: bug

#4521 fix resource leak (and file lock)
  exist-core/src/main/java/org/exist/xquery/value/BinaryValueFromFile.java
Labels: bug

#4524 [5.x.x] fix resource leak (and file lock)
  exist-core/src/main/java/org/exist/xquery/value/BinaryValueFromFile.java
Labels: bug
