Repository eXist-db/exist, pull requests merged in 2022-04, with the labels that each got.

#4302 Fix license header (previously eXist 4.x.x syntax)
  exist-core/src/test/java/org/exist/xquery/XQueryIsLibraryModuleTest.java
Labels: bug

#4307 [5.x.x] Update to Xerces 2.12.2
  exist-core/pom.xml
Labels: bug

#4306 Update to Xerces 2.12.2
  exist-core/pom.xml
Labels: bug

#4308 [4.x.x] Update from Xerces 2.11.0 to 2.12.2
  .classpath
  lib/endorsed/xercesImpl-2.11.0.jar
  lib/endorsed/xercesImpl-2.12.2.jar
  nbproject/project.properties
Labels: enhancement

#4299 [5.x.x] Send a valid HTTP Accept Header
  exist-core/src/main/java/org/exist/source/URLSource.java
  exist-parent/pom.xml
Labels: bug

#4310 [5.x.x] Reinstate all XQuery 3 tests
  exist-core/src/test/java/xquery/xquery3/XQuery3Tests.java
Labels: regression

#4294 Optimise URI Encoding of Path Components
  exist-core-jmh/pom.xml
  exist-core-jmh/src/main/java/org/exist/storage/lock/LockTableBenchmark.java
  exist-core-jmh/src/main/java/org/exist/xquery/utils/URIUtilsBenchmark.java
  exist-core/pom.xml
  exist-core/src/main/java/org/exist/xquery/util/URIUtils.java
  exist-core/src/test/java/org/exist/xquery/util/URIUtilsTest.java
Labels: enhancement, performance

#4315 Drop build workflow
  .github/workflows/ci-build.yml
Labels: enhancement, ci

#4316 Use builtin maven-cache of setup-java action
  .github/workflows/ci-test.yml
Labels: enhancement, ci

#4323 Update Jing from version 20151127 to 20181222
  .classpath
  lib/optional/jing-20151127.jar
  lib/optional/jing-20181222.jar
  nbproject/project.properties
Labels: enhancement

#4328 Fix XML Catalogue Resolution
  exist-core/pom.xml
  exist-core/src/main/java/org/exist/resolver/ResolverFactory.java
  exist-core/src/main/java/org/exist/resolver/XercesXmlResolverAdapter.java
  exist-core/src/main/java/org/exist/util/Configuration.java
  exist-core/src/main/java/org/exist/util/XMLReaderObjectFactory.java
  exist-core/src/main/java/org/exist/validation/Validator.java
  exist-core/src/main/java/org/exist/validation/resolver/SearchResourceResolver.java
  exist-core/src/main/java/org/exist/validation/resolver/eXistXMLCatalogResolver.java
  exist-core/src/main/java/org/exist/xmlrpc/RpcConnection.java
  exist-core/src/main/java/org/exist/xquery/functions/validation/Jaxp.java
  exist-core/src/test/java/org/exist/util/XMLReaderPoolTest.java
  exist-parent/pom.xml
Labels: bug

#4320 [4.x.x] Fix XML Catalogue Resolution
  exist-core/src/main/java/org/exist/resolver/ResolverFactory.java
  exist-core/src/main/java/org/exist/resolver/XercesXmlResolverAdapter.java
  exist-core/src/main/java/org/exist/util/Configuration.java
  exist-core/src/main/java/org/exist/util/XMLReaderObjectFactory.java
  exist-core/src/main/java/org/exist/validation/Validator.java
  exist-core/src/main/java/org/exist/validation/resolver/SearchResourceResolver.java
  exist-core/src/main/java/org/exist/validation/resolver/eXistXMLCatalogResolver.java
  exist-core/src/main/java/org/exist/xmlrpc/RpcConnection.java
  exist-core/src/main/java/org/exist/xquery/functions/validation/Jaxp.java
  exist-core/src/main/java/org/exist/xquery/functions/validation/Validation.java
  lib/endorsed/xmlresolver-4.2.0-data.jar
  lib/endorsed/xmlresolver-4.2.0.jar
Labels: bug

#4337 request:get-data#0 should support Chunked Transfer Encoding
  exist-core/src/main/java/org/exist/xquery/functions/request/GetData.java
  exist-core/src/test/java/org/exist/xquery/functions/request/GetDataTest.java
Labels: bug

#4335 Log xsl:fo render errors to exist.log
  extensions/modules/xslfo/src/main/java/org/exist/xquery/modules/xslfo/RenderFunction.java
Labels: bug

#4322 [bugfix] file:sync#3 updates only changed files
  extensions/modules/file/src/main/java/org/exist/xquery/modules/file/Sync.java
  extensions/modules/file/src/test/resources/util/fixtures.xqm
  extensions/modules/file/src/test/resources/util/helper.xqm
  extensions/modules/file/src/test/xquery/modules/file/sync.xqm
Labels: bug, regression

#4344 [4.x.x] Reinstate code for a historical Jetty bugfix
  exist-core/src/main/java/org/exist/xquery/functions/request/GetData.java
Labels: bug

#4343 [5.x.x] request:get-data#0 should support Chunked Transfer Encoding
  exist-core/src/main/java/org/exist/xquery/functions/request/GetData.java
  exist-core/src/test/java/org/exist/xquery/functions/request/GetDataTest.java
Labels: bug

#4342 [4.x.x] request:get-data#0 should support Chunked Transfer Encoding
  .idea/runConfigurations.xml
  exist-core/src/main/java/org/exist/xquery/functions/request/GetData.java
  exist-core/src/test/java/org/exist/xquery/functions/request/GetDataTest.java
Labels: bug

#4340 [4.x.x] Fix catalog uris when using Windows Paths
  exist-core/src/main/java/org/exist/resolver/ResolverFactory.java
  exist-core/src/main/java/org/exist/resolver/XercesXmlResolverAdapter.java
  exist-core/src/main/java/org/exist/validation/Validator.java
Labels: bug

#4338 Fix catalog uris when using Windows Paths
  exist-core/src/main/java/org/exist/resolver/ResolverFactory.java
Labels: bug

#4333 Run XQTS against eXist-db in CI
  .github/workflows/ci-xqts.yml
  exist-distribution/pom.xml
  exist-parent/pom.xml
  exist-xqts/LGPL-21-license.txt
  exist-xqts/pom.xml
  pom.xml
Labels: enhancement, ci

#4346 License file for exist-xqts distro needs to be excluded from license checks
  exist-parent/pom.xml
Labels: bug

#4360 Implement fn:default-language#0
  exist-core/src/main/java/org/exist/interpreter/Context.java
  exist-core/src/main/java/org/exist/xquery/XQueryContext.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FnDefaultLanguage.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FnFormatDates.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FnModule.java
  exist-core/src/test/java/org/exist/xquery/XQueryFunctionsTest.java
  exist-core/src/test/xquery/xquery3/fnLanguage.xqm
Labels: enhancement, xquery

#4356 Improve performance of JAC Query Dialog
  exist-core/src/main/java/org/exist/client/QueryDialog.java
Labels: enhancement

#4357 [5.x.x] Improve performance of JAC Query Dialog
  exist-core/src/main/java/org/exist/client/QueryDialog.java
Labels: enhancement

#4358 [4.x.x] Improve performance of JAC Query Dialog
  eXist-db.iml
  exist-core/src/main/java/org/exist/client/QueryDialog.java
  exist-core/src/main/java/org/exist/util/Holder.java
Labels: enhancement

#4352 Capture xs:anyURI error details in XMLDB Module
  exist-core/src/main/java/org/exist/xquery/XPathException.java
  exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBAbstractCollectionManipulator.java
  exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBAuthenticate.java
  exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBCopy.java
  exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBGetMimeType.java
  exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBHasLock.java
  exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBMove.java
  exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBRemove.java
  exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBRename.java
  exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBSetMimeType.java
  exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBSize.java
  exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBStore.java
Labels: bug

#4353 [5.x.x] Capture xs:anyURI error details in XMLDB Module
  exist-core/src/main/java/org/exist/xquery/XPathException.java
  exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBAbstractCollectionManipulator.java
  exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBAuthenticate.java
  exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBCopy.java
  exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBGetMimeType.java
  exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBHasLock.java
  exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBMove.java
  exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBRemove.java
  exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBRename.java
  exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBSetMimeType.java
  exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBSize.java
  exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBStore.java
Labels: bug

#4354 [4.x.x] Capture xs:anyURI error details in XMLDB Module
  exist-core/src/main/java/org/exist/xquery/XPathException.java
  exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBAbstractCollectionManipulator.java
  exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBCopy.java
  exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBDocument.java
  exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBGetMimeType.java
  exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBHasLock.java
  exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBMove.java
  exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBRemove.java
  exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBRename.java
  exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBSetMimeType.java
  exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBSetResourcePermissions.java
  exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBSize.java
  exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBStore.java
Labels: bug

#4349 Improvements to system:as-user
  exist-core/src/main/java/org/exist/xquery/functions/system/AsUser.java
  exist-core/src/main/java/org/exist/xquery/functions/system/SystemModule.java
  exist-core/src/test/java/xquery/system/SystemTests.java
  exist-core/src/test/xquery/system/as-user.xqm
Labels: enhancement

#4364 [4.x.x] Add missing entity-resolver elements to the Schema for collection.xconf
  schema/collection.xconf.xsd
Labels: bug

#4363 [5.x.x] Add missing entity-resolver elements to the Schema for collection.xconf
  schema/collection.xconf.xsd
Labels: bug

#4362 Add missing entity-resolver elements to the Schema for collection.xconf
  schema/collection.xconf.xsd
Labels: bug
