Repository eXist-db/exist, pull requests merged in 2023-05, with the labels that each got.

#4892 Correct the capitalisation and spelling of 'Lucene' in error messages
  extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/LuceneIndex.java
Labels: bug

#4899 [fix] jetty configuration changes don't stick, and eventually crash eXist-db
  exist-core/src/main/java/org/exist/launcher/ConfigurationDialog.java
  exist-core/src/main/java/org/exist/launcher/ConfigurationUtility.java
  exist-core/src/main/resources/org/exist/launcher/jetty.xsl
Labels: bug

#4895 Fix docker builds
  .github/workflows/ci-deploy.yml
  exist-docker/src/main/resources-filtered/Dockerfile
Labels: bug

#4854 [feature] Allow Saxon licensed editions (EE and PE)
  exist-core/src/main/java/org/exist/storage/BrokerPool.java
  exist-core/src/main/java/org/exist/util/Configuration.java
  exist-core/src/main/java/org/exist/util/SaxonConfiguration.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FnTransform.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/transform/Options.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/transform/Transform.java
  exist-core/src/test/java/org/exist/config/SaxonConfigTest.java
  exist-core/src/test/resources-filtered/conf.xml
  exist-core/src/test/xquery/xquery3/transform/fnTransform66.xqm
  exist-distribution/src/main/config/conf.xml
  exist-distribution/src/main/config/saxon-config.xml
Labels: enhancement, needs documentation

#4883 Fix missing fn:transform global parameters
  exist-core/src/main/java/org/exist/xquery/functions/fn/transform/Options.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/transform/Transform.java
  exist-core/src/test/resources/org/exist/xquery/tei-toc.xsl
  exist-core/src/test/xquery/xquery3/transform/fnTransformIssue4609.xqm
Labels: bug

#4913 [6.x.x] Ensure that EXPath packages installed in $EXIST_HOME/data/expathrepo are filesystem portable
  exist-core/src/main/java/org/exist/repo/ClasspathHelper.java
  exist-core/src/main/java/org/exist/repo/ExistPkgExtension.java
Labels: bug

#4902 Ensure that EXPath packages installed in $EXIST_HOME/data/expathrepo are filesystem portable
  exist-core/src/main/java/org/exist/repo/ClasspathHelper.java
  exist-core/src/main/java/org/exist/repo/ExistPkgExtension.java
Labels: bug, needs 4.x.x backport

#4917 Further improvements to GitHub Actions config
  .github/workflows/ci-deploy.yml
  .github/workflows/ci-test.yml
  .github/workflows/ci-xqts.yml
  .github/workflows/sonarcloud.yml
Labels: ci

#4927 Remove pre-1.0 syntax for variable declarations
  exist-core/src/main/antlr/org/exist/xquery/parser/XQuery.g
  exist-core/src/test/java/org/exist/http/RESTServiceTest.java
  exist-core/src/test/java/org/exist/xquery/XPathQueryTest.java
  exist-core/src/test/java/org/exist/xquery/XQueryFunctionsTest.java
  exist-core/src/test/java/org/exist/xquery/XQueryTest.java
  exist-core/src/test/java/org/exist/xquery/functions/util/EvalTest.java
Labels: enhancement

#4900 [fix] castable as for untyped atomic value(s)
  exist-core/src/main/java/org/exist/xquery/value/UntypedAtomicValue.java
  exist-core/src/test/xquery/xquery3/castable-untyped-atomic.xqm
Labels: bug

#4934 Use newer copy-maven-plugin which does not have CVE issues with its dependencies
  exist-distribution/pom.xml
Labels: enhancement

#4941 Upgrade from JAXB 3 to JAXB 4
  exist-parent/pom.xml
Labels: enhancement

#4930 Fix passing database nodes from XQuery to fn:transform as parameters
  exist-core/src/main/java/org/exist/xquery/functions/fn/transform/Convert.java
  exist-core/src/test/java/xquery/xquery3/XQuery3Tests.java
  exist-core/src/test/xquery/xquery3/transform/fnTransformRegressionDocAsParameter.xqm
Labels: bug

#4931 Fix the resolution of XmldbURIs from within fn:transform
  exist-core/src/main/java/org/exist/util/SaxonConfiguration.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/transform/Options.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/transform/Transform.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/transform/URIResolution.java
  exist-core/src/test/java/org/exist/xquery/functions/fn/transform/FunTransformTest.java
Labels: bug, enhancement

#4859 Use mvnd in GitHub Actions
  .github/actions/install-mvnd/action.yml
  .github/workflows/ci-test.yml
Labels: ci
