Repository eXist-db/exist, pull requests merged in 2023-01, with the labels that each got.

#4668 [BUG] HTML5 serializer should escape contents of title and textarea elements
  exist-core/src/main/java/org/exist/util/serializer/HTML5Writer.java
  exist-core/src/test/xquery/xquery3/serialize.xql
Labels: bug, high prio, security

#4324 [5.x.x] backport of encoding and file module fixes
  exist-ant/src/main/java/org/exist/ant/XMLDBXPathTask.java
  exist-ant/src/main/java/org/exist/ant/XMLDBXQueryTask.java
  exist-core/src/main/java/org/exist/backup/Backup.java
  exist-core/src/main/java/org/exist/backup/SystemExport.java
  exist-core/src/main/java/org/exist/backup/SystemImport.java
  exist-core/src/main/java/org/exist/client/InteractiveClient.java
  exist-core/src/main/java/org/exist/http/RESTServer.java
  exist-core/src/main/java/org/exist/http/Response.java
  exist-core/src/main/java/org/exist/http/servlets/AbstractExistHttpServlet.java
  exist-core/src/main/java/org/exist/http/servlets/HttpRequestWrapper.java
  exist-core/src/main/java/org/exist/http/servlets/HttpServletRequestWrapper.java
  exist-core/src/main/java/org/exist/http/servlets/RedirectorServlet.java
  exist-core/src/main/java/org/exist/http/servlets/XSLTServlet.java
  exist-core/src/main/java/org/exist/http/urlrewrite/XQueryURLRewrite.java
  exist-core/src/main/java/org/exist/protocolhandler/xmlrpc/XmlrpcDownload.java
  exist-core/src/main/java/org/exist/protocolhandler/xmlrpc/XmlrpcUpload.java
  exist-core/src/main/java/org/exist/source/BinarySource.java
  exist-core/src/main/java/org/exist/source/DBSource.java
  exist-core/src/main/java/org/exist/storage/serializers/Serializer.java
  exist-core/src/main/java/org/exist/storage/serializers/XIncludeFilter.java
  exist-core/src/main/java/org/exist/util/serializer/AbstractSerializer.java
  exist-core/src/main/java/org/exist/util/serializer/TEXTWriter.java
  exist-core/src/main/java/org/exist/util/serializer/XMLWriter.java
  exist-core/src/main/java/org/exist/validation/internal/node/NodeSerializer.java
  exist-core/src/main/java/org/exist/validation/resolver/AnyUriResolver.java
  exist-core/src/main/java/org/exist/validation/resolver/SearchResourceResolver.java
  exist-core/src/main/java/org/exist/xmldb/LocalCollection.java
  exist-core/src/main/java/org/exist/xmldb/RemoteResourceSet.java
  exist-core/src/main/java/org/exist/xmldb/XmldbURI.java
  exist-core/src/main/java/org/exist/xquery/functions/request/GetData.java
  exist-core/src/main/java/org/exist/xquery/functions/response/Stream.java
  exist-core/src/main/java/org/exist/xquery/functions/util/BinaryToString.java
  exist-core/src/main/java/org/exist/xquery/util/SerializerUtils.java
  exist-core/src/main/java/org/exist/xquery/util/URIUtils.java
  exist-core/src/test/xquery/unparsed-text.xql
  extensions/modules/file/src/main/java/org/exist/xquery/modules/file/Sync.java
  extensions/modules/file/src/test/resources/util/fixtures.xqm
  extensions/modules/file/src/test/resources/util/helper.xqm
  extensions/modules/file/src/test/xquery/modules/file/sync-serialize.xqm
  extensions/modules/file/src/test/xquery/modules/file/sync.xqm
Labels: bug, regression

#4679 [4.x.x] Fix http redirect schema test
  exist-core/src/test/java/org/exist/validation/CollectionConfigurationValidationModeTest.java
Labels: bug

#4680 Fix http redirect schema test
  exist-core/src/test/java/org/exist/validation/CollectionConfigurationValidationModeTest.java
Labels: bug

#4681 [5.x.x] Fix http redirect schema test
  exist-core/src/test/java/org/exist/validation/CollectionConfigurationValidationModeTest.java
Labels: bug

#4678 [4.x.x] Canonical source of apps
  build.properties
  build/scripts/installer.xml
  build/scripts/setup.xml
  installer/apps.properties
Labels: bug

#4684 Also build the IzPack installer
  exist-versioning-release.md
Labels: bug

#4676 [5.x.x] Also build the IzPack installer
  exist-versioning-release.md
Labels: bug

#4685 Windows Service installer - prunsrv.exe expects memory to be supplied as an integer
  exist-core/src/main/java/org/exist/launcher/WindowsServiceManager.java
  exist-core/src/test/java/org/exist/launcher/WindowsServiceManagerTest.java
Labels: bug, windows

#4696 [bugfix] corrects version number on missed POMs
  exist-core-jcstress/pom.xml
  exist-core-jmh/pom.xml
Labels: bug, ci
