Repository eXist-db/exist, pull requests merged in 2023-02, with the labels that each got.

#4708 Ensure that XSLT stylesheets are only compiled once when used from an xsl-pi in the REST Server
  .idea/runConfigurations/Java_Admin_Client.xml
  .idea/runConfigurations/Jetty_Server.xml
  .idea/runConfigurations/Local_Jetty_Server.xml
  exist-core/src/main/java/org/exist/http/RESTServer.java
  exist-core/src/main/java/org/exist/storage/serializers/Serializer.java
  exist-core/src/main/java/org/exist/storage/serializers/XIncludeFilter.java
  exist-core/src/main/java/org/exist/util/serializer/AbstractSerializer.java
  exist-core/src/main/java/org/exist/util/serializer/CharacterMappingWriter.java
  exist-core/src/main/java/org/exist/util/serializer/SerializerObjectFactory.java
  exist-core/src/main/java/org/exist/xquery/util/SerializerUtils.java
  exist-core/src/test/java/org/exist/http/RESTServiceTest.java
Labels: bug, regression

#4709 [5.x.x] Ensure that XSLT stylesheets are only compiled once when used from an xsl-pi in the REST Server
  exist-core/src/main/java/org/exist/http/RESTServer.java
  exist-core/src/main/java/org/exist/storage/serializers/Serializer.java
  exist-core/src/main/java/org/exist/storage/serializers/XIncludeFilter.java
  exist-core/src/main/java/org/exist/util/serializer/SerializerObjectFactory.java
  exist-core/src/test/java/org/exist/http/RESTServiceTest.java
Labels: bug, regression

#4715 [4.x.x] Ensure that XSLT stylesheets are only compiled once when used from an xsl-pi in the REST Server
  exist-core/src/main/java/org/exist/storage/serializers/Serializer.java
  exist-core/src/main/java/org/exist/storage/serializers/XIncludeFilter.java
  exist-core/src/main/java/org/exist/util/serializer/SerializerObjectFactory.java
  exist-core/src/test/java/org/exist/http/RESTServiceTest.java
Labels: bug, regression

#4703 [hotfix] fn:serialize issues
  exist-core/src/main/java/org/exist/xquery/functions/fn/FunSerialize.java
  exist-core/src/main/java/org/exist/xquery/functions/util/Eval.java
  exist-core/src/main/java/org/exist/xquery/util/SerializerUtils.java
  exist-core/src/test/java/xquery/xquery3/XQuery3Tests.java
  exist-core/src/test/xquery/xquery3/serialize.xql
Labels: bug, regression, xquery

#4574 Upgrade to Java 17
  .github/dependabot.yml
  .github/workflows/ci-deploy.yml
  .github/workflows/ci-docs.yml
  .github/workflows/ci-test.yml
  .github/workflows/ci-xqts.yml
  .github/workflows/sonarcloud.yml
  .idea/runConfigurations/Java_Admin_Client.xml
  .idea/runConfigurations/Jetty_Server.xml
  .idea/runConfigurations/Local_Jetty_Server.xml
  BUILD.md
  README.md
  exist-ant/pom.xml
  exist-core/pom.xml
  exist-core/src/main/java/org/exist/dom/persistent/SymbolTable.java
  exist-core/src/main/java/org/exist/security/internal/HttpSessionAuthentication.java
  exist-core/src/main/java/org/exist/source/SourceFactory.java
  exist-core/src/main/java/org/exist/storage/BrokerPool.java
  exist-core/src/main/java/org/exist/storage/journal/Journal.java
  exist-core/src/main/java/org/exist/storage/journal/JournalManager.java
  exist-core/src/main/java/org/exist/xmldb/LocalUserManagementService.java
  exist-core/src/main/java/org/exist/xquery/util/DocUtils.java
  exist-core/src/test/java/org/exist/storage/journal/AbstractJournalTest.java
  exist-core/src/test/java/org/exist/storage/journal/JournalXmlTest.java
  exist-core/src/test/xquery/util/util.xml
  exist-distribution/pom.xml
  exist-docker/pom.xml
  exist-docker/src/main/resources-filtered/Dockerfile
  exist-docker/src/main/resources-filtered/Dockerfile-DEBUG
  exist-docker/src/main/resources-filtered/README.md
  exist-parent/pom.xml
  extensions/indexes/lucene/pom.xml
  extensions/indexes/spatial/pom.xml
  extensions/modules/counter/pom.xml
  extensions/modules/file/pom.xml
  extensions/modules/mail/src/main/java/org/exist/xquery/modules/mail/MailModule.java
  extensions/modules/persistentlogin/pom.xml
  extensions/modules/sql/src/test/java/org/exist/xquery/modules/sql/ConnectionIT.java
  extensions/modules/sql/src/test/java/org/exist/xquery/modules/sql/ImplicitConnectionCloseIT.java
  extensions/modules/sql/src/test/java/org/exist/xquery/modules/sql/JndiConnectionIT.java
  extensions/security/activedirectory/pom.xml
  extensions/security/ldap/pom.xml
Labels: enhancement

#3905 [feature] Remove IPrange filter to be deployed automagically.
  exist-distribution/pom.xml
Labels: enhancement, security

#4470 Bugfix/cardinality enforcement
  exist-core/src/main/java/org/exist/xquery/functions/fn/ExtCollection.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FnFormatIntegers.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FunDocumentURI.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FunXmlToJson.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/JSON.java
Labels: bug

#3701 Remove legacy json utilities
  exist-core/src/main/resources/org/exist/xquery/lib/json.xq
  exist-core/src/main/resources/org/exist/xquery/lib/json.xq.html
  exist-core/src/main/resources/org/exist/xquery/lib/jsonp.xq
  exist-distribution/src/main/config/conf.xml
Labels: deprecation

#4730 Update to exist-xqts-runner 1.2.0
  exist-xqts/pom.xml
Labels: enhancement

#4649 Correct the response code of the REST Server when executing an invalid stored query (2)
  exist-core/src/main/java/org/exist/http/RESTServer.java
Labels: bug

#3376 Switch to `empty least` as default ordering behaviour in XQuery
  exist-core/pom.xml
  exist-core/src/main/java/org/exist/xquery/XQueryContext.java
  exist-core/src/test/xquery/order.xqm
Labels: enhancement, xquery

#3738 Switch map:merge from use-last to use-first as per XQuery spec
  exist-core/src/main/java/org/exist/xquery/functions/map/AbstractMapType.java
  exist-core/src/main/java/org/exist/xquery/functions/map/MapFunction.java
  exist-core/src/test/xquery/maps/maps.xqm
Labels: enhancement, xquery

#3991 Refactor DBBroker into an Interface
  exist-core/src/main/java/org/exist/storage/DBBroker.java
  exist-core/src/main/java/org/exist/storage/NativeBroker.java
  exist-core/src/main/java/org/exist/storage/NativeValueIndex.java
Labels: enhancement

#4578 Preserve XML Declaration
  exist-core/pom.xml
  exist-core/src/main/java/org/exist/Indexer.java
  exist-core/src/main/java/org/exist/client/InteractiveClient.java
  exist-core/src/main/java/org/exist/collections/triggers/DocumentTriggers.java
  exist-core/src/main/java/org/exist/collections/triggers/SAXTrigger.java
  exist-core/src/main/java/org/exist/dom/memtree/DocumentBuilderReceiver.java
  exist-core/src/main/java/org/exist/dom/persistent/DocumentImpl.java
  exist-core/src/main/java/org/exist/dom/persistent/XMLDeclarationImpl.java
  exist-core/src/main/java/org/exist/http/RESTServer.java
  exist-core/src/main/java/org/exist/http/RESTServerParameter.java
  exist-core/src/main/java/org/exist/indexing/AbstractMatchListener.java
  exist-core/src/main/java/org/exist/storage/index/CollectionStore.java
  exist-core/src/main/java/org/exist/storage/serializers/AbstractChainOfReceivers.java
  exist-core/src/main/java/org/exist/storage/serializers/EXistOutputKeys.java
  exist-core/src/main/java/org/exist/storage/serializers/NativeSerializer.java
  exist-core/src/main/java/org/exist/storage/serializers/Serializer.java
  exist-core/src/main/java/org/exist/storage/serializers/XIncludeFilter.java
  exist-core/src/main/java/org/exist/util/Configuration.java
  exist-core/src/main/java/org/exist/util/serializer/AbstractSerializer.java
  exist-core/src/main/java/org/exist/util/serializer/CharacterMappingWriter.java
  exist-core/src/main/java/org/exist/util/serializer/EXISerializer.java
  exist-core/src/main/java/org/exist/util/serializer/MicroXmlWriter.java
  exist-core/src/main/java/org/exist/util/serializer/Receiver.java
  exist-core/src/main/java/org/exist/util/serializer/ReceiverToSAX.java
  exist-core/src/main/java/org/exist/util/serializer/SAXSerializer.java
  exist-core/src/main/java/org/exist/util/serializer/SerializerWriter.java
  exist-core/src/main/java/org/exist/util/serializer/XMLWriter.java
  exist-core/src/main/java/org/exist/xmldb/LocalCollection.java
  exist-core/src/main/java/org/exist/xmlrpc/RpcConnection.java
  exist-core/src/test/java/org/exist/backup/XMLDBBackupTest.java
  exist-core/src/test/java/org/exist/http/RESTServiceTest.java
  exist-core/src/test/java/org/exist/util/serializer/HTML5WriterTest.java
  exist-core/src/test/java/org/exist/xmldb/SerializationTest.java
  exist-core/src/test/java/org/exist/xquery/TransformTest.java
  exist-distribution/src/main/config/client.properties
  exist-distribution/src/main/config/conf.xml
  exist-distribution/src/main/config/webdav.properties
  extensions/contentextraction/pom.xml
  extensions/contentextraction/src/main/java/org/exist/contentextraction/ContentReceiver.java
  extensions/webdav/src/main/resources/org/exist/webdav/webdav.properties
  extensions/webdav/src/test/java/org/exist/webdav/SerializationTest.java
  schema/conf.xsd
Labels: enhancement

#4741 [bugfix] NPE on qname of CDATA section
  exist-core/src/main/java/org/exist/dom/QName.java
  exist-core/src/main/java/org/exist/dom/persistent/StoredNode.java
  exist-core/src/test/java/org/exist/xquery/AbstractDescendantOrSelfNodeKindTest.java
Labels: bug

#4766 Hotfix for NPE in LuceneMatchListener.scanMatches when expanding node containing both Lucene & NGram matches
  extensions/indexes/indexes-integration-tests/pom.xml
  extensions/indexes/indexes-integration-tests/src/test/java/xquery/indexing/tests/IndexingTests.java
  extensions/indexes/indexes-integration-tests/src/test/resources-filtered/conf.xml
  extensions/indexes/indexes-integration-tests/src/test/resources/log4j2.xml
  extensions/indexes/indexes-integration-tests/src/test/xquery/indexing/tests/exist-matches.xqm
  extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/LuceneMatchListener.java
  extensions/indexes/pom.xml
Labels: bug

#4622 Fix bugs in XQSuite and XQuery tests written for XQSuite
  .github/workflows/ci-deploy.yml
  exist-core/pom.xml
  exist-core/src/main/java/org/exist/xquery/UntypedValueCheck.java
  exist-core/src/main/java/org/exist/xquery/XQueryContext.java
  exist-core/src/main/java/org/exist/xquery/functions/inspect/InspectFunctionHelper.java
  exist-core/src/main/java/org/exist/xquery/functions/util/IndexKeys.java
  exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBGetMimeType.java
  exist-core/src/main/java/org/exist/xquery/value/Type.java
  exist-core/src/main/resources/org/exist/xquery/lib/xqsuite/xqsuite.xql
  exist-core/src/test/xquery/arrays/arrays.xql
  exist-core/src/test/xquery/integers.xq
  exist-core/src/test/xquery/numbers/format-numbers.xql
  exist-core/src/test/xquery/optimizer/optimizer.xql
  exist-core/src/test/xquery/optimizer/positional.xql
  exist-core/src/test/xquery/type-promotion.xqm
  exist-core/src/test/xquery/xqsuite/xqsuite-assertions-dynamic.xqm
  exist-core/src/test/xquery/xqsuite/xqsuite-assertions-inline.xqm
  exist-core/src/test/xquery/xqsuite/xqsuite-assertions.resources.xqm.ignore
  exist-core/src/test/xquery/xquery3/parseIetfDate.xqm
  exist-core/src/test/xquery/xquery3/serialize.xql
  extensions/indexes/lucene/src/main/java/org/exist/xquery/modules/lucene/LuceneIndexKeys.java
  extensions/indexes/range/src/main/java/org/exist/xquery/modules/range/IndexKeys.java
  extensions/indexes/range/src/test/xquery/range/conditions.xql
  extensions/indexes/range/src/test/xquery/range/field-type.xql
  extensions/indexes/range/src/test/xquery/range/optimizer.xql
  extensions/indexes/range/src/test/xquery/range/types.xql
  extensions/modules/cache/src/test/xquery/modules/cache/cache.xqm
  extensions/modules/expathrepo/expathrepo-trigger-test/src/test/java/org/exist/repo/ExampleModuleTest.java
  extensions/modules/mail/src/main/java/org/exist/xquery/modules/mail/MailFolderFunctions.java
  extensions/modules/mail/src/main/java/org/exist/xquery/modules/mail/MailSessionFunctions.java
  extensions/modules/mail/src/main/java/org/exist/xquery/modules/mail/MailStoreFunctions.java
  extensions/modules/mail/src/main/java/org/exist/xquery/modules/mail/MessageFunctions.java
  extensions/modules/mail/src/main/java/org/exist/xquery/modules/mail/MessageListFunctions.java
Labels: bug, high prio
