Repository eXist-db/exist, pull requests merged in 2023-03, with the labels that each got.

#4792 Small fixes for the Java Admin Client
  exist-core/src/main/java/org/exist/client/ClientFrame.java
  exist-core/src/main/java/org/exist/client/InteractiveClient.java
Labels: bug

#4793 Small optimisations to the Lucene Index Worker
  extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/DefaultTextExtractor.java
  extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/LuceneConfig.java
  extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/LuceneIndexConfig.java
Labels: enhancement

#4695 [fix] permissions on install
  exist-core/src/main/java/org/exist/repo/Deployment.java
  exist-core/src/main/java/org/exist/security/AbstractUnixStylePermission.java
  exist-core/src/test/java/org/exist/security/UnixStylePermissionTest.java
Labels: needs documentation, security

#4772 Fix some issues with CLI args
  exist-core/src/main/java/org/exist/backup/ExportGUI.java
  exist-core/src/main/java/org/exist/backup/ExportMain.java
  exist-core/src/main/java/org/exist/backup/Main.java
  exist-core/src/main/java/org/exist/client/CommandlineOptions.java
  exist-core/src/main/java/org/exist/jetty/JettyStart.java
  exist-core/src/main/java/org/exist/jetty/ServerShutdown.java
  exist-core/src/main/java/org/exist/launcher/LauncherWrapper.java
  exist-core/src/main/java/org/exist/management/client/JMXClient.java
  exist-core/src/main/java/org/exist/util/OSUtil.java
  exist-distribution/pom.xml
  exist-start/src/main/java/org/exist/start/Main.java
Labels: bug

#4799 [fix] XQSuite assertXPath annotation: Support default element namespace
  exist-core/src/main/resources/org/exist/xquery/lib/xqsuite/examples.xql
  exist-core/src/main/resources/org/exist/xquery/lib/xqsuite/xqsuite.xql
Labels: needs documentation

#3313 Make fn:collection signature compliant with the XQuery 3.1 F&O spec
  exist-core/src/main/java/org/exist/xquery/functions/fn/ExtCollection.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FnModule.java
  exist-core/src/main/java/org/exist/xquery/functions/xmldb/FunXCollection.java
  exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBModule.java
Labels: bug, xquery

#4661 Compare this XQTS run with previous XQTS run
  .github/workflows/ci-xqts.yml
  exist-parent/pom.xml
  exist-xqts/src/main/xslt/compare-results.xslt
Labels: enhancement

#4802 Add mail:get-mail-session#2 with authentication
  extensions/modules/mail/src/main/java/org/exist/xquery/modules/mail/MailModule.java
  extensions/modules/mail/src/main/java/org/exist/xquery/modules/mail/MailSessionFunctions.java
  extensions/modules/mail/src/test/java/org/exist/xquery/modules/mail/SendEmailIT.java
Labels: enhancement

#4158 Remove unused PluginsManager
  exist-core/src/main/java/org/exist/Database.java
  exist-core/src/main/java/org/exist/backup/BackupHandler.java
  exist-core/src/main/java/org/exist/backup/RestoreHandler.java
  exist-core/src/main/java/org/exist/backup/SystemExport.java
  exist-core/src/main/java/org/exist/backup/restore/SystemImportHandler.java
  exist-core/src/main/java/org/exist/client/InteractiveClient.java
  exist-core/src/main/java/org/exist/plugin/Plug.java
  exist-core/src/main/java/org/exist/plugin/PluginsManager.java
  exist-core/src/main/java/org/exist/plugin/PluginsManagerImpl.java
  exist-core/src/main/java/org/exist/plugin/Utils.java
  exist-core/src/main/java/org/exist/plugin/command/AbstractCommand.java
  exist-core/src/main/java/org/exist/plugin/command/AbstractCommandResolver.java
  exist-core/src/main/java/org/exist/plugin/command/Command.java
  exist-core/src/main/java/org/exist/plugin/command/CommandException.java
  exist-core/src/main/java/org/exist/plugin/command/CommandNotFoundException.java
  exist-core/src/main/java/org/exist/plugin/command/CommandResolver.java
  exist-core/src/main/java/org/exist/plugin/command/Commands.java
  exist-core/src/main/java/org/exist/storage/BrokerPool.java
  exist-core/src/main/java/org/exist/storage/StartupTriggersManager.java
  exist-core/src/main/java/org/exist/xmldb/EXistCollectionManagementService.java
  exist-core/src/main/java/org/exist/xmldb/LocalCollectionManagementService.java
  exist-core/src/main/java/org/exist/xmldb/RemoteCollectionManagementService.java
  exist-core/src/main/java/org/exist/xmlrpc/RpcAPI.java
  exist-core/src/main/java/org/exist/xmlrpc/RpcConnection.java
  exist-core/src/test/java/org/exist/storage/journal/AbstractJournalTest.java
Labels: enhancement
