Repository eXist-db/exist, pull requests merged in 2023-08, with the labels that each got.

#5021 Rename Function flag overloaded to variadic
  exist-core/src/main/java/org/exist/xquery/Function.java
  exist-core/src/main/java/org/exist/xquery/FunctionSignature.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FunHigherOrderFun.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FunNamespaceURI.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/LoadXQueryModule.java
  exist-core/src/main/java/org/exist/xquery/functions/response/StreamBinary.java
  exist-core/src/main/java/org/exist/xquery/functions/util/GetFragmentBetween.java
  extensions/indexes/range/src/test/xquery/range/range.xql
Labels: discuss

#5012 [6.x.x] Fix an issue with XQuery transient imports within EXPath Package
  exist-core/src/main/java/org/exist/client/InteractiveClient.java
  exist-core/src/main/java/org/exist/repo/ExistRepository.java
  exist-core/src/main/java/org/exist/util/Configuration.java
  exist-core/src/main/java/org/exist/util/ConfigurationHelper.java
  exist-core/src/main/java/org/exist/util/SingleInstanceConfiguration.java
  exist-core/src/main/java/org/exist/xquery/XQueryContext.java
  exist-parent/pom.xml
Labels: bug

#5007 Allow the user to override the JDWP Suspend at Docker build time
  exist-docker/src/main/resources-filtered/Dockerfile-DEBUG
Labels: enhancement

#5006 [5.x.x] Fix the use of Debian Stretch repositories in the Docker builds
  exist-docker/src/main/resources-filtered/Dockerfile
Labels: bug

#5008 [6.x.x] Allow the user to override the JDWP Suspend at Docker build time
  exist-docker/src/main/resources-filtered/Dockerfile-DEBUG
Labels: enhancement
