Repository eXist-db/exist, pull requests merged in 2024-10, with the labels that each got.

#5484 Fix an issue where XQuery Trigger state may leak
  exist-core/src/main/java/org/exist/collections/triggers/XQueryTrigger.java
Labels: bug

#5466 [6.x.x] Switch CI from Temurin to Liberica
  .github/actions/install-mvnd/action.yml
  .github/workflows/ci-deploy.yml
  .github/workflows/ci-test.yml
  .github/workflows/ci-xqts.yml
  exist-core/pom.xml
  exist-core/src/main/java/org/exist/plugin/PluginsManagerImpl.java
  exist-core/src/main/java/org/exist/storage/recovery/RecoveryManager.java
Labels: ci

#5481 [6.x.x] Fix an issue where XQuery Trigger state may leak
  exist-core/src/main/java/org/exist/collections/triggers/XQueryTrigger.java
Labels: bug

#5469 Hide journal recovery messages during test suite run
  .github/actions/install-mvnd/action.yml
  .github/workflows/ci-test.yml
  exist-core/pom.xml
  exist-core/src/main/java/org/exist/storage/recovery/RecoveryManager.java
  exist-parent/pom.xml
Labels: ci

#5482 [5.x.x] Fix an issue where XQuery Trigger state may leak
  exist-core/src/main/java/org/exist/collections/triggers/XQueryTrigger.java
Labels: bug

#5467 [5.x.x] Switch CI from Temurin to Liberica
  .github/actions/install-mvnd/action.yml
  .github/workflows/ci-deploy.yml
  .github/workflows/ci-test.yml
  .github/workflows/sonarcloud.yml
  exist-core/pom.xml
  exist-core/src/main/java/org/exist/plugin/PluginsManagerImpl.java
  exist-core/src/main/java/org/exist/storage/recovery/RecoveryManager.java
  exist-parent/pom.xml
Labels: ci

#5468 [4.x.x] Switch CI from Temurin to Liberica
  .github/workflows/ci.yml
  build/scripts/junit.xml
  exist-core/src/main/java/org/exist/plugin/PluginsManagerImpl.java
  exist-core/src/main/java/org/exist/storage/recovery/RecoveryManager.java
Labels: ci

#5480 Switch CI from Temurin to Liberica
  .github/workflows/ci-deploy.yml
  .github/workflows/ci-test.yml
  .github/workflows/ci-xqts.yml
  .github/workflows/sonarcloud.yml
Labels: ci

#5491 Fix flaky storage test timing
  exist-core/src/test/java/org/exist/storage/StoreResourceTest.java
Labels: bug

#5483 [4.x.x] Fix an issue where XQuery Trigger state may leak
  exist-core/src/main/java/org/exist/collections/triggers/XQueryTrigger.java
  exist-core/src/test/java/org/exist/storage/StoreResourceTest.java
Labels: bug

#5492 [6.x.x] Fix flaky storage test timing
  exist-core/src/test/java/org/exist/storage/StoreResourceTest.java
Labels: bug

#4643 Remove the last small dependency on Apache Xalan
  exist-core/pom.xml
  exist-core/src/main/java/org/exist/dom/memtree/NodeImpl.java
  exist-core/src/test/java/org/exist/xslt/TransformerFactoryAllocatorTest.java
  exist-core/src/test/resources/org/exist/config/conf1.xml
  exist-core/src/test/resources/org/exist/config/conf2.xml
  exist-parent/pom.xml
  extensions/indexes/spatial/pom.xml
  extensions/indexes/spatial/src/main/java/org/exist/indexing/spatial/AbstractGMLJDBCIndexWorker.java
  extensions/indexes/spatial/src/main/java/org/exist/indexing/spatial/GMLHSQLIndexWorker.java
  extensions/indexes/spatial/src/main/java/org/exist/xquery/modules/spatial/FunGMLProducers.java
  extensions/indexes/spatial/src/main/java/org/exist/xquery/modules/spatial/FunGeometricProperties.java
  extensions/indexes/spatial/src/main/java/org/exist/xquery/modules/spatial/FunSpatialSearch.java
  extensions/indexes/spatial/src/test/java/org/exist/indexing/spatial/GMLIndexTest.java
Labels: enhancement

#4910 Fix concurrency issues in Performance Stats code
  exist-core/src/main/java/org/exist/storage/BrokerPool.java
  exist-core/src/main/java/org/exist/xquery/GeneralComparison.java
  exist-core/src/main/java/org/exist/xquery/LocationStep.java
  exist-core/src/main/java/org/exist/xquery/PerformanceStats.java
  exist-core/src/main/java/org/exist/xquery/PerformanceStatsImpl.java
  exist-core/src/main/java/org/exist/xquery/PerformanceStatsService.java
  exist-core/src/main/java/org/exist/xquery/Profiler.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FunMatches.java
  exist-core/src/main/java/org/exist/xquery/functions/system/FunctionTrace.java
  exist-core/src/test/xquery/indexing/range.xml
  exist-core/src/test/xquery/optimizer/expressions.xqm
  exist-core/src/test/xquery/optimizer/positional.xqm
  extensions/indexes/lucene/src/main/java/org/exist/xquery/modules/lucene/Query.java
  extensions/indexes/lucene/src/main/java/org/exist/xquery/modules/lucene/QueryField.java
  extensions/indexes/lucene/src/test/xquery/lucene/queries.xml
  extensions/indexes/ngram/src/main/java/org/exist/xquery/modules/ngram/NGramSearch.java
  extensions/indexes/range/src/main/java/org/exist/xquery/modules/range/FieldLookup.java
  extensions/indexes/range/src/main/java/org/exist/xquery/modules/range/Lookup.java
  extensions/indexes/range/src/test/xquery/range/conditions.xql
  extensions/indexes/range/src/test/xquery/range/fields.xql
  extensions/indexes/range/src/test/xquery/range/optimizer.xql
  extensions/indexes/range/src/test/xquery/range/types.xql
Labels: bug

#4866 [5.x.x] Fixes to fn:replace, fn:tokenize, and fn:analyze-string
  exist-core/src/main/java/org/exist/xquery/functions/fn/FnModule.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FunAnalyzeString.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FunMatches.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FunReplace.java
  exist-core/src/main/java/org/exist/xquery/functions/fn/FunTokenize.java
  exist-core/src/test/xquery/regex.xml
Labels: bug

#5497 Fix failing Range Index test after merge of https://github.com/eXist-db/exist/pull/4910
  extensions/indexes/range/src/test/xquery/range/optimizer.xql
Labels: bug, regression

#5186 [6.x.x] Allow setting the namespace on the result of sql:execute
  extensions/modules/sql/src/main/java/org/exist/xquery/modules/sql/ExecuteFunction.java
  extensions/modules/sql/src/test/java/org/exist/xquery/modules/sql/ExecuteIT.java
Labels: enhancement

#5503 Fix test resource leaks introduced in https://github.com/eXist-db/exist/pull/5276
  .github/workflows/ci-test.yml
  exist-core/pom.xml
  exist-core/src/main/java/org/exist/test/ExistXmldbEmbeddedServer.java
  exist-core/src/test/java/org/exist/xquery/update/UpdateInsertTriggersDefrag.java
  exist-core/src/test/java/org/exist/xquery/update/UpdateInsertTriggersDefragTest.java
  exist-parent/pom.xml
Labels: bug

#5504 Allow setting the namespace on the result of sql:execute
  extensions/modules/sql/src/main/java/org/exist/xquery/modules/sql/ExecuteFunction.java
  extensions/modules/sql/src/test/java/org/exist/xquery/modules/sql/ExecuteIT.java
Labels: enhancement

#5507 Bump org.apache.xmlgraphics:fop-core from 2.9 to 2.10 in /extensions/modules/xslfo
  extensions/modules/xslfo/pom.xml
Labels: dependencies

#5513 [6.x.x] Fix CI Windows stream corruption
  .github/workflows/ci-test.yml
  exist-core/pom.xml
  exist-parent/pom.xml
Labels: bug, ci

#5514 Fix CI issues with PR that require GitHub Secrets
  .github/workflows/ci-test.yml
Labels: bug, ci
