Repository eXist-db/exist, pull requests merged in 2025-01, with the labels that each got.

#5598 Backport multi arch 5533
  .github/workflows/ci-deploy.yml
  exist-docker/pom.xml
  exist-docker/src/main/resources-filtered/Dockerfile
  exist-docker/src/main/resources-filtered/Dockerfile-DEBUG
Labels: docker

#5576 [bugfix] registered import-uris have precedence
  exist-core/src/main/java/org/exist/xslt/XsltURIResolverHelper.java
  exist-core/src/test/java/org/exist/xquery/functions/transform/ImportLocalStylesheetTest.java
Labels: bug, needs 6.x.x backport

#5529 Allow module imports in one-off xqueries
  exist-core/src/main/java/org/exist/source/SourceFactory.java
  exist-core/src/main/java/org/exist/test/XQueryCompilationTest.java
  exist-core/src/main/java/org/exist/xquery/XQueryContext.java
  exist-core/src/test/java/org/exist/xquery/AbsolutePathTests.java
  exist-core/src/test/java/org/exist/xquery/ModuleImportTest.java
  exist-core/src/test/resources-filtered/org/exist/xquery/conf.xml
Labels: needs 6.x.x backport
